### ISSUE TITLE
[question] passing headers

### ISSUE THREAD

**Issue by kudanai** [brianwernick/ExoMedia#103]
Is there any way to pass headers up like a session token like setting headers in `FrameworkSampleSource`?

**Comment by brianwernick** [comment]
Currently there isn't a way to add headers to the requests.  However https://github.com/brianwernick/ExoMedia/issues/86 will add the ability to modify or add headers

**Comment by kudanai** [comment]
That would do it. +1 for #86. Closing this one in favour of HttpDataSource
