### ISSUE TITLE
Inconsistencies between millisecond representation

### ISSUE THREAD

**Issue by koesie10** [brianwernick/ExoMedia#104]
[EMVideoView.seekTo()](https://github.com/brianwernick/ExoMedia/blob/3df369b2dd09b583a26a80f8eccc433aaf5e325d/library/src/main/java/com/devbrackets/android/exomedia/EMVideoView.java#L893) accepts an `int` as millisecond parameter, while [EMVideoView.getCurrentPosition()](https://github.com/brianwernick/ExoMedia/blob/3df369b2dd09b583a26a80f8eccc433aaf5e325d/library/src/main/java/com/devbrackets/android/exomedia/EMVideoView.java#L1038) and [EMVideoView.getDuration()](https://github.com/brianwernick/ExoMedia/blob/3df369b2dd09b583a26a80f8eccc433aaf5e325d/library/src/main/java/com/devbrackets/android/exomedia/EMVideoView.java#L1004) return a `long`.

**Comment by brianwernick** [comment]
This has been fixed in the 3.0 branch (https://github.com/brianwernick/ExoMedia/commit/639d55ae283a2ee73932b35bf00e1df3650823b6)
