### ISSUE TITLE
How to use InvokeRepeat on mp3 playlist?

### ISSUE THREAD

**Issue by thomasdola** [brianwernick/ExoMedia#106]
Many many thanks for this awsome library...
first => i have trying for hours to setup a repeat function but can't get my head around it/...Any help?
second => how do you know that a particular track has finished playing?
thanks...

**Comment by brianwernick** [comment]
The second question is really the answer to the first.  You can listen for playback completion on a track so that you can start that track (or playlist) again.

To answer the second question, you can register for playback changes with `registerServiceCallbacks(EMPlaylistServiceCallback callback)` in the `EMPlaylistManager`.  Alternatively, if you are in the `EMPlaylistService` then you can override the `performMediaCompletion()` method

**Comment by thomasdola** [comment]
Thanks 
let me give a try..

**Comment by thomasdola** [comment]
By the way i have tried invoking the "invokeRepeat()" function from my activity but nothing...

**Comment by brianwernick** [comment]
The `invokeRepeat()` function just sends the command to the PlaylistService.  You will need to override `performRepeat()` on your own to provide the expected functionality.

**Comment by thomasdola** [comment]
Sorry to be disturbing you this much... but am a biginer in Android.. don't realy get how to do..
can you please give me an example of how you setup for::
=>`registerServiceCallbacks()`
=>`performRepeat()`
=>`performMediaCompletion()`
really begin you...
thanks

**Comment by brianwernick** [comment]
I'm happy to help :)

I'll use the Demo app for the explanation since that is a source we both have access to.  Realistically you won't need to register service callbacks so lets skip that one.

For `performRepeat()` I'm going to assume you want to repeat the current playlist, and that calling `invokeRepeat()` from the PlaylistManager will toggle.

```java
    private boolean repeatPlaylist = false;
    // ... Other methods, etc.
    
    @Override
    protected void performRepeat() {
        repeatPlaylist = !repeatPlaylist;
    }
```

Then in the `performMediaCompletion()` you will look at the current item position, and the value for `repeatPlaylist`

```java

    @Override
    protected void performMediaCompletion() {
        //Moves to the next playlist item
        if (getMediaPlaylistManager().isNextAvailable()) {
            performNext();
            return;
        }
        
        //If there is no next and we are repeating, move to the first item
        if (repeatPlaylist) {
            getMediaPlaylistManager().setCurrentIndex(0);
            startItemPlayback();
        }
    }
```

Now I haven't tested to see if this works correctly, but the idea is there and you should be able to resolve any cases I missed.

**Comment by thomasdola** [comment]
I was able to do it but what if i want the user to repeat a particular item, say the second one out 3 item?
How do i customize the notification? Like defining my own(say i already defined it , how do make use mine instead of the default one?)

**Comment by brianwernick** [comment]
To define your own notification you will need to override all the notification methods in the `EMPlaylistService` such as `updateNotification` and `setupForeground()`

**Comment by thomasdola** [comment]
How to retry in case of ERROR , because that is crashing the app..

**Comment by brianwernick** [comment]
Currently the audio player will attempt a single retry if there is an error in the playback. Sadly, there isn't a way to intercept these errors currently as the internal listener is private (in `EMPlaylistService`).  In the [PlaylistCore](https://github.com/brianwernick/PlaylistCore) this is fixed, but in the meantime I don't know what to tell you.  

Is the audio failing on the first play, or when you try to repeat the item?

**Comment by thomasdola** [comment]
this is the error am getting:
`
Internal track renderer error.
02-17 13:56:00.007 19107-20113/primr.apps.eurakacachet.com.primr E/ExoPlayerImplInternal: com.google.android.exoplayer.ExoPlaybackException: com.google.android.exoplayer.upstream.HttpDataSource$HttpDataSourceException: Unable to connect to http://cs1.mp3.pm/download/37889938/R1YvRW9naVBEQngvMXdqOGkwRTY4VWVXUzBWb1hUZ3I2TGIxMnRtc08yM0dKYUFiQWt3M3lxU3dtQndHdDY2OHp2d2hvcFdTZ3U5eXFpRlJ6MzBOK0RVNHRuaFBKNEZSYUpKNExSbzJHU0RTRFNLUUoydzFPRnlNTHYvSDF5KzE/Chris_Brown_-_101_Interlude_(mp3.pm).mp3
02-17 13:56:00.007 19107-20113/primr.apps.eurakacachet.com.primr E/ExoPlayerImplInternal:     at com.google.android.exoplayer.SampleSourceTrackRenderer.maybeThrowError(SampleSourceTrackRenderer.java:263)
02-17 13:56:00.007 19107-20113/primr.apps.eurakacachet.com.primr E/ExoPlayerImplInternal:     at com.google.android.exoplayer.SampleSourceTrackRenderer.maybeThrowError(SampleSourceTrackRenderer.java:149)
02-17 13:56:00.007 19107-20113/primr.apps.eurakacachet.com.primr E/ExoPlayerImplInternal:     at com.google.android.exoplayer.ExoPlayerImplInternal.incrementalPrepareInternal(ExoPlayerImplInternal.java:283)
02-17 13:56:00.007 19107-20113/primr.apps.eurakacachet.com.primr E/ExoPlayerImplInternal:     at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:205)
02-17 13:56:00.007 19107-20113/primr.apps.eurakacachet.com.primr E/ExoPlayerImplInternal:     at android.os.Handler.dispatchMessage(Handler.java:98)
02-17 13:56:00.007 19107-20113/primr.apps.eurakacachet.com.primr E/ExoPlayerImplInternal:     at android.os.Looper.loop(Looper.java:135)
02-17 13:56:00.007 19107-20113/primr.apps.eurakacachet.com.primr E/ExoPlayerImplInternal:     at android.os.HandlerThread.run(HandlerThread.java:61)
02-17 13:56:00.007 19107-20113/primr.apps.eurakacachet.com.primr E/ExoPlayerImplInternal:     at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
02-17 13:56:00.007 19107-20113/primr.apps.eurakacachet.com.primr E/ExoPlayerImplInternal:  Caused by: com.google.android.exoplayer.upstream.HttpDataSource$HttpDataSourceException: Unable to connect to http://cs1.mp3.pm/download/37889938/R1YvRW9naVBEQngvMXdqOGkwRTY4VWVXUzBWb1hUZ3I2TGIxMnRtc08yM0dKYUFiQWt3M3lxU3dtQndHdDY2OHp2d2hvcFdTZ3U5eXFpRlJ6MzBOK0RVNHRuaFBKNEZSYUpKNExSbzJHU0RTRFNLUUoydzFPRnlNTHYvSDF5KzE/Chris_Brown_-_101_Interlude_(mp3.pm).mp3
02-17 13:56:00.007 19107-20113/primr.apps.eurakacachet.com.primr E/ExoPlayerImplInternal:     at com.google.android.exoplayer.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:193)
02-17 13:56:00.007 19107-20113/primr.apps.eurakacachet.com.primr E/ExoPlayerImplInternal:     at com.google.android.exoplayer.upstream.DefaultUriDataSource.open(DefaultUriDataSource.java:135)
02-17 13:56:00.007 19107-20113/primr.apps.eurakacachet.com.primr E/ExoPlayerImplInternal:     at com.google.android.exoplayer.extractor.ExtractorSampleSource$ExtractingLoadable.load(ExtractorSampleSource.java:713)
02-17 13:56:00.007 19107-20113/primr.apps.eurakacachet.com.primr E/ExoPlayerImplInternal:     at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:209)
02-17 13:56:00.007 19107-20113/primr.apps.eurakacachet.com.primr E/ExoPlayerImplInternal:     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
02-17 13:56:00.007 19107-20113/primr.apps.eurakacachet.com.primr E/ExoPlayerImplInternal:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
02-17 13:56:00.007 19107-20113/primr.apps.eurakacachet.com.primr E/ExoPlayerImplInternal:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
02-17 13:56:00.007 19107-20113/primr.apps.eurakacachet.com.primr E/ExoPlayerImplInternal:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
02-17 13:56:00.007 19107-20113/primr.apps.eurakacachet.com.primr E/ExoPlayerImplInternal:     at java.lang.Thread.run(Thread.java:818)
02-17 13:56:00.007 19107-20113/primr.apps.eurakacachet.com.primr E/ExoPlayerImplInternal:  Caused by: java.net.SocketTimeoutException
02-17 13:56:00.007 19107-20113/primr.apps.eurakacachet.com.primr E/ExoPlayerImplInternal:     at java.net.PlainSocketImpl.read(PlainSocketImpl.java:488)
02-17 13:56:00.007 19107-20113/primr.apps.eurakacachet.com.primr E/ExoPlayerImplInternal:     at java.net.PlainSocketImpl.access$000(PlainSocketImpl.java:37)
02-17 13:56:00.007 19107-20113/primr.apps.eurakacachet.com.primr E/ExoPlayerImplInternal:     at java.net.PlainSocketImpl$PlainSocketInputStream.read(PlainSocketImpl.java:237)
02-17 13:56:00.007 19107-20113/primr.apps.eurakacachet.com.primr E/ExoPlayerImplInternal:     at com.android.okio.Okio$2.read(Okio.java:113)
02-17 13:56:00.007 19107-20113/primr.apps.eurakacachet.com.primr E/ExoPlayerImplInternal:     at com.android.okio.RealBufferedSource.indexOf(RealBufferedSource.java:147)
02-17 13:56:00.007 19107-20113/primr.apps.eurakacachet.com.primr E/ExoPlayerImplInternal:     at com.android.okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:94)
02-17 13:56:00.007 19107-20113/primr.apps.eurakacachet.com.primr E/ExoPlayerImplInternal:     at com.android.okhttp.internal.http.HttpConnection.readResponse(HttpConnection.java:175)
02-17 13:56:00.007 19107-20113/primr.apps.eurakacachet.com.primr E/ExoPlayerImplInternal:     at com.android.okhttp.internal.http.HttpTransport.readResponseHeaders(HttpTransport.java:101)
02-17 13:56:00.007 19107-20113/primr.apps.eurakacachet.com.primr E/ExoPlayerImplInternal:     at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:616)
02-17 13:56:00.007 19107-20113/primr.apps.eurakacachet.com.primr E/ExoPlayerImplInternal:     at com.android.okhttp.internal.http.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:379)
02-17 13:56:00.007 19107-20113/primr.apps.eurakacachet.com.primr E/ExoPlayerImplInternal:     at com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:323)
02-17 13:56:00.007 19107-20113/primr.apps.eurakacachet.com.primr E/ExoPlayerImplInternal:     at com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:491)
02-17 13:56:00.007 19107-20113/primr.apps.eurakacachet.com.primr E/ExoPlayerImplInternal:     at com.google.android.exoplayer.upstream.DefaultHttpDataSource.makeConnection(DefaultHttpDataSource.java:351)
02-17 13:56:00.007 19107-20113/primr.apps.eurakacachet.com.primr E/ExoPlayerImplInternal:     at com.google.android.exoplayer.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:191)
`

**Comment by thomasdola** [comment]
Are the playlist items downloaded in linear or parallel?
Is it possible to hook into that event?
(say when the next is finished downloading) 
Or even downloading the next item while the playing the current item...

**Comment by brianwernick** [comment]
The media items aren't downloaded, they are streamed (with buffering).  This means that only the current item specified as playback will perform any network events (buffering).

**Comment by thomasdola** [comment]
ohh ok..
1=>is it possible to overide EMPlaylistService?
2=>if yes what methods can i overide safely (because i have a case where i only users to be able to pause and play the current playlist item through the notification and the screen lock)
am sure this is the last question (:

**Comment by brianwernick** [comment]
1) `EMPlaylistService` is abstract and must be extended (see the `AudioService` in the Demo)
2) Other than the abstract methods that must be overridden, there are a few empty methods (such as the previously mentioned `performRepeat()` and `performMediaCompletion()`).  Other than those, there are a few methods that you could fairly safely override, but it would still take some work to figure out how they are used by the rest of the service.

**Comment by thomasdola** [comment]
Really sorry about the disturbance , but you are real saviour
one last question: how to play a local file (data/data/package.name/filename.mp3)
do i just pass the path as the online way?

**Comment by brianwernick** [comment]
Yes, you would just pass the absolute path to the media in (or if you are using the EMPlaylistService you would return that value from `getDownloadedMediaUri()` in the `PlaylistItem`)

**Comment by thomasdola** [comment]
hi 
am trying to download the playlistcore package but error
`Error:(36, 13) Failed to resolve: com.devbrackets.android:playlistcore:1.0.0`
