### ISSUE TITLE
Reset doesn't clear last frame

### ISSUE THREAD

**Issue by eygraber** [brianwernick/ExoMedia#107]
Calling `EMVideoView.reset()` does not remove the last frame from the playback surface. I see it calls `EMExoPlayer.replaceRenderBuilder(null)` (through `setVideoUri`) which calls `prepare()` which does nothing if `rendererBuilder` is `null`.

**Comment by brianwernick** [comment]
Hmm, this looks like it is a problem with the `stopPlayback()` method which should be performing a clear surface call.  Not a major issue though, so it will be addressed in 3.0 instead of a 2.5.x patch

**Comment by brianwernick** [comment]
Also, not the same issue (or cause) but related; https://github.com/brianwernick/ExoMedia/issues/105

**Comment by brianwernick** [comment]
Fixed in #177
