### ISSUE TITLE
EMLockScreen - Unable to start service exception

### ISSUE THREAD

**Issue by veresvit** [brianwernick/ExoMedia#110]
Hello,

In my published app which uses ExoMedia 2.5.3 about 10% of users experiences exception with Service intent launch. I was not able to reproduce this exception on any of my devices..
You can see the full exception at: [UnableToStartServiceException Gist](https://gist.github.com/veresvit/955da8dce070741463f1)

Thank you for this great library!

**Comment by brianwernick** [comment]
The only thing that seems to make sense is that the `context` is null when they attempt to retrieve the app icon.  However the fact that it is null only on some devices is indicative of a different issue (one that probably causes release to be called before `startForeground`)

**Comment by veresvit** [comment]
I came to the same conclusion, but sadly there my knowledge ends.. I would like to give you more information, but I don't see any lead.

According to Crashlytics:

- 
 Any brand of phone and basically
- 
 Any version of Android from 4.1 to 6.
- 
 99,94% app in focus
-
 10% phones rooted

**Comment by brianwernick** [comment]
Hmm, without either of us being able to reproduce it I added null checking and fixed a few cases so it shouldn't be null anymore.  I'm not sure if it will fix the issue though (https://github.com/brianwernick/ExoMedia/commit/bcb2fce7c699cade31bf22773a2e0564648f09e9).  If it doesn't actually fix it in the 2.5.5 release, then please re-open this bug
