### ISSUE TITLE
How to define my custom layout of player?

### ISSUE THREAD

**Issue by ehaahe** [brianwernick/ExoMedia#111]
must I modify the source code?Is there any api to do this?

**Comment by brianwernick** [comment]
I'm not sure what you are asking. Would you rephrase the question and be a little more explicit

**Comment by ehaahe** [comment]
I would like to make a custom skin,How can I  achieve the goal?

**Comment by DrewCarlson** [comment]
@ehaahe

I believe you are looking for the following:

[DefaultControlsMobile.java](https://github.com/brianwernick/ExoMedia/blob/master/library/src/main/java/com/devbrackets/android/exomedia/widget/DefaultControlsMobile.java)

[exomedia_video_controls_overlay.xml](https://github.com/brianwernick/ExoMedia/blob/master/library/src/main/res/layout/exomedia_video_controls_overlay.xml)

**Comment by ehaahe** [comment]
Ths,I solve this problem
but now i found the seekbar's skin cannot be modified,why?
the next is my progressDrawable:
bg_progress.xml
![image](https://cloud.githubusercontent.com/assets/9740081/13173935/623252e2-d73b-11e5-820a-3536e26a3be7.png)

and next is the definition of my seekbar:
![image](https://cloud.githubusercontent.com/assets/9740081/13173956/81f649c6-d73b-11e5-824c-caf89a9adf9b.png)

**Comment by ehaahe** [comment]
I find the reason,that is the library‘s resource file and app's resource file is same name
