### ISSUE TITLE
prepare bug

### ISSUE THREAD

**Issue by ehaahe** [brianwernick/ExoMedia#117]
when the video is preparing,it can block the http request if the url is disabled.

**Comment by brianwernick** [comment]
Would you be more descriptive of the issue.  What are you expecting to see vs what you are seeing.  What do you mean "if the url is disabled"; how is the url disabled?

**Comment by ehaahe** [comment]
Can video prepare not in the main thread?

**Comment by brianwernick** [comment]
The video is prepared on a background thread, only small initialization procedures are performed on the UI thread
