### ISSUE TITLE
fullscreen support

### ISSUE THREAD

**Issue by LiuDeng** [brianwernick/ExoMedia#119]
I really love this lib and thank you so much for this great job and i hope you can add fullscreen play support thank you ~

**Comment by LiuDeng** [comment]
if you will add this please note 
1.when change common play to fullscreen, keep the watch progress and seek to the watch pos
2.add exit fullscreen and replay btn when play end
3.hope check the release of the media view avoid memory leak

**Comment by brianwernick** [comment]
The ability to specify custom buttons on the DefaultControls is already a feature in the 3.0 branch which will allow you to create your own fullscreen button.  Similarly, the replay button will be something you can dynamically add.

As far as `#3` goes, All media and associated utilties, views, etc. are released when the view is detached.  If there is an area where memory is being leaked, please include more details
