### ISSUE TITLE
Lock screen doesn't work.

### ISSUE THREAD

**Issue by Thanhktm** [brianwernick/ExoMedia#12]
Hi.

I running demo everything work well except Lock screen feature. Not show artwork, media buttons on Lock screen.

Nexus 5, Lollipop 5.1.1

**Comment by Thanhktm** [comment]
Hi,

Sorry, I missed your update.

I've upgrade newest version I it works well.

Your library make me done my project.

Thank.

**Comment by brianwernick** [comment]
I'm glad that it is working well for you, and even though the bug was already fixed, thanks for spending the time to write up a bug.
