### ISSUE TITLE
Can't hear the sound

### ISSUE THREAD

**Issue by aleigood** [brianwernick/ExoMedia#122]
File url: http://7xozx5.com1.z0.glb.clouddn.com/2016-02-28_182011.mp4
File infomation:
Video: h264 (Constrained Baseline) (avc1 / 0x31637661), yuv420p, 1920x1080, 5378 kb/s, 15 fps, 15 tbr, 15360 tbn, 30 tbc (default)
Audio: mp3 (mp4a / 0x6134706D), 16000 Hz, mono, s16p, 24 kb/s (default)

The mobile built-in player can play normal, but playing with ExoMedia I can't hear the sound.

**Comment by brianwernick** [comment]
The root of this may be https://github.com/google/ExoPlayer/issues/1263

**Comment by brianwernick** [comment]
Closing as the example Url is no longer valid and I haven't been able to find another file that has the same issue
