### ISSUE TITLE
Looping is broken

### ISSUE THREAD

**Issue by eygraber** [brianwernick/ExoMedia#125]
Using the latest commit in the 3.0 branch, the following code doesn't do anything (most likely because `ExoPlayer` is in `STATE_IDLE`):

```java
// in a subclass of EMVideoView
setOnCompletionListener(new OnCompletionListener() {
  @Override
  public void onCompletion() {
    seekTo(0);
    start();
  }
});
```

I've verified that `onCompletion` is actually called, and I set a breakpoint on `EMExoPlayer.onPlayerStateChanged`. After the video finishes playing, it is called twice, both times with `ExoPlayer.STATE_IDLE`.

**Comment by brianwernick** [comment]
This may have been a change in the ExoPlayer 1.5.6 release, but I can't say for certain without looking in to it a little more.

**Comment by eygraber** [comment]
I've done some investigation, and it seems this commit is the last time that code worked (https://github.com/brianwernick/ExoMedia/commit/639d55ae283a2ee73932b35bf00e1df3650823b6). I assume the next commit which was to call `ExoPlayer.stop()` is the problem.

**Comment by brianwernick** [comment]
It looks like it is due to calling `stopPlayback()` when the media has ended.  We should probably perform a little different functionality in that case. (see 
https://github.com/brianwernick/ExoMedia/blob/3.0/library/src/main/java/com/devbrackets/android/exomedia/EMAudioPlayer.java#L294 )

**Comment by eygraber** [comment]
What about something like a `restart` method, so the resources can still be freed when playback ends?

**Comment by brianwernick** [comment]
Well before the change we used to just call what is equivalent to `pause()` which makes sense when the playback was just completed (not ended due to an error).  

Looking in to the source a little more, it looks like there needs to be more cleanup around the `EMListenerMux` in general.

**Comment by brianwernick** [comment]
OK, I think you are right that there should be a `restart()` method instead of performing the `pause()`.

**Comment by ehaahe** [comment]
this is my current solution,which is added in EMVideoView.java:
public void restart() {
        seekTo(0);
        emExoPlayer.forcePrepare();
        emExoPlayer.prepare();
        emExoPlayer.setPlayWhenReady(true);
        if (defaultControls != null) {
            defaultControls.updatePlayPauseImage(true);
            defaultControls.hideDelayed(DefaultControls.DEFAULT_CONTROL_HIDE_DELAY);
        }
        pollRepeater.start();
    }

is the slution correct?

**Comment by ehaahe** [comment]
and this is the "onPlayPauseClick" function of the DefaultControls.java:
protected void onPlayPauseClick() {
        if (callback != null && callback.onPlayPauseClicked()) {
            return;
        }

        if (bus != null) {
            bus.post(new EMMediaPlayPauseEvent());
            if (busPostHandlesEvent) {
                return;
            }
        }

        //toggles the playback
        boolean playing = videoView.isPlaying();
        if (playing) {
            videoView.pause();
        } else {
            if (videoView.getCurrentPosition() >= videoView.getDuration()) {
                videoView.restart();
                return;
            }
            videoView.start();
        }
    }

**Comment by brianwernick** [comment]
@ehaahe I'm assuming this is in a 2.5.x release that you are doing this with?

**Comment by brianwernick** [comment]
See (https://github.com/brianwernick/ExoMedia/pull/131)

**Comment by eygraber** [comment]
Looks like [this commit](https://github.com/brianwernick/ExoMedia/commit/a2cb521ea6fd784a3ab2712b602a7c832975368f) broke this again. `EMVideoView.onPlaybackEnded` gets called after `EMExoPlayer.restart` overriding its call to `ExoPlayer.setPlayWhenReady(true)`. Not sure what the solution is. Maybe a flag in `EMExoPlayer` that maintains when media is being restarted, and if it is set, `EMExoPlayer.stop` will not have any effect?

**Comment by franklinexpress** [comment]
So how do I loop a video without have to reload from server? I restart video but see a blank screen on every restart

**Comment by brianwernick** [comment]
Seamless (and cached) looping isn't currently supported. ExoPlayer 2.0 introduced true seamless looping, but caching requires either a custom RenderBuilder or a caching proxy (see #328)

**Comment by Saketme** [comment]
@brianwernick Does the preview version support seamless looping?

**Comment by brianwernick** [comment]
Yes, see the `MediaSource` provided by the ExoPlayer

**Comment by Saketme** [comment]
@brianwernick how do I use `MediaSource` with `VideoView`?

**Comment by tohjg** [comment]
example of looping a video. hope it help.

`MediaSource videoSource = new ExtractorMediaSource(Uri.parse(VIDEO_SAMPLE_URL),
new DefaultDataSourceFactory(this, Util.getUserAgent(this, "MyApp")),
new DefaultExtractorsFactory(), null, null);
videoView.setVideoURI(null, new LoopingMediaSource(videoSource));`
