### ISSUE TITLE
Select audio track?

### ISSUE THREAD

**Issue by ebr11** [brianwernick/ExoMedia#126]
Is it possible to switch audio tracks during playback for straight playback sources like mkv/mp4?

I believe the underlying ExoPlayer added support for this last summer.  Is there a way to do it through EM?

Thanks.

**Comment by brianwernick** [comment]
Hmm, I remember looking at an issue (question) on the ExoPlayer a while ago about this but can't seem to find it again.  

Currently there is no support for this in ExoMedia, however you may be able to add the functionality yourself by providing a customized `RenderBuilder` when you set the Uri.  However without seeing how this support was added to the ExoPlayer I can't say for certain.

If you do end up finding the ExoPlayer issue would you link that here.

**Comment by ebr11** [comment]
Here you go.  Looks like it was put in in Sep.  Thanks!

https://github.com/google/ExoPlayer/issues/514

**Comment by brianwernick** [comment]
OK, Since this is a new feature it will be in one of the 3.x releases.  I would like to get it in 3.0 but I'm not making any promises.

(Sadly due to my schedule at work and with other personal things I can't give you a solid timeline for the release.  My best estimate would be 1 - 2 months at most)

**Comment by brianwernick** [comment]
I have updated the appropriate files to add the ability to select tracks (audio, video, cc, metadata).  See the linked PR for details.

**Comment by ebr11** [comment]
Thanks very much.

When do you expect 3.0 to make it to some sort of release on maven?

**Comment by brianwernick** [comment]
I'm trying to get the features and bugs with architecture changes done first so I can release a preview (hopefully in the next week or so).  I'm hoping that the full release will be fairly short afterwards (1 - 2 weeks?).
