### ISSUE TITLE
Can you force a downmix of AC3/DTS to stereo?

### ISSUE THREAD

**Issue by ebr11** [brianwernick/ExoMedia#127]
I have found that the device will report that it can handle full multi-channel streams even when connected to something like a TV that cannot.  When passing an AC3 or DTS stream to these devices there is just no sound.

Is it possible to set an option that will force a downmix of these audio streams to stereo and/or properly identify when the outbound equipment cannot support the stream?

**Comment by brianwernick** [comment]
Are you connecting via Bluetooth?

**Comment by ebr11** [comment]
No, this is with the device (Shield, Nexus Player) connected to a TV via HDMI.  If an AC3 or DTS stream is passed and the TV cannot handle it, there is no audio at all.

**Comment by brianwernick** [comment]
OK, I haven't tried this on a TV directly in quite some time (I usually go through a sound system).  I'm also unsure as to when this can be addressed.  If it is an easy fix then it will probably end up in a patch on the 2.5.x release cycle, however if it requires a decent amount of work (or architectural changes) it will be in a 3.x release.

**Comment by ebr11** [comment]
Okay.  Thanks.

If you are open to pull requests and can point me in the right direction (on both of these issues) I can take a look as well.

**Comment by brianwernick** [comment]
I'm always open to PR's.  I'll try to give you some direction later today

**Comment by ebr11** [comment]
Any further thoughts on this?  Plugging headphones into the Shield also results in no audio if something is being bitstreamed.

**Comment by brianwernick** [comment]
Sorry, I haven't even had enough time to look in to where we would register for audio output changes (or supported types).  This may be something that should be handled in the ExoPlayer library itself.

**Comment by brianwernick** [comment]
I have started working on a fix in [branch: issue_127](https://github.com/brianwernick/ExoMedia/tree/issue_127).  It looks like adding support for #126 would also allow us to fix this issue with a simple call.

**Comment by ebr11** [comment]
Awesome.  Thanks for the update.

**Comment by brianwernick** [comment]
This should be fixed in the next release
