### ISSUE TITLE
Got an error when invoke the start method in ViewHolder

### ISSUE THREAD

**Issue by daimajia** [brianwernick/ExoMedia#13]
```
java.lang.IllegalStateException: Handler (android.os.Handler) {ed82dba} sending message to a Handler on a dead thread
            at android.os.MessageQueue.enqueueMessage(MessageQueue.java:325)
            at android.os.Handler.enqueueMessage(Handler.java:631)
            at android.os.Handler.sendMessageAtTime(Handler.java:600)
            at android.os.Handler.sendMessageDelayed(Handler.java:570)
            at android.os.Handler.sendMessage(Handler.java:507)
            at android.os.Message.sendToTarget(Message.java:416)
            at com.google.android.exoplayer.ExoPlayerImplInternal.prepare(ExoPlayerImplInternal.java:132)
            at com.google.android.exoplayer.ExoPlayerImpl.prepare(ExoPlayerImpl.java:99)
            at com.devbrackets.android.exomedia.exoplayer.EMExoPlayer.onRenderers(EMExoPlayer.java:285)
            at com.devbrackets.android.exomedia.exoplayer.EMExoPlayer$InternalRendererBuilderCallback.onRenderers(EMExoPlayer.java:601)
            at com.devbrackets.android.exomedia.builder.RenderBuilder.buildRenderers(RenderBuilder.java:95)
            at com.devbrackets.android.exomedia.exoplayer.EMExoPlayer.prepare(EMExoPlayer.java:246)
            at com.devbrackets.android.exomedia.exoplayer.EMExoPlayer.replaceRenderBuilder(EMExoPlayer.java:146)
            at com.devbrackets.android.exomedia.EMVideoView.setVideoURI(EMVideoView.java:642)
            at com.devbrackets.android.exomedia.EMVideoView.setVideoURI(EMVideoView.java:624)
```

```java
mTitle.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                mEmVideoView.setOnPreparedListener(new MediaPlayer.OnPreparedListener() {
                    @Override
                    public void onPrepared(MediaPlayer mp) {
                        mEmVideoView.start();
                    }
                });
                mEmVideoView.setVideoURI(Uri.parse("http://.....................mp4"));
            }
        });
```

**Comment by daimajia** [comment]
Seems like this: https://github.com/google/ExoPlayer/issues/426

**Comment by brianwernick** [comment]
@daimajia Is this causing a crash, or is it just logged as described in the link you provided?

**Comment by daimajia** [comment]
When this happened, the video failed to play.

**Comment by daimajia** [comment]
It cause and error, but the app won't crash.

**Comment by daimajia** [comment]
I used the emvideoview in recyclerview, there are multiple emvideoview in the screen at the same time, I don't know if it is the reason?

**Comment by daimajia** [comment]
I found a simple solution: when dynamically add EMVideoView to the recyclerview item, it works.

**Comment by brianwernick** [comment]
@daimajia Seeing as you have a temporary workaround I'll leave this until I get some time to look in to it.  Though It may be something that comes from the ExoPlayer so I may not be able to fix it.

**Comment by eneim** [comment]
Hm I'm working on the same thing with @daimajia . It turns out that your EMVideoView will release the ```exoPlayer``` in ```onDetachedFromWindow```, therefore the VideoView will no longer be useable after that point. Don't have any good idea for this now, but please consider to improve this :D. Is that safe to not release the player after the view got detached? I deeply understand that it may cause the memory leak of the Player, we can think about this for a better solution. Best Regards!

**Comment by daimajia** [comment]
@eneim 
This lib made by @brianwernick is really awesome, good design pattern, clear code, and documentation. While I think the ExoPlayer itself is buggy, there is so many bugs exist. 

I actually recommend [ijkPlayer](https://github.com/Bilibili/ijkplayer), which is the best player as far as I know. 

I really didn't mean that this lib is not good, it's the problem of google's exoplayer. Hope @brianwernick don't misunderstand.

**Comment by eneim** [comment]
@daimajia I agree. I read his implementation and had a good impression though. Actually I tried to dynamically add the EMVideoView to recyclerview's viewholder but still could not make it works. Could you please share your snippet ? @daimajia . Furthermore, I know about ijkPlayer, but IMO, it's about a codec based player, which provides a lot more functions than ExoPlayer/EMVideoView. So I don't think it fits my requirement for now. Hope @brianwernick could fix this.

**Comment by daimajia** [comment]
@eneim I tried varias method to solved that, but there still a lot problems. It can not work corretly on some kind of devices. For example, only audio, no video... This is the problem of ExoPlayer. So I recommend to use ijkPlayer.

**Comment by brianwernick** [comment]
I've added a method to allow disabling the releasing of resources in `onDetachedFromWindow()` https://github.com/brianwernick/ExoMedia/commit/ac950d9d6a21a24116482b6dd0fe57b4558ebeb9.  

On the other topic; I understand that there are many other libraries out there the handle a much broader range of devices.  My main focus for this library was to simplify interaction with the ExoPlayer which isn't supported on many devices (usually if they don't have the Play Store then they don't pass the CTS and therefore don't support the ExoPlayer).

Thanks for the interesting discussion, but since I have added a solution I will close the bug.

**Comment by eneim** [comment]
Thank @brianwernick , can't wait to check it out.

**Comment by daimajia** [comment]
@brianwernick  Thanks a lot!

**Comment by oximer** [comment]
@brianwernick after using method setReleaseOnDetachFromWindow, if I scroll down and comeback to the same video and try to play it again, I have a black screen for the first seconds of the video. Have you notice it?

**Comment by Iamtodor** [comment]
Yeah. Faced with this problem too. Want to approve those bug from @oximer Also, I have 10 video items and I can't play the last two. How can I fix this @brianwernick ?

**Comment by brianwernick** [comment]
@Iamtodor See [128_c-196608092](https://github.com/brianwernick/ExoMedia/issues/128#issuecomment-196608092) for a description on what you should be doing.
