### ISSUE TITLE
TextureVideoView Starts Without Calling Start

### ISSUE THREAD

**Issue by eygraber** [brianwernick/ExoMedia#130]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests

###### Include the following:
 - ExoMedia version: `3.0.0`
 - Device OS version: `5.1.1`
 - Devide Manufacturer: `Motorola`
 - Device Name: `Droid Turbo`
 
###### Reproduction Steps
 0.  Use `exomedia_default_native_video_view` as the `videoViewApiImpl` for a `EMVideoView`
 1.  Call `EMVideoView.setVideoURI`

###### Expected Result
  Nothing happens until `EMVideoView.start` is called

###### Actual Result
  When [`onSurfaceTextureSizeChanged`](https://github.com/brianwernick/ExoMedia/blob/3.0/library/src/main/java/com/devbrackets/android/exomedia/core/video/TextureVideoView.java#L522) is called, it calls `start()`, and the video starts playing.

**Comment by brianwernick** [comment]
This was fixed in https://github.com/brianwernick/ExoMedia/pull/138
