### ISSUE TITLE
Javadoc failing bintrayUpload

### ISSUE THREAD

**Issue by eygraber** [brianwernick/ExoMedia#132]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests

###### Include the following:
 - ExoMedia version: `3.0.0`
 
###### Reproduction Steps
1.  Run `gradlew clean build bintrayUpload -PbintrayUser=BINTRAY_USERNAME -PbintrayKey=BINTRAY_KEY -PdryRun=false` (with `BINTRAY_USERNAME` and `BINTRAY_KEY` replaced of course)

###### Expected Result
1.  The library will be built and uploaded to bintray

###### Actual Result
1.  The build fails with the following output:

```
:library:androidJavadocs FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':library:androidJavadocs'.
```

**Comment by brianwernick** [comment]
Does your machine running JDK 7 or JDK 8 (there are different paragraph and br tag rules).

With Java 7 you could have `<p/>`
Whereas with Java 8 you need to use the incorrectly formatted `<p>` with no end tag (you can also use an end tag if you wish)

**Comment by eygraber** [comment]
Interesting. I'm running 8.

**Comment by brianwernick** [comment]
See (https://github.com/brianwernick/ExoMedia/pull/133)
