### ISSUE TITLE
Restart fails if ExoPlayer is in STATE_ENDED

### ISSUE THREAD

**Issue by eygraber** [brianwernick/ExoMedia#134]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests

###### Include the following:
 - ExoMedia version: `3.0.0`
 
###### Reproduction Steps
 1.  Call `ExoPlayer.restart` from `OnCompletionListener.onComplete`

###### Expected Result
 1. The media is restarted

###### Actual Result
 1. The call to restart fails because `ExoPlayer` is not in `ExoPlayer.STATE_IDLE`, but is in `ExoPlayer.STATE_ENDED`

**Comment by brianwernick** [comment]
See (https://github.com/brianwernick/ExoMedia/pull/135)
