### ISSUE TITLE
compile 'com.devbrackets.android:exomedia:3.0.0' can not be resolved

### ISSUE THREAD

**Issue by LiuDeng** [brianwernick/ExoMedia#146]
com.devbrackets.android:exomedia:3.0.0 is not in jcenter

**Comment by TonyTangAndroid** [comment]
It has not been released yet. If you have to use 3.0.0, you are suggested to reference the library using [jitpack.io](https://jitpack.io/).

**Comment by brianwernick** [comment]
Once I finish up the architecture changes I will publish a beta or preview to JCenter, until then you can either use the above jitpack idea or publish it to your local maven with `./gradlew clean build aRel uploadArchives`

**Comment by brianwernick** [comment]
There is now a preview release of 3.0.0 (`compile "com.devbrackets.android:exomedia:3.0.0-preview1"`)
