### ISSUE TITLE
Add checkstyle tests

### ISSUE THREAD

**Issue by se-bastiaan** [brianwernick/ExoMedia#149]
I noticed that a style guide page appeared on the wiki. Would it be a good idea to include [checkstyle](http://checkstyle.sourceforge.net/) tests?

[artem-zinnatullin/qualitymatters/code_quality_tools/quality.gradle](https://github.com/artem-zinnatullin/qualitymatters/blob/master/code_quality_tools/quality.gradle) is a good example of how to add this to the project. In the case you setup a CI using (for example) Travis you can have it run the codestyle tests to make sure PR's follow it.

**Comment by brianwernick** [comment]
I've wanted to look in to adding style checking for a while, however I need to finish updating the style guide and get a CI server set up.  This is lower on my priority list right now though
