### ISSUE TITLE
Can't open Activity from Notification bar. (But Lock screen works)

### ISSUE THREAD

**Issue by Thanhktm** [brianwernick/ExoMedia#15]
Hi.

I tried newest version 2.3.3 and I found that when I press notification on status bar it's not open my activity like version 2.3.2.

Please help me fix the problem.

Thanks.

**Comment by brianwernick** [comment]
Looking in to it a little more, it looks like the small notification still correctly launches the passed pending intent, but the large notification does not.

**Comment by brianwernick** [comment]
@Thanhktm This has been fixed, and will be in the next release.

https://github.com/brianwernick/ExoMedia/commit/9ec42c6163515e585a5a1428f578ae7f88efae9d
