### ISSUE TITLE
How to repeat playing song?

### ISSUE THREAD

**Issue by sujitkjha** [brianwernick/ExoMedia#154]
I have achieved all the functionality thou I can't able to change the controller, understood that can't be done, so I'm going with the same default controller, in next version of the app I will update the controller when I use Exomedia 3.0 but for now I want to add repeat functionality so that user can listen the same track, please guide me how to repeat the playing song. 
I'm very new in android so please explain me with demo app. 

![audio-player](https://cloud.githubusercontent.com/assets/8043974/14099249/8dadc326-f5a3-11e5-9bae-1486dfc8e199.jpg)

**Comment by brianwernick** [comment]
https://github.com/brianwernick/ExoMedia/issues/106
