### ISSUE TITLE
Add ability to specify ReBuffer length

### ISSUE THREAD

**Issue by bkhall** [brianwernick/ExoMedia#157]
- [ x ] I have verified there are no duplicate active or recent bugs, questions, or requests
###### Include the following:
- ExoMedia version: `2.5.5`
- Device OS version: `6.0`
- Devide Manufacturer: `Samsung`
- Device Name: `Galaxy S6`
###### Reproduction Steps

 Start a remote stream, especially on a slow or low bandwidth (cell) connection.  
###### Expected Result

Starts playing
###### Actual Result

Buffers indefinitely, may eventually play.

Reference:
https://github.com/google/ExoPlayer/issues/1285

It seems your library either needs to set minRebufferMs to 0 or expose it so we can manipulate it to work around the ExoPlayer issue.

**Comment by brianwernick** [comment]
Currently it is expected that the media won't play until you get some amount of media to play.  In your case where it will sometimes play to me this means that you just need to wait (and it isn't actually in Buffering indefinitely).  As such, the ability to override `player = ExoPlayer.Factory.newInstance(RENDER_COUNT, BUFFER_LENGTH_MIN, REBUFFER_LENGTH_MIN);` or specify the `REBUFFER_LENGTH_MIN` will be a future feature

**Comment by bkhall** [comment]
Of course...

However it's impossible to know the difference between, just wait, and never starts. The instances where we just waiting works, is on the order of minutes, sometimes tens of minutes, Most users just bail and fail into the never starts complaint.

So, I'll have to fork and mod it myself until it gets fixed, by either you or ExoPlayer.

But at least you know about it now.

**Comment by brianwernick** [comment]
You are always welcome to make the change and create a PR against the 3.0 branch as well.
