### ISSUE TITLE
Exomedia 3.0, gradle dependence is not resolved 

### ISSUE THREAD

**Issue by sujitkjha** [brianwernick/ExoMedia#160]
compile 'com.devbrackets.android:exomedia:3.0.0' is not resolved in android studio 1.5.1 ???

**Comment by brianwernick** [comment]
Duplicate of #146

**Comment by brianwernick** [comment]
There is now a preview release of 3.0.0 (`compile "com.devbrackets.android:exomedia:3.0.0-preview1"`)

**Comment by sujitkjha** [comment]
While running demo app so many dependency is not recognized and  so many place it says method need to override some method and all, please have a look to demo app @brianwernick
