### ISSUE TITLE
m3u8 keep playing the track even track finished 

### ISSUE THREAD

**Issue by sujitkjha** [brianwernick/ExoMedia#166]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests

###### Include the following:
 - ExoMedia version: `2.5.6`
 - Device OS version: `5.0.2`
 - Devide Manufacturer: `Samsung`
 - Device Name: `Galaxy Tab A
 
###### Reproduction Steps
While playing m3u8 (mp4), it will keep playing beyond the size of the the audio file.

###### Expected Result

It should play next audio, having m3u8 (mp4) url in the same playlist

###### Actual Result
bug

----

I'm using m3u8 link to populate the playlist but the player wont play the second song as the first played song keep playing after the track size get finished. Timer keep increasing. 

I have override the method  
```java
@Override
protected void performMediaCompletion() {
    super.performMediaCompletion();
    Log.e("Yaha aayo next time","Next Time yaha aayo");
    performNext();
    immediatelyPause = false;
}
```
 but still seebar keep ticking more then what the value of the end seekbar

**Comment by sujitkjha** [comment]
I hope you will guide me solving this problem, as I have used your great library for my company app and I have implemented all the required functionality so far with Exomedia library.

**Comment by brianwernick** [comment]
Please provide the information requested in the issue template

**Comment by brianwernick** [comment]
Also, if you plug your m3u8 url in to the `demo` it should work correctly so It is probably just a setup issue with linking the VideoView to the PlaylistService

**Comment by sujitkjha** [comment]
I have checked the same issue with the demo app provided with Exomedia Liberary -2.5.5 and got the same issue

**Comment by sujitkjha** [comment]
Exomedia can play video M3U8 streams wrapped (mp4) but can not play the m3u8 wrapped (mp3). I have checked with VLC in android and window, both URL get played without any problem. I have devices like android 4.2, 5.02 and others

**Comment by sujitkjha** [comment]
Here is two different link for your review, please check with the demo app,Now I'm having new issue  that it can play first URl of mp4 but wont play second url of mp3

1. http://nettv.truestreamz.com:8081/nettvmovies/mobile/hindi/ABCD2.mp4/playlist.m3u8?wmsAuthSign=c2VydmVyX3RpbWU9NC84LzIwMTYgNToxMjowMiBBTSZoYXNoX3ZhbHVlPUpkQ0lqc0FQOTk5VDgrTUtLU0hEVnc9PSZ2YWxpZG1pbnV0ZXM9NTAwMA==

2. http://202.166.193.113:8081/music/ActionJackson.mp3/playlist.m3u8?wmsAuthSign=c2VydmVyX3RpbWU9NC84LzIwMTYgNToxMjowMiBBTSZoYXNoX3ZhbHVlPUpkQ0lqc0FQOTk5VDgrTUtLU0hEVnc9PSZ2YWxpZG1pbnV0ZXM9NTAwMA==

**Comment by sujitkjha** [comment]
Error 

W/VideoCapabilities: Unrecognized profile 2130706433 for video/avc
04-08 11:26:14.974 31892-32042/com.devbrackets.android.exomediademo W/AudioCapabilities: Unsupported mime audio/evrc
04-08 11:26:14.974 31892-32042/com.devbrackets.android.exomediademo W/AudioCapabilities: Unsupported mime audio/qcelp
04-08 11:26:14.974 31892-32042/com.devbrackets.android.exomediademo W/AudioCapabilities: Unsupported mime audio/mpeg-L1
04-08 11:26:14.974 31892-32042/com.devbrackets.android.exomediademo W/AudioCapabilities: Unsupported mime audio/mpeg-L2
04-08 11:26:14.984 31892-32042/com.devbrackets.android.exomediademo W/AudioCapabilities: Unsupported mime audio/x-ms-wma
04-08 11:26:14.984 31892-32042/com.devbrackets.android.exomediademo W/AudioCapabilities: Unsupported mime audio/x-ima
04-08 11:26:14.984 31892-32042/com.devbrackets.android.exomediademo W/AudioCapabilities: Unsupported mime audio/qcelp
04-08 11:26:14.994 31892-32042/com.devbrackets.android.exomediademo W/AudioCapabilities: Unsupported mime audio/evrc
04-08 11:26:15.014 31892-32042/com.devbrackets.android.exomediademo W/VideoCapabilities: Unsupported mime video/wvc1
04-08 11:26:15.014 31892-32042/com.devbrackets.android.exomediademo W/VideoCapabilities: Unsupported mime video/x-ms-wmv
04-08 11:26:15.034 31892-31892/com.devbrackets.android.exomediademo D/EMLockScreen: update, controller is null ? false
04-08 11:26:15.044 31892-32042/com.devbrackets.android.exomediademo W/VideoCapabilities: Unrecognized profile/level 32768/2 for video/mp4v-es
04-08 11:26:15.044 31892-32042/com.devbrackets.android.exomediademo W/VideoCapabilities: Unsupported mime video/wvc1
04-08 11:26:15.054 31892-31907/com.devbrackets.android.exomediademo I/art: Background partial concurrent mark sweep GC freed 20492(930KB) AllocSpace objects, 8(288KB) LOS objects, 44% free, 4MB/8MB, paused 6.529ms total 50.170ms
04-08 11:26:15.054 31892-32042/com.devbrackets.android.exomediademo W/VideoCapabilities: Unsupported mime video/x-ms-wmv
04-08 11:26:15.064 31892-32042/com.devbrackets.android.exomediademo W/VideoCapabilities: Unsupported mime video/x-ms-wmv7
04-08 11:26:15.064 31892-32042/com.devbrackets.android.exomediademo W/VideoCapabilities: Unsupported mime video/x-ms-wmv8
04-08 11:26:15.074 31892-32042/com.devbrackets.android.exomediademo W/VideoCapabilities: Unsupported mime video/mp43
04-08 11:26:15.084 31892-32042/com.devbrackets.android.exomediademo W/VideoCapabilities: Unsupported mime video/sorenson
04-08 11:26:15.094 31892-32042/com.devbrackets.android.exomediademo W/VideoCapabilities: Unsupported mime video/mp4v-esdp
04-08 11:26:15.114 31892-32042/com.devbrackets.android.exomediademo I/VideoCapabilities: Unsupported profile 4 for video/mp4v-es

**Comment by sujitkjha** [comment]
#169 for device specification

**Comment by brianwernick** [comment]
As far as the original (first) issue goes, I can't access the URL you provided but it sounds like the M3U8 file doesn't specify the duration or specifies an incorrect duration.  In my experience many M3U files don't include the duration.

The reason the second URL is not playing is because it contains no supported audio file types (this is from the ExoPlayer)

**Comment by brianwernick** [comment]
Linking in the ExoPlayer bug https://github.com/google/ExoPlayer/issues/1436
