### ISSUE TITLE
M3u8, file type keep playing beound the size 

### ISSUE THREAD

**Issue by sujitkjha** [brianwernick/ExoMedia#169]
- [Yes ] I have verified there are no duplicate active or recent bugs, questions, or requests

###### Include the following:
 - ExoMedia version: `2.5.6`
 - Device OS version: `5.0.2`
 - Devide Manufacturer: `Samsung`
 - Device Name: `Galaxy Tab A
 
###### Reproduction Steps
While playing m3u8 (mp4), it will keep playing beyond the size of the the audio file.

###### Expected Result

It should play next audio, having m3u8 (mp4) url in the same playlist

###### Actual Result
bug

**Comment by brianwernick** [comment]
I have moved the template information to the original issue #166
