### ISSUE TITLE
Play the audio with skipping certain time will keep the loading progress bar showing

### ISSUE THREAD

**Issue by TonyTangAndroid** [brianwernick/ExoMedia#175]
- [ ] I have verified there are no duplicate active or recent bugs, questions, or requests

###### Include the following:
 - ExoMedia version: `3.0`
 - Device OS version: `6.0`
 - Devide Manufacturer: `LG`
 - Device Name: `Nexus 5`
 
###### Reproduction Steps
 0.  change the method 
`            playlistManager.play(0, false);
` in `AudioPlayerActivity.java`
to
`            playlistManager.play(50 * 1000, false);
`

1. Play the audio, the loading progress bar will be keeping showing because the last playback state update is SEEKING rather than play.

###### Expected Result
 the loading progress bar disappears and plays the audio starting with 50 seconds. 
###### Actual Result
 the loading progress bar did not disappear but the audio starts with 50 seconds.

**Comment by brianwernick** [comment]
This sounds like an issue in `PlaylistCore` so please log it in the correct project.  (Or is this an issue with the `demo`?)

**Comment by TonyTangAndroid** [comment]
Yes, it is an issue in PlaylistCore. I have reproduced it there and logged issue. We could close this one.
