### ISSUE TITLE
Custom PlayList

### ISSUE THREAD

**Issue by powerthazan** [brianwernick/ExoMedia#176]
How to create a Playlist which contains Video URLs? I saw your demo. But You used custom class to make list. I want to make list in player activity with Extra bundles from previous activity.
Please show example code.

**Comment by brianwernick** [comment]
see https://github.com/brianwernick/ExoMedia/issues/70 and https://github.com/brianwernick/ExoMedia/issues/74

**Comment by powerthazan** [comment]
I followed following way
`private final List<String> videoList = new LinkedList<>();`
`videoList.add(VideoURL);`
`videoList.add(VideoURL2);`
`videoList.add(VideoURL3);`

Then,
`EMPlaylistManager playlistManager;`
 `playlistManager.setParameters(mediaItems, selectedIndex);`
` playlistManager.setPlaylistId(PLAYLIST_ID);`

Finelly,
`playlistManager.setVideoView(emVideoView);`
`playlistManager.play(0, false);`

But I got Null point error on  `playlistManager.setParameters(mediaItems, selectedIndex);` line.
