### ISSUE TITLE
Can't restart playback once it's ended on Android N

### ISSUE THREAD

**Issue by afollestad** [brianwernick/ExoMedia#180]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests

###### Include the following:
 - ExoMedia version: `2.5.6` and `3.0.0-preview1``
 - Device OS version: `N`
 - Devide Manufacturer: `Huawei`
 - Device Name: `Nexus 6P`
 
###### Reproduction Steps
 1.  Start video playback
 2.  Wait until it completes
 3.  `seekTo(0)` and `start()`

###### Expected Result

The video should be back at the start and begin playback.

###### Actual Result

The `EMVideoView` is black and playback does not restart.

**Comment by afollestad** [comment]
I did see a closed issue too, but I saw that it was merged, so I thought it might be possible it was included in 3.0.0-preview1 and doesn't work.

**Comment by brianwernick** [comment]
You should be using what is described in https://github.com/brianwernick/ExoMedia/issues/134.  If that doesn't work then let me know

**Comment by afollestad** [comment]
I should've looked more into that. Sorry for the duplicate!

**Comment by brianwernick** [comment]
No problem, the naming of the bug is slightly off (I only found it again because I knew it was there)

**Comment by afollestad** [comment]
@brianwernick a small suggestion though, for being intuitiveness for others: it would be nice if `seekTo(0)` would automatically make a call to `restart()` IF playback had been completed. That used to work, not sure what has changed.

**Comment by brianwernick** [comment]
Yeah, that might be something to consider.  The reason it used to work was the ExoMedia was (incorrectly) not calling `emExoPlayer.stop()` when playback was completed.  Not being able to seek and play is a side effect of that (I think `2.5.4` was the first version to correct this)
