### ISSUE TITLE
Next song not getting played

### ISSUE THREAD

**Issue by sujitkjha** [brianwernick/ExoMedia#186]
Dear Sir,
I am using exomedia 3.0.0, I have created the playlist but next track is not getting played???
Could you please guide me how to play next song automatically after first song finished.

**Comment by brianwernick** [comment]
3.0 doesn't have built in playlist support... Are you using `PlaylistCore`?

**Comment by sujitkjha** [comment]
Yes, I am trying to get that functionality in Demo app

**Comment by brianwernick** [comment]
The question should be on that library then (and please follow the issue templates)

**Comment by sujitkjha** [comment]
sure! I have achieved the functionality thou, I will follow the templates and write in the respected branch from the next time. Thank you for your great library
