### ISSUE TITLE
Possible NPE in textContainer

### ISSUE THREAD

**Issue by codeteo** [brianwernick/ExoMedia#193]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests

###### Include the following:
 - ExoMedia version: `3.0.0-preview1`
 - Device OS version: `any version`
 - Devide Manufacturer: `Huawei`
 - Device Name: `Nexus 6P`
 
Hi @brianwernick 

I'm trying to extend VideoControlsMobile class so I can add an extra view (full screen Button) to my controls.
The problem is that I'm getting a NPE in `textContainer`. I understand that this is an issue for StackOverflow and I posted it [there](http://stackoverflow.com/questions/37013181/npe-when-extending-videocontrolsmobile-class) but since I can verify that `controlsContainer` is **not** null and they are both in the same file ( exomedia_default_controls_mobile ) I was thinking that maybe there's a bug somewhere ? 

Thanks,
Teo

**Comment by brianwernick** [comment]
Is there a reason you aren't using `addExtraView(@NonNull View view)` or overriding many methods without calling `super.xxx()`?

**Comment by codeteo** [comment]
I didn't noticed there was an `addExtraView(@NonNull View view)` method.
Thanks
