### ISSUE TITLE
Touch listener problems in landscape

### ISSUE THREAD

**Issue by AbdelrahmanSalem** [brianwernick/ExoMedia#196]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests

###### Include the following:
 - ExoMedia version: `2.5.6`
 - Device OS version: `6.0`,`5.0.1`
 - Devide Manufacturer: `LG`
 - Device Name: `G4`,`G3`
 
###### Reproduction Steps
 0. Play a video
 1. Rotate to landscape
 2. When the bottom bar not visible 
 3. try tapping on the right half
 4. the controls don't show 

###### Expected Result
The expected result is for the default controls to show

###### Actual Result
The default controls dont show up

It is a strange bug since it is not reproduced on other devices like Lenovo yoga tab, sony Xperia s, sony Xperia z3, nexus 5,Samsung note 3 and on emulators. It only occurs on LG devices

**Comment by brianwernick** [comment]
Would you be willing to test this with the current demo app (which is using 3.0.0-preview1)?
