### ISSUE TITLE
Custom AudioTrackRenderer

### ISSUE THREAD

**Issue by nienlm-hhtv** [brianwernick/ExoMedia#198]
- [ Yes] I have verified there are no duplicate active or recent bugs, questions, or requests

###### Include the following:
 - ExoMedia version: `r1.5.7`
 - Device OS version: `4.4.2`
 - Devide Manufacturer: `Samsung`
 - Device Name: `Galaxy note 3`
 
###### Reproduction Steps
 0.  I use a custom TrackRenderer from this link: https://github.com/skonb/MediaCodecSpeedControllableTrackRenderer/blob/master/MediaCodecSpeedControllableAudioTrackRenderer.java

###### Expected Result
I want to find the way to set the custom TrackRenderer

###### Actual Result
I could'n find any method to set the custom TrackRenderer.

**Comment by brianwernick** [comment]
There isn't a `r1.5.7` of ExoMedia (It looks like you put the ExoPlayer version) however in the 2.5.x versions there is the ability to specify your own `RenderBuilder` when specifying a URI.  You can override the expected one from ExoMedia and use the linked AudioTrackRenderer

**Comment by nienlm-hhtv** [comment]
Thankyou ! I'll try.
