### ISSUE TITLE
Show Close Captioning

### ISSUE THREAD

**Issue by hcoderonly** [brianwernick/ExoMedia#203]
Hi, I am unable to find any help in showing close captioning for a HLS Video.
I am getting a HLS Video, I can play it, but I do not know how I can show the subtitles/ Close captions?
if you can point me to any helpful guide that will be great.
Thanks

**Comment by brianwernick** [comment]
Currently subtitles aren't supported out of the box (see #115), however in 3.0 you can provide your own support by overriding the `VideoViewApi` implementation used for the ExoPlayer (`ExoVideoView`) and linking your own functionality (see `getVideoViewApiImplementation(...)` in the `EMVideoView`) with

```java
@Override
protected void setup() {
    super.setup();

    emExoPlayer.setCaptionListener(new CaptionListener() {
        @Override
        public void onCues(List<Cue> cues) {
            //Your Subtitle functionality here
        }
    });
}
```
