### ISSUE TITLE
does it support fullscreen ?

### ISSUE THREAD

**Issue by srinivas3120** [brianwernick/ExoMedia#204]
- [ ] I have verified there are no duplicate active or recent bugs, questions, or requests

###### Include the following:
 - ExoMedia version: `2.5.5`
 - Device OS version: `6.0`
 - Devide Manufacturer: `Huawei`
 - Device Name: `Nexus 6P`
 
###### Reproduction Steps
 0.

**Comment by brianwernick** [comment]
see #119, or see the Demo application
