### ISSUE TITLE
Ability to change playback speed for audio and video

### ISSUE THREAD

**Issue by faizan-tariq-confiz** [brianwernick/ExoMedia#207]
The ability to change playback speed for audio and video should be added. ExoPlayer already have this functionality and its simple to add this functionality. Are you planing to add this later on? If not then i can add this functionality and send you a commit request.

**Comment by brianwernick** [comment]
Reading the threads on ExoPlayer, the playback speed functionality is only supported on API 23+.  Unless I missed a thread this isn't something that would be worth supporting currently.

That being said, you can provide your own `RenderBuilder` implementation with a custom `AudioTrackRenderer` to handle the playback speed changes (there are a couple third party implementations you can use)

**Comment by faizan-tariq-confiz** [comment]
Thanks a lot for your quick response. I will surely follow what you have suggested and get back to you in case i need any further suggestion. Many thanks

**Comment by euroclydon37** [comment]
@brianwernick, what are the chances that I could get you to help me implement this feature? I'm on a deadline with a project that has to have it, and I'm new to handling media, especially in Android.

**Comment by brianwernick** [comment]
I can't really help you much more that what is in this thread. If you have specific questions while you work on it (that aren't readily answered in general) then feel free to open a new issue

**Comment by faizan-tariq-confiz** [comment]
HI @brianwernick ,

Any updates from your side on this? After the release of Android N, are you planning to add this functionality?

**Comment by brianwernick** [comment]
With the projects MinSdk being much lower than API 23 it isn't worth it currently to add the support for this. It's something I would love to have but with my limited amount of time I can't prioritize it above other issues/features. If you (or someone else) wants to update the project to support it then that would be great
