### ISSUE TITLE
VideoControls don't abide by seek state (loading not shown while seeking)

### ISSUE THREAD

**Issue by brianwernick** [brianwernick/ExoMedia#210]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests

###### Include the following:
 - ExoMedia version: `3.0.0-preview1`
 - Device OS version: `6.0`
 - Devide Manufacturer: `Huawei`
 - Device Name: `Nexus 6P`
 
###### Reproduction Steps
 0. Open the Demo application and select one of the videos (not a live stream one)
 1. Wait until the video starts to play
 2. Drag the seek bar to a different position

###### Expected Result
The `VideoControls` display the loading progress until the seek has completed

###### Actual Result
The `VideoControls` don't show the loading progress and act as though the seek has completed

**Comment by billyjoker** [comment]
###### My Fix:

**EMVideoView**:

```
    public void seekTo(int milliSeconds) {
        videoControls.setLoading(true);
        videoViewImpl.seekTo(milliSeconds);
    }

```

EMVideoView -> **MuxNotifier**:

```
    protected class MuxNotifier extends EMListenerMux.EMListenerMuxNotifier {
      ....
        /**
         * Defined abstract at EMListenerMuxNotifier
         */
        @Override
        public void onSeekCompletion() {
            Log.i(TAG, "muxNotifier onSeekCompletion");
            videoControls.setLoading(false);
            onSeekCompletionPlugin();
        }
      ...

```

**EMListenerMuxNotifier :**

```
public static abstract class EMListenerMuxNotifier {
...
    public abstract void onSeekCompletion();
...
}
```

**Comment by brianwernick** [comment]
I started a branch a while ago with very similar changes, however there are a few other areas that need to be handled and cleaned up including:
* Not hiding the controls when loading (currently they will still hide after the standard delay)
* The transition between the loading state and ready needs to be cleaned up
* The organization of the `VideoControls` (and sub-classes) needs to be cleaned up a bit to handle the above cases
