### ISSUE TITLE
Rotation Issue

### ISSUE THREAD

**Issue by volser** [brianwernick/ExoMedia#212]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests

###### Include the following:
 - ExoMedia version: `3.0.0-preview1`
 - Device OS version: `4.4`
 - Devide Manufacturer: `Xiaomi`
 - Device Name: `Mi4`
 
###### Reproduction Steps
Sample video:
https://drive.google.com/file/d/0BwgmgDZTQevyT2NUV2VDQWJwc1NMWWhXYnE5YWpMbE9Uem9r/view?usp=sharing

```java
videoView.setScaleType(ScaleType.CENTER_CROP);
videoView.setOnCompletionListener(new OnCompletionListener() {
                        @Override
                        public void onCompletion() {
                            videoView.restart();
                        }
                    });
videoView.setVideoURI(fileUri);
videoView.start();
```

###### Expected Result
Correct rotation and scale

###### Actual Result
1. setScaleType(ScaleType.CENTER_CROP); doesn't work correctly
2. After .restart() video are rotated again (90, 180, 270, ....)

https://drive.google.com/file/d/0BwgmgDZTQevyUy1xT3U4WVJCb0o2UHdzV09RSGVqZUcwdGNR/view?usp=sharing

**Comment by brianwernick** [comment]
I'm unable to reproduce this on 4.3 and 4.4 devices.  It may be an issue with the Mi4 or Xiaomi in general as I don't have any devices from them

**Comment by volser** [comment]
I made a branch. And with this MatrixManager work properly
https://github.com/volser/ExoMedia/blob/master/library/src/main/java/com/devbrackets/android/exomedia/core/video/scale/MatrixManager.java

**Comment by volser** [comment]
Can you check my test branch on your devices?

**Comment by volser** [comment]
To reproduce this on emulator 4.4 just add line in Samples.java

videoSamples.add(new Sample("My video", "https://drive.google.com/uc?export=download&id=0BwgmgDZTQevyT2NUV2VDQWJwc1NMWWhXYnE5YWpMbE9Uem9r"));

screenshot:
http://prntscr.com/bak725

**Comment by volser** [comment]
#220

**Comment by brianwernick** [comment]
If you use the master branch and just comment out line 34 (`view.getTransform(transformMatrix);`) in the MatrixManager instead of your changes, does that resolve the issue?  

So far this seems to be a device specific issue, so unless we can find a clean solution I don't want to change how this is being applied just yet.

**Comment by volser** [comment]
No, it doesn't resolve.

There few issues:
1. view.getTransform(transformMatrix);
You are right, if rotate() or scale() calls few times (for example after restart or after setScale) transformation applies few times (rotation effect after restart())

**Comment by volser** [comment]
2. After rotate wrong aspect ratio. 
example: 
http://prntscr.com/bak725

to fix that:
```
if (view.getRotation() == ROTATION_90 || view.getRotation() == ROTATION_270){
           float scaleTemp = xScale;
             xScale = yScale *  view.getHeight() / view.getWidth();
             yScale = scaleTemp *  view.getWidth() / view.getHeight();
         }
```

**Comment by volser** [comment]
3 Transformation order.
Correct order: rotate then scale
In your implementation, transformation order not fixed

**Comment by volser** [comment]
4 Some times rotate() not calls.
When matrix not ready yet but layout requested already.
To fix this:
```
protected boolean updateVideoSize(int width, int height) {
          matrixManager.setIntrinsicVideoSize(width, height);		          matrixManager.setIntrinsicVideoSize(width, height);
 
         updateRotateScale(); //IMPORTANT!!!
...
```

**Comment by volser** [comment]
"So far this seems to be a device specific issue, so unless we can find a clean solution I don't want to change how this is being applied just yet."

It's not device specific.
You can reproduce this on Android emulator API19.

Video for test:
videoSamples.add(new Sample("My video", "https://drive.google.com/uc?export=download&id=0BwgmgDZTQevyT2NUV2VDQWJwc1NMWWhXYnE5YWpMbE9Uem9r"));

result (wrong aspect ratio):
http://prntscr.com/bak725

**Comment by brianwernick** [comment]
As I have said before, I'm unable to reproduce the rotation issue.  Linking the same video multiple times doesn't change that fact; as such it seems to be device specific.

Now, because you never mentioned that you were seeing scaling issues before 40 minutes ago how was I supposed to know that's what you were referring to?

I agree that there seems to be an issue with scaling, but the other "issues" don't exist (or are symptoms of the original).  Specifically ordering, currently we perform scaling then rotation which is why we don't worry about the rotation amount (nor should we ever have to update the rotation after the video size is updated for many reasons, but I don't have the time to explain it right now)

**Comment by brianwernick** [comment]
I just realized reading that again, It may have come off a little cross; that wasn't my intent. 

Anyways, as far as the scaling is concerned, it looks like [EMVideoView.java#L755](https://github.com/brianwernick/ExoMedia/blob/master/library/src/main/java/com/devbrackets/android/exomedia/ui/widget/EMVideoView.java#L755) is the main culprit of the incorrect sizing.  I'll perform some additional testing to see if it can be removed.

**Comment by brianwernick** [comment]
As per the update, would you mind checking out master again and testing with your mi4.  I didn't change how the `MatrixManager` was performing the scaling like you did in your PR because I'm not certain that is needed anymore.

**Comment by volser** [comment]
Oh man... Forget about mi4. 

I reproduced the issue on "android device emulator".

Last your update resolved only 2, may be 3. But not 1 and 4.

Issue 1 (rotation effect):
https://drive.google.com/file/d/0BwgmgDZTQevybE1wQ1NuaWRCLUpHSjd6LUhVWVZrbmRGcUln/view?usp=sharing

Because, view.getTransform(transformMatrix); multiply rotation

Issue 4: Sometimes I had this result (lost first rotation + rotation effect)
https://drive.google.com/file/d/0BwgmgDZTQevyVEFCaVhEMnJ3M1oyb2lQd2VmTGhFWi1hOVE4/view?usp=sharing

setVideoRotation() called when matrix not ready yet but layout requested already and GlobalLayoutMatrixListener.onGlobalLayout was not called

Your comment
/**
     * Requests for the Matrix to be updated on layout changes.  This will
     * ensure that the scaling is correct and the rotation is not lost or
     * applied incorrectly.
     */
But rotation sometimes lost



My PR (correct result):
https://drive.google.com/file/d/0BwgmgDZTQevyV0xWS0x6X25OMGk1d1Z1U1hRaUpNY09iaEl3/view?usp=sharing

**Comment by volser** [comment]
please, also revert this commit
https://github.com/brianwernick/ExoMedia/commit/926cc5a90073000964be9fec16617e6f5cc7c0cb

**Comment by brianwernick** [comment]
That shouldn't be needed anymore with the changes from https://github.com/brianwernick/ExoMedia/commit/d6d69bce469f0e09d49b7e1baa2088dbfa0668da

**Comment by volser** [comment]
You are right, all works properly!  Thank you
