### ISSUE TITLE
Events start, pause, seek are not fired from VideoApi

### ISSUE THREAD

**Issue by billyjoker** [brianwernick/ExoMedia#215]
Hi, in my implementation i have to retrieve the VideoView onstart, onresume, onpause... i've looked up to VideoApi but i see that as play() function is executed, not seems to occur with pause() or seekTo(millis). 

So, i'd like to have some way to do some stuff when this events are fired, what should i do?

Thanks and congratulations for your library!!

**Comment by billyjoker** [comment]
It seems that events are fired from EMVideoView but not are fired at VideoApi...

**Comment by brianwernick** [comment]
You are the one that calls `play()`, `pause()`, and `seekTo()`  so it should be pretty easy to know whey they are called.  If you are using the default `VideoControls` then you can specify the `VideoControlsButtonListener` with `setButtonListener(@Nullable VideoControlsButtonListener callback)`
