### ISSUE TITLE
Wrong ScaleType result, in respect to ImageView's ScaleType

### ISSUE THREAD

**Issue by eneim** [brianwernick/ExoMedia#216]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests

###### Include the following:
 - ExoMedia version: `3.0.0-preview2`
 - Device OS version: `6.0.1`
 - Devide Manufacturer: `LG`
 - Device Name: `Nexus 5`
 
###### Reproduction Steps
 Use ```ScaleType.CENTER_INSIDE.``` and it doesn't produce the result which ```ImageView$ScaleType.CENTER_INSIDE``` would do.  

Here I have 3 results for 3 Scale types, from one 1080 x 1920 video (made by me, for copyright issue):

<img src="https://cloud.githubusercontent.com/assets/1776230/15598515/f1fa96d8-2415-11e6-9e05-af184278245b.png" width=200px><img src="https://cloud.githubusercontent.com/assets/1776230/15598517/f6cd9dae-2415-11e6-8122-40f30b9dd936.png" width=200px><img src="https://cloud.githubusercontent.com/assets/1776230/15598520/fe35208a-2415-11e6-8a50-39857ba28646.png" width=200px>

###### Expected Result
So in sample above, I think result from ```CENTER_INSIDE``` should be like ```FIT_CENTER``` in case the video size is larger than the View.

###### Actual Result
The result from ```CENTER_INSIDE``` was like ```CENTER_CROP``` in case the video size is larger than the View, which is not what ```ImageView$ScaleType.CENTER_INSIDE``` for.

Please take a look.

**Comment by brianwernick** [comment]
Unless we are getting an incorrect size reported, we should be scaling like the FitCenter (see [MatrixManager.java#L121](https://github.com/brianwernick/ExoMedia/blob/d5a5d6e01cd3ca0226467d67da1925329a549515/library/src/main/java/com/devbrackets/android/exomedia/core/video/scale/MatrixManager.java#L121)).

Now for a little more information; how are you setting up the scaling:
* Before or after you set the media source
* Before or after `onPrepared()` is called
* Any other VideoView setup performed (aside from the basics)?

**Comment by eneim** [comment]
@brianwernick Here is my snippet : https://gist.github.com/eneim/d3cf8e26da01fd3073db0f49bfdc3b87

What I did:

- Setup ScaleType first (before I setup onPrepared() behavior and media source).

- Setup Video URL (which may change by a click event).

- Dynamically change ScaleType by another click event.

- Only ```videoView.setVideoPath``` is used here.

I think your matrix calculator may have issue (I assume that you didn't expect the case of vertical Video whose size is much bigger than the view's size). That is one of my assumption. Hope this helps.

**Comment by eneim** [comment]
Update: so my tested video was of size 540 x 960 (I encoded it for bandwidth saving). Here is the one taht you can use for testing. It's created by me under CC license, feel free to use:

https://drive.google.com/file/d/0B4eo03wIaJs9NFJTclVsVEt6T00/view?usp=sharing

**Comment by eneim** [comment]
Hm, so I'm reading this [line](https://github.com/brianwernick/ExoMedia/blob/d5a5d6e01cd3ca0226467d67da1925329a549515/library/src/main/java/com/devbrackets/android/exomedia/core/video/scale/MatrixManager.java#L122) and figure out that you may accidentally switch the co-ordinate of the view and video size:

IMO:

- intrinsicVideoSize.y (the vertical size) should be compared with view.getHeight() and intrinsicVideoSize.x (the horizontal size) should be compared with view.getWidth().

Supposing that this is some easy-to-go issue, let's take a look and check it out. I think that's the only problem here.

**Comment by brianwernick** [comment]
Yeah... mixing those up would cause issues.  You can either create a PR with the fix, or I'll get to it tomorrow morning

**Comment by eneim** [comment]
@brianwernick It depends on my workload here. But if you didn't see any PR, just go forward.

**Comment by brianwernick** [comment]
OK, I've pushed an update with the comparison fixed

**Comment by eneim** [comment]
Just one question (not really related, except for the milestone), do you have any plan of when will 3.0.0 out? I'm working on something have the same concept and it turns out that I'm kind of re-inventing the wheel. So it would be good to hear your schedule.

**Comment by brianwernick** [comment]
I'm hoping to have an official (non preview) build out in the next week or two.  It just depends on my availability and if any more critical issues are found
