### ISSUE TITLE
Initilialize wideo with setUri and a MediaItem

### ISSUE THREAD

**Issue by billyjoker** [brianwernick/ExoMedia#223]
- [ ] I have verified there are no duplicate active or recent bugs, questions, or requests

###### Include the following:
 - ExoMedia version: `2.5.6`
 - Device OS version: `5.1`
 - Devide Manufacturer: `Motorola`
 - Device Name: `Moto X 2014`
 
As your main doc says, to starts a single video i should do

`emVideoView.setVideoURI(Uri.parse("https://archive.org/download/Popeye_forPresident/Popeye_forPresident_512kb.mp4"));`

But i'd like to keep the mediaItem with additional info to show as the playlist work:

`playlistManager.setParameters(mediaItems, selectedIndex);`

Of course i'm able to load a playlist with a single mediaitem:

```
Samples.Sample sample = new Samples.Sample("MPEG DASH !! - Sintel by Blender", "https://bitdash-a.akamaihd.net/content/sintel/sintel.mpd");
MediaItem mediaItem = new MediaItem(sample, false);
mediaItems.add(mediaItem);
playlistManager.setParameters(mediaItems, selectedIndex);
```

My question is if there is supported any tool to perform this scenario more simple that reuse a component thought to play a list of items

**Comment by brianwernick** [comment]
And what is setup in the demo app won't work for you? (see the AudioPlayerFragment for the item access)

**Comment by billyjoker** [comment]
The demo setup works like a charm!! My issue is if i want to play a single video with MediaItem info. I've seen the AudioPlayeractivity but it uses de playlist

**Comment by brianwernick** [comment]
You just need to set it up the same way you would with the native Android `VideoView`.  e.g.
```java
private void setupVideoView() {
    EMVideoView emVideoView = (EMVideoView)findViewById(R.id.video_view);
    emVideoView.setOnPreparedListener(this);
    
    MediaItem mediaItem = getMediaItem(...); //however you want to retrieve the specified MediaItem
    emVideoView.setVideoURI(Uri.parse(mediaItem.getMediaUrl()));
}

@Override
public void onPrepared() {
    //Starts the video playback as soon as it is ready
    emVideoView.start();
}
```
