### ISSUE TITLE
Pause doesn't work after restart in EMVideoView

### ISSUE THREAD

**Issue by denis-trailin-hs** [brianwernick/ExoMedia#226]
- [✓] I have verified there are no duplicate active or recent bugs, questions, or requests

###### Include the following:
 - ExoMedia version: `3.0.0-preview3`
 - Device OS version: `5.5.1`
 - Device Manufacturer: `LG`
 - Device Name: `Nexus 4`
 
###### Reproduction Steps
 1. Make a `EMVideoView` 
 2. Put in the following code:
```
  mVideoView.setOnCompletionListener(() -> {
            mVideoView.restart();
            mVideoView.pause();
        });
```
   3\. Open a video

###### Expected Result

Video is returned to initial position and paused. 

###### Actual Result

Video starts playing from the beginning and doesn't pause.

**Comment by brianwernick** [comment]
Are you setting the OnPreparedListener as

```java
mVideoView.setOnPreparedListener(() -> {
    mVideoView.start();
});
```

If you are then this is why it is playing instead of staying paused because when you call `restart()` the prepared and completion methods will get called again.

**Comment by denis-trailin-hs** [comment]
Even when I don't do that it doesn't work.

**Comment by brianwernick** [comment]
I tried this on a `4.4` and `5.1.1` device making sure not to call `mVideoView.start();` when I was restarting and couldn't reproduce the issue.  Do you have any other setup around the VideoView?

**Comment by denis-trailin-hs** [comment]
Even with an empty `onPreparedListener` and making the `setOnCompletionListener` only call restart my video just keeps looping. I'm assuming that this is because `restart()` is a call that also starts the player again.

**Comment by brianwernick** [comment]
Yes, `restart()` will start the playback when it is ready which is why what you had above with `mVideoView.pause();` was correct for the completion listener.
I'll try to reproduce it again when I get some time, I'm just wondering if you have anything else that may be controlling it (e.g. playlist service)

**Comment by denis-trailin-hs** [comment]
Removing the start from my prepared listener worked.
