### ISSUE TITLE
Using abstraction to switch to another player

### ISSUE THREAD

**Issue by billyjoker** [brianwernick/ExoMedia#227]
Hi, i'm working in using your abstraction that currently works with MediaPlayer and Exoplayer, in order to include or switch into another external player. The escenario would be that in the future maybe would be interesting using another external video engine, so, using the current APIs and abstraction, would be easy keep the current behaviour of the player, events, videocontrols, etc.. but with another engine as Vitamio o whatever.

The way i'm starting to see would be when including the new video engine, write a new class like

`public class NewExternalVideoView extends TextureVideoView implements VideoViewApi {...}`

How do you perform this feature?

**Comment by brianwernick** [comment]
You should be able to duplicate what is done in either the [`NativeVideoView`](https://github.com/brianwernick/ExoMedia/blob/master/library/src/main/java/com/devbrackets/android/exomedia/core/video/NativeVideoView.java) or the [`ExoVideoView`](https://github.com/brianwernick/ExoMedia/blob/master/library/src/main/java/com/devbrackets/android/exomedia/core/video/ExoVideoView.java) swapping out the root implementation with Vitamio.  In general, you don't need to (nor be able to) have a custom `VideoViewApi` implementation extend `TextureVideoView` unless you are writing your own video player view
