### ISSUE TITLE
Video dies on complete

### ISSUE THREAD

**Issue by denis-trailin-hs** [brianwernick/ExoMedia#229]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests

###### Include the following:
 - ExoMedia version: `3.0.0`
 - Device OS version: `5.1.1`
 - Devide Manufacturer: `LG`
 - Device Name: `Nexus 4`
 
###### Reproduction Steps
 1. Create an EMVideoView
 2. Open and play any video with it

###### Expected Result

After the video is complete the controls still work and the video doesn't need to be restarted as is the case with the native VideoView

###### Actual Result
Video gets killed and needs to be restarted

**Comment by brianwernick** [comment]
This is working as designed because the most common case is the playback will move on after a video or audio completes.  As such we release the ExoPlayer resources .

**Comment by denis-trailin-hs** [comment]
@brianwernick How do I get around this then? It seems like that should be something you can turn on and off.

**Comment by dogo** [comment]
Hi @brianwernick would be nice have a method like ```mVideoView.restartAt(desiredPosition);``` and the ExoPlayer resources not be released
