### ISSUE TITLE
onPrepared and onCompletion are called with a null MediaPlayer parameter

### ISSUE THREAD

**Issue by Tourenathan-G5organisation** [brianwernick/ExoMedia#230]
In my fragment, am implementing the MediaPlayer.OnPreparedListener and MediaPlayer.OnCompletionListener interfaces. The MediaPlayer  parameter of the Interface methods(onPrepared and onCompletion) is always null

###### Include the following:
 - ExoMedia version: `2.5.6`
 - Device OS version: `5.0.2`
 - Devide Manufacturer: `Alcatel`
 - Device Name: `Alcatel One touch Idol3`
 
###### Reproduction Steps
 0.

**Comment by brianwernick** [comment]
The listeners have been completely swapped out in `3.0` to avoid confusion like this. The reason MediaPlayer is null is because the ExoPlayer is being used and therefore we have no MediaPlayer to return.
