### ISSUE TITLE
Press play after completion a video never reachs start()

### ISSUE THREAD

**Issue by billyjoker** [brianwernick/ExoMedia#231]
Hi, i have an issue when the playback ends and i press the play button again. The problem is located at VideoControls: 

```
    protected void onPlayPauseClick() {
        if (buttonsListener == null || !buttonsListener.onPlayPauseClicked()) {
            internalListener.onPlayPauseClicked();
        }
    }
```

`onPlayPauseClicked()` is never called. Only when `buttonsListener == null` is called correctly.

Temporarily, i've commented when updateVideoControls (at PlaylistManager) as follows:

`//videoControls.setButtonListener(new ControlsListener());`

And nows i press play and starts the video again.

**Comment by brianwernick** [comment]
Are you returning `false` from your `ControlsListener#onPlayPauseClicked()`?  

I'm not sure what you expect to happen, if a custom `VideoControlsButtonListener` hasn't been specified, or the custom `VideoControlsButtonListener` doesn't handle the `#onPlayPauseClicked()` are the only times the `internalListener.onPlayPauseClicked()` is called

**Comment by billyjoker** [comment]
I expect that when a video is `onCompletion`, then i press play again and get the` start()` execution (at `EMVideoView`). If i set `setButtonListener`, there is no start() execution.

**Comment by brianwernick** [comment]
going back to my question,

Are you returning `false` from your `ControlsListener#onPlayPauseClicked()`?

**Comment by billyjoker** [comment]
Having your `videoControls.setButtonListener(new ControlsListener());`, 
`onPlayPauseClicked()` is returning `false`. This is the default behaviour, i mean, I did not added anything to your code

**Comment by brianwernick** [comment]
Ah, you miss-understand what is happening.  Everything is called and is working as expected, what you are seeing is the VideoView has been stopped (this happens in the onCompletion).  If you want to play a video after it has completed then you need to call `restart()`.

See #229 and #180
