### ISSUE TITLE
seekTo total video duration never calls onCompletion

### ISSUE THREAD

**Issue by billyjoker** [brianwernick/ExoMedia#232]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests

###### Include the following:
 - ExoMedia version: `3.0`
 - Device OS version: `5.1`
 - Devide Manufacturer: `Motorola`
 - Device Name: `Moto X 2014`
 
###### Reproduction Steps
 1.  Play the video
 2.  Seek to the end of the seekBar
 3.  Waiting stop the video...

###### Expected Result
onSeekCompletion and onCompletion execution

###### Actual Result
State of the player is no changing. It's like is seeking all the time

###### My Fix:

EMVideoView class:

```
    public void seekTo(int milliSeconds) {

        //In this way i force to perform a seek very near to the video duration
        if(milliSeconds > 100){
            milliSeconds = milliSeconds - 100;
        }

        videoViewImpl.seekTo(milliSeconds);
    }
```

**Comment by brianwernick** [comment]
I just tried this on the master branch with a 5.1 and 6.0 device and wasn't seeing the issue.  If you try this with the current demo does the issue still exist?

**Comment by billyjoker** [comment]
No, is no longer occurring, i see you overrided in the activity

@Override
public boolean onPlaybackStateChanged(@NonNull PlaylistServiceCore.PlaybackState ```
playbackState) {
    if (playbackState == PlaylistServiceCore.PlaybackState.STOPPED) {
        finish();
        return true;
    }

    return false;
}

```

Personally, i do not like so much that fix, so you are forcing an exit from the player activity when a track reach ends. If i had a playListManager with a single item and i perform seekTo(duration) is a bad user experience destroy the player activity, i'd like to hold my screen player.

**Comment by brianwernick** [comment]
Not quite, I'm exiting the playback activity when the last item in the playlist completes.  Although that is besides the point, you are complaining about the demo application which is not forcing you to use that experience.  The callbacks are informed of the completion which is what you were originally asking about; the rest is up to your implementation.
