### ISSUE TITLE
Aspect ratio bad performing

### ISSUE THREAD

**Issue by billyjoker** [brianwernick/ExoMedia#233]
Hi, i'm with an issue related with the aspect ratio. When i perform seekTo or rotating the device, the aspect ratio goes wrongly. I suppose is caused by the EMVideoView component is not wrapped by an AspectRatioFrameLayout (as Exoplayer does in their demo).

My temporarily fix:

video_player_activity.xml

```
    <com.google.android.exoplayer.AspectRatioFrameLayout
        android:id="@+id/aspectRatioView"
        android:layout_centerVertical="true"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_gravity="center">

    <com.devbrackets.android.exomedia.ui.widget.EMVideoView
        android:id="@+id/video_play_activity_video_view"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        EMVideoView:useDefaultControls="true"/>

    </com.google.android.exoplayer.AspectRatioFrameLayout>
```
EMVideoView.java
```
        //Previously I did a set from the Activity to EMVideoView in order to have available the AspectRatio component.
        @Override
        @SuppressWarnings("SuspiciousNameCombination")
        public void onVideoSizeChanged(int width, int height, int unAppliedRotationDegrees, float pixelWidthHeightRatio) {
            //NOTE: Android 5.0+ will always have an unAppliedRotationDegrees of 0 (ExoPlayer already handles it)
            videoViewImpl.setVideoRotation(unAppliedRotationDegrees, false);
            videoViewImpl.onVideoSizeChanged(width, height);

            if (aspectRatioView != null) {
                aspectRatioView.setAspectRatio(
                        height == 0 ? 1 : (width * pixelWidthHeightRatio) / height);
            }
        }
```

How would you resolve this??

**Comment by brianwernick** [comment]
Please add the information from the template, otherwise I can't help you

**Comment by billyjoker** [comment]
- [ ] I have verified there are no duplicate active or recent bugs, questions, or requests

###### Include the following:
 - ExoMedia version: `2.5.5`
 - Device OS version: `5.1`
 - Devide Manufacturer: `Motorola`
 - Device Name: `Moto X 2014`
 
###### Reproduction Steps
 0.  Play the video
 1.  seekTo any time OR rotate the device

###### Expected Result

  Still having a good aspect ratio playing the video

###### Actual Result

  Bad aspect ratio

**Comment by brianwernick** [comment]
As a note, the ExoPlayer implementation for the video uses the [VideoTextureView](https://github.com/brianwernick/ExoMedia/blob/5dc963c8f49aa9e6bef318118e97e859b22979a4/library/src/main/java/com/devbrackets/android/exomedia/widget/VideoTextureView.java) which is the same functionality as the `AspectRatioFrameLayout`.

I haven't seen this on the 3.0 releases so it may already be fixed (I'm not releasing any more 2.x versions)

**Comment by billyjoker** [comment]
Brian i'm confused, VideoTextureView was removed some time ago, so is no more available. I'm updated on 3.0 releases and the problem stills

**Comment by brianwernick** [comment]
`VideoTextureView` is still in the 2.5.x releases (you said you are using `2.5.5`) which is why I linked it; however the same functionality is available in [ResizingTextureView](https://github.com/brianwernick/ExoMedia/blob/master/library/src/main/java/com/devbrackets/android/exomedia/core/video/ResizingTextureView.java) for the 3.0 release (though it has been slightly modified).  Also, I'm not seeing this on the current master branch so it may be related to #216 or #212

**Comment by billyjoker** [comment]
###### Include the following:
ExoMedia version: 3.0
Device OS version: 5.1
Devide Manufacturer: Motorola
Device Name: Moto X 2014
Reproduction Steps

###### Reproduction Steps
1. Device in portrait position
2. Play the video: MPEG DASH - Sintel by Blender
3. Let goes the playback 12 seconds
4. Movie is resized like x2 zoomed

###### Expected Result

Still having a good aspect ratio playing the video

###### Actual Result

Bad aspect ratio (seems to be x2 zoomed)

**Comment by billyjoker** [comment]
Finally i've figured out my problem. I had a set in the activity

`emVideoView.setScaleType(ScaleType.CENTER);`

So that caused the override of the default `ScaleType.FIT_CENTER`

Thanks for your patient!!

**Comment by brianwernick** [comment]
Oh, glad you figured it out :)
