### ISSUE TITLE
Question: how to have video return to beginning on complete and pause

### ISSUE THREAD

**Issue by denis-trailin-hs** [brianwernick/ExoMedia#234]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
Version: 3.0.0-preview3

I have filed a tickets about this already but my general goal when using this library is to have the video player return to beginning when it reaches the end and pause. Currently the way the library is set up it seems like this is impossible but parhaps I'm missing something. How do I accomplish this?

**Comment by brianwernick** [comment]
See #226 (Don't purposefully duplicate your own issues)
