### ISSUE TITLE
Sample app/steps to use ExoMedia v3.x in an activity ?

### ISSUE THREAD

**Issue by Simon-Kaz** [brianwernick/ExoMedia#237]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests

 - ExoMedia version: `3.0`
 - Device OS version: `6.0.1`
 - Devide Manufacturer: `LG`
 - Device Name: `Nexus 5x`

Hey @brianwernick , great lib! I was wondering if there is a sample app or steps to use the preview version of exomedia (3.x) in the activity? The tutorial only shows the 2.5.6.

**Comment by brianwernick** [comment]
See the [demo](https://github.com/brianwernick/ExoMedia/tree/master/demo)
