### ISSUE TITLE
After Playback Ended, On changing the seekbar position playback not restarting.

### ISSUE THREAD

**Issue by aroraprateek202112** [brianwernick/ExoMedia#238]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests

###### Include the following:
 - ExoMedia version: `2.5.5`
 - Device OS version: `6.0`
 - Devide Manufacturer: `Huawei`
 - Device Name: `Nexus 6P`
 
###### Reproduction Steps
1. Start video playback
2. Wait until it completes
3. Change the seekbar position to somewhere in between.
4. Click on Play icon.

###### Expected Result
The video should start the playback at that seekbar position.

###### Actual Result
playback does not started.

**Comment by brianwernick** [comment]
See #229 and #180
