### ISSUE TITLE
Pause doesn't work after restart in EMVideoView [Duplicate of #226]

### ISSUE THREAD

**Issue by aroraprateek202112** [brianwernick/ExoMedia#239]
- [ ] I have verified there are no duplicate active or recent bugs, questions, or requests

###### Include the following:
 - ExoMedia version: `2.5.5`
 - Device OS version: `6.0`
 - Devide Manufacturer: `Huawei`
 - Device Name: `Nexus 6P`
 
###### Reproduction Steps
Start video playback
Wait until it completes
videoView.restart()

###### Expected Result
In onPrepared() callback method, call start() to start the playback, or pause() depending on the conditions.

###### Actual Result
Playback is started without calling start();

**Comment by brianwernick** [comment]
Don't purposefully create duplicates (#226)
