### ISSUE TITLE
Player is playing but no video is showing, but audio is heard. Video works properly after a reset. 

### ISSUE THREAD

**Issue by simtse** [brianwernick/ExoMedia#240]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests

###### Include the following:
 - ExoMedia version: `3.0.0-preview3`
 - Device OS version: `5.1.1`
 - Devide Manufacturer: `LG`
 - Device Name: `Nexus 4`
 
###### Reproduction Steps
1. Make an EMVideoVideo 
2. Open a streamed MP4 URI (e.g. from Facebook)

###### Expected Result
Video plays properly after initial load

###### Actual Result
Player is playing but no video is showing, but audio is heard. Video works properly after a reset.

**Comment by brianwernick** [comment]
What do you mean "while still sending information back through listeners"?

**Comment by simtse** [comment]
@brianwernick The video (mp4) would be playing but not showing anything. The progress increases for the video and the audio is being played (and heard). After the video is reset, the video shows up with audio.

**Comment by brianwernick** [comment]
Is there anything in logcat that indicates what the issue might be?

**Comment by brianwernick** [comment]
Please provide a demo url

**Comment by simon-tse-hs** [comment]
Sure. It is a video in facebook. I'll get a link or find a way so you can get authenticated to view it.

**Comment by brianwernick** [comment]
Tested on (Nexus 4, 5.1.1).
The specified video works as expected on the master branch.  This may have been an issue with `ExoPlayer` `1.5.8` as they made mp4 improvements in `1.5.9`
