### ISSUE TITLE
MediaPlayer: Error (1,-2147483648)

### ISSUE THREAD

**Issue by ch-muhammad-adil** [brianwernick/ExoMedia#241]
I am using this library in a listview, Some of the videos are working fine but the one recorded by iOS device are not working. I have tested this video in ExoPlayer Demo project. 

this is the code I run for exoplayer demo. 
Intent intent = new Intent(context, ExoPlayerScreen.class).setData(Uri.parse("http://travel.gockell.com/data/251/videos/2016-06-09_13-21-12.mp4"))
                                        .putExtra(ExoPlayerScreen.CONTENT_ID_EXTRA, "dizzy")
                                        .putExtra(ExoPlayerScreen.CONTENT_TYPE_EXTRA, 3)
                                        .putExtra(ExoPlayerScreen.PROVIDER_EXTRA, "");
                                context.startActivity(intent);

it works fine as they have used ExtractorRendererBuilder.class under above settings. 

I have used this class too for this function 
eMVideoView.setVideoURI(Uri.parse(url),new ExtractorRendererBuilder(context,userAgent,url));

here user agent is 
String userAgent = Util.getUserAgent(context, "AppName");

please let me know what I have to do to fix this issue. I really like this library but if exoplayer is working fine then this should also work like you have mentioned its wrapper. 

here is the link of the video you can try too. 
http://travel.gockell.com/data/251/videos/2016-06-09_13-21-12.mp4

**Comment by brianwernick** [comment]
Please fill in the template information, otherwise I cannot help

**Comment by ch-muhammad-adil** [comment]
- [ ] I have verified there are no duplicate active or recent bugs, questions, or requests

###### Include the following:
 - ExoMedia version: `3.+`
 - Device OS version: `6.0`
 - Devide Manufacturer: `LG`
 - Device Name: `G4`
 
###### Reproduction Steps
 Could not get this properly well I am using EMVideoView in a listview. 
This link has the video uploaded by iOS device. It is not working in Android in EMVideoView. 
http://travel.gockell.com/data/251/videos/2016-06-09_13-21-12.mp4
The one uploaded by Android devices are working fine. 
I have also checked this video in ExoPlayer it works fine in Exoplayer but not in EMVideoView.  

###### Expected Result
The video in this link should work
http://travel.gockell.com/data/251/videos/2016-06-09_13-21-12.mp4
###### Actual Result
getting error mentioned in the TITLE of issue.

**Comment by brianwernick** [comment]
That fact that you are getting a `MediaPlayer` error is indicative that it is using the system `MediaPlayer` instead of the `ExoPlayer`.  I'll look in to it when I get some time

**Comment by ch-muhammad-adil** [comment]
OK thanks please let me know if you have any solution and also thanks for giving me a hint to think. 

Your help will be really appreciated. thanks again.

**Comment by ch-muhammad-adil** [comment]
Hey Now I got this error... 

06-12 20:48:23.063 9527-10135/com.gocktrip E/ExtMediaPlayer-JNI: QCMediaPlayer could not be located....
06-12 20:48:23.063 9527-10135/com.gocktrip E/MediaPlayer-JNI: JNIMediaPlayerFactory: bIsQCMediaPlayerPresent 0
06-12 20:48:23.063 9527-10135/com.gocktrip E/ExtMediaPlayer-JNI: QCMediaPlayer could not be located....
06-12 20:48:23.063 9527-10135/com.gocktrip E/MediaPlayer-JNI: JNIMediaPlayerFactory: bIsQCMediaPlayerPresent 0

Also I get "video has no sound" when i try to play video .

**Comment by brianwernick** [comment]
I tried to reproduce this on the current master branch with both ExoPlayer `1.5.8` and `1.5.9` on a 6P (`6.0.1`), 6 (`N`), and `6.0.0` emulator all of which had the same experience as the ExoPlayer demo.  It's possible this was fixed by some other change after the `preview3` release.
