### ISSUE TITLE
Add DRM support

### ISSUE THREAD

**Issue by billyjoker** [brianwernick/ExoMedia#243]
Hi, i'd like to play some drm videos but i do not see where to place my widevine server key. I see that you have some related implementation in DashRendererBuilder. Please, could you give me a hint?

**Comment by se-bastiaan** [comment]
You can provide your own RenderBuilder using https://github.com/brianwernick/ExoMedia/blob/master/library/src/main/java/com/devbrackets/android/exomedia/ui/widget/EMVideoView.java#L273 and https://github.com/brianwernick/ExoMedia/blob/master/library/src/main/java/com/devbrackets/android/exomedia/EMAudioPlayer.java#L117. Your own RenderBuilder can then be modeled after the example Google gives in the ExoPlayer demo application that has the `MediaDrmCallback`: https://github.com/google/ExoPlayer/blob/master/demo/src/main/java/com/google/android/exoplayer/demo/player/DashRendererBuilder.java

**Comment by brianwernick** [comment]
I'll look at this tonight to see if it would be relatively simple to add DRM callbacks and key specifiers; if it is then I'll add it to the 3.0 release.  Otherwise it will be in the 3.1 release

**Comment by billyjoker** [comment]
I'm doing in the way you said. Firstly i've implemented a DashRenderBuilderWV that is similar your class but including the MediaDrmCallback. After that, in the activity:

```
        String url = "http://XXX.com/manifest.mpd";

        DashRenderBuilderWV dashRenderBuilderWV = new DashRenderBuilderWV(this, getUserAgent(), url, new WidevineTestMediaDrmCallback("Deviceid???", "http://XXX.com/proxy_widevine/XXXX"));

        emVideoView.setVideoURI(Uri.parse(url), dashRenderBuilderWV);

```
But i can not render the video yet...

**Comment by se-bastiaan** [comment]
Well, it looks like `executeKeyRequest` can't be executed because the callback is `null`?

**Comment by billyjoker** [comment]
My `drmCallback` is not null. I've the doubt if i am building the WidevineTestMediaDrmCallback defaultUri correctly:

`defaultUti="https://proxy.uat.widevine.com/proxy?video_id=myDeviceId&provider=http://my_proxy_key_server"`

You are right that both executeProvisionRequest and executeKeyRequest are not executing

**Comment by billyjoker** [comment]
Currently i reach the WidevineTestMediaDrmCallback  `executeKeyRequest` method, but i am not able to render the video. 

Also, i tested my drm on Exoplayer demo with success, so i have no idea what is happening.

**Comment by billyjoker** [comment]
As i am researching, it seems that a drm video can not be displayed on a TextureView, the only way is on a SurfaceView, it is related with the security...

[](https://github.com/google/ExoPlayer/issues/370)

**Comment by brianwernick** [comment]
Hmm, this is just an additional thing to add to the SurfaceView vs TextureView discussion... 
With the TextureView we have
 0. [Pro] Treated as a normal view (multiple can be overlayed, correct z-ordering, etc.)
 0. [Pro] Transformations and animations are supported (e.g. scaling)
 0. [Con] ~30% increased battery usage (over SurfaceView)
 0. [Con] Inconsistent DRM support (usually not supported)

While the SurfaceView has
 0. [Pro] DRM support
 0. [Pro] Lower memory and battery usage
 0. [Con] No transformations or animations
 0. [Con] Treated differently from any other view on Android

If you have anything else to add to the list please do so.  Just know that whichever stance I end up taking with ExoMedia there will be a loss of useful functionality :(

**Comment by se-bastiaan** [comment]
I'd say a way to dynamically swap would be the best solution, in the end. That way the library does not block people from using ExoPlayer in the way they want to.

**Comment by billyjoker** [comment]
Dinamically swap would be great, i'm going to work with this idea, so i need to play drm. In fact the last day i performed a quick refactor int the ResizingTextureView class to replace `TextureView `with `SurfaceView`, i played a drm video successfully but with some side effects, like the aspectratio. 

I've observed that all the methods from `MatrixManager `class receive as argument a `TextureView`, so i've replaced by a `View `as argument (in this way it could be pass either a TextureView or a SurfaceView ), i think that the performing of your methods would have a similar operation with a `TextureView `or with a `View`, what do you think about it?

**Comment by billyjoker** [comment]
Hi again, i've fixed my troubles in my last post and i have almost ready my final implementation swapping between `SurfaceView`/`TextureView `but i still have a bug. If i play on SurfaceView (drm or not), in portrait i have black screen, while in landscape i play the video perfectly.

**Comment by billyjoker** [comment]
As i see is a problem related with some rotate operation, the video is outside of the screen with a weird position. I'm tryng to figure out what is the correct point to place the SurfaceView

**Comment by brianwernick** [comment]
Try commenting out the calls to the `MatrixManager`.  I'm pretty sure the `SurfaceView` doesn't correctly handle rotation or scale requests to the view or views matrix

**Comment by billyjoker** [comment]
Hi Brian, commenting out the calls to the MatrixManager shows black screen again... the best i've got is with rotation=359 but is partially well shown... I'm really stuck with this

**Comment by se-bastiaan** [comment]
Why don't you create a branch in your work with your changes? Maybe we can help?

**Comment by billyjoker** [comment]
Finally i've got it!! I've had to wrap the xml from emvideoview inside a AspectRatioFrameLayout (currently i have two xml, one for drm an another one for whatelse):

```
<com.google.android.exoplayer.AspectRatioFrameLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    android:id="@+id/video_frame"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:layout_gravity="center">

    <com.devbrackets.android.exomedia.ui.widget.EMVideoView
        xmlns:android="http://schemas.android.com/apk/res/android"
        xmlns:tools="http://schemas.android.com/tools"
        xmlns:EMVideoView="http://schemas.android.com/apk/res-auto"
        android:id="@+id/video_play_activity_video_view"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        EMVideoView:useDefaultControls="true"
        EMVideoView:drmControl="true"/>

</com.google.android.exoplayer.AspectRatioFrameLayout>

The only one little bug now is that the content video is top aligned (instead center). Scale is well represented both portrait and landscape.
```

**Comment by brianwernick** [comment]
Cool!  

As a side note; I did some work on this last night to prepare for the abstraction, however it is on a different computer so I can't upload the branch.  It would be great If you would create a branch as Sébastiaan mentioned so we can build off each other

**Comment by brianwernick** [comment]
I've pushed my branch up to [issue_243](https://github.com/brianwernick/ExoMedia/tree/issue_243).  Currently it has the ability to swap between a `TextureView` and `SurfaceView` backing though I haven't thoroughly tested it and there are a few more optimizations I want to do before moving on to the DRM portion.

**Comment by billyjoker** [comment]
Ok, i'm going to prepare my branch to upload (i have to clean up some local changes not related with drm ). I've just pulled your branch issue_243, i'm just viewing in deep

**Comment by billyjoker** [comment]
I've just merged issue_243 on my branch successfully (i had lots of conflicts, you know...), i can create now a pull request onto your issue_243

**Comment by billyjoker** [comment]
Sorry yesterday i created badly the upload from my branch. Now you have my pull request correctly

**Comment by brianwernick** [comment]
The current PR is still not correct.  There are merge conflicts that need to be resolved

**Comment by billyjoker** [comment]
I do not know how i did (i'm noobie doing fork and pull request), but i'm my master i have no conflicts, there is nothing to compare between base:issue_243 and my master

**Comment by billyjoker** [comment]
Ok, finally i've got perform the pull request onto issue_243. Conflicts were resolved
