### ISSUE TITLE
Video not playing

### ISSUE THREAD

**Issue by MarkedWarrior** [brianwernick/ExoMedia#245]
- [X ] I have verified there are no duplicate active or recent bugs, questions, or requests
###### Include the following:
- ExoMedia version: `3.0.0`
- Device OS version: `4.4`

Hey Brian,
Thank you for your help last time! 

Unfortunately, I am having another issue but this time it's with the player unable to play certain videos. 

The following is a link of a video that isn't being able to play:
http://158.69.25.113:8080/FankooshTV/537.m3u8

I tried it on your demo, thinking that it's my app's problem but your demo app couldn't play it either. If you could please check it out I'd be more than grateful. Any pointers would be helpful too! 

Thank you again for such an awesome library!

**Comment by brianwernick** [comment]
The current `ExoPlayer` master branch is having the same issue, as such you should report it there (and link this issue)

The relevant line in LogCat is `I/VideoCapabilities: Unsupported profile 4 for video/mp4v-es`

**Comment by brianwernick** [comment]
I just verified that this is fixed with the current `ExoMedia 3.1.0` branch; It may have been fixed a while ago. Alternatively, the source video has changed; either way this is not an issue any longer
