### ISSUE TITLE
Don't hang Android Studio 2.2 preview 3 layout editor

### ISSUE THREAD

**Issue by Kisty** [brianwernick/ExoMedia#246]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests

###### Include the following:
 - ExoMedia version: `3.0.0-preview3`
 - Device OS version: `6.0`
 - Devide Manufacturer: `Emulator x64`
 - Device Name: `Nexus 5X`
 
###### Reproduction Steps
 1. Download Android Studio 2.2 preview 3
 2. Open a layout with EMVideoView
 3. Close Android Studio
 4. Open Android Studio

###### Expected Result
Should be able to edit it fine.

###### Actual Result
On first load of the layout, it hangs for a while. On the second time (if the layout is the last window open) it hangs Android Studio forcing it to close. Have reported it to the Android bug tracker but the problem is with setting up the view in the first place.

https://code.google.com/p/android/issues/detail?id=210962

**Comment by brianwernick** [comment]
This has been fixed in https://github.com/brianwernick/ExoMedia/commit/5360698533bdc461f4226e7ba977dd8c4cdb1f63 and will be in the next patch

**Comment by Kisty** [comment]
Thanks for getting back to me so quickly and fixing this! 

Have updated the issue on Android bug tracker too.
