### ISSUE TITLE
Add AVI file support

### ISSUE THREAD

**Issue by metalurgus** [brianwernick/ExoMedia#249]
AFAIK `FrameworkSampleSource` can extract from AVI container. It would be nice to have feature to at least try to play AVI files

**Comment by brianwernick** [comment]
And what is stopping you from trying?  Setting the data source just takes a URI

**Comment by AdityaAnand1** [comment]
@metalurgus Were you able to play AVI files? I'd love some direction as to how this can be done :)

**Comment by metalurgus** [comment]
@AdityaAnand1 no unfortunately. I've closed my project as the online resource, which I was creating client app for has stopped. What I did before that is used external players to play AVI files.

**Comment by brianwernick** [comment]
I looked in to this not too long ago (don't remember why) and there are no current plans to support AVI parsing directly; however you can create a `Renderer` that is backed by ffmpeg and register it in `ExoMedia` to handle the `.avi` files
