### ISSUE TITLE
no video looping method?

### ISSUE THREAD

**Issue by raytona** [brianwernick/ExoMedia#25]
i need setlooping method like media player.
how can i implement?

**Comment by raytona** [comment]
@Override
    public void onCompletion(MediaPlayer mp) {
        mvideo.seekTo(0);
        mvideo.start();
    }

this is not working. loop just a time

**Comment by brianwernick** [comment]
Would you elaborate what "this is not working" means.  What is it doing vs what are you expecting it to do?  

The MediaPlayer provides a method to enable/disable looping, but doesn't provide the ability to loop a specific section (this is what I took "loop just a time" to mean). http://developer.android.com/reference/android/media/MediaPlayer.html#setLooping(boolean)

Additionally, even using the loop method in the MediaPlayer is not gapless, so you will need to take that in to account as well.
