### ISSUE TITLE
Rtmp

### ISSUE THREAD

**Issue by bmutinda** [brianwernick/ExoMedia#253]
Thanks for the lib. I was just wondering if there is a way to stream rtmp for audio with the lib?
I have tried to use it but I get a java exception 
```java
com.google.android.exoplayer.upstream.HttpDataSource$HttpDataSourceException: Unable to connect to rtmp://blah.blah...XXXXXX
.......

Caused by: java.net.MalformedURLException: Unknown protocol: rtmp
```

**Comment by brianwernick** [comment]
The ExoPlayer doesn't support RTMP, though there may be third party libraries that provide RTMP RenderBuilders which you can then provide to ExoMedia's `AudioPlayer` or `EMVideoView`

**Comment by bmutinda** [comment]
Thanks @brianwernick. I have seen a very long conversation about it on exoplayer with some suggestions on how to achieve it. I will check the available options

**Comment by bobheadxi** [comment]
I am trying a similar thing, have you made any progress @bmutinda ?

**Comment by fukemy** [comment]
me too
