### ISSUE TITLE
Video Controls - Null Pointer Exception

### ISSUE THREAD

**Issue by prince78686** [brianwernick/ExoMedia#256]
I get null pointer exception at emVideoView.showControls() , also at emVideoView.getVideoControls() ... and not showing any controls when playing video. Can anybody help plz.. Can you give me a snippet how to use video controls correctly, add buttons and their respective listener..

**Comment by se-bastiaan** [comment]
if `emVideoView.showControls()` gives a NullPointerException then `emVideoView` is probably `null`?

**Comment by brianwernick** [comment]
This is all explained in the documentation which can be found in the README or in the source itself

**Comment by prince78686** [comment]
emVideoView in not null, i can play video but shows no control and gets null pointer execption as mentioned above.. btw thanks for helping @brianwernick
