### ISSUE TITLE
Show the last frame after completion instead of black screen

### ISSUE THREAD

**Issue by ypresto** [brianwernick/ExoMedia#261]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests

EMVideoView shows black screen after completion.
It'd be better if the last frame is shown instead of black one.

**Comment by brianwernick** [comment]
This was a purposeful decision, and won't be changed

**Comment by ypresto** [comment]
What was the purpose?
iOS Safari's built-in video player shows last frame instead of black screen.
I want similar behavior to other apps.

**Comment by ypresto** [comment]
At least preview image should be shown instead of black one.

**Comment by ypresto** [comment]
For workaround this for now override EMVideoView and put below snippet.

```java
    // To prevent from black screen shown after play.
    @Override
    protected void onPlaybackEnded() {
        pause();
    }
```

**Comment by brianwernick** [comment]
The reason it shows a black screen is to indicate the state of the VideoView.  After playback completes the backing will be cleaned up (which is also why you cannot play media after it has completed).

**Comment by ypresto** [comment]
Perhaps end user does not want black screen and want to replay video (or not).

> backing will be cleaned up

Is it for reducing battery consumption..?
It could be done at onDestroy() manually.
