### ISSUE TITLE
Can't play  a livestream that doesn't have a extension specified.

### ISSUE THREAD

**Issue by erkand-imeri** [brianwernick/ExoMedia#262]
Hello there, i have already checked the code with the default http link, but when i was checking with my own links, http liveastreaming that doesn't have any extension specified, the link won't play. Do i need to add an additional code or what?

Thanks in advance.

**Comment by brianwernick** [comment]
You will either need to use a URI that includes the extension (or in a format such as `.mpd/manifest`) or provide your own media type determination (i.e. pass in the correct `RenderBuilder` for the format)

**Comment by erkand-imeri** [comment]
Can you please elaborate on RenderBuilder, how can i assume which media type has the correct RenderBuilder?

Sorry  if my question seems noobish, but i am quite interested to figure it out.

Thanks in advance, brianwernick.

**Comment by se-bastiaan** [comment]
The default `setVideoURI` makes a guess based on the extension ([ExoVideoView.java#L250](https://github.com/brianwernick/ExoMedia/blob/master/library/src/main/java/com/devbrackets/android/exomedia/core/video/ExoVideoView.java#L250)), if your URL does not have an extension then you'll have to provide the RenderBuilder that is suitable for your source.

For example, if your URL is `http://test.com/teststream/`

HLS:
```
videoView.setVideoUri(null, new HlsRenderBuilder(context.getApplicationContext(), "MyUserAgent", "http://test.com/teststream/"));
```

DASH:
```
videoView.setVideoUri(null, new DashRenderBuilder(context.getApplicationContext(), "MyUserAgent", "http://test.com/teststream/"));
```

SmoothStream:
```
videoView.setVideoUri(null, new SmoothStreamRenderBuilder(context.getApplicationContext(), "MyUserAgent", "http://test.com/teststream/"));
```

**Comment by erkand-imeri** [comment]
se-bastiaan, which one of  the hls or dash or smoothstream should i use? Or it doesn't matter?

**Comment by se-bastiaan** [comment]
You say you're using HTTP livestreaming, so you probably already have such a protocol specified for you. What does your URL look like?

**Comment by erkand-imeri** [comment]
Right now, i have with the .m3u8 extension. Can i play it with the hlsrendering function?

**Comment by erkand-imeri** [comment]
se-bastiaan, now after i made the http livestreaming links with .m3u8 extension i can play them only with the emVideoView.setVideoURI(Uri.parse(livstrm)) function, i add the renderbuilder parameter

videoView.setVideoUri(null, new SmoothStreamRenderBuilder(context.getApplicationContext(), "MyUserAgent", "http://test.com/teststream/"));
 :+1: 

It  doesn't play.

**Comment by se-bastiaan** [comment]
M3U8 implies that you're using HLS, so you'll have to use the right RenderBuilder:

```
videoView.setVideoUri(null, new HlsRenderBuilder(context.getApplicationContext(), "MyUserAgent", "http://test.com/teststream/"));
```

**Comment by erkand-imeri** [comment]
Thanks a lot, but  what about links  that need UserAgent? How do i implement the livestream with the useragent. Interesting enough, with ExoMedia a http livestram that needs useragent to function, it plays the link

**Comment by se-bastiaan** [comment]
What do you mean? The user agent is `EMAudioPlayer %versionName% (%versionCode%) / Android %osVersion% / %deviceModel%` by default. If you want to change it then you'll need to use a custom RenderBuilder or override it in the lower level code.

**Comment by meet2011** [comment]
what do you mean by lower level code for custom userAgent?

**Comment by brianwernick** [comment]
@meet2011 The userAgent is handled by the [MediaSourceBuilder#build()](https://github.com/brianwernick/ExoMedia/blob/7433b8805e9e81d8e100cef6e1f539ec0840690c/library/src/main/java/com/devbrackets/android/exomedia/core/source/builder/MediaSourceBuilder.java#L19) and [MediaSourceBuilder#buildDataSourceFactory()](https://github.com/brianwernick/ExoMedia/blob/7433b8805e9e81d8e100cef6e1f539ec0840690c/library/src/main/java/com/devbrackets/android/exomedia/core/source/builder/MediaSourceBuilder.java#L22) implementations. If you need a custom user agent you can create custom `MediaSourceBuilders` and register them with [ExoMedia#registerMediaSourceBuilder()](https://github.com/brianwernick/ExoMedia/blob/7433b8805e9e81d8e100cef6e1f539ec0840690c/library/src/main/java/com/devbrackets/android/exomedia/ExoMedia.java#L68) or use the preferred method of setting a custom `DataSourceFactoryProvider` that has your custom user agent via [ExoMedia#setDataSourceFactoryProvider()](https://github.com/brianwernick/ExoMedia/blob/7433b8805e9e81d8e100cef6e1f539ec0840690c/library/src/main/java/com/devbrackets/android/exomedia/ExoMedia.java#L94) (see #86 for an example)

**Comment by meet2011** [comment]
How to set custom `DataSourceFactoryProvider` that has custom agent? I saw #86 but not getting it.

**Comment by brianwernick** [comment]
The demo [App](https://github.com/brianwernick/ExoMedia/blob/7433b8805e9e81d8e100cef6e1f539ec0840690c/demo/src/main/java/com/devbrackets/android/exomediademo/App.java#L43) has an example of setting it, You'll just need to use your custom user agent instead of the userAgent that is passed in. If you have more questions about this please open a new issue.
