### ISSUE TITLE
How to maintain the Aspect Ratio of video on varying the size of view.

### ISSUE THREAD

**Issue by aroraprateek202112** [brianwernick/ExoMedia#264]
- [ ] I have verified there are no duplicate active or recent bugs, questions, or requests
###### Include the following:
- ExoMedia version: `3.0.0`
- Device OS version: `6.0`
- Devide Manufacturer: `Motorola`
- Device Name: `MOTO X`
###### Reproduction Steps
1.  EMVideoView is added in a container having some fixed height and width as match_parent and ScaleType.FIT_CENTER
2. Decreased the sized of container to some min height.
3. Aspect Ratio is not maintained by the EMVideoView, the video height is decreased, but it's width is not decreased to maintain the aspect ratio.
###### Expected Result

Aspect Ratio should be maintained.
###### Actual Result

Video height is decreased, but video width is showing as match_parent.

**Comment by brianwernick** [comment]
Are you resizing the container after the view has been sized (e.g. with an animation)?

**Comment by aroraprateek202112** [comment]
Hi Brian, thanks for your quick response.
I am resizing the container, by changing the height in layout params of the container.

**Comment by brianwernick** [comment]
Again, is this a dynamic change (such as with an animation) or static?

**Comment by aroraprateek202112** [comment]
Hi Brian,
I have a requirement to vary the height of EMVideoView dynamically based on some events.
For varying the height of EMVideoView, I am changing the layoutparams of the container dynamically in which EMVideoView is placed.

**Comment by aroraprateek202112** [comment]
Hi Brian,
Any update on the use. Waiting for your response.

**Comment by brianwernick** [comment]
I haven't had the time to verify that it is a bug.  It will probably be a few weeks before I can get to it (or you can create a pr with a fix)
