### ISSUE TITLE
How to place controls outside of EMVideoView

### ISSUE THREAD

**Issue by ypresto** [brianwernick/ExoMedia#265]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests

###### Include the following:
 - ExoMedia version: `3.0.0`

setControlls() requires View instance.
addView() is called in setControlls(), so cannot place controls to outside of EMVideoView even manually.

It'd be better if setControls() accepts generic interface of controls.

**Comment by brianwernick** [comment]
I'm not sure what you mean by "so cannot place controls outside of EMVideoView".  The `VideoControls` is just a ViewGroup that I've used outside of the `EMVideoView` so it is possible (and quite easy)

**Comment by ypresto** [comment]
> addView() is called in setControlls()

I found the way to do it:

```
MyControls myControls = new MyControls(this);
videoView.setControls(myControls);
videoView.removeView(myControls); // not looks good...
findViewById(R.id.container).addView(myControls);
```

removeView() is necessary to avoid "the specified child already has a parent" exception.
I think it is not straightforward way...

**Comment by brianwernick** [comment]
What is your usecase that you need the `VideoControls` to have a different parent than the `EMVideoView`?
