### ISSUE TITLE
Audio Playback Continues After App goes Background

### ISSUE THREAD

**Issue by PhatJo** [brianwernick/ExoMedia#266]
- [ ] I have verified there are no duplicate active or recent bugs, questions, or requests

###### Include the following:
 - ExoMedia version: `3.0.0`
 - Device OS version: `6.0`
 - Devide Manufacturer: `Asus`
 - Device Name: `Nexus Player`
 
###### Reproduction Steps
1. Select video card in top carousel (should start auto-playing). Sample project at 
https://github.com/PhatJo/androidtvdemo
2. Let video play for a few seconds
3. Hit back button on the remote (or emulator) to exit app (to background)
4. Playback momentarily stops but audio is heard as if video playback starts all over again

###### Expected Result
Video completely stops and all resources freed

###### Actual Result
Playback seems to stop but audio is heard in the background
Seems to be related to https://github.com/google/ExoPlayer/issues/27 but even then calling `EMVideoView.seekTo(0)` before `stopPlayback()` doesn't seem to help

**Comment by PhatJo** [comment]
I made sure that `EMVideoView.release()` when the app was being exited (as triggered from onDetachedFromWindow()). Also, in the MainFragment's onPause(), I tried stopping playback on the current EMVideoView instance like so: 

`@Override
    public void onPause() {
        if (mVideoCardView != null) {
            mVideoCardView.stopPlayback();
        }
        super.onPause();
    }`

**Comment by brianwernick** [comment]
Is this reproducible in the Demo app?  (also, the linked ExoPlayer bug is completely different)

**Comment by PhatJo** [comment]
Yes it's reproducible in the demo app, hence why I linked it

**Comment by brianwernick** [comment]
I meant is this reproducible in the ExoMedia demo app?

**Comment by PhatJo** [comment]
I have just run the ExoMedia demo app and it's not reproducible there. Not surprising though, because the back button would simply go back to the previous activity as opposed to exit the app, which I think is the key issue here

**Comment by brianwernick** [comment]
The back should still place the VideoView in to the same state for both backgrounding the app or exiting the Activity.  I don't really have the time to go look through the androidTVdemo currently, but make sure you are pausing when the activity focus is lost (`onStop()` or `onPause()`)

**Comment by brianwernick** [comment]
This is an issue in your demo app. You are creating an `EMVideoView` when the app goes in to the background, then proceed to call `start()`. More specifically `VideoCardPresenter#L32`
