### ISSUE TITLE
I am trying to stream 360 video through Exomedia?

### ISSUE THREAD

**Issue by sujitkjha** [brianwernick/ExoMedia#267]
I just have issue because there is no method that can let me set the surface, like android default method have public void setSurface(Surface surface) ?????

**Comment by brianwernick** [comment]
This is by design.  The EMVideoView handles swapping between different surface backing implementations.  Why do you need to specify the surface manually?

**Comment by sujitkjha** [comment]
I am trying to set the surface as Sphere for 360 video

**Comment by brianwernick** [comment]
You can create your own VideoAPI implementation similar to the `ExoVideoView` or `NativeVideoView` and provide that as the backing implementation with your custom surface. Builtin support is beyond the scope of ExoMedia
