### ISSUE TITLE
.CH format support?

### ISSUE THREAD

**Issue by erkand-imeri** [brianwernick/ExoMedia#268]
I can't  play livestreaming links generated through Xtream Codec that have the extension of .ch and apparently they are of the format h264.

Also, how can i make the EmVideoView fullscreen?

Thanks in advance.

**Comment by brianwernick** [comment]
The .ch file extension is unsupported, you can look at the ExoPlayers [supported formats](https://google.github.io/ExoPlayer/supported-formats.html) which will be the same for ExoMedia.

As far as fullscreen goes, see the demo app and #119

**Comment by erkand-imeri** [comment]
I can play .ch file extension with Videoview not with  ExoMedia/ExoPlayer?

**Comment by brianwernick** [comment]
Not currently (3.1.0 should allow something similar based on the DRM changes).

My questions are
 0. What format does ".ch" actually represent?
 0. Why can't you use a more standardized format?

**Comment by erkand-imeri** [comment]
.ch represent the h264 format.

**Comment by brianwernick** [comment]
H.264 is typically wrapped in the .mp4 container (MPEG-4 AVC).  What I was meaning is, what does the ".ch" container represent?

**Comment by erkand-imeri** [comment]
I have no idea precisely what does the .ch represent, i just know that it's an extension generated by Xstream Codes Panel, what renderbuilder represents the .mp4, should i declare the renderbuilder in this case? Would it work?

Also, i don't really understand how can make the emvideview to scale fullsize some videos. Any tips?

**Comment by brianwernick** [comment]
The `RenderBuilder` class is what handles most of the formats (all non-streaming formats) and is used as the fallback if the extension is unknown.  This means that specifying the RenderBuilder manually won't help in your situation.  I would modify the output format the Xstream is exporting.

What do you mean "scale fullsize"?  Are you looking for `FIT_CENTER`, `CENTER_INSIDE`, or something else?

**Comment by erkand-imeri** [comment]
Well, i mean that, the video resolution of the http livestream is smaller than the  TV screen, and i need to adjust the aspect ratio of the video so it can fit the fullscreen.

**Comment by brianwernick** [comment]
By default the video will be scaled to fit the container (keeping the aspect ratio), If it isn't matching the screen size make sure you have specified `match_parent` for the videoViews height and width

**Comment by erkand-imeri** [comment]
I do have that brian, but it doesn't fit.

**Comment by brianwernick** [comment]
Compare what you have with the Demo app since I know that works as I have described.
