### ISSUE TITLE
TextureVideoView stopPlayback() issues

### ISSUE THREAD

**Issue by wanglg** [brianwernick/ExoMedia#269]
public void stopPlayback() {
        currentState = State.IDLE;

        if (isReady()) {
            try {
                mediaPlayer.stop();
            } catch (Exception e) {
                Log.d(TAG, "stopPlayback: error calling mediaPlayer.stop()", e);
            }
        }

        playRequested = false;
    }

  protected boolean isReady() {
        return currentState != State.ERROR && currentState != State.IDLE && currentState !=        State.PREPARING;
    }

isReady always return false

**Comment by brianwernick** [comment]
`isReady()` will return true when the `currentState` is `PREPARED`, `PLAYING`, `PAUSED`, or `COMPLETED`.  In no way does it "always return false"
