### ISSUE TITLE
setRequestedOrientation at VideoControls

### ISSUE THREAD

**Issue by billyjoker** [brianwernick/ExoMedia#273]
- [ ] I have verified there are no duplicate active or recent bugs, questions, or requests

###### Include the following:
 - ExoMedia version: `3.0.0`
 - Device OS version: `5.1`
 - Devide Manufacturer: `Motorola`
 - Device Name: `Moto X`
 
###### 

Hi, i'm implementing a fullscreen button. It's all right but i need to call the `setRequestedOrientation` method, so i need to have access to the main activity. Someway like an interface to communicate `VideoControls `with `Activity`, but i do not see anything to do that or if you have thought about this kind of communications. How would you perform this one? Thanks!

**Comment by se-bastiaan** [comment]
The context in the VideoControls is probably the parent Activity of the view.

**Comment by billyjoker** [comment]
The context has not visibility with `setRequestedOrientation `method, only the activity can do it

**Comment by brianwernick** [comment]
You control the addition of the `View` that is your fullscreen button, just have that view reference the activity (or have the `onClickListener` be your activity) and handle the functionality there.
There is no part of this that is specific to ExoMedia; as such I'm closing the issue
