### ISSUE TITLE
Video is visible only after some delay on some scenarios

### ISSUE THREAD

**Issue by minas90** [brianwernick/ExoMedia#275]
###### Include the following:
 - ExoMedia version: `3.0.0`
 - Device OS version: `6.0`
 - Devide Manufacturer: `LeEco`
 - Device Name: `LeEco Le 1S`
 
###### Reproduction Steps
 0. Call eMVideoView.pause();  inside onPause() 
 1. Press home button and open the app again

###### Expected Result
Video should continue to play
###### Actual Result
Audio continues to play, but video is being visible after some delay ( 1-3 seconds).
The same is happening inside recyclerview items when they get off the screen, but not recycled yet.

**Comment by se-bastiaan** [comment]
> video is being visible after some delay

That's normal imo, some initialization is required.

**Comment by minas90** [comment]
After some debugging I found out that it is happening when view is detached from windows. 
I called videoView.setReleaseOnDetachFromWindow(false); to avoid .release()
Otherwise it was not playing video inside recyclerview after release.

The problem is with the recyclerview. I need to do a lot of ugly hacks, which affects scrolling performance. Item views get detached from recyclerview, however they are still in memory, so when I scroll to them, it's white ( no preview image ) and when it starts playing I can hear audio, but video appears after few seconds.

**Comment by brianwernick** [comment]
Yeah, it is expected (as se-bastiaan noted) that there will be a little initialization period where you only hear the sound while the VideoView is buffering the image data.
As you mentioned, the RecyclerView is a completely separate problem (see #13 and #128); however your comment of "ugly hacks" sounds like you have too complex of a ViewHolder, or don't completely understand the paradigm behind it.

**Comment by minas90** [comment]
Hey, thanks for the reply :)
I do understand the paradigm behind RecyclerView. Actually I discussed and fixed some issues behind it with Google devs.
The problem is that item views get detached from RecyclerView when they are not visible in screen. However when you return they are reused again from memory and you get the little "initialization" pause (in case when release is disabled during detach).
It is not allowable in my use case, it should be smooth auto play experience. The only solution is to use attach, detach callbacks of recyclerview to find out which views are attached to recyclerview and call setVideoURI in which case it starts to play immediately when you focus to the newly attached item.

**Comment by minas90** [comment]
I think there should be something other than setReleaseOnDetachFromWindow to not just avoid release() during detach, but all the other logic, because the core of RecyclerView is reuse of items even if it's detached from window it still can be used.

**Comment by brianwernick** [comment]
What does `all the other logic` refer to in this case?  The only thing the `EMVideoView` does in `onDetachedFromWindow` is release when enabled

**Comment by minas90** [comment]
Ok, I didn't dig deeper. Maybe exoplayer does something during detach, because when you return to the item cached in memory it takes longer to show video than cold initialization and load of video.

**Comment by brianwernick** [comment]
Hmm, It might have something to do with how the `TextureView` is interacted with.  I'd be interested to see if you are still having the same issue using the SurfaceView backing... (though the ability to swap between the two hasn't been released, but is on the 3.1.0 branch)
