### ISSUE TITLE
Option to automatically handle AudioFocus

### ISSUE THREAD

**Issue by brianwernick** [brianwernick/ExoMedia#280]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests

The Android VideoView requests and releases audio focus when appropriate (though they don't listen to changes).  It would be nice to have the option to have EMVideoView perform the same functionality (with listening to changes)

**Comment by djontso** [comment]
Hi,
so please I want you to help me with my project I just want a button play / stop to play the radio in background with a notification bar with ExoMedia. Thank you to want to help me because I am a beginner in java development
