### ISSUE TITLE
How can i change to fullscreen not in new activity?

### ISSUE THREAD

**Issue by ehaahe** [brianwernick/ExoMedia#282]
- [ ] How can i change the video to fullscreen in only one activity?

###### Include the following:
 - ExoMedia version: `3.0.0`
 - Device OS version: `6.0`
 - Devide Manufacturer: `Huawei`
 - Device Name: `Nexus 6P`
 
###### Reproduction Steps
 0.

**Comment by brianwernick** [comment]
See #247, #204, #119, or the Demo Application
