### ISSUE TITLE
how can i change the controller in real time?

### ISSUE THREAD

**Issue by ehaahe** [brianwernick/ExoMedia#283]
- [ ]how can i change the controller in real time?

###### Include the following:
 - ExoMedia version: `3.0.0`
 - Device OS version: `6.0`
 - Devide Manufacturer: `Huawei`
 - Device Name: `Nexus 6P`
 
###### Reproduction Steps
 0.

**Comment by brianwernick** [comment]
Do you mean swap out the `VideoControls`?  There is [`setControls(videoControls)`](https://github.com/brianwernick/ExoMedia/blob/master/library/src/main/java/com/devbrackets/android/exomedia/ui/widget/EMVideoView.java#L210); though swapping dynamically isn't a fully supported operation (i.e. the state of the VideoControls may not be correct)

**Comment by ehaahe** [comment]
I solve it by other way,i make a controller with two kinds of interface,when i change to landscape to one,and change to portrait to another one ,so the controller is only one ,there are no longer the incorrect state issue
