### ISSUE TITLE
How get video progress?

### ISSUE THREAD

**Issue by psadanowicz** [brianwernick/ExoMedia#284]
- [ ] I have verified there are no duplicate active or recent bugs, questions, or requests

###### Include the following:
 - ExoMedia version: `3.0.1`
 - Device OS version: `6.0`
 - Devide Manufacturer: `Huawei`
 - Device Name: `Nexus 6P`
 
###### Reproduction Steps
 0.

**Comment by brianwernick** [comment]
You should read the documentation

**Comment by psadanowicz** [comment]
Sorry but I asked here because documentation don't resolve my question. EMVideoView don't contain single method to set listener for progress.

**Comment by brianwernick** [comment]
That's by design; if you need progress updates use a timer to periodically poll `getCurrentPosition, `getDuration`, and `getBufferPercentage`.  See `VideoControls` for a reference implementation

**Comment by LLin233** [comment]
@brianwernick  so we can't use listener or callback anymore?

**Comment by brianwernick** [comment]
for progress, no.  Those listeners were removed as part of re-focusing what ExoMedia handles
