### ISSUE TITLE
Override support lib version and compileSdkVersion

### ISSUE THREAD

**Issue by maohieng** [brianwernick/ExoMedia#289]
- [ ] I have verified there are no duplicate active or recent bugs, questions, or requests

###### Include the following:
 - ExoMedia version: `3.0.1`
 
When I use `compile 'com.devbrackets.android:exomedia:3.0.1'` into my project, it requires me that I have to change my `compileSdkVersion` 23 to 24. It seems to use `compileSdkVersion 24` in your library with support library (`appcompat`) version 24.0.0. Is it required for some code in your library? I think it should be able to override the support-lib version by my own.

**Comment by se-bastiaan** [comment]
Why don't you want to use API level 24? There is no reason to stick with 23.

**Comment by brianwernick** [comment]
You can also exclude the `appcompat-v7` transitive dependency (if you already include one) with
```gradle
compile ('com.devbrackets.android:exomedia:3.0.1') {
    exclude module: 'appcompat-v7'
}
```

However this doesn't change that ExoMedia was compiled with SDK version 24
