### ISSUE TITLE
What is the callback to report tracks played?  I tried onMediaPlaybackEnded() but is not working

### ISSUE THREAD

**Issue by jjvargas** [brianwernick/ExoMedia#294]
- [ YES ] I have verified there are no duplicate active or recent bugs, questions, or requests

I want to catch an event to report the info about tracks played and if they were played partial or in full. looks like this  is the right call back
@Override protected void onMediaPlaybackEnded(MediaItem playlistItem, long currentPosition, long duration)
{
}

Its never called, not sure if the event is connected correctly

###### Include the following:
 - ExoMedia version: `3.0.0`
 - Device OS version: `6.0.1`
 - Device Manufacturer: `Samsung Galaxy `
 - Device Name: `Note 4`
 
###### Reproduction Steps
 0.  

###### Expected Result
I expect onMediaPlaybackEnded() is triggered when skipping a song or finish fully playing a song

###### Actual Result
it never gets called

**Comment by brianwernick** [comment]
There is no method `protected void onMediaPlaybackEnded(MediaItem playlistItem, long currentPosition, long duration)` in `ExoMedia`, you are looking for the `PlaylistCore` repo.  If you look at the documentation for that method you will find "This is called when we are unable to play an item.", this indicates this is not the method you want; instead look at `onMediaPlaybackEnded()`
