### ISSUE TITLE
Exomedia Player blocking occassionally when livestreaming?

### ISSUE THREAD

**Issue by erkand-imeri** [brianwernick/ExoMedia#295]
Hello there, i am using ExoMedia Player for playing livestreaming links on my application and i am really liking it except that sometimes the video is blocking occassionally when i play the livestreaming http link?

How can i fix this?

**Comment by brianwernick** [comment]
What do you mean by "blocking"? that term can have many meanings

**Comment by erkand-imeri** [comment]
I mean that while the video is playing it stops at certain amount of time and then again starts to play, this doesn't happen with VideoView. I compared  both  players with the same link.

**Comment by brianwernick** [comment]
It sounds like the video is buffering (see #102)

**Comment by erkand-imeri** [comment]
@brianwernick, thanks for your reply. I want to ask you, how can i implement the buffering on the player.

What solution do you propose. Should i use the setOnBufferingListener() method on Android. I  was curious to know how do you implement  it.

Thanks in advance.

**Comment by brianwernick** [comment]
A Buffering indicator isn't currently implemented (not to be confused with initial loading or buffer percentage). The `OnBufferUpdateListener` informs you of percentage updates not status updates; what you want is a status callback (#257 with Open PR #293) to know when the media is buffering
