### ISSUE TITLE
Documentation links does not work

### ISSUE THREAD

**Issue by homburg** [brianwernick/ExoMedia#30]
Hi @brianwernick 

Thank you for developing this helpful library around exoplayer.

Apparently the documentation link in the root README.md is pointing to an invalid url:

http://devbrackets.com/dev/libs/docs/exomedia/2.4.0/index.html

The latest working documentation version link is: http://devbrackets.com/dev/libs/docs/exomedia/2.3.4/index.html

**Comment by brianwernick** [comment]
Oops.  I'll get that published later today when I have access to the computer with rights to push website changes.

**Comment by homburg** [comment]
Great, thanks!

**Comment by brianwernick** [comment]
Javadocs have been updated.

**Comment by homburg** [comment]
Hello Brian

The current link on master/2.4.1 does not seem to work: http://devbrackets.com/dev/libs/docs/exomedia/2.4.1/index.html

https://github.com/brianwernick/ExoMedia/commit/f4450f22cf772e4b3209ca04c8cf79ee36787e8e

**Comment by homburg** [comment]
Never mind, I had the old page cached. Works perfectly :+1:
