### ISSUE TITLE
Streaming really slow

### ISSUE THREAD

**Issue by franklinexpress** [brianwernick/ExoMedia#300]
- [ ] I have verified there are no duplicate active or recent bugs, questions, or requests

###### Include the following:
 - ExoMedia version: `3.0.0`
 - Device OS version: `6.0`
 - Devide Manufacturer: `Huawei`
 - Device Name: `Nexus 6P`
 
###### Reproduction Steps
 0.  

###### Expected Result
Smooth stream with 70Mbps internet
###### Actual Result
slow and sticky

When I open the video in chrome(android) it starts playing immediately and smoothly, on my app(same phone) it takes a while to start and the streaming is very skippy and slow, stops constantly, why is this?

**Comment by brianwernick** [comment]
There is a lot of information you have left out.
* What is the resolution?
* What is the format?
* Are you seeing this with other videos?
* Are there any logs indicating loss of packets, incorrect formats, etc.?
* What have you tried to fix this?
* etc.

**Comment by franklinexpress** [comment]
`public class VideoPlayerView extends AppCompatActivity {

    EMVideoView emVideoView;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_video_player_view);
        setupVideoView();
    }

    private void setupVideoView() {

        String postId = "";

        emVideoView = (EMVideoView)findViewById(R.id.video_view);

        Bundle extras = getIntent().getExtras();

            postId = extras.getString("videoid");
            //The key argument here must match that used in the other activity

            //For now we just picked an arbitrary item to play.  More can be found at
            //https://archive.org/details/more_animation
            Log.i("Upload", postId);
            String uri = "https://openout.herokuapp.com/posts/" + postId;
            Log.i("Upload", uri);

            emVideoView.setVideoURI(Uri.parse(uri));
            emVideoView.setControls(null);
            emVideoView.start();


    }`

Happens with every video. the postid is correct, I pasted the exact string in chrome mobile and it works perfectly. Is there something I'm doing wrong with the setup? I have resolution set to worse "0"

**Comment by franklinexpress** [comment]
I tried a few things, also note that the postid doesn't end with .mp4 it looks like this:

`https://openout.herokuapp.com/posts/57bda5f2c8ee380003a34501`

that returns an mp4 stream

Also, is there a way to get this to work with query params? as in ?id=57bda5f2c8ee380003a34501

**Comment by brianwernick** [comment]
To handle the query params you will need to implement your own `RenderBuilder` determination logic.

I just tested the provided URI on a Nexus 6 (7.0), Nexus 4 (4.4), and Nexus 6P (6.0) on a network that has a consistent throughput of 12-15 mbps; only the Nexus 4 had buffering issues (which is what the stuttering you are seeing is).

**Comment by franklinexpress** [comment]
I"m on a galaxy s7 edge, it's much better now. shoot I gotta delete those videos lol

**Comment by brianwernick** [comment]
Hmm, If you happen to figure out why the buffering is slower than the web browser please let me know. (Does chrome have a compression algorithm that mobile traffic is routed through?)

**Comment by franklinexpress** [comment]
Not sure, gzip?
