### ISSUE TITLE
Enable hiding/styling the progress and other video controls

### ISSUE THREAD

**Issue by StephaneBischoff** [brianwernick/ExoMedia#304]
Their seems to exist a VideoControls class which holds the various controls that I would like to style. Unfortunately, I have no idea how to do that.

Would need a way to:

- Hide or style the loading progress.
- style other controls such as Play, Pause, etc.

**Comment by brianwernick** [comment]
You should read the documentation for the `VideoControls`, `VideoControlsMobile`, and `VideoControlsLeanback` as this is already possible

**Comment by Shajeel-Afzal** [comment]
@brianwernick can you please share link of the documentation of `VideoControls`?
