### ISSUE TITLE
Update to ExoPlayer 2.0

### ISSUE THREAD

**Issue by brianwernick** [brianwernick/ExoMedia#311]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests

Title says it all

**Comment by cristin** [comment]
Hei!

Any update on this? Thank you!

**Comment by cristin** [comment]
Ok. Thank you! I recently updated to exoplayer 2 on an app that we are working and have an issue when playing mp4 video files encoded on iOS. Only the audio plays and no video. I saw that exomedia doesn't have this problem. Do you know what's the issue and how did you solved it? Thank you!

**Comment by brianwernick** [comment]
With the changes that they made to ExoPlayer 2.0 some of the unofficially supported formats were removed :(. Just using the ExoPlayer 1.5.x versions should allow you to play most videos recorded on iOS; I'm hoping this one is just a bug in ExoPlayer as it will most likely be a common use case.
