### ISSUE TITLE
EMVideoView not fitting the screen, looks slightly tilted

### ISSUE THREAD

**Issue by Shajeel-Afzal** [brianwernick/ExoMedia#318]
I am showing video using EMVideoView, but I see that it is not fitting the screen properly. Please see the screenshot. I have a basic layout:

```
<?xml version="1.0" encoding="utf-8"?>
<FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:EMVideoView="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:background="@color/icons"
    android:fitsSystemWindows="true"
    android:orientation="vertical">

    <com.devbrackets.android.exomedia.ui.widget.EMVideoView
        android:id="@+id/video_view"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:background="@color/icons"
        EMVideoView:useDefaultControls="true" />

    <include layout="@layout/toolbar" />
</FrameLayout>
```
Following is the view when using     `android:fitsSystemWindows="true"`
![device-2016-09-22-134400](https://cloud.githubusercontent.com/assets/3718283/18741755/475c40d4-80ca-11e6-80e1-caf98a1b2827.png)

And following is when not using     android:fitsSystemWindows="true", Can you please tell me what might be wrong?
![device-2016-09-22-134228](https://cloud.githubusercontent.com/assets/3718283/18741722/1ee217fa-80ca-11e6-9458-df73d7bb277c.png)

- [x] I have verified there are no duplicate active or recent bugs, questions, or requests

###### Include the following:
 - ExoMedia version: `3.0.0`
 - Device OS version: `6.0`
 - Devide Manufacturer: `Samsung`
 - Device Name: `S7 Edge`

**Comment by brianwernick** [comment]
It looks like the metadata for the video includes a non standard (multiple of 90) rotation.  Do you see this with different videos?

**Comment by brianwernick** [comment]
@Shajeel-Afzal If possible would you post the url to the video you are seeing this with. Otherwise I cannot Reproduce the issue

**Comment by Shajeel-Afzal** [comment]
@brianwernick sorry it was mistakenly done by me. It is resolved now, Thank you so much for creating this library 👍
