### ISSUE TITLE
Random .mp4 videos not playing

### ISSUE THREAD

**Issue by Keopss** [brianwernick/ExoMedia#324]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
###### Include the following:
- ExoMedia version: `3.0.1`
- Device OS version: `5.1`
- Devide Manufacturer: `Motorola`
- Device Name: `Moto G 3rd Gen`
###### Reproduction Steps

 I can play mp4 videos from URL but randomly some videos return error attached:
###### Expected Result

Reproduce the videos correctly.
###### Actual Result

09-28 22:42:39.418 20970-21952 E/AudioTrack: AudioFlinger could not create track, status: -12
09-28 22:42:39.420 20970-21952 E/AudioTrack-JNI: Error -12 initializing AudioTrack
09-28 22:42:39.422 20970-21952 E/android.media.AudioTrack: Error code -20 when initializing AudioTrack.
09-28 22:42:39.450 20970-20982 W/MediaPlayer-JNI: MediaPlayer finalized without being released
09-28 22:42:39.455 20970-21952 E/ExoPlayerImplInternal: Internal track renderer error.
                                                                              com.google.android.exoplayer.ExoPlaybackException: com.google.android.exoplayer.audio.AudioTrack$InitializationException: AudioTrack init failed: 0, Config(44100, 12, 61440) 

![captura de pantalla 2016-09-29 a las 9 44 05](https://cloud.githubusercontent.com/assets/7506141/18945136/66c35d4a-8629-11e6-9c00-d021e46abca3.png)

**Comment by Keopss** [comment]
Same error like this post https://github.com/google/ExoPlayer/issues/954

**Comment by se-bastiaan** [comment]
This doesn't look like it's ExoMedia's fault

**Comment by Keopss** [comment]
Why? It´s random not always fails same videos.

**Comment by se-bastiaan** [comment]
Because of the exception that you posted. Look at it, do you see anything that says 'ExoMedia'? It occurs in ExoPlayer code.
