### ISSUE TITLE
Make sure that all methods and variable related to duration and position are long

### ISSUE THREAD

**Issue by Gounlaf** [brianwernick/ExoMedia#327]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests

Hi,

As fixed brianwernick/PlaylistCore#21, everything related to duration and position are quite ambiguous: sometimes `int`, sometimes `long` (probably because of native MediaPlayer ?).

Same here: should it be long everywhere ?

I should be able submit PR to fix that.

Regards

**Comment by brianwernick** [comment]
I'll probably end up wrapping it which is what is already done for the ExoPlayer. I don't like the idea of having multiple methods for each call (e.g. `getDuration()` and `getDurationLong()`)

**Comment by Gounlaf** [comment]
Ok, i will do it :)

**Comment by brianwernick** [comment]
There is no branch to base it off yet. That's why it wasn't already done. (I was waiting until after the 3.1 release)

**Comment by Gounlaf** [comment]
Oh OK =/ I thank you haven't time to do it ;)

**Comment by brianwernick** [comment]
Yeah, don't get me wrong; I would appreciate help. It's just too early to update it currently

**Comment by Gounlaf** [comment]
> Yeah, don't get me wrong; I would appreciate help. It's just too early to update it currently
I don't ;) Let me know when you start it!
