### ISSUE TITLE
Video not play from assets and raw , but play from Https url

### ISSUE THREAD

**Issue by vkropivko** [brianwernick/ExoMedia#329]
Video not play from assets and raw , but play from Https url
How fix this ?

**Comment by se-bastiaan** [comment]
Please use the issue template and provide logs.

**Comment by vkropivko** [comment]
Unsupported mime audio/mpeg-L1
Unsupported mime audio/mpeg-L2
Unsupported mime audio/x-ms-wma
Unsupported mime audio/x-ima
Unrecognized profile/level 32768/2 for video/mp4v-es
Unrecognized profile 2130706433 for video/avc
 Unsupported mime video/wvc1
Unsupported mime video/x-ms-wmv
Unsupported mime video/x-ms-wmv7
Unsupported mime video/x-ms-wmv8
Unsupported mime video/mp43
Unsupported profile 4 for video/mp4v-es
Unsupported mime video/sorenson

**Comment by brianwernick** [comment]
It looks more like the particular video you are attempting to play isn't supported.

**Comment by vkropivko** [comment]
but this video from your URL with , I also download local video and add to assets

**Comment by brianwernick** [comment]
Please follow the issue template (as se-bastiaan already requested) and provide any other relevant information.
