### ISSUE TITLE
ExoMedia internal media controller changes size if IMMERSIVE MODE is used.

### ISSUE THREAD

**Issue by danielmaciel** [brianwernick/ExoMedia#33]
A margin appears on the right side of devices using software Navigation Bar.
It happens when your rotate the device when EMVideoView is fullscreen, changing from being on Landscape + Immersive Mode to Portrait without Immersive Mode nor Fullscreen.

**Comment by danielmaciel** [comment]
(I will attach a screenshot soon, I think it makes it easier to see the problem)

**Comment by brianwernick** [comment]
Ah thanks, A picture would be worth a lot in the case :)

**Comment by danielmaciel** [comment]
UI flags used:
    public static final int UI_OPTIONS = View.SYSTEM_UI_FLAG_LAYOUT_HIDE_NAVIGATION
            | View.SYSTEM_UI_FLAG_LAYOUT_STABLE
            | View.SYSTEM_UI_FLAG_LAYOUT_FULLSCREEN
            | View.SYSTEM_UI_FLAG_HIDE_NAVIGATION
            | View.SYSTEM_UI_FLAG_FULLSCREEN
            // NOTE: Only works on API 19+ ...
            | View.SYSTEM_UI_FLAG_IMMERSIVE
            ;

**Comment by danielmaciel** [comment]
Before Rotating:
![screenshot_2015-11-11-16-17-26](https://cloud.githubusercontent.com/assets/2924812/11099026/110c1398-8890-11e5-83e3-7afe0425adf5.png)

On Landscape mode:
![screenshot_2015-11-11-16-17-32](https://cloud.githubusercontent.com/assets/2924812/11099028/17cbb684-8890-11e5-8909-b3297e9a16a9.png)

After returning to Portrait
![screenshot_2015-11-11-16-17-36](https://cloud.githubusercontent.com/assets/2924812/11099030/19feac04-8890-11e5-954c-3cacd7043f93.png)

**Comment by danielmaciel** [comment]
(Thanks a lot)

**Comment by danielmaciel** [comment]
(Not sure it helps, but the gap seems to be exactly the same size as the Navigation Bar)

**Comment by brianwernick** [comment]
Yeah, It's because of a class that I'm using for performing the fitsStystemUI manually (since the actual flag can only be used once per layout).  I just need to re-calculate it on orientation changes.

**Comment by brianwernick** [comment]
Fixed (https://github.com/brianwernick/ExoMedia/commit/797f23f067b1774f5bab37abc13213c834cb1662)
