### ISSUE TITLE
HSL with encrypted data

### ISSUE THREAD

**Issue by rainboy93** [brianwernick/ExoMedia#330]
Hi,
How to use library for streaming video encrypted with AES128-bit.
Thanks in advance.

**Comment by brianwernick** [comment]
If you are talking about DRM content see #243. If your video data is actually encrypted you will need to provide your own RenderBuilder (or DataSource) that performs the decryption.

**Comment by rainboy93** [comment]
Thank for reply.
Do you have any example of DataSource that relate to AES128 encrypt?

**Comment by se-bastiaan** [comment]
Take a look at the [Aes128DataSource](https://github.com/google/ExoPlayer/blob/release-v2/library/src/main/java/com/google/android/exoplayer2/source/hls/Aes128DataSource.java) in the ExoPlayer v2 branch.

**Comment by rainboy93** [comment]
Thanks for reply.
At the moment, i'm using amazon for encrypt provider. 
Also, I use the existed `Aes128DataSource` file and create my own `HlsRendererBuilder` file.
`onSingleManifest` callback i insert the AES128DataSource  with constructor relate to DefaultUriDataSource

`byte[] encryptionKey = getKey("AQEDAHh27I7ep8UA8h4ZkT7gjFnS50KkxJDdrviotvprqVDP9AAAAG4wbAYJKoZIhvcNAQcGoF8wXQIBADBYBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDA96RCavMQRqiSr8iwIBEIArzmvU03UeW0ZBVh2Vgiby/S8h7hW2AKklfrNpvlOW6hMSMdR5dGpNe3wC+w==");`
` byte[] encryptionIv = Base64.decode("sydcozjckA+4OYQl9wBXkg==", Base64.DEFAULT);`
`Aes128DataSource aes128DataSource = new Aes128DataSource(dataSource, encryptionKey, encryptionIv);`
`final HlsChunkSource chunkSource;`
`chunkSource = new HlsChunkSource(true /* isMaster */, aes128DataSource , manifest,
                        DefaultHlsTrackSelector.newDefaultInstance(context), bandwidthMeter,
                        timestampAdjusterProvider);`

But when i run it always return `Error while finalizing cipher` Exception.
How can i turn out of this problem.
By the way i get the key decrypted like the answer in this link [https://forums.aws.amazon.com/thread.jspa?messageID=606859](url)

**Comment by rainboy93** [comment]
By the way, this is the link stream that i use to test:
[http://dgk6hzyysiw9f.cloudfront.net/hlsprotected/002testpl.m3u8](url)
and the key information:

Encryption Key
`AQEDAHh27I7ep8UA8h4ZkT7gjFnS50KkxJDdrviotvprqVDP9AAAAG4wbAYJKoZIhvcNAQcGoF8wXQIBADBYBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDA96RCavMQRqiSr8iwIBEIArzmvU03UeW0ZBVh2Vgiby/S8h7hW2AKklfrNpvlOW6hMSMdR5dGpNe3wC+w==`

Encryption Key MD5
`thCW4vOEyIGjfAM3rbrwnw==`

Encryption Initialization Vector
`sydcozjckA+4OYQl9wBXkg==`

I can't find the way to make it possible to run. Can you help me.

**Comment by brianwernick** [comment]
It will probably be a few days until I have time to look in to it; If it hasn't been resolved by then I will do so

**Comment by rainboy93** [comment]
Thanks. I am looking forward to hearing from you incase i can't resolve it.

**Comment by brianwernick** [comment]
Sorry about the delay other projects had been left alone too long. Did you end up figuring out the encryption issues? I know that ExoPlayer `1.5.12` fixed some issues with encryption; I'm assuming these fixes are in a later `2.0.x` release as well

**Comment by rainboy93** [comment]
Thanks in advance. I finnaly find out the way correct it. :D
