### ISSUE TITLE
Help me when add a full screen button.

### ISSUE THREAD

**Issue by DoaiNguyen** [brianwernick/ExoMedia#332]
Help me!!!
Thank you so much!

**Comment by brianwernick** [comment]
see #119, #204, or see the Demo application

**Comment by DoaiNguyen** [comment]
I saw 119 and 2014 issue, that right, when i rotated device, it's run true. But i want add a full screen button and when i handle to click event, i want to call to your method but i'm not found. when rotate the device, the VideoView is alo rotate and resize full screen, i don't know where
