### ISSUE TITLE
Set aspect ratio of player before playing video

### ISSUE THREAD

**Issue by sachinvelaga** [brianwernick/ExoMedia#333]
Hi,

I have implemented you exoplayer wrapper  successfully to play a .m3u8 url on android.  I am generating the url with a broadcast of a 640x480 camera resolution capturer.

While playing the video on device through URL,  the video does plays with a left right black border in landscape mode. 

Is it because the player's aspect ratio is 16:9 and i am playing a video of aspect ratio 4:3 ? if yes how do i set the player's aspect ratio to be same as video? 

If that is not the case, Where am i going wrong.. 

This is my view.. 

<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:EMVideoView="http://schemas.android.com/apk/res-auto"
    android:layout_width="fill_parent"
    android:layout_height="fill_parent">
  <com.devbrackets.android.exomedia.ui.widget.EMVideoView
         android:id="@+id/video_view"
         android:layout_width="fill_parent"
         android:layout_height="fill_parent"
         android:layout_alignParentBottom="true"
         android:layout_alignParentTop="true"
         android:layout_alignParentLeft="true"
         android:layout_alignParentRight="true"
         EMVideoView:useDefaultControls="true"
         android:visibility="invisible"/>
</RelativeLayout>

And in my activity.. i play the video with following lines.

        emVideoView.setVisibility(View.VISIBLE);
        emVideoView.setVideoURI(Uri.parse(mBroadcastUrl));
        emVideoView.setOnPreparedListener(this);

Please help me as i need to close this issue down asap.

**Comment by brianwernick** [comment]
By default the EMVideoView will use a scale type of `FIT_CENTER`, you can change this with `emVideoView.setScaleType()`
