### ISSUE TITLE
Can't find the exomedia api from import after updating to 3.0.5.

### ISSUE THREAD

**Issue by erkand-imeri** [brianwernick/ExoMedia#334]
Hello there, i updated the exomedia to the newest release 3.0.5 but i get errors since it doesn't recognize the import commands from my code.

`import com.devbrackets.android.exomedia.ui.widget.EMVideoView;`

What's the issue here? 

Thanks in advance.

**Comment by brianwernick** [comment]
This sounds like you have an issue with your gradle setup or something else isn't building correctly. `com.devbrackets.android.exomedia.ui.widget` is the correct package that `EMVideoView` resides in
