### ISSUE TITLE
setOnBufferUpdateListener never called

### ISSUE THREAD

**Issue by rajaEBA** [brianwernick/ExoMedia#335]
I want to show progressbar when change seekbar pin position.
This is my snippet code:

		emVideoView.setOnBufferUpdateListener(new OnBufferUpdateListener() {
			@Override
			public void onBufferingUpdate(@IntRange(from = 0, to = 100) int percent) {
				System.out.println("**************************************************");
			}
		});
P.s:I want use method like InfoListener in media player.

###### Include the following:

 - Device OS version: `4.2.1`
 - Devide Manufacturer: `Huawei`
 - Device Name: `G700`
 
###### Reproduction Steps
 0.

**Comment by brianwernick** [comment]
You have 2 separate questions here.
 1. Buffer listener not called was fixed with #321 
 2. Progress updates aren't emitted by the `EMVideoView` or `EMAudioPlayer`; you will need to poll them for changes (see the demo).
