### ISSUE TITLE
addExternalView didn't work on the android tv 

### ISSUE THREAD

**Issue by alexWr** [brianwernick/ExoMedia#339]
- [ ] I have verified there are no duplicate active or recent bugs, questions, or requests

Hello there, I have trouble with addExtraView() on the android tv.  
###### Include the following:
 - ExoMedia version: `3.0.5`
 - Device OS version: `5.1`
 - Devide Manufacturer: `Emulator`
 - Device Name: `Custom`

I add view with fullscreen button and run the app with player on the mobile device and everything is ok, I see my fullscreen button and it works fine. But when I try the same app on the tv emulator and real device extra view didn't show. Could you help me with this problem or it's android tv feature. Thanks

**Comment by brianwernick** [comment]
This is working as designed; `VideoControlsLeanback` doesn't support adding extra views (I thought I had documented it, probably got lost on a non-merged branch or merge conflict)
