### ISSUE TITLE
Is there a way to stream with HTTP Range headers ?

### ISSUE THREAD

**Issue by tigranbs** [brianwernick/ExoMedia#340]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests

It's not a bug, that's why I'm not putting device information!

I'm trying to serve video with HTTP Range headers, and most most of the Web Servers like Nginx have native support for that kind of streaming. Is there a way to explain how to stream video with `HTTP Range` ?

Thanks

**Comment by se-bastiaan** [comment]
You don't have to do anything. This is [supported out of the box](https://github.com/google/ExoPlayer/blob/release-v1/library/src/main/java/com/google/android/exoplayer/upstream/DefaultHttpDataSource.java#L457).

**Comment by tigranbs** [comment]
It is just getting Range header and setting Content Length, but it is not making another request to get next chunk range as it is described here <a href="https://tools.ietf.org/html/rfc7233">https://tools.ietf.org/html/rfc7233</a>.

Same server working great with basic iOS player and HTML5 player, but with Android MediPlayer or ExoPlayer it is not making correct HTTP Range requests

**Comment by se-bastiaan** [comment]
That part only gets the Range header and calculates the Content-Length yes. But [this part](https://github.com/google/ExoPlayer/blob/release-v1/library/src/main/java/com/google/android/exoplayer/upstream/DefaultHttpDataSource.java#L397) sets the range header using the current position and the content length passed to it. 

[Issues](https://github.com/google/ExoPlayer/issues/1238) and [pull requests](https://github.com/google/ExoPlayer/pull/382) in the repository also suggest that this is supported. Afaik it has to be supported for DASH to work at all. It's rather important for video playback, so I don't believe that it's not implemented.

However, it seems like this is not an issue with ExoMedia but with ExoPlayer. Maybe it would be better to create an issue in their repository?
