### ISSUE TITLE
Audio Handle While Calling

### ISSUE THREAD

**Issue by harsh-special** [brianwernick/ExoMedia#342]
- [ ] I have verified there are no duplicate active or recent bugs, questions, or requests

###### Include the following:
 - ExoMedia version: `3.0.0`
 - Device OS version: `6.0`
 - Devide Manufacturer: `LG`
 - Device Name: `Nexus 5`
 
###### Reproduction Steps
 1.Music to play
2.Receiving Incoming Call pauses Audio
3.) After Call ends, it doesn't automatically starts playing audio

###### Expected Result
After Call ends, it requires to play audio

###### Actual Result
After Call ends, it doesn't automatically starts playing audio

**Comment by brianwernick** [comment]
The `EMAudioPlayer` doesn't handle AudioFocus, that is up to you to implement. Likewise the `EMVideoView` doesn't currently handle AudioFocus (it will in `3.1.0`).

**Comment by harsh-special** [comment]
Can  you provide me some suggestion how to do that

**Comment by brianwernick** [comment]
A google search will give you all you need; or checkout StackOverflow.com
