### ISSUE TITLE
Bad fitsystemwindows with portrait orientation

### ISSUE THREAD

**Issue by billyjoker** [brianwernick/ExoMedia#343]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests

###### Include the following:
 - ExoMedia version: `3.0.0`
 - Device OS version: `5.1`
 - Devide Manufacturer: `Motorola`
 - Device Name: `Moto X 2015`
 
###### Reproduction Steps
1.  Prepare a EMVideoView on a layout with portrait orientation, top aligned
2.  Play a video

###### Expected Result

Respect top system bar, and below the EMVideoView

###### Actual Result

EMVideoView is overlaping the top system bar (portrait orientation).

It seems to be related with the fitSystemWindow attribute, is there any way to remove this behaviour?? I tried fitSystemWindow=true in my main DrawerLayout, provoking bad alignment on some versions of Android, i can get some fix with Api>=21 bad below Lollypop is driving me nuts. I have some difficulties to perform right in all versions at once.

One case of use: with soft buttons, Lollypop and below make in portrait bad alignment of other views at bottom, overlaping the soft buttons. It is needed some calculation to get the soft buttons height...

Thanks!!

**Comment by brianwernick** [comment]
This sounds like something you specified in your layout file, not something that is due to the `EMVideoView`.
