### ISSUE TITLE
setPreviewImage() not working 

### ISSUE THREAD

**Issue by AmirHadifar** [brianwernick/ExoMedia#35]
I use this function with URL & drawable but didn't work ( Nexus 5 , Android 6.0 ) 

here is my code : 

 emVideoView = (EMVideoView) findViewById(R.id.video_play_activity_video_view);
        emVideoView.setPreviewImage(getResources().getDrawable(R.drawable.ic_test));
        emVideoView.setOnPreparedListener(this);      emVideoView.setVideoURI(Uri.parse("https://archive.org/download/Popeye_forPresident/Popeye_forPresident_512kb.mp4"));

**Comment by brianwernick** [comment]
Thanks, I'll look in to it this weekend

**Comment by brianwernick** [comment]
The problem was that the `emVideoView.setVideoURI(...);` was prematurely hiding the image.  It will now be displayed until playback is started.

https://github.com/brianwernick/ExoMedia/pull/38

**Comment by liveaffiliates** [comment]
Hi, This is still not working. 

This is my code:

 videoView = findViewById(R.id.video_view);
        videoView.setPreviewImage(Uri.parse(downloadedAlarmToPlay.getAlarmPackImageLocation()));
        videoView.setVideoURI(Uri.parse(downloadedAlarmToPlay.getAlarmMediaLocation()));
        Log.d("Chex ", "image = " + downloadedAlarmToPlay.getAlarmPackImageLocation());
        videoView.setOnPreparedListener(this);

I checked the image link and it is fine. Is there maybe only certain image formats maybe?

It just gives a black screen and the loading icon and then the music starts (it is not a video would that make a difference?) .

Thanks

**Comment by liveaffiliates** [comment]
Checked with video as well and multiple image urls. Same thing.
