### ISSUE TITLE
Video bad quality!

### ISSUE THREAD

**Issue by erkand-imeri** [brianwernick/ExoMedia#350]
Hello there, i am using ExoMedia at my application, and i must say that it's a superfast player, but with some http links the quality of video is bad.

I don't know whether this happens when i put this code

`        emVideoView.setScaleType(ScaleType.NONE);
`

This code allows me to play http livestreaming videos on fullscreen. But i still have issues with the quality of video.

Any idea or suggestion to enlighten me about this problem?

Thanks in advance, Erkand.

- [x] I have verified there are no duplicate active or recent bugs, questions, or requests

###### Include the following:
 - ExoMedia version: `3.0.0`
 - Device OS version: `6.0`
 - Devide Manufacturer: `Huawei`
 - Device Name: `Nexus 6P`
 
###### Reproduction Steps
 0.

**Comment by brianwernick** [comment]
Are these videos that have decent quality when played elsewhere?

Also, you shouldn't have to change the ScaleType (default is `FIT_CENTER`) to support fullscreen, as long as the VideoView matches the entire screen it should work (e.g. see the demo app)

**Comment by erkand-imeri** [comment]
Yes, they are decent quality when played somewhere else with default VideoView. If i use the VideView then the Video is full screen but in ExoMedia it's not.

**Comment by se-bastiaan** [comment]
Aren't you able to provide a test stream or video? That would probably help a lot :)
