### ISSUE TITLE
How to show Next and Previous Controls

### ISSUE THREAD

**Issue by Shajeel-Afzal** [brianwernick/ExoMedia#352]
Hi, 

I want to show next and previous button in the VideoView but i am not sure how to do it? I see that there is VideoControl class in the library that can be used to show/hide next and previous controls but I am not sure how to use it. 

Can you please share the documentation if available or update the demo project?

- [x] I have verified there are no duplicate active or recent bugs, questions, or requests

###### Include the following:
 - ExoMedia version: `3.1.0`
 - Device OS version: `6.0`
 - Devide Manufacturer: `Samsung`
 - Device Name: `Nexus 6P`
 ######

**Comment by brianwernick** [comment]
The demo project already makes use of the next/previous buttons and the documentation is in the README

**Comment by Shajeel-Afzal** [comment]
@brianwernick I see that there is an example but it is using the Audio Player. I want to use it with the Video Player.

Currently, if I use it as follows it shows default controls (Play Button and Seekbar)

```
<com.devbrackets.android.exomedia.ui.widget.EMVideoView
            android:id="@+id/video_view"
            android:layout_width="match_parent"
            android:layout_height="wrap_content">

```
But i want next and previous button as well and this is how i am trying to achieve it:

```
<com.devbrackets.android.exomedia.ui.widget.EMVideoView
            android:id="@+id/video_view"
            android:layout_width="match_parent"
            android:layout_height="wrap_content">

            <com.devbrackets.android.exomedia.ui.widget.VideoControlsMobile
                android:id="@+id/video_controls"
                android:layout_width="match_parent"
                android:layout_height="wrap_content" />

        </com.devbrackets.android.exomedia.ui.widget.EMVideoView>

```

But when i do `setControls` in the activity it throws this exception: `Caused by: java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.`

```
mVideoView = (EMVideoView) findViewById(R.id.video_view);
mVideoView.setControls(mVideoControls);
```

**Comment by Shajeel-Afzal** [comment]
I also tried 

```
<com.devbrackets.android.exomedia.ui.widget.EMVideoView
            android:id="@+id/video_view"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            EMVideoView:useDefaultControls="true" />

```
And then in code: 

```
        mVideoView = (EMVideoView) findViewById(R.id.video_view);

        VideoControls controls = mVideoView.getVideoControls();
        controls.setNextButtonEnabled(true);
        controls.setPreviousButtonEnabled(true);

```

But no Luck.

**Comment by brianwernick** [comment]
Please read the documentation; more specifically [setNextButtonEnabled()](https://devbrackets.com/dev/libs/docs/exomedia/3.1.0/com/devbrackets/android/exomedia/ui/widget/VideoControls.html#setNextButtonEnabled-boolean-) and [setNextButtonRemoved()](https://devbrackets.com/dev/libs/docs/exomedia/3.1.0/com/devbrackets/android/exomedia/ui/widget/VideoControls.html#setNextButtonRemoved-boolean-)

**Comment by Shajeel-Afzal** [comment]
Thank you so much. I solved my problem.

**Comment by sarathsvs** [comment]
Is there any ways that i can switch between different qualities of my HLS Video

**Comment by aashish-bth** [comment]
getVideoControls() method is deprecated, instead of this we can use getVideoControlsCore() as suggested. But how we can add/enable next and previous button using getVideoControlsCore()?
