### ISSUE TITLE
Enable AC3 Passthough

### ISSUE THREAD

**Issue by jdprajapati** [brianwernick/ExoMedia#355]
Hello,

Can you please help me to enable audio passthrough?
I want to enable "AC-3, –enable-decoder=ac3"

Thanks in advance,
Jd

**Comment by brianwernick** [comment]
What have you tried, what ExoMedia version, what OS version, etc.

**Comment by jdprajapati** [comment]
Hello Brianwernick,

Sorry for delay reply.

ExoMedia library: 3.1.0
AndroidTV Version: 6.0.1

Is it support AC3? or enable something like that? because I do not hear the voice from my AndroidtTV.

Please give me replay ASAP.

Thanks,
Jd

**Comment by se-bastiaan** [comment]
Looking at the [AudioTrack.java](https://github.com/google/ExoPlayer/blob/release-v1/library/src/main/java/com/google/android/exoplayer/audio/AudioTrack.java#L393) file from ExoPlayer passthrough should be enabled for AC3 on API 21+. Since ExoMedia doesn't change any of this I do not think you'll find the source of your problem here.

**Comment by jdprajapati** [comment]
Hi,

Thanks for the replay.

Then why the sound is not working in our android box?
I need to set extation of FFPEG in project? 
For example: https://github.com/google/ExoPlayer/tree/release-v2/extensions/ffmpeg

Thanks,
Jd

**Comment by brianwernick** [comment]
If you call [`getAvailableTracks()`](https://github.com/brianwernick/ExoMedia/blob/master/library/src/main/java/com/devbrackets/android/exomedia/ui/widget/EMVideoView.java#L568) what tracks are returned for the [`TrackRenderType`](https://github.com/brianwernick/ExoMedia/blob/master/library/src/main/java/com/devbrackets/android/exomedia/annotation/TrackRenderType.java#L33) for audio?

**Comment by jdprajapati** [comment]
Yes, I checked and there is showing AC3 mimetype.

**Comment by brianwernick** [comment]
Hmm, It should be switching to AC3 then. What happens if you force it to use the AC3 track?

**Comment by jdprajapati** [comment]
Mean how can i use AC3 track force? is there available funcation to set force fully AC3 track?

**Comment by jdprajapati** [comment]
I am receiving audio format:
Format(2, null, audio/ac3, -1, , und, [-1, -1, -1.0], [6, 48000])

**Comment by brianwernick** [comment]
You can force it by manually setting the audio track to the AC3 one

**Comment by jdprajapati** [comment]
you mean I need to change audio configuration from AudioTrack.java?

**Comment by brianwernick** [comment]
I mean call [`setTrack()`](https://github.com/brianwernick/ExoMedia/blob/master/library/src/main/java/com/devbrackets/android/exomedia/ui/widget/EMVideoView.java#L557) (after retrieving the tracks with [`getAvailableTracks()`](https://github.com/brianwernick/ExoMedia/blob/master/library/src/main/java/com/devbrackets/android/exomedia/ui/widget/EMVideoView.java#L568) )

**Comment by jdprajapati** [comment]
there is no method available like setTrack....

**Comment by brianwernick** [comment]
It exists. [`setTrack(int, int)`](https://github.com/brianwernick/ExoMedia/blob/d7d45b86cc23bab7315c249455844f3ea1a1ef25/library/src/main/java/com/devbrackets/android/exomedia/ui/widget/EMVideoView.java#L557) is the exact code that is in `3.1.0`

**Comment by jdprajapati** [comment]
Hello Brianwernick,

My monitor is connected via HDMI:
Audio working: Format: [MediaFormat(null, audio/mp4a-latm, -1, -1, -1, -1, -1, -1.0, 2, 16000, null, -1, false, -1, -1, -1, -1, -1)]

Audio Not working:  Format: [MediaFormat(null, audio/ac3, -1, -1, -1, -1, -1, -1.0, 6, 48000, null, -1, false, -1, -1, -1, -1, -1)],, I tested in MxPlayer and its working then why its now working in our app?

I enable the audio using setTrack(EMExoPlayer.RENDER_AUDIO, 0);

Thanks,
Jd
