### ISSUE TITLE
not resizing video after view size is changed

### ISSUE THREAD

**Issue by scroozer** [brianwernick/ExoMedia#356]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests

###### Include the following:
 - ExoMedia version: `3.1.0`
 - Device OS version: `5.0`
 
###### Reproduction Steps
 0.  set source to EMVideoView , video loads correctly with correct aspect ratio.
 1. update layout params of EMVideoView and its container (Tried both) or resize EMVideoView in any way

###### Expected Result
EMVideoView re-scales the video depending on the new View size with the correct aspect ratio
###### Actual Result
For some reason EMVideoView does not detect a size change at all, the video is just stretched without taking the aspect ratio in count.

For some reason I couldnt find something in VideoApi that detects a size change, I did however find an interface called OnSurfaceSizeChanged but it is not used at all so I doubt something has been implemented to change the video size when surface is changed, I tried modifying the code and manually calling onVideoSizeChanged and calculating the height using MediaFormat.pixelWidthHeightRatio to pass it to onVideoSizeChanged but the height still doesnt seem to be correct. Please enlighten me if there is a way to notify EMVideoView that the surface size has changed. Thanks

**Comment by brianwernick** [comment]
This sounds like #264
