### ISSUE TITLE
Releasing after multiple attach and detach even though releaseOnDetach is false

### ISSUE THREAD

**Issue by scroozer** [brianwernick/ExoMedia#357]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests

###### Include the following:
 - ExoMedia version: `3.0.0`
 - Device OS version: `6.0`
 - Devide Manufacturer: `Huawei`
 - Device Name: `Nexus 6P`
 
###### Reproduction Steps
 0.  set releaseOnDetach to false
1. Detach EMVideoView from current parent 
2. Attach to a new parent (In y case addView to window manager)
3. Detach from current parent and add to another

###### Expected Result
Should detach and re-attach as normal like in first step
###### Actual Result
After detach the player is released for some reason

**Comment by brianwernick** [comment]
Please include relevant logs and anything that indicates it's the EMVideoView performing the release

**Comment by scroozer** [comment]
I did the same test using ExoPLayer and it looks like its ExoPlayer thats performing the release and not ExoMedia  since the error persists

**Comment by brianwernick** [comment]
Hmm.  Why do you need to re-attach the `EMVideoView` to the window? The reason I added the `releaseOnDetach` was mainly for lists so that playback wouldn't halt when the view went outside of the visible bounds.

**Comment by scroozer** [comment]
because I have a full screen button the detaches the player and attached it to a new view using windowmanager addView an dwhen the user clicks again it should detach again and return to normal size
