### ISSUE TITLE
doesnot support  sdp ‎format

### ISSUE THREAD

**Issue by altaf2892** [brianwernick/ExoMedia#358]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests

###### Include the following:
 - ExoMedia version: `3.0.0`
 - Device OS version: `6.0`
 - Devide Manufacturer: `Huawei`
 - Device Name: `Nexus 6P`
 
###### Reproduction Steps
 0.

**Comment by brianwernick** [comment]
See https://github.com/google/ExoPlayer/issues/55
Currently there are no plans to support RTSP, SDP, SIP, etc. in the ExoPlayer nor in ExoMedia because of this
