### ISSUE TITLE
Support for ID3 metatags

### ISSUE THREAD

**Issue by daliz** [brianwernick/ExoMedia#359]
I see I can attach an Id3MetadataListener to an EMAudioPlayer instance, but this event is never fired during a streaming. I can't find methods to manually fire it. Is there a way to get ID3 metatags with ExoMedia?

**Comment by brianwernick** [comment]
Id3 metadata is currently only supported in HLS (per ExoPlayer), are you using an HLS source that includes the extra metadata tags?

**Comment by daliz** [comment]
No, I'm not using an HLS stream and sadly I can't change this. I'll have to find another way to extract the ID3 tags. Thank you for your reply.
