### ISSUE TITLE
setOnCompletionListener is called only once

### ISSUE THREAD

**Issue by wesjon** [brianwernick/ExoMedia#36]
Hello brianwernick,

We were using `setOnCompletionListener` to rewind the video once it ends and we noticed this listener would only be called the first time the video is completed.

As a workaround we are now using the `addExoPlayerListener` with `playbackstate ExoPlayer.STATE_ENDED`

**Comment by brianwernick** [comment]
OK.  The flag for completion should probably be reset when the video playback begins again.  It will probably be a few days before I can address this, or you can create a PR.

**Comment by brianwernick** [comment]
This has been fixed in https://github.com/brianwernick/ExoMedia/pull/39.
