### ISSUE TITLE
how can hide seek bar for hls streaning

### ISSUE THREAD

**Issue by mohammed94949494** [brianwernick/ExoMedia#361]
hello how can hide seek bar such as 
emVideoView.getVideoControls().setPreviousButtonRemoved(true);
        emVideoView.getVideoControls().setNextButtonRemoved(true);

**Comment by brianwernick** [comment]
You will either need to extend the `VideoControlsMobile` (or `VideoControlsLeanback`) and provide that, or you can probably use `emVideoView.getVideoControls().findViewById(R.id.exomedia_controls_video_seek)`

**Comment by linslouis** [comment]
getVideoControls() depricated
