### ISSUE TITLE
Question about custom seek-bar

### ISSUE THREAD

**Issue by maxglu** [brianwernick/ExoMedia#363]
Hi! Thank you for excellent library :)
Please tell me, how I can create a custom seek-bar? And disable all other controls.

Info:
 - ExoMedia version: `3.1.0`
 - Device OS version: `6.0.1 (CyanogenMod)`
 - Devide Manufacturer: `Xiaomi`
 - Device Name: `Mi4 (cancro)`

**Comment by brianwernick** [comment]
What do you mean by `custom seek-bar`, do you just mean custom styling?  You can disable the other controls with the `videoView.getVideoControls().set*ButtonRemoved()` methods

**Comment by maxglu** [comment]
Thank you for the quick answer!
No, i don't mean styling. I need to calculate thumb widht in dependency of a video length for limit seeking . But i think i will just construct custom element based on standard seek bar, and use method seekTo(), for controlling seeking. Perhaps it will help me.
I thought maybe I need to override some internal class.
