### ISSUE TITLE
Choppy video playback

### ISSUE THREAD

**Issue by vipulpurohit** [brianwernick/ExoMedia#369]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests

###### Include the following:
 - ExoMedia version: `3.1.0`
 - Device OS version: `5.1`
 - Device Manufacturer: `HiMedia`
 - Device Name: `Q10 Pro`
 
###### Reproduction Steps
 Play any video with 2K HEVC in HLS/Mp4 format in offline mode (Files are on local storage).

###### Expected Result
Video should play smoothly without any choppiness.

###### Actual Result
The video stuck for around 50-100 ms in random duration.

I've tried the same video with ExoMedia and ExoPlayer's sample application in .mp4 and hls format. With ExoMedia's sample it's choppy and not producing smooth result. But with ExoPlayer's sample it's working fine. I'm using the same ExoPlayer version r1.5.12 in both application.

I tried with multiple HEVC files with 2K and higher resolution and the result is same. I guess it might be something with HEVC format as I'm facing this issue with some standard HD videos too.

I tried the same file with device's native player and its working fine without any issue.
Due to copyrights issue I'm not able to share the video files.
If you need any further information please let me know.

Thanks

**Comment by brianwernick** [comment]
I can't do much without a video to duplicate the issue with.

**Comment by vipulpurohit** [comment]
Found the solution.
TextureView was causing the problem. I changed it to SurfaceView and now it working fine.
This might be as issue with ExoPlayer.

https://github.com/google/ExoPlayer/issues/98
https://github.com/google/ExoPlayer/issues/58

**Comment by brianwernick** [comment]
Hmm, that's interesting I'm glad that you figured it out. 

Among many other things I want to update the default backing to be the SurfaceView in 4.0 for a few reasons;
 * SurfaceView uses less power
 * SurfaceView supports DRM
 * Most uses won't require the Animations or other natural View tendencies a TextureView has.

This just adds to that list :)
