### ISSUE TITLE
can not play video

### ISSUE THREAD

**Issue by madaotw** [brianwernick/ExoMedia#370]
###### Include the following:
 - ExoMedia version: `3.1.0`
 - Device OS version: `6.0`
 - Devide Manufacturer: `LG`
 - Device Name: `G4`
 
###### Reproduction Steps
use readme.md's simple code to play a RTSP video(test more urls..)

###### Expected Result
should work
###### Actual Result
just loading...
how would I do?

**Comment by brianwernick** [comment]
RTSP is currently not a supported format in either ExoMedia or ExoPlayer. There are projects that created RenderBuilders for RTSP but nothing that is native

**Comment by madaotw** [comment]
Thank you for your answer, 
Do you know the player can hardware-decode(like mediacodec) support RTSP?
currently I use android media player, it has delay problem.

**Comment by brianwernick** [comment]
AFAIK the Android VideoView uses software (native) decoding for RTSP. There is an open issue against the ExoPlayer discussing RTSP that may be of interest to you https://github.com/google/ExoPlayer/issues/55
