### ISSUE TITLE
listener for tracking loading start/stop

### ISSUE THREAD

**Issue by mugar** [brianwernick/ExoMedia#373]
- [ ] I have verified there are no duplicate active or recent bugs, questions, or requests

###### Include the following:
 - ExoMedia version: `3.0.0`
 - Device OS version: `any`
 - Devide Manufacturer: `any`
 - Device Name: `any`
 
###### Reproduction Steps
 0.  

###### Actual Result

Hi Brian. thanks for such an amazing library. 

I just want to know how to get notified when the video starts/stops loading in the middle of a play after the onPrepared has been fired. I know exoplayer has a method for that with the following signature: 
  public void onLoadingChanged(boolean isLoading) {}

thanks for your help.

**Comment by brianwernick** [comment]
This isn't currently available, however as this will be possible with #257 I'll mark this as a duplicate
