### ISSUE TITLE
Audio only

### ISSUE THREAD

**Issue by Misiur** [brianwernick/ExoMedia#377]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests

###### Include the following:
 - ExoMedia version: `3.1.0`
 - Device OS version: `4.3`
 - Devide Manufacturer: `Emulator`
 - Device Name: `Emulator`
 
###### Reproduction Steps
 Code I'm using as an extension in openfl (haxe) environment
```java
public class Video
{
    private EMVideoView emVideoView = null;

    public Video(Activity mainActivity, final View mainView, final Context mainContext) {
        new Handler(Looper.getMainLooper()).post(new Runnable() {           
            @Override
            public void run() {
                emVideoView = new EMVideoView(mainContext);
                RelativeLayout.LayoutParams params = new RelativeLayout.LayoutParams(RelativeLayout.LayoutParams.MATCH_PARENT, RelativeLayout.LayoutParams.WRAP_CONTENT);
                params.addRule(RelativeLayout.ALIGN_PARENT_RIGHT);
                emVideoView.setLayoutParams(params);

                ViewGroup container = (ViewGroup) mainView;

                container.addView(emVideoView);
                emVideoView.setOnPreparedListener(new OnPreparedListener() {
                    @Override
                    public void onPrepared() {
                        emVideoView.start();
                    }
                });
                // emVideoView.setVideoURI(Uri.parse("https://archive.org/download/Popeye_forPresident/Popeye_forPresident_512kb.mp4"));
                emVideoView.setVideoURI(Uri.parse("http://clips.vorwaerts-gmbh.de/big_buck_bunny.mp4"));
            }
        });
    }
}
```

###### Expected Result
Playing video

###### Actual Result
Sound playing only. Console output:
```
I/VideoCapabilities( 2274): Unsupported profile 4 for video/mp4v-es
I/OMXClient( 2274): Using client-side OMX mux.
I/MediaFocusControl( 1480):  AudioFocus  requestAudioFocus() from android.media.AudioManager@382c371ccom.devbrackets.android.exomedia.ui.widget.EMVideoView$AudioFocusHelper@1f462f25 req=1flags=0x0
```
This is my first day with android, so sorry if it's unrelated. Yet I can't play neither mp4 (popeye example is sound only as well), nor webm (which seems to be just a wrapper around mp4). If it's not a ExoMedia bug, please point me where I should be looking instead.

**Comment by se-bastiaan** [comment]
You probably want to do all of the code in your class directly in your activity. You shouldn't even need the Handler for this. Also, the activity ís the context you need for the view.

Just guessing, but I think that the VideoView just isn't visible due to the implementation. Maybe because the alignment is incorrect, or wrap_content doesn't work.

**Comment by Misiur** [comment]
All extensions are in separate threads, so that's a must unfortunately. However, I solved the problem! I missed this line of log
`W/TextureView( 2434): A TextureView or a subclass can only be used with hardware acceleration enabled.`

So, the solution is: When setting up the emulator make sure that "Use host GPU" is enabled

Thank you
