### ISSUE TITLE
Unsupported Video Capabilities

### ISSUE THREAD

**Issue by mitsus** [brianwernick/ExoMedia#384]
- [ ] I have verified there are no duplicate active or recent bugs, questions, or requests

###### Include the following:
 - ExoMedia version: `3.1.1`
 - Device OS version: `6.0.1`
 - Devide Manufacturer: `Sony`
 - Device Name: `Xperia Z5`
 
When i try to start video streming from my TVHeadend home video server i see there errors:

W/VideoCapabilities: Unrecognized profile 2130706433 for video/avc
W/AudioCapabilities: Unsupported mime audio/alac
W/AudioCapabilities: Unsupported mime audio/dsd
W/VideoCapabilities: Unsupported mime video/divx
W/VideoCapabilities: Unsupported mime video/divx311
W/VideoCapabilities: Unsupported mime video/divx4
 W/VideoCapabilities: Unsupported mime video/mp4v-esdp
 I/VideoCapabilities: Unsupported profile 4 for video/mp4v-es

How can i solve?
Thanks

**Comment by brianwernick** [comment]
This is an unsupported format from the ExoPlayer Renders. You can either provide a customized RenderBuilder that supports one of the mime types listed or re-encode the media
