### ISSUE TITLE
[Feature] AudioPlayback with ExoPlayer

### ISSUE THREAD

**Issue by Gounlaf** [brianwernick/ExoMedia#385]
Hi @brianwernick,

According to [this](https://realm.io/news/360andev-effie-barak-switching-exoplayer-better-video-android/), ExoPlayer can read audio from a video stream, without drawing the video on a surface (with something like this: `player.blockingSendMessage(videoRenderer, MediaCodecVideoTrackRenderer.MSG_SET_SURFACE, null);`)

Have you any time / quick idea to allow switching between audio/video ?

I've take a look; I started to work on it. But I would like to have some input / advices.

Thanks

**Comment by brianwernick** [comment]
What do you mean `"switching between audio/video"`?

If you want to just play the audio from a video url you can just pass that in to the `EMAudioPlayer`.  Alternatively if you want the Video without audio you can disable the audio channel with a combination of [`getAvailableTracks()`](https://github.com/brianwernick/ExoMedia/blob/master/library/src/main/java/com/devbrackets/android/exomedia/ui/widget/EMVideoView.java#L568) and [`setTrack()`](https://github.com/brianwernick/ExoMedia/blob/master/library/src/main/java/com/devbrackets/android/exomedia/ui/widget/EMVideoView.java#L557) (which can also be used for other fun track selection opportunities like YouTubes quality selection)

**Comment by Gounlaf** [comment]
> What do you mean `"switching between audio/video"`?

I would like to play the Audio track from my video, without starting the `EMAudioPlayer`, for example when the screen turn off, and so keeping it in a Service to allow playing in background mode. Then, when screen turn on, the player will be updated with the new surface.

Starting it is "too long", causing an earable break (1 or 2s).
With an existing initialized `EMExoPlayer`, playing a video stream could be done without break (at least, it would keep the already buffered stream), by setting or clearing the surface.

Right now, I'm switching manually between the video and the audio player.

**Comment by brianwernick** [comment]
Oh, #88 should be of interest to you then. In order to get background playback to work correctly then you will need to perform some additional work to be able to add and remove the surface from the Player (i.e. this isn't provided by the EMVideoView or EMAudioPlayer out of the box).
