### ISSUE TITLE
dev_v4 build not available in jcenter()

### ISSUE THREAD

**Issue by needz** [brianwernick/ExoMedia#390]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests

###### Include the following:
 - ExoMedia version: `4.0.0`
 - Device OS version: `7.1.1`
 - Devide Manufacturer: `Asus`
 - Device Name: `Nexus Player`
 
###### Reproduction Steps
0.  Add compile 'com.devbrackets.android:exomedia:4.0.0' to app gradle
1. Sync gradle

###### Expected Result
0. Gradle is synced

###### Actual Result
0. Error:(60, 13) Failed to resolve: com.devbrackets.android:exomedia:4.0.0

**Comment by needz** [comment]
Dear Brian, could you please post the dev_v4 build to the jcenter(), so it can be included in the app?

**Comment by brianwernick** [comment]
Publishing a `4.0.0-EAP` is on my list of things to do this week, there are a few things that need to be fixed before then though (the loading state, etc. aren't quite right)

**Comment by brianwernick** [comment]
`4.0.0-preview1` is now in JCenter

**Comment by brianwernick** [comment]
Oops, apparently my first attempt at the `4.0.0-preview1` didn't publish correctly. I have updated the publication so it should work now
