### ISSUE TITLE
FullScreen Layout EMVideoView Landscape No Status or Navigation bars

### ISSUE THREAD

**Issue by ndy1g14** [brianwernick/ExoMedia#392]
Hi, congrats on the amazing work. I have troubles making my EMVideoView fullscreen. I use the last version of the library.
![screenshot_20170205-192749](https://cloud.githubusercontent.com/assets/17951430/22629207/b528923c-ebd9-11e6-97c3-803918064175.png)

I use the flags that are in full screen activity demo plus the immerse sticky flag. Is there a way for the the title and the seekbar to match parent on landscape mode. Thank you!

**Comment by brianwernick** [comment]
You shouldn't hide the navigation (i.e. be in immersive mode) when the controls are visible. Otherwise the use will have to click twice (once where the immersive mode captures and exits, and once more to hit the playback controls).

**Comment by ndy1g14** [comment]
I meant to use it as youtube does. You click and the title shows with the seek bar and you scroll from top to show navigation and status bar. Sorry I didn't understand from your response whether this is possible.

**Comment by brianwernick** [comment]
Oh, I see what you are asking. Yes, it's possible by disabling the `fitssystemwindow` flag for the video controls

**Comment by ndy1g14** [comment]
I tried it but sadly it didn't work. If it works with your example can you show me how to do it. I did it like this:

`emVideoView.getVideoControls().setFitsSystemWindows(false);`

**Comment by brianwernick** [comment]
Oops, I had forgotten that the backing was `FitsSystemWindowRelativeLayout` which effectively ignores the `setFitsSystemWindows()` flag and always applies it.  Because of the way `fitsSystemWindows` flag works you can essentially short circuit the `FitsSystemWindowRelativeLayout` by adding a view higher in the xml that has `fitsSystemWindows` enabled.

e.g.
```xml
    <!-- Short circuits the ExoMedia VideoControls fitsSystemWindows  -->
    <View
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:fitsSystemWindows="true"/>

    <com.devbrackets.android.exomedia.ui.widget.EMVideoView
        android:id="@+id/video_view"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        app:useDefaultControls="true"/>
```

**Comment by ndy1g14** [comment]
Awesome! Thank you very much and keep up the good work!
