### ISSUE TITLE
Player gives Rendering error when video width is less than 400

### ISSUE THREAD

**Issue by Farrukh381** [brianwernick/ExoMedia#393]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
Hi i have used your library for live streaming app of different TV channels..........player play most of channels but any channel whose width is less than 400 gives an error and won't play
###### Include the following:
 - ExoMedia version: `3.0.0`
 - Device OS version: `5.0`,'6.0.1'
 - Devide Manufacturer: `Samsung s4`,Samsung s4

what i get from logs 
ExoPlayerImplInternal: Internal track renderer error.                                                                                        com.google.android.exoplayer.ExoPlaybackException: com.google.android.exoplayer.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 404

This issue does not occur on sdk level 17-20 but gives this error from 20+ sdk level
Thanks

**Comment by brianwernick** [comment]
The response code indicates that the source your are attempting to play doesn't exist. Additionally a few of the samples have a width under 400 and play just fine.
