### ISSUE TITLE
catching ExoPlaybackException and Response Codes

### ISSUE THREAD

**Issue by SAlavizadeh** [brianwernick/ExoMedia#394]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests

###### Include the following:
 - ExoMedia version: `3.1.1`
 
 
How can I catch ExoPlaybackException and Response Codes by my own error handler in activity?

in `ExoPlayer` I implemented  `onError(EMExoPlayer emExoPlayer, Exception e)` method from `ExoPlayerListener`, but here how I can do this?

Thanks for your efforts

**Comment by brianwernick** [comment]
What are you trying to do by catching the exception and responses?  Maybe see #299

**Comment by SAlavizadeh** [comment]
Maybe, I need Exception message to detect response code.

**Comment by brianwernick** [comment]
OK, yeah this is resolved with #299 then
