### ISSUE TITLE
Possible Memory leak when showing bitmap on the Notification

### ISSUE THREAD

**Issue by jjvargas** [brianwernick/ExoMedia#40]
When playing tracks the Audio Service updates the notification and lock screen with a given Image , By mistake I was not resizing my images and it was loading an 1080x1080 image , so after playing some tracks and changing this images a few times, I got an OOM.    

I reckon the Bitmaps are not being recycled properly?  

I just made a temporarely fix by resizing the bitmaps when loading them but I believe this will just delay the OOM.

I am not sure if keeping the BItmap references on the AudioService might be causing this??

**Comment by brianwernick** [comment]
Sorry I haven't replied before now.  I'm looking in to the issue

**Comment by brianwernick** [comment]
OK, this was fixed in https://github.com/brianwernick/ExoMedia/commit/8800783bda7f8fcb1546a99c9874faa1e220c738 and will be in the next release.

However, you should still resize the bitmaps before passing back to the EMPlaylistService.
