### ISSUE TITLE
Native error when finishAffinity called

### ISSUE THREAD

**Issue by maxglu** [brianwernick/ExoMedia#402]
Hello.
I use qour library, and its working perfect on my device :)
But I have one problem. On Samsung Galaxy S3 with Android 4.4 (CyanogenMod) and Huawei G6 with Android 4.3 (Original firmware) application crashes, when I trying call finishAffinity();
Library version is 3.1.0
You may see part of my fragment in [this gist](https://gist.github.com/maxglu/b007dab44a89eb307c4ded84fb224411)

In logs I see [this error](https://gist.github.com/maxglu/d3c3ae32dd37b16abd9ed19ab44d1a0b) and I dont understand whats happening. 
I trying call player.release() before finish and result is same.
Could you help me please?

**Comment by brianwernick** [comment]
Are the errors actually the same between the two devices? I don't put any credibility on correctness (for googles required compatibility) in CM so I'm more interested in the logs from the Huawei G6

**Comment by maxglu** [comment]
I'm so sorry, my mistake. In Huawei all seems good now, I fixed my own bug. On Samsung device still getting error, but I think this is firmware problem.
Thank you for answer
