### ISSUE TITLE
OnErrorListener Doesn't get called

### ISSUE THREAD

**Issue by YasserHossam** [brianwernick/ExoMedia#403]
I'm using your library to play videos repeatedly, There are sometimes the videos I fetch couldn't be encoded, so the solution to this is assigning OnErrorListener to my EMVideoView, but the onError doesn't get called and OnCompletion is called instead. and since I restart video on completion, it repeatedly restarts the broken video. 
Thanks in advance.

**Comment by brianwernick** [comment]
Please include the necessary information. How can this be reproduced? etc.

**Comment by YasserHossam** [comment]
I'm sorry for bothering You. 
but i found that this issue happened only with the emulator, when i tried it on a mobile it didn't happen. 
Sorry again .

**Comment by brianwernick** [comment]
Oh, no problem. It's good to know that may happen with Emulators
