### ISSUE TITLE
java.lang.NoClassDefFoundError:

### ISSUE THREAD

**Issue by magirtopcu** [brianwernick/ExoMedia#407]
-  java.lang.NoClassDefFoundError: com.devbrackets.android.exomedia.core.exoplayer.EMExoPlayer

###### Include the following:
 - ExoMedia version: `3.1.1`
 - Device OS version: `6.0`
 - Devide Manufacturer: `Samsung`
 - Device Name: `Galaxy S6`
 
When trying to create new instance of  EMAudioPlayer, throws ava.lang.NoClassDefFoundError exception on runtime for class EMExoPlayer.  But I can see compiled EMExoPlayer.class in adt.
Also see https://github.com/google/ExoPlayer/issues/2062 . 

Problem : 
Other dependencies which use   1.5.13+ version of ExoPlayer  override ExoPlayer version  in project and ExoPlayer has no backward compatibility, after release of 2.0.0 of ExoPlayer , its package  name changes from com/google/android/exoplayer to com/google/android/exoplayer2 . That's why android can't find class on runtime from package  com/google/android/exoplayer.

**Comment by brianwernick** [comment]
This is definitely expected as ExoMedia 3.x doesn't support ExoPlayer 2.x. There are two choices, revert the other dependencies that are using ExoPlayer to a supported version, or you can use the preveiw for ExoMedia 4.0 which was updated to use ExoPlayer 2.x
