### ISSUE TITLE
loadingProgress (loader) hidden immediately during a manual seek by the user. 

### ISSUE THREAD

**Issue by devanshuk** [brianwernick/ExoMedia#409]
###### Device Info:
 - ExoMedia version: `3.1.1`
 - Device OS version: `6.0`
 - Devide Manufacturer: `Samsung`
 - Device Name: `J7`
 
###### Reproduction Steps
 1. Open the video activity which uses `emVideoView`
2. Perform a seek event by touching the seek bar

###### Expected Result
(indeterminate) progressbar should be shown

###### Actual Result
(indeterminate) progressbar is not shown

###### Debug Hint
`onSeekComplete` is being called twice, once immediately after the seek event is initiated (not expected) and once after the seek event is actually completed (expected). The first call causes the progressBar to be hidden immediately.

**Comment by brianwernick** [comment]
This kind of sounds like the digitizer isn't working correctly, I'll look in to it though and see why controls are hiding when the user is interacting

**Comment by devanshuk** [comment]
Just to clarify the `(indeterminate) progressbar` refers to the `loadingProgress' - this is visible when I trigger a seek even programmatically using `seekTo()` but not when the user seeks using the seek bar on the controller.

**Comment by brianwernick** [comment]
Just to clarify: you are saying that the user performs a seek (ui), the loading progress doesn't show, and the video isn't playing?

**Comment by devanshuk** [comment]
Yes, correct. The seek happens but the loading progress does not show.

**Comment by devanshuk** [comment]
Hi Brian, can you please let me know if this fix is in your roadmap for the next release?

**Comment by brianwernick** [comment]
I looked a little in to it a week or so ago and it looked like the state that the ExoPlayer was reporting was `READY` which is what causes the progress to hide. I didn't have time to look further in to it, or in to why `onSeekComplete` is called twice. This is looking like it's more related to #102 than being a new bug. My hope is to get a fix (if it is a bug) for the next release

**Comment by devanshuk** [comment]
Okay. If it helps, I was using version 3.0.5 earlier, and this specific bug wasn't there.

**Comment by brianwernick** [comment]
Knowing that it broke after `3.0.5` was enough to point me to the correct spot that causes the issue
