### ISSUE TITLE
Rotating EMVideoView

### ISSUE THREAD

**Issue by droidekas** [brianwernick/ExoMedia#41]
Is there any way that i can rotate the video view without sufferring from state loss?
I've tried using setRotation and also from xml.
 I am show an EMVideoView in a dialog fragment and would like to rotate that by 90 degrees. However I just get a transparent background instead of a video then.
Is there a correct way to rotate ? Is rotation possible?

**Comment by brianwernick** [comment]
The current demo app correctly handles device rotation when playing a video.  Your problem sounds like an issues with the dialog fragment.  Possibly related to http://stackoverflow.com/questions/14657490/how-to-properly-retain-a-dialogfragment-through-rotation

**Comment by droidekas** [comment]
Sorry I was not clear enough.I have a portrait activity where I have am trying to open a Dialog fragment where by rotating the EMVideView by 90,i plan to make it look like landscape.Is that possible?

**Comment by brianwernick** [comment]
Not currently (and I don't plan on adding it in the future since it is a very small edge case).  You might be able to do something similar to what is described in http://stackoverflow.com/questions/8586526/rotating-an-android-videoview

**Comment by droidekas** [comment]
Can i get a reference to the VideoView used here?

**Comment by brianwernick** [comment]
Sorry, I'm not sure what you are asking?

**Comment by droidekas** [comment]
in EMVideoView can i get a reference to the underlying view to rotate it.Or is it not possible with EMVideoView?

**Comment by brianwernick** [comment]
Oh, you would probably need to modify the exoVideoSurfaceView (https://github.com/brianwernick/ExoMedia/blob/master/library/src/main/java/com/devbrackets/android/exomedia/EMVideoView.java#L239).  However, this would require modifications to the layouts referenced in `initView` which is private.  So when I get a little time I will update method availabilities to protected and maybe re-structure a little to help with any custom video layouts like this

**Comment by droidekas** [comment]
OK thanks,Feel free to close the issue if its out of scope .Thank you :+1:  :)

**Comment by droidekas** [comment]
Also ,I do not want to open an issue for something this trivial hence asking here.But I cannot play webm videos on a Samsung API 17 phone. Is that possible? Or am i doing something wrong. Only audio plays while there is no video.

**Comment by brianwernick** [comment]
Hmm, webm should work :/

**Comment by droidekas** [comment]
And if a video does not play,is there a callback that I can receive and choose an alternating format

**Comment by brianwernick** [comment]
Sorry; I haven't forgotten about this, I've just been pretty busy with work lately.  It looks like it may be closer to the new year when I can get around to any issues :(

**Comment by droidekas** [comment]
No issues.Thank you for the library :).

**Comment by brianwernick** [comment]
I just tried webm again and it plays without issues on my Nexus devices (and the new emulator) [http://video.webmfiles.org/big-buck-bunny_trailer.webm]

**Comment by brianwernick** [comment]
I'm going to close this as WEBM is currently working (there are updates that will be in 2.5.0 that should fix a few minor playback issues).  The method availability changes will be in the next major release (3.0) since I'm making other architectural changes I will wait until then.

**Comment by brianwernick** [comment]
As far as the original Rotation question goes: I have added the ability to manually specify video rotation in the 3.0 branch.  See https://github.com/brianwernick/ExoMedia/pull/159

**Comment by droidekas** [comment]
Thanks a lot!
