### ISSUE TITLE
Media player controls (full screen back and forth)

### ISSUE THREAD

**Issue by hsnbsst** [brianwernick/ExoMedia#411]
We do not have the chance to add this feature

- [ ] I have verified there are no duplicate active or recent bugs, questions, or requests

###### Include the following:
 - ExoMedia version: `3.0.0`
 - Device OS version: `6.0`
 - Devide Manufacturer: `Huawei`
 - Device Name: `Nexus 6P`
 
###### Reproduction Steps
 0.

**Comment by brianwernick** [comment]
What are you asking?

**Comment by hsnbsst** [comment]
full screen button
