### ISSUE TITLE
HLS video freezing after switching resolution

### ISSUE THREAD

**Issue by jboisjo** [brianwernick/ExoMedia#412]
- [ ] I have verified there are no duplicate active or recent bugs, questions, or requests

###### Include the following:
 - ExoMedia version: `3.0.0`
 - Device OS version: `6.0.1`
 - Devide Manufacturer: `PikTV Media Box`
 - Device Name: `HMB2213PW22TS`
 
###### Reproduction Steps
 0.  Video is freezing when switching resolution with a HLS. After couple seconds, when its about to change resolution, video is freezing. I tried to add this on the XML when it seems to be working, but won't go full screen.

 <com.devbrackets.android.exomedia.ui.widget.EMVideoView
        android:id="@+id/video_view"
        android:layout_width="fill_parent"
        android:layout_height="fill_parent"
        EMVideoView:useDefaultControls="false"
        EMVideoView:useSurfaceViewBacking="true"/>

when i use useSurfaceViewBacking, it's working, but the display won't go fullscreen at all.

**Comment by jboisjo** [comment]
found it. You just need to add this on your code. 

emVideoView.setMeasureBasedOnAspectRatioEnabled(true);

**Comment by brianwernick** [comment]
Yeah, this is somewhat related to #369; and is an issue on any version above `3.0.5` where the `measureBasedOnAspectRatio` flag in the `SurfaceView` is incorrectly defaulted to `false`. This is fixed in the `4.0` branch so I'll mark it as that
