### ISSUE TITLE
Avoid red screen at the end?

### ISSUE THREAD

**Issue by Saketme** [brianwernick/ExoMedia#414]
Hello. Is there any way to avoid `VideoView` going red when a video finishes playing?

###### Include the following:
 - ExoMedia version: `4.0.0-preview3`
 - Device OS version: `7.0`
 - Devide Manufacturer: `Google`
 - Device Name: `Emulator`

**Comment by brianwernick** [comment]
It shouldn't be red when it finishes. Is the background of your view Red? does this only happen on a particular video?

**Comment by Saketme** [comment]
No, this happens on all videos. There is no red background on the View. I will try playing a video on my phone and report back in case this is just an emulator bug.

**Comment by Saketme** [comment]
Update: No, it goes black on an actual phone. Looks like the red color is just an Emulator thing.
