### ISSUE TITLE
Video Resolution Change Automatically

### ISSUE THREAD

**Issue by jdprajapati** [brianwernick/ExoMedia#415]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
Its automatically change size after start video.

I/VideoCapabilities: Unsupported profile 4 for video/mp4v-es
I/MediaCodec: name=OMX.qcom.video.decoder.avc isType=false encoder=false
I/MediaCodec: (0xb861d4b8) init name(OMX.qcom.video.decoder.avc) isType(0) encoder(0)
I/OMXClient: Using client-side OMX mux.
I/MediaCodec: (0xb861d4b8) Component Allocated (OMX.qcom.video.decoder.avc)
I/MediaCodec: (0xb861d4b8) configure nativeWindow(0xb86202c8) crypto(0x0) flags(0)
E/ACodec: [OMX.qcom.video.decoder.avc] storeMetaDataInBuffers failed w/ err -1010
I/ACodec: [OMX.qcom.video.decoder.avc] DRC Mode: Port Reconfig Mode
I/ACodec: [OMX.qcom.video.decoder.avc] setupVideoDecoder Width Height (704x576)
I/ACodec: mime (video/avc) compressionFormat (7)
I/ExtendedCodec: Decoder will be in frame by frame mode
I/MediaCodec: (0xb861d4b8) start
I/MediaCodec: (0xb861d4b8) input buffers allocated
I/MediaCodec: (0xb861d4b8) numBuffers (4)
I/MediaCodec: (0xb861d4b8) output buffers allocated
I/MediaCodec: (0xb861d4b8) numBuffers (18)
I/MediaCodec: name=OMX.google.aac.decoder isType=false encoder=false
I/MediaCodec: (0xb8620d98) init name(OMX.google.aac.decoder) isType(0) encoder(0)
I/OMXClient: Using client-side OMX mux.
E/OMXMaster: A component of name 'OMX.qcom.audio.decoder.aac' already exists, ignoring this one.
I/MediaCodec: (0xb8620d98) Component Allocated (OMX.google.aac.decoder)
I/MediaCodec: (0xb8620d98) configure nativeWindow(0x0) crypto(0x0) flags(0)
I/MediaCodec: (0xb8620d98) start
I/MediaCodec: (0xb8620d98) input buffers allocated
I/MediaCodec: (0xb8620d98) numBuffers (4)
I/MediaCodec: (0xb8620d98) output buffers allocated
I/MediaCodec: (0xb8620d98) numBuffers (4)
I/SoftAAC2: limiting to stereo output
I/MediaCodec: (0xb861d4b8) codec output format changed
I/SoftAAC2: Reconfiguring decoder: 0->16000 Hz, 0->2 channels
I/MediaCodec: (0xb8620d98) output buffers allocated
I/MediaCodec: (0xb8620d98) numBuffers (4)
I/MediaCodec: (0xb8620d98) codec output format changed
**EMVideoView: onVideoSizeChanged() called with: width = [704], height = [576],** unAppliedRotationDegrees = [0], pixelWidthHeightRatio = [1.0]

Please give me solution, Thanks in advance
###### Include the following:
 - ExoMedia version: `3.1.0`
 - Device OS version: `5.0`
 - Device Name: `Motorola E`
 
###### Reproduction Steps
 0.

**Comment by brianwernick** [comment]
What are you seeing that is an issue? What should be seen instead?

**Comment by jdprajapati** [comment]
The issue is video is not showing in actual resolution, why its set auto resolution?

**Comment by brianwernick** [comment]
Resizing the video to match the VideoView is expected in the majority of cases. If you want to keep the original resolution see [setScaleType()](https://github.com/brianwernick/ExoMedia/blob/master/library/src/main/java/com/devbrackets/android/exomedia/ui/widget/EMVideoView.java#L577)

**Comment by jdprajapati** [comment]
Hi Brian,

I have set vidView.setScaleType(ScaleType.NONE); and I am not getting actual video size.
Let me know if I am doing anything wrong.

Thanks,
Jd

**Comment by brianwernick** [comment]
What are you seeing instead?
