### ISSUE TITLE
Closed Captions?

### ISSUE THREAD

**Issue by jboisjo** [brianwernick/ExoMedia#417]
Hi,

any news on the Closed Captions in the latest version? Would be cool :)

Thanks

**Comment by brianwernick** [comment]
Se #115

**Comment by jboisjo** [comment]
there's a difference between Closed Captions and Subtitles...and #115 is about subtitles...im trying to make my device get the HLS Captions but doesnt seems to work...

**Comment by brianwernick** [comment]
Technically there is a difference between subtitles and closed captions, however as far as the path for enabling and getting callbacks inside of ExoMedia they are considered the same.
