### ISSUE TITLE
Add a video dimensions change listener

### ISSUE THREAD

**Issue by Saketme** [brianwernick/ExoMedia#418]
- [X ] I have verified there are no duplicate active or recent bugs, questions, or requests

###### Include the following:
 - ExoMedia version: `4.0.0-preview3`
 - Device OS version: `7.0`
 - Devide Manufacturer: `Google`
 - Device Name: `Emulator`
 
Hey Brian, will it be possible to add a video size change listener to `ExoMedia`? `ExoPlayer` has a `VideoRendererEventListener`, which gives a `onVideoSizeChanged()` callback which is useful in some situations.

I already tried using `ResizingTextureView#setOnSizeChangeListener()`, but it's finicky. It gives two callbacks with different video sizes for each video so I guess that is not what I'm looking for.

**Comment by brianwernick** [comment]
The `setOnSizeChangeListener()` method are setting a listener to get informed of when the surface is resized, not when the actual Video size changes and is expected to get called a few times before it stabilizes (depending on the complexity of the layout containing the `VideoView`).

**Comment by Saketme** [comment]
Ah, makes sense.
