### ISSUE TITLE
Control buttons not showing

### ISSUE THREAD

**Issue by laylizzlle** [brianwernick/ExoMedia#427]
- [ ] I have verified there are no duplicate active or recent bugs, questions, or requests

###### Include the following:
 - ExoMedia version: `3.1.1`
 - Device OS version: `7.0`
 - Devide Manufacturer: `LG`
 - Device Name: `Nexus 5x`
 
###### Reproduction Steps
 This is my layout:

    <?xml version="1.0" encoding="utf-8"?>
    <RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:EMVideoView="http://schemas.android.com/tools"
    android:background="#eeeeee">

    <com.devbrackets.android.exomedia.ui.widget.EMVideoView
        android:id="@+id/video_view"
        android:layout_width="match_parent"
        android:layout_height="250dp"
        EMVideoView:useDefaultControls="true"
        android:focusableInTouchMode="true"
        android:focusable="true"/>

    <android.support.v7.widget.Toolbar
        style="@style/ToolBar"
        android:id="@+id/toolbar"
        android:background="@android:color/transparent"/>

    
    <android.support.v7.widget.RecyclerView
        android:id="@+id/comments"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:layout_below="@id/video_view"/>

    </RelativeLayout>

This is my java code:

    

        emVideoView = (EMVideoView)findViewById(R.id.video_view);
        emVideoView.setOnPreparedListener(this);
        emVideoView.setScaleType(ScaleType.CENTER_CROP);

        emVideoView.setVideoURI(Uri.parse("path"));

###### Expected Result
When the user taps on the video view it toggles the controls so they can interact with it.
###### Actual Result
Controls doesn't show.

**Comment by brianwernick** [comment]
It's probably due to the `EMVideoView` eating the touch events because of your xml attributes
```
android:focusableInTouchMode="true"
android:focusable="true"
```
