### ISSUE TITLE
is it possible to set preferredPeakBitRate?

### ISSUE THREAD

**Issue by jboisjo** [brianwernick/ExoMedia#429]
is it possible to set the desired limit, in bits per second, of network bandwidth consumption for an item playing?

Thank you :)

**Comment by brianwernick** [comment]
Not directly, however a possible path would be to provide a customized OKHttp client (pre 4.0 this requires you to extend the `RenderBuilder` classes, in 4.0 you can call `ExoMedia.setHttpDataSourceFactoryProvider()`) that handles the throttling for you.
