### ISSUE TITLE
Set hidedelay

### ISSUE THREAD

**Issue by jjfster** [brianwernick/ExoMedia#436]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests

###### Include the following:
 - ExoMedia version: `3.0.0`
 - Device OS version: `6.0`
 - Devide Manufacturer: `Huawei`
 - Device Name: `Nexus 6P`
 
###### Reproduction Steps
 0.

**Comment by jjfster** [comment]
Any easy way to override the hide delay timeout value without compiling the source (would prefer to just use gradle).

I did try this but it was ignored:

       mVideoView.getVideoControls().hideDelayed(5000);

**Comment by jjfster** [comment]
Sorry for being clueless, but is this supposed to be exposed in the latest preview4 build?  Can't use it.

compile 'com.devbrackets.android:exomedia:4.0.0-preview4'

mVideoView.getVideoControls().setHideDelayed(4000);

**Comment by brianwernick** [comment]
No, this will be in the official `4.0.0` release. `preview4` was released about 2 weeks ago
