### ISSUE TITLE
preview 4.0 scaling resolution...

### ISSUE THREAD

**Issue by jboisjo** [brianwernick/ExoMedia#437]
Hi Brian,

I just updated to the lastest version which is 4.0.0 preview4 and the player doesnt seems to get the highest resolution with my m3u8 playlist.

I was using this in 3.1.1
```
<com.devbrackets.android.exomedia.ui.widget.EMVideoView
        android:id="@+id/video_view"
        android:layout_width="fill_parent"
        android:layout_height="fill_parent"
        EMVideoView:useDefaultControls="false"
        EMVideoView:useSurfaceViewBacking="true">

    </com.devbrackets.android.exomedia.ui.widget.EMVideoView>
```

and resolution was switching to higher after couple seconds with this...`D/SurfaceUtils: set up nativeWindow 0x8eb97e08 for 960x540, color 0x32315659, rotation 0, usage 0x10002900`

But now...im doing this..

```
<com.devbrackets.android.exomedia.ui.widget.VideoView
            android:id="@+id/video_view"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            app:useDefaultControls="false"/>
```

but he keeps getting me the lowest resolution on my playlist.

Anything i'm doing wrong?

**Comment by brianwernick** [comment]
It should be automatically updating based on your bandwidth, and per the HLS spec it will start with the resolution that is first in the `.m3u8` file until it has enough data to determine the best resolution (this can take up to ~15 seconds)

**Comment by jboisjo** [comment]
I even tried in your demo app just to put my m3u8 and it's doing the samething. I tried in your demo app in older version in 3.1.1 and when i put `EMVideoView:useSurfaceViewBacking="true"` everything works perfectly. :/

**Comment by jboisjo** [comment]
is there a way to access or use `VideoView:useSurfaceViewBacking="true"` in 4.0.0? Looks like its my issue...

**Comment by jboisjo** [comment]
You can try with this playlist if you want, you will see -> https://bitdash-a.akamaihd.net/content/sintel/hls/playlist.m3u8

there's couple resolution and hes only taking the lowest one and looks like it limits de bitrate...

**Comment by brianwernick** [comment]
`4.0` uses the surfaceView backing by default. However in my logcat I get 
```
04-25 12:41:06.594 3156-3349/com.devbrackets.android.exomediademo D/MediaCodecInfo: NoSupport [sizeAndRate.support, 1277x554x-1.0] [OMX.qcom.video.decoder.avc, video/avc] [shamu, Nexus 6, motorola, 24]
04-25 12:41:06.594 3156-3349/com.devbrackets.android.exomediademo D/MediaCodecInfo: NoSupport [sizeAndRate.support, 1921x818x-1.0] [OMX.qcom.video.decoder.avc, video/avc] [shamu, Nexus 6, motorola, 24]
04-25 12:41:06.594 3156-3349/com.devbrackets.android.exomediademo D/MediaCodecInfo: NoSupport [sizeAndRate.support, 1921x818x-1.0] [OMX.qcom.video.decoder.avc, video/avc] [shamu, Nexus 6, motorola, 24]
04-25 12:41:49.893 3156-3453/com.devbrackets.android.exomediademo D/MediaCodecInfo: NoSupport [sizeAndRate.support, 1277x554x-1.0] [OMX.qcom.video.decoder.avc, video/avc] [shamu, Nexus 6, motorola, 24]
04-25 12:41:49.894 3156-3453/com.devbrackets.android.exomediademo D/MediaCodecInfo: NoSupport [sizeAndRate.support, 1921x818x-1.0] [OMX.qcom.video.decoder.avc, video/avc] [shamu, Nexus 6, motorola, 24]
04-25 12:41:49.894 3156-3453/com.devbrackets.android.exomediademo D/MediaCodecInfo: NoSupport [sizeAndRate.support, 1921x818x-1.0] [OMX.qcom.video.decoder.avc, video/avc] [shamu, Nexus 6, motorola, 24]
```

This is most likely caused by one of the many changes Google has made to the ExoPlayer in V2, but not something that ExoMedia controls

**Comment by jboisjo** [comment]
were you able to get atleast 958x408 or u got stuck on 422 or 638x272?

**Comment by brianwernick** [comment]
It was updated to the 958 format. I've tested quite a few other HLS urls and all of them work as expected, leaving the issue to be the bandwidth limiting the host is doing and the format of the `.ts` segments

**Comment by brianwernick** [comment]
So with #450 I'm not sure why I was seeing any of the HLS url's work. I messed up pretty badly on this one and you have my apologies and appreciation for bringing this up
