### ISSUE TITLE
Unable to Zoom in using Gesture in VideoView

### ISSUE THREAD

**Issue by Ronakgadhia** [brianwernick/ExoMedia#442]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests

###### Include the following:
 - ExoMedia version: `4.0.0`
 - Device OS version: `7.0`
 - Devide Manufacturer: `Google`
 - Device Name: `Pixel XL`
 
###### Reproduction Steps
 0.  

###### Expected Result
Need to Zoom in on Gesture
###### Actual Result
Unable to Zoom in using Gesture

**Comment by brianwernick** [comment]
Pinch-to-zoom isn't a feature nor is it a planned feature.

**Comment by Ronakgadhia** [comment]
Okay.
