### ISSUE TITLE
onMediaPlaybackEnded() called repeatedly, even after resetting and preparing ExoAudioPlayer

### ISSUE THREAD

**Issue by arashn** [brianwernick/ExoMedia#443]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests

###### Include the following:
 - ExoMedia version: `4.0.0`
 - Device OS version: `6.0.1`
 - Devide Manufacturer: `Google`
 - Device Name: `Nexus 5`
 
###### Reproduction Steps
 0.  Initialize an ExoAudioPlayer
 1.  Prepare the ExoAudioPlayer for playback (reset(), setDataSource(), prepareAsync())
 2.  Wait for the ExoAudioPlayer to prepare. Then in the onPrepared() callback of ListenerMux.Notifier, call ExoAudioPlayer.start().
 3.  Wait for media playback to finish.
 4.  In the onMediaPlaybackEnded() callback of ListenerMux.Notifier, repeat step 1 above to prepare another media item for playback

###### Expected Result
The onPrepared() callback of ListenerMux.Notifier should be called when the second media item is prepared.
###### Actual Result
onMediaPlaybackEnded() is called again right after attempting to prepare the second item for playback, causing an infinite loop.

**Comment by brianwernick** [comment]
It's expected that `onMediaPlaybackEnded()` can be called multiple times. Unless there is a particular reason you need to use the `ExoAudioPlayer` directly you should be using the `AudioPlayer` instead

**Comment by arashn** [comment]
Great. That's what I was looking for. Thank you for the clarification.
