### ISSUE TITLE
AudioPlayer.getDuration() sometimes returns 0 or C.TIME_UNSET for online MP3/HLS media source

### ISSUE THREAD

**Issue by arashn** [brianwernick/ExoMedia#444]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests

###### Include the following:
 - ExoMedia version: `4.0.0`
 - Device OS version: `6.0.1`
 - Devide Manufacturer: `Google`
 - Device Name: `Nexus 5`
 
###### Reproduction Steps
 0.  Initialize an AudioPlayer
 1.  Prepare the AudioPlayer with an MP3 from a remote source, or HLS media (that is not a live stream), using setDataSource(Uri) and prepareAsync()

###### Expected Result
The onPrepared() callback should be called exactly once, and afterwards, AudioPlayer.getDuration() should return a positive integer representing the length of the media item (since it is not a live stream)
###### Actual Result
onPrepared() is called twice for the same media item. For the first call, AudioPlayer.getDuration() returns 0, and for the second call, AudioPlayer.getDuration() returns C.TIME_UNSET.

**Comment by brianwernick** [comment]
> C.TIME_UNSET : Special constant representing an unset or unknown time or duration. Suitable for use in any time base.
If the hls manifest metadata doesn't include the duration information then you will be given the unknown value

**Comment by arashn** [comment]
Yes, but the problem is that I'm using a fixed-length media source, not a live stream. Version 3.1.1 reported the correct duration for the same hls media (onPrepared() was called once, and afterwards, getDuration() was correct). Here, onPrepared() is called twice for the same media source, and both times AudioPlayer reports either 0 or C.TIME_UNSET.

I should clarify that this issue happens only when we try to prepare AudioPlayer with a media item while it is playing another media source. The first media source to be played by AudioPlayer has the correct duration reported.

**Comment by brianwernick** [comment]
Is there anything in logs that points to issues?

**Comment by arashn** [comment]
No, nothing shows up in the logs. Whenever onPrepared() is called, I check the value of getDuration(). onPrepared() usually gets called twice. The first time, duration is 0. The second time, it's C.TIME_UNSET.

If I stop and release the AudioPlayer completely, the problem doesn't appear for the next item to be played. Also, if I prepare an item, but don't start playing, durations are reported correctly.

**Comment by arashn** [comment]
Just to add, this problem happens even with mp3s loaded from the Internet.

**Comment by brianwernick** [comment]
Hmm, In the demo app I'm calling
```
audioPlayer.reset();
audioPlayer.setDataSource(uri);
audioPlayer.prepareAsync()
```
(With a few other lines in between that don't change the audio player)

I am seeing the `onPrepared()` called twice, however the second time it is getting a valid duration. Is there anything else that you are doing with the AudioPlayer that could be related?

**Comment by arashn** [comment]
I see. Thanks for the update.

**Comment by brianwernick** [comment]
While I'm looking in to seeing if there's something I can do about it (it may be a bug with ExoPlayer, or an undocumented intended thing) you can always handle it yourself similar to how the demo handles it for audio.

e.g.
```java
// 1. Listen to progress
// 2. hold a value that represents if you've set the duration for the UI
// 3. Unset the `durationSet` flag when appropriate

private boolean durationSet = false;
void onProgress(long progress) {
    if (!durationSet && getDuration() > 0) {
        // TODO: set duration in the UI
        durationSet = true;
    }
}
```

**Comment by arashn** [comment]
Thanks. The tricky part for me is that my app also has a live stream component, where C.TIME_UNSET would be correct.

**Comment by brianwernick** [comment]
`4.0.1` was just released with the fixes

**Comment by arashn** [comment]
@brianwernick Thank you very much.
