### ISSUE TITLE
Missing setProgressCallback in VideoView

### ISSUE THREAD

**Issue by electrolobzik** [brianwernick/ExoMedia#446]
- ExoMedia version: `4.0.0`

In ExoMedia version 2.x there was a method `setProgressCallback`. Could you please explain how should I implement the same behaviour in the v.4.x?

**Comment by brianwernick** [comment]
The progressCallbacks were removed in `3.0.0`. You will now need to poll the progress (like you would with the MediaPlayer/Android.VideoView). For an example see the [VideoControls](https://github.com/brianwernick/ExoMedia/blob/master/library/src/main/java/com/devbrackets/android/exomedia/ui/widget/VideoControls.java#L78)
