### ISSUE TITLE
HLS streaming no longer changing quality with 4.0.0 release, previously 3.1.1

### ISSUE THREAD

**Issue by parkgrrr** [brianwernick/ExoMedia#447]
- [x ] I have verified there are no duplicate active or recent bugs, questions, or requests

###### Include the following:
 - ExoMedia version: `4.0.0`
 - Device OS version: `7.1`
 - Devide Manufacturer: `Google`
 - Device Name: `Android TV Emulator`
 
###### Reproduction Steps
Set library to use 3.1.1 and pass in HLS adaptive stream to Video View.  It should switch to higher quality on a good connection.

Upgrade library to 4.0.0 and pass in the same stream, the video quality stays low the whole time.

###### Expected Result
Should upscale.
###### Actual Result
quality stays down.

Is there anything special I need to do to enable adaptive streaming with the 4.0.0 release?  Is there a change log or release notes for this new version?

**Comment by brianwernick** [comment]
Would you mind including a demo url if possible. I've tried a few HLS urls that seem to update, but it's possible I've misconfigured something

**Comment by jboisjo** [comment]
Having the same issue too!

**Comment by parkgrrr** [comment]
@brianwernick I am not able to post the url publicly, but I sent it to you in the dev brackets contact form.  Let me know if that doesn't work for you.

**Comment by brianwernick** [comment]
OK thanks, that should work.

**Comment by brianwernick** [comment]
`4.0.1` was just released with the fix

**Comment by parkgrrr** [comment]
Fantastic, thank you so much! You're library is excellent.
