### ISSUE TITLE
Allow only single video playback

### ISSUE THREAD

**Issue by fmagalhaes** [brianwernick/ExoMedia#452]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests

###### Include the following:
 - ExoMedia version: `4.0.0`
 
In ExoMedia 4.0.0 is there any easy method to allow only one video playback at a time?

Thanks and great lib btw! 👍

**Comment by brianwernick** [comment]
Do you mean you have multiple `VideoView` instances active and only want 1 playing at any given time? If that's the case there isn't any built in functionality to do that so you will have to listen to the play/pause/stop events (can be done with a listener for the `VideoControls`) to handle it yourself.
