### ISSUE TITLE
Exoplayer + data binding

### ISSUE THREAD

**Issue by lazarvgd** [brianwernick/ExoMedia#456]
Hi, is this player able to be used in conjunction with data binding library (mvvm architecture)?

**Comment by brianwernick** [comment]
There shouldn't be anything stopping you

**Comment by lazarvgd** [comment]
can you please tell me what properties to use in XML file in order to set `setOnPreparedListener`,`setVideoURI` and `start`? For example, in exoplayer I use ` android:player`.

**Comment by brianwernick** [comment]
Oh, I see what you are asking.
No, ExoMedia doesn't support that type of databinding, you can retrieve the view (as with any other view) but there aren't particular fields to manage the listeners/etc.

**Comment by lazarvgd** [comment]
Ok Thanks, sorry for bothering you :)
