### ISSUE TITLE
Accessing STATE_BUFFERING 

### ISSUE THREAD

**Issue by martinsce** [brianwernick/ExoMedia#457]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests

###### Include the following:
 - ExoMedia version: `4.0.1`

Is it possible to get STATE_BUFFERING updates in ExoMedia without forking the repo? See comments about using it in  https://github.com/brianwernick/ExoMedia/issues/102

Sometimes live streams stall for quite some time without receiving onError so it would be very useful.

**Comment by brianwernick** [comment]
You even linked the issue this is a duplicate of, so I'm not sure why you created the issue
