### ISSUE TITLE
AudioPlayer.setAudioStreamType(AudioManager.STREAM_DTMF) is ignored

### ISSUE THREAD

**Issue by httpdispatch** [brianwernick/ExoMedia#458]
- [ V] I have verified there are no duplicate active or recent bugs, questions, or requests

###### Include the following:
 - ExoMedia version: `4.0.1`
 - Device OS version: `7.1.1`
 - Devide Manufacturer: `Google`
 - Device Name: `Nexus 4`
 
###### Reproduction Steps
The alternative audio stream type is ignored in the recent ExoMedia version. However it was working fine in ExoMedia 3.x
 0.  Mute STREAM_MUSIC
```
adjustStreamMute(AudioManager.STREAM_MUSIC, true);
...
public static int adjustStreamVolume(int stream, boolean mute){
    if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.M) {
        audioManager.adjustStreamVolume(stream, mute ? AudioManager.ADJUST_MUTE : AudioManager.ADJUST_UNMUTE, 0);
    } else {
        audioManager.setStreamMute(stream, mute);
    }
}
```
1. Set alternative stream for the AudioPlayer
`audioPlayer.setAudioStreamType(AudioManager.STREAM_DTMF);`

2. Prepare audio player asynchronously using prepareAsync()

2. Play any sound with initialized audioPlayer when preparation is done.

###### Expected Result
Sound should be played normally

###### Actual Result
Sound is muted because of stream was not actually switched.

**Comment by httpdispatch** [comment]
It looks like ExoMedia doesn't send proper events to ExoPlayer like here

https://github.com/google/ExoPlayer/blob/d979469659861f7fe1d39d153b90bdff1ab479cc/library/core/src/main/java/com/google/android/exoplayer2/SimpleExoPlayer.java#L302-L312

**Comment by brianwernick** [comment]
`4.0.2` is released with the fix
