### ISSUE TITLE
Can not play url m3u8

### ISSUE THREAD

**Issue by yuucharawae** [brianwernick/ExoMedia#46]
I do like tutorial but still cant play .m3u8 url http://edge7.psitv.tv:1935/liveedge/292277227873_600/playlist.m3u8
what wrong with me ?

thanks you

**Comment by brianwernick** [comment]
It doesn't appear to be a valid url.  VLC, Chrome, Firefox, ExoMedia, ExoPlayerDemo all cannot access the url.

**Comment by yuucharawae** [comment]
Thanks you Brian
