### ISSUE TITLE
Bitrate of upscale HLS stays the same

### ISSUE THREAD

**Issue by jboisjo** [brianwernick/ExoMedia#461]
- [ ] I have verified there are no duplicate active or recent bugs, questions, or requests

###### Include the following:
 - ExoMedia version: `4.0.2`
 - Device OS version: `7.0`
 - Devide Manufacturer: `Google`
 - Device Name: `Pixel XL`
 
###### Expected Result
In this version, it keeps the bitrate the same when selecting a new playlist instead of resetting like before. It doesn't try to get the lowest playlist available and then scale up.

###### Actual Result
The first playlist, the player will start from the lowest bitrate and resolution available and then go up. After, when selecting another playlist, it keeps the same highest bitrate and used the save bitrate as the highest one.

Is there a way to reset the bitrate everytime the user select a playlist and not keep the highest one?

Thank you !

**Comment by brianwernick** [comment]
Why is it you want the bandwidth meter to reset? As long as the host server is the same, it's expected that that bandwidth will stay the same between playlists

**Comment by jboisjo** [comment]
Well in iOS and also your 3.0.2 version, it will always reset when switching for a new playlist. I thought it was one of HLS requirement, to start the lowest bitrate and get the highest...:/

**Comment by brianwernick** [comment]
With the HLS specification you start with the specified bitrate (usually not included in the manifest) or the first quality listed (commonly a low or mid-low bitrate) until the videos bandwidth can be determined. In this case we already know the bandwidth so we can immediately select the appropriate quality for that bitrate.
