### ISSUE TITLE
EMVideoViewControlsCallback not found in 4.0.0

### ISSUE THREAD

**Issue by ravirajjak** [brianwernick/ExoMedia#463]
- [ ] I have verified there are no duplicate active or recent bugs, questions, or requests

###### Include the following:
 - ExoMedia version: `4.0.0`
 - Device OS version: `6.0`
 - Devide Manufacturer: `Mi`
 - Device Name: `Max`
 
I wasn't able to find EMVideoViewControlsCallback Interface in ExoMedia 4.0.0. How am I suppose to Replace this Interface with new one?

**Comment by brianwernick** [comment]
This can be seen in the Demo app and documented in the `VideoControls` and `VideoView`

`import com.devbrackets.android.exomedia.listener.VideoControlsButtonListener;`
