### ISSUE TITLE
Red banner on the video after expand Listview item(With videos) 

### ISSUE THREAD

**Issue by diogo10** [brianwernick/ExoMedia#472]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests

###### Include the following:
 - ExoMedia version: `4.0.2`
 - Device OS version: `7.0`
 - Devide Manufacturer: `Google Nexus 5`
 - Device Name: `Emulator`
 
###### Reproduction Steps
 0.  Create an ExpandListView with videoView child
 1. Open group item one. The item video is loaded correctly.
 2. Collapse group item one(close the group). 
 3. Open another group item. We got a red banner, the video is playing in the back of the red banner.
![screenshot_1496743665](https://cloud.githubusercontent.com/assets/1541244/26824491/80f57ff0-4aa9-11e7-9db5-d692f302e80b.png)
![screenshot_1496743652](https://cloud.githubusercontent.com/assets/1541244/26824501/90947f74-4aa9-11e7-9c7e-7fb032c827a7.png)

###### Expected Result
Playback the video without the red banner.
###### Actual Result
![screenshot_1496743698](https://cloud.githubusercontent.com/assets/1541244/26824460/6e98cb64-4aa9-11e7-98a6-f7f6d7a3c9fd.png)

###### More info

I have tried these methods when the user closes the group(Collapse item)...but it doesn't work out. The audio is gone but the red banner still there.

```
stopPlayback()
release();
invalidate();
```

**Comment by brianwernick** [comment]
Are you seeing this on a physical device as well?

**Comment by diogo10** [comment]
Sorry, I am not seeing it on the physical device. Sorry about that.
