### ISSUE TITLE
Change ProgressBar and SeekBar thumb color

### ISSUE THREAD

**Issue by pkb126** [brianwernick/ExoMedia#473]
Hey, 

How i can change ProgressBar color except black and also SeekBar thumb and progress color.

**Comment by brianwernick** [comment]
Assuming you are using an Activity that extends `AppCompatActivity` then you can just modify your accent color to change the progress bar colors.
E.g.
```xml
<style name="App.VideoActivity" parent="Theme.AppCompat.Light.DarkActionBar">
    <item name="colorPrimary">#FF55AADD</item>
    <item name="colorPrimaryDark">#FF5588AA</item>
    <item name="colorAccent">#FF5588AA</item>
</style>
```

**Comment by ravirajjak** [comment]
@brianwernick  do i need to add theme for eg:
 <activity
            android:name=".VideoActivity"
            android:theme="@style/App.VideoActivity" />
or 
Should I write Style name as <style name="PackageName.VideoWebActivity" parent="Theme.AppCompat.Light.DarkActionBar">
?

**Comment by ravirajjak** [comment]
@brianwernick  how to change the background color of the controls. the one in light grey.
