### ISSUE TITLE
EMVideoView V2.5.6 Plays only Audio 

### ISSUE THREAD

**Issue by ravirajjak** [brianwernick/ExoMedia#475]
- [ ] I have verified there are no duplicate active or recent bugs, questions, or requests

###### Include the following:
 - ExoMedia version: `2.5.6`
 - Device OS version: `6.0`
 - Devide Manufacturer: `Google`
 - Device Name: `Nexus`
 EMvideoView plays only Audio no video is visible and the url which I play is m3u8.

**Comment by brianwernick** [comment]
`2.5.6` is over a year old and as such won't be supported. You should update to the latest version
