### ISSUE TITLE
HLS stream occasionally stops when running out of buffer/switching tracks and doesn't resume playback

### ISSUE THREAD

**Issue by parkgrrr** [brianwernick/ExoMedia#476]
- [X ] I have verified there are no duplicate active or recent bugs, questions, or requests

###### Include the following:
 - ExoMedia version: `4.0.2` and `3.1.1`
 - Device OS version: `6.0`
 - Devide Manufacturer: `Custom`
 - Device Name: `Allwinner Quad-core R18 ads`
 
###### Reproduction Steps
I had a very hard time reproducing this, as it only happens in poor network conditions, and android monitor does not give any errors or unusual debug info.  I was able to replicate what I think is similar or the same behavior in the demo app by doing the following: 

- Add HLS stream to samples list in demo app
```` videoSamples.add(new Sample("HLS - Verity Hull Demo", "http://view.vzaar.com/10331838/adaptive.m3u8"));````

- in onCreate tweak buffer settings to replicate behavior

````ExoMedia.setLoadControl(new DefaultLoadControl(new DefaultAllocator(true,64 * 1024),0,DefaultLoadControl.DEFAULT_MAX_BUFFER_MS,0L,0L));````

(I don't set the load control at all in my app where I'm seeing it)

- Play video.  On first playback it will work fine, showing the lowest quality stream, then switching after ~10 seconds.

- Skip back on the playlist, it may freeze, click the back button to return to the Selection Activity

- Play the hls stream again

###### Expected Result
Stuttered playback, or frequent buffering, but continued playback.

###### Actual Result
it will play the first 10 seconds, run out of buffer, and stop where it usually would switch to the higher resolution stream.  No buffer icon is displayed, and it is stopped until a user interacts with the app.  In my app, it will sometimes start up again if the user scrubs forward or back.

Android monitor repeatedly displays this every few seconds:

````06-13 06:41:10.413 18525-18525/? I/pppd: Starting pppd````

######
Here are two logs I was able to capture when it happened on my device, after simulating a poor wifi connection. [gist 1](https://gist.github.com/parkgrrr/3a4cb84393efd7d1efe2c0e535a6ecef) [gist 2](https://gist.github.com/parkgrrr/47051b0da77e7f719cb6ab75333b1fcf)

Any advice on how to get more logging data, or implement something like EventLogger or player.setVideoDebugListener() like in the ExoPlayer demo would be appreciated.

**Comment by parkgrrr** [comment]
@brianwernick Do you have any hunches on why I may be seeing this?  Do you have any suggestions on further debugging the issue?

**Comment by brianwernick** [comment]
I'm assuming that the `ExoMediaPlayer` isn't monitoring the buffer state correctly and so it stops due to out of buffer, but when it's updated doesn't resume.

**Comment by parkgrrr** [comment]
I think this may be fixed with Exoplayer r2.5.1

**Comment by brianwernick** [comment]
Hmm, I'll see if I can verify with the `master` branch which has r2.5.2 sometime this week

**Comment by mokoshalb** [comment]
also suffering this..

**Comment by brianwernick** [comment]
This does seem to be fixed with r2.5.x, as such I'm going to close this and tag it with 4.1.0 (the next version to release with an updated ExoPlayer version)
