### ISSUE TITLE
Lock Screen Stop Handled Improperly

### ISSUE THREAD

**Issue by Haub100** [brianwernick/ExoMedia#477]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests

###### Include the following:
 - ExoMedia version: `4.0.0`
 - Device OS version: `7.0`
 - Devide Manufacturer: `Google`
 - Device Name: `Nexus 5X`
 
###### Reproduction Steps
 1. Launch Audio Playback and make a selection
 2. After audio starts, lock your screen
 3. Expand the notification and press the X
 4. Unlock device 

###### Expected Result
The audio UI should display that the playback has stopped.
###### Actual Result
UI displays the pause icon and the audio cannot be restarted

**Comment by brianwernick** [comment]
What you are seeing is just a part of the Demo app which isn't guaranteed to be 100% correct as far as playlist stuff and external control of the `AudioPlayer` and `VideoView`.
