### ISSUE TITLE
HLS Video streaming stops frequently 

### ISSUE THREAD

**Issue by Norhan-El-Ashry** [brianwernick/ExoMedia#478]
I'm a beginner in android and I'm trying to build an iptv app using .ts channel streams.
the problem is that the videos keeps pausing frequently and i don't know whether it's a wifi connection speed problem or it's a cash problem.
Any help Please.

- [x] I have verified there are no duplicate active or recent bugs, questions, or requests

###### Include the following:
 - ExoMedia version: `4.0.0`
 - Device OS version: `7.0`
 - Devide Manufacturer: `Google`
 - Device Name: `Pixel XL`
 
###### Reproduction Steps
 0.

**Comment by brianwernick** [comment]
Are you asking in general or asking if there is a callback to let you know when we are buffering? The former would be a StackOverflow.com question while the latter is part of #102 and #257
