### ISSUE TITLE
Implement DRM with Exoplayer2

### ISSUE THREAD

**Issue by billyjoker** [brianwernick/ExoMedia#479]
Hi, i've implemented correctly drm with Exomedia based in Exoplayer 1.x.x, but i'm trying to do the same with your last imeplementation based in Exoplayer 2.x.x with no success. My issue:

    private void setDrmProvider() {
      final String licenseURL = "http://licensedUrl";
      emVideoView.setDrmProvider( new DrmProvider(){
        @Nullable
        @Override
        public MediaDrmCallback getDefaultCallback() {

          MediaDrmCallback mdcallback = new MediaDrmCallback() {
            @Override
            public byte[] executeProvisionRequest(UUID uuid, ExoMediaDrm.ProvisionRequest request) throws Exception {
              return Util.executePost(licenseURL, request.getData(), null);
            }

            @Override
            public byte[] executeKeyRequest(UUID uuid, ExoMediaDrm.KeyRequest request) throws Exception {
              return Util.executePost(licenseURL, request.getData(), null);
            }
          };

          return mdcallback;
        }
      });
    }

The problem is that the executePost method is no longer exist, so i see no chance to do this now, how is the right way to perform in this way?? Thanks in advance.

**Comment by brianwernick** [comment]
You are most likely looking for a `https://github.com/google/ExoPlayer/blob/release-v2/library/core/src/main/java/com/google/android/exoplayer2/drm/HttpMediaDrmCallback.java`, Please be better at looking for a solution before posting an issue; the `MediaDrmCallback` is well documented in the `ExoPlayer` with examples
