### ISSUE TITLE
Fullscreen not working

### ISSUE THREAD

**Issue by AlaaZarifa** [brianwernick/ExoMedia#480]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests

###### Include the following:
 - ExoMedia version: `3.1.1`
 - Device OS version: `6.0`
 - Devide Manufacturer: `HTC`
 - Device Name: `One M8`
 
###### Reproduction Steps
0.  I added the fullscreen class from the demo with some line commented, here's my class [GIST](https://gist.github.com/AlaaZarifa/f81bacbebc97e6addde40c034213e808)
0. I declared the activity in Manifest  
```
         <activity
          android:name=".FullScreenVideoPlayerActivity"
          android:configChanges="orientation|keyboardHidden|screenSize">
        </activity>
```
0. I added a button for fullscreen action, and insde the onClick I added this, just like in the demo..

```
fulscreen_button.setOnClickListener(new OnClickListener() {
      @Override
      public void onClick(View v) {
          Intent intent = new Intent(activity.getApplicationContext(), FullScreenVideoPlayerActivity.class);
          intent.setFlags(Intent.FLAG_ACTIVITY_NEW_TASK);
          activity.getBaseContext().startActivity(intent);
      }
    });
```

###### Expected Result
to open the video in full screen like the demo

###### Actual Result

it opens an empty activity with no playback or anything..!?
these logs show when pressing the fullscreen button:
```
 ActivityManager: START u0 {flg=0x10000000 "path..".FullScreenVideoPlayerActivity} from uid 10497 pid 20651 on display 0
 PMS: acquireWL(e9f42b8): PARTIAL_WAKE_LOCK  *launch* 0x1 1067 1000 WorkSource{10497}
```

**Comment by brianwernick** [comment]
This is a stackoverflow.com question, not a library issue
