### ISSUE TITLE
Error > Failed to get omx plugin handle 

### ISSUE THREAD

**Issue by AlaaZarifa** [brianwernick/ExoMedia#481]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests

###### Include the following:
 - ExoMedia version: `4.0.2`
 - Device OS version: `6.0`
 - Devide Manufacturer: `HTC`
 - Device Name: `M8`
 
###### Reproduction Steps
 0.  I was using the library via the gradle dependency v3.1.1
0. I then removed the dependency and instead I added the library module to my project coz I wanna change some UI stuff of the video controls
0. before changing anything, I run the app after adjusting the declarations for the library instead of the dependency 

###### Expected Result
the video will run normally like it used to do on the dependency 3.1.1

###### Actual Result

when I play the video, it flashes for a second and won't play anything , the play button reappears !
I notice this in the log when I press the play button!
```
E/OMXMaster: A component of name 'OMX.qcom.audio.decoder.aac' already exists, ignoring this one.
E/OMXMaster: Failed to get omx plugin handle
```

**Comment by brianwernick** [comment]
The posted log can be expected and won't affect the output of playback. It sounds like something else is not configured correctly with including a module project or there are other logcat errors not posted.

**Comment by AlaaZarifa** [comment]
you were right, It seems to be a problem with module importing, I re-did the process and the logs errors still shows, but it plays normally now!

Thanks
