### ISSUE TITLE
how to get the current video time

### ISSUE THREAD

**Issue by AlaaZarifa** [brianwernick/ExoMedia#482]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests

###### Include the following:
 - ExoMedia version: `4.0.0`
 - Device OS version: `7.0`
 - Devide Manufacturer: `Google`
 - Device Name: `Pixel XL`
 
###### Reproduction Steps
 0.  click on a button on top of the videoview
0. I couldn't find a method to get the current time of the playing video
I used this inside the onClick > `    intent.putExtra("time", videoView.getCurrentPosition())`
and this on the other activty with a differnt videoview 
```
        //code..
     long time = getIntent().getLongExtra("time",0);
       //code..
     videoView.setOnPreparedListener(new OnPreparedListener() {
       @Override
        public void onPrepared() {
          loader.setVisibility(View.GONE);
          VideoWidget.isFullScreen = true;
          videoView.setPositionOffset(time);
          videoView.start();
      }
    });
```
###### Expected Result
to find a method for tracking the time of the video
or a workaround using these methods since it's not clear to use them `getDuration` & `setPosition`

for example, let's assume I'm playing a video and when it reaches a certain time, I save with intent extra 
then open a new videoview but it will start withe time I save, not the from beginning!

is that possible?

###### Actual Result
the seekbar of the new player was correct, it continues withe right time, but it the video playback isn't correct, it starts the video from beginning and ignores the stuff that I did, so my solution so far affect the UI only..! any help?

**Comment by brianwernick** [comment]
This is another question better suited for StackOverflow.com as it isn't specific to ExoMedia

**Comment by androidovshchik** [comment]
@AlaaZarifa 
Instead of `videoView.setPositionOffset(time)` write `videoView.seekTo(time);`
it works
