### ISSUE TITLE
Video is not playing once completed

### ISSUE THREAD

**Issue by electrolobzik** [brianwernick/ExoMedia#483]
- ExoMedia version: `4.0.2`
 - Device OS version: `7.0`
 - Devide Manufacturer: `Samsung`
 - Device Name: `S7`
 
###### Reproduction Steps
This is the sequence of commands to the VideoView in my Activity:
```
setVideoURI
seekTo(position = 0)
seekTo(position = 0)
start
OnPreparedListener fired
```
After this steps the video is playing fine. Next:
```
pause
start
```
Video has stopped and resumed fine. Next:
```
OnCompletionListener fired
seekTo(position = 0)
start  
```
Video has finished. But it doesn't play again from the beginning.

###### Expected Result

Video is playing from the beginning.

###### Actual Result

Nothing happens when calling `start()` method after `OnCompletionListener` fired.

**Comment by brianwernick** [comment]
See #382
