### ISSUE TITLE
Pause button is disabled when video is paleyed

### ISSUE THREAD

**Issue by AlaaZarifa** [brianwernick/ExoMedia#484]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests

###### Include the following:
 - ExoMedia version: `4.0.2`
 - Device OS version: `6.0`
 - Devide Manufacturer: `HTC`
 - Device Name: `one m8`
 
###### Reproduction Steps
0.  I play the video by a custom button on top of the VideoView widget by calling  `videoView.start();`
0. the video is being played normally ..

###### Expected Result
the pause button should be white so I can stop it when I want.! 

###### Actual Result
the pause button is in grey color and disabled yet the video is completely loaded and buffered because I the seekbar color indicator is visible and the video starts inside on Prepared.!
the only way it will retain being enabled and white is when I change the seekbar thumb forward or backward.. other than that it won't be allowing me to pause the video at all..!?

**Comment by brianwernick** [comment]
Are you extending any of the `VideoControls` classes? It sounds like you are bypassing a loading state check somewhere or calling `showLoading()` and never informing the controls of the paired `finishLoading()`
