### ISSUE TITLE
Change the color of the useDefaultControls...

### ISSUE THREAD

**Issue by jboisjo** [brianwernick/ExoMedia#486]
Hey Brian!

Just a quick question, i'm using the Leanback theme for Android TV, and i can't find anywhere to change the color of the controls...it's set to blue per default. Is there a somewhere i can change that? 

Thank you :)

**Comment by jboisjo** [comment]
Even if i change the color of my Theme it's still not working...

```
<style name="AppTheme" parent="@style/Theme.Leanback">
        <item name="colorPrimary">#FFFFFFFF</item>
        <item name="colorPrimaryDark">#FFFFFFFF</item>
        <item name="colorAccent">#FFFFFFFF</item>
    </style>
```

**Comment by brianwernick** [comment]
Not currently, apparently I missed adding that in when I first created the leanback controls.

**Comment by brianwernick** [comment]
The leanback controls will now abide by the primary, accent, and text colors
