### ISSUE TITLE
Live video issue

### ISSUE THREAD

**Issue by brian2694** [brianwernick/ExoMedia#488]
###### Include the following:
 - ExoMedia version: `4.0.2`
 - Device OS version: `7.0`
 - Devide Manufacturer: `Motorola`
 - Device Name: `Moto G4 plus`
 
### Details
I'm trying to play a live video, but plays the previous four minutes, it's not playing live.

I just upgraded from the 3.1.0 to the 4.0.2 library and now it does not actually play live. Before if I could do it.

**Comment by brian2694** [comment]
Sorry for my english

**Comment by brianwernick** [comment]
This depends on what type of stream you are using (MPD, HLS, SS, etc.); but for the most part nothing major was changed in the live handling functionality or buffering that would affect you this much. 
Before we can really help though we will need reproduction steps, which should include information such as the stream type, and if possible an example URI.

**Comment by brian2694** [comment]
Thanks for your reply. 

Well, I am testing with the last demo, I put the link in the samples. This is the URI

http://a3live-lh.akamaihd.net/i/mghds/geomega_1@328914/index_3_av-b.m3u8?sd=10&rebase=on


It is worth clarifying that in the previous library I did not have to add additional parameters, the player interpreted that it was streaming live

**Comment by brianwernick** [comment]
So after trying it out it sounds like this is what you are seeing:
The VideoControls show a duration of ~4 to 5 minutes, however the playback starts at the beginning instead of near the end; is this correct?

That being the case there are two things that need to be handled in ExoMedia
  1. Determining if the video is live streaming in the VideoControls (correlated to #454) for the duration display
  2. If the stream is live start near the end (I say near because we want to be able to play some media before the next manifest sync)

**Comment by brian2694** [comment]
Yes this is correct, starts at the beginning.

My question: is there any method in your library to do that? Or should I do something in the exoplayer library?

**Comment by brianwernick** [comment]
Well, once the video loads you can seek to near the end; and if you want it to look correct in the controls you can extend the `VideoControlsMobile` to display the live information instead of the ~4 minutes

**Comment by brian2694** [comment]
playlistManager.play(260000, false);

This method worked for me.  Now I have to extend the VideoControlsMobile to display the live information.

Thanks Brian.

**Comment by brian2694** [comment]
Hello again.

playlistManager.play(260000, false) works for my when the streaming segment is aprox. 4 minutes, but i've tried with another uri and its chunk is aprox 30 seconds and this uri doesn't start to play.

**Comment by firofame** [comment]
i am also having the same problem. is there any way to make the video start as live?

**Comment by asujiman** [comment]
I have the same problem. any way tio fixed this as temporary?

**Comment by firofame** [comment]
I switched to [ExoPlayer](https://github.com/google/ExoPlayer).

**Comment by meet2011** [comment]
I'm also facing live streaming issue. It plays for 1-2 minutes and then it throws error.  If i use default controls then seeker values are totally wrong. Is it possible to hide seekbar and keep play/pause button for live streaming?

This is the stream URL(shortened URL)
https://goo.gl/oHaj6o

**Comment by brianwernick** [comment]
Looking in to this now and it looks like there are 2 types of "live" videos, only 1 of which we (partially) handle currently. These 2 different types are:
1. A live stream where the available media at both the start and end of the stream is constantly changing (e.g. a CCTV camera that is caching 2 minutes of video)
 2. An "event" stream where the available media is growing at the end of the stream (e.g. streaming the Google I/O keynote)
 
Currently ExoMedia is only, partially, handling the 2nd case so I'm reviewing what work will be necessary to support both cases but from what I can tell the ExoPlayer really only exposes if the stream is live/dynamic and not which case it is.
