### ISSUE TITLE
Source Error

### ISSUE THREAD

**Issue by spurts51** [brianwernick/ExoMedia#491]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests

###### Include the following:
 - ExoMedia version: `4.0.0`
 - Device OS version: `7.0`
 - Devide Manufacturer: `Google`
 - Device Name: `Pixel XL`
 
###### Reproduction Steps
 0.  

###### Actual Result

Following error comes:

E/ExoPlayerImplInternal: Source error.

And just a progress bar is displayed and video doesn't play.

**Comment by Ronakgadhia** [comment]
What is a solution?
