### ISSUE TITLE
How to implement buttons like seek button and toggle screen button?

### ISSUE THREAD

**Issue by spurts51** [brianwernick/ExoMedia#492]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests

###### Include the following:
 - ExoMedia version: `4.0.0`
 - Device OS version: `7.0`
 - Devide Manufacturer: `Google`
 - Device Name: `Pixel XL`
 
###### Reproduction Steps
 0.  

###### Actual Result

I want to implement all the controls that a video controller has how to implement it. Please tell I am very new to exo player. Also when the screen is rotated the video starts from beginning so how to save the state.

**Comment by brianwernick** [comment]
See the Demo app for an example of both.

**Comment by spurts51** [comment]
I am not able to inflate buttons using the method videoView.showcontrols();
  
                <com.devbrackets.android.exomedia.ui.widget.VideoView
                   android:id="@+id/video_view"
                   android:layout_width="match_parent"
                   android:layout_height="match_parent"
                   app:useDefaultControls="true"/>

And if I use EMVideoView  then it gives the following error

Binary XML file line #6: Binary XML file line #6: Error inflating class com.devbrackets.android.exomedia.EMVideoView
