### ISSUE TITLE
Problems with AudioFocus on Android 8.0 (API 26)

### ISSUE THREAD

**Issue by ElectroBuddha** [brianwernick/ExoMedia#493]
Hi,
On Android 8.0 (API 26) audio stops as soon as video playout starts.
The message in console:

```
W/AudioManager: Use of stream types is deprecated for operations other than volume control
W/AudioManager: See the documentation of requestAudioFocus() for what to use instead with android.media.AudioAttributes to qualify your playback use case
I/MediaFocusControl:  AudioFocus  requestAudioFocus() from uid/pid 10047/6345 clientId=android.media.AudioManager@96ca3e7com.devbrackets.android.exomedia.ui.widget.VideoView$AudioFocusHelper@8dc5b94 req=1 flags=0x0
```

It seems that AudioManager API has been changed in Android 8:
https://developer.android.com/preview/features/audiofocus.html

Tested only on Android Emulator

**Comment by brianwernick** [comment]
Please follow the template to allow us to better help you. Additionally, are you using API 26 as the target SDK?

**Comment by ElectroBuddha** [comment]
Hi,
I'm working on Android TV leanback project. As far as I could test this only happens on Android TV emulator running latest Android 8.0 (API 26). It doesn't happen on Phone emulators. The issue could be observed by running ExoMedia demo app on Android TV emulator with OS ver. 8.0, and trying to play any video clip.

I'm building my app against API 25.

###### Include the following:
 - ExoMedia version: `4.0.3`
 - Device OS version: `8.0`
 - Devide Manufacturer: `Google`
 - Device Name: `Android TV Emulator`
 
###### Reproduction Steps
Run app which implements ExoMedia video player (for example ExoMedia demo app) on Android TV emulator OS version 8.0 (API 26)

###### Expected Result
Playing video with sound

###### Actual Result
Video plays without sound, or video stops completely.

Console displays the following warnings, and on the device screen a small warning notification pops up with 'Audio' symbol:

```
W/AudioManager: Use of stream types is deprecated for operations other than volume control
W/AudioManager: See the documentation of requestAudioFocus() for what to use instead with android.media.AudioAttributes to qualify your playback use case
I/MediaFocusControl:  AudioFocus  requestAudioFocus() from uid/pid 10047/6345 clientId=android.media.AudioManager@96ca3e7com.devbrackets.android.exomedia.ui.widget.VideoView$AudioFocusHelper@8dc5b94 req=1 flags=0x0
```

**Comment by brianwernick** [comment]
Have you tried this on a physical TV device? This sounds like an emulator issue (the TV emulators have always had issues playing video)

**Comment by ElectroBuddha** [comment]
Would like to test on physical device but don't have device with the latest Android 8.0 :) Could be issue with emulator, I also get some ExoMedia DRM warnings only on TV emulators. If you find some time just try running ExoMedia demo app on Android TV emulator and check if you get the same problem. Best regards.

**Comment by brianwernick** [comment]
This looks like it's just an emulator issue, as such I'm going to close this

**Comment by ivanzhang** [comment]
No, it's happen on many physical devices.... 
but it fails only some videos, not all videos,  well, i have some logcat info to share：


12-19 13:13:08.077 21366-21366/com.dianmoge I/ExoPlayerImpl: Init 1971167 [ExoPlayerLib/2.9.1] [16th, 16th, Meizu, 27]
12-19 13:13:08.079 21366-21366/com.dianmoge W/AudioManager: Use of stream types is deprecated for operations other than volume control
    See the documentation of requestAudioFocus() for what to use instead with android.media.AudioAttributes to qualify your playback use case
12-19 13:13:08.092 21366-21403/com.dianmoge I/ReactNativeJS: 'video url:', 'https://1251052432.vod2.myqcloud.com/3ef5dd60vodtransgzp1251052432/06200bd85285890783193923458/v.f30.mp4'
12-19 13:13:08.094 21366-21403/com.dianmoge I/ReactNativeJS: 'onAudioFocusChanged ...', { hasAudioFocus: false }
    'video url:', 'https://1251052432.vod2.myqcloud.com/3ef5dd60vodtransgzp1251052432/59a687555285890783191143697/v.f30.mp4'
12-19 13:13:08.115 21366-23342/com.dianmoge I/BufferQueue: [unnamed-21366-85](this:0xb2224000,id:85,api:0,p:-1,c:-1) BufferQueue core=(21366:com.dianmoge)
12-19 13:13:08.116 21366-23119/com.dianmoge I/MediaCodec: [OMX.qcom.video.decoder.avc] setting surface generation to 21878868
12-19 13:13:08.121 21366-21366/com.dianmoge I/ExoPlayerImpl: Release 2d08719 [ExoPlayerLib/2.9.1] [16th, 16th, Meizu, 27] [goog.exo.core, goog.exo.okhttp]
12-19 13:13:08.180 21366-21366/com.dianmoge I/BufferQueue: [unnamed-21366-86](this:0xce48a400,id:86,api:0,p:-1,c:-1) BufferQueue core=(21366:com.dianmoge)
12-19 13:13:08.183 21366-21366/com.dianmoge I/Choreographer: Skipped 3 frames!  The application may be doing too much work on its main thread.
12-19 13:13:09.298 21366-21394/com.dianmoge I/qtaguid: Untagging socket 138 failed errno=-22
12-19 13:13:09.683 21366-23346/com.dianmoge I/qtaguid: Untagging socket 138 failed errno=-22
12-19 13:13:11.314 21366-21394/com.dianmoge I/qtaguid: Untagging socket 138 failed errno=-22
12-19 13:13:11.724 21366-23348/com.dianmoge I/qtaguid: Untagging socket 146 failed errno=-22
12-19 13:13:13.337 21366-21394/com.dianmoge I/qtaguid: Untagging socket 138 failed errno=-22

**Comment by elmarbeckmann** [comment]
Hi @ivanzhang have you ever found a solution? I'm getting the same errors.

**Comment by brianwernick** [comment]
Sorry @ivanzhang I don't remember getting notified of any additional comments on this thread. Looking in to it some more, the audio focus method calls definitely need to be updated; not sure why I was thinking it was only an emulator issue. I'm going to re-open the issue to track updating the AudioFocus
