### ISSUE TITLE
HLS Video freezes frequently and Playlist goes to next video with no reason

### ISSUE THREAD

**Issue by Norhan-El-Ashry** [brianwernick/ExoMedia#494]
- [ ] I have verified there are no duplicate active or recent bugs, questions, or requests

###### Include the following:
 - ExoMedia version: `4.0.2`
 - Device OS version: `6.0`
 - Devide Manufacturer: `Huawei, xiaomi`
 - Device Name: `Huawei cam-l21, mi android tv box `
 Hiii,
 I used the demo app as a reference to my app. My App displays a list of  live(.ts) and movie streams. 
it works fine but it freezes frequently and the logcat gives me that error :
E/OMXNodeInstance: getExtensionIndex(96:k3.decoder.avc, OMX.google.android.index.storeMetaDataInBuffers) ERROR: NotImplemented(0x80001006)
 E/ACodec: [OMX.k3.video.decoder.avc] storeMetaDataInBuffers failed w/ err -2147483648

I know that it is a problem with buffering but i do not know how to fix it. I also need to know where the buffered data are stored. and if i should fix that error.

setGpuBoost:228: Can't open /sys/class/devfreq/gpufreq/max_freq: Permission denied
07-24 15:09:42.365 2456-2456/? E/hwcomposer: setGpuBoost:228: Can't open /sys/class/devfreq/gpufreq/max_freq: Permission denied
07-24 15:09:42.380 2456-2456/? E/hwcomposer: setGpuBoost:228: Can't open /sys/class/devfreq/gpufreq/max_freq: Permission denied
07-24 15:09:42.396 2456-2456/? E/hwcomposer: setGpuBoost:228: Can't open /sys/class/devfreq/gpufreq/max_freq: Permission denied
07-24 15:09:42.413 2456-2456/? E/hwcomposer: setGpuBoost:228: Can't open /sys/class/devfreq/gpufreq/max_freq: Permission denied
07-24 15:09:42.430 2456-2456/? E/hwcomposer: setGpuBoost:228: Can't open /sys/class/devfreq/gpufreq/max_freq: Permission denied

There is another issue that happens occasionally, the playlist jumps to the next video with no reason. 
I don't know whether it is related to buffering issues or unknown duration in live streams. Actually i tried to hide the seek-bar and duration text in live streams and disable any related controls actions  but i couldn't.

Please help me to understand more about this great library and handle these issues.
Sorry for my bad English.
Thank you.

**Comment by brianwernick** [comment]
The main question would be better to post in the ExoPlayer repo instead as that's where you will get help figuring it out (though it might just be a bad implementation on the device).
As far as the playlist goes; that's a different library however it doesn't just `"jumps to the next video with no reason"`, my assumption is that an error occurs in the playback and because of that the service is moving on to the next playable item.

**Comment by Norhan-El-Ashry** [comment]
Thank you for your reply
