### ISSUE TITLE
rotate videoview but previewImageView is not rotated

### ISSUE THREAD

**Issue by leimenghao** [brianwernick/ExoMedia#497]
I have a list videos to play using viewpager. The aspect ratio of video is uncertain. So i display video that w:h >= 4 : 3 landscape by rotate videoView 90 degrees. But i find that the previewImageView is not rotated. Is this a bug?
Another problem is that the video is not full-screen, but previewImageView is full-screen. So when i play a video (not full-screen), there is a flash from full-screen to non-full-scree. So is there any ways i can solve it？

###### Include the following:
 - ExoMedia version: `4.0.2`
 - Device OS version: `7.0`
 - Devide Manufacturer: `xiaomi`
 - Device Name: `Pixel XL`
 
first issue
###### Reproduction Steps
1.make video view match_parent in xml.
2. set previewImageView iamge
3. rotate videoView by 90 degrees  

###### Expected Result
previewImageView and videoView are all rotated by 90 degrees
###### Actual Result
only videoView is rotated and previewImageView is not

second issue
###### Reproduction Steps
1.make video view match_parent in xml.
2. set previewImageView iamge
3. play a non-full-screen video 

###### Expected Result
previewImageView are as big as video played 
###### Actual Result
previewImageView is full-screen and video is not

**Comment by leimenghao** [comment]
I solve the second question by code:
videoView.getPreviewImageView().setScaleType(ImageView.ScaleType.FIT_CENTER).
happy~

**Comment by brianwernick** [comment]
This is working as designed. The rotate method in the VideoView will only affect the video output, not the controls, preview image, etc. You will need to apply a rotate to the ImageView as well if that's your expected result.
