### ISSUE TITLE
on Receiving notification the video playing is stopped

### ISSUE THREAD

**Issue by PonnamKarthik** [brianwernick/ExoMedia#499]
on Receiving notification the video playing is stopped

**Comment by brianwernick** [comment]
By default the VideoView will automatically handle audio focus changes (`setHandlesAudioFocus()`), correctly pausing or reducing the volume when appropriate. If a notification is pausing the video then it is a high-priority message in which case this is expected.

**Comment by PonnamKarthik** [comment]
How to play the video after the notification completed ?

**Comment by PonnamKarthik** [comment]
Thanks @brianwernick
