### ISSUE TITLE
Update for ExoPlayer 2.5.x

### ISSUE THREAD

**Issue by rubengees** [brianwernick/ExoMedia#500]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests

###### Version Info
 - ExoMedia version: `4.0.3`
 - Device OS version: Not relevant
 - Devide Manufacturer: Not relevant
 - Device Name: Not relevant

The new `ExoPlayer` version `2.5.0` has been released with [many new features and improvements](https://github.com/google/ExoPlayer/blob/release-v2/RELEASENOTES.md#r250).
Sadly `ExoMedia` is not compatible with it due to the use of the deprecated and now removed `ExoPlayer$EventListener`.

Proguard error:
 
```
com/devbrackets/android/exomedia/core/exoplayer/ExoMediaPlayer.<init>:
(Landroid/content/Context;)V references unknown class member: 
com/google/android/exoplayer2/ExoPlayer.addListener:
(Lcom/google/android/exoplayer2/ExoPlayer$EventListener;)V
```

This is just a reminder that a new version exists and an update for it would be great :smiley:.

**Comment by brianwernick** [comment]
I typically wait at least a few days after a major release version because of broken functionality (e.g. they just released a 2.5.1). Additionally, It looks like Google made breaking changes in a minor version (pretty common for them) and I have other higher priorities to work on, so it may be a few weeks before it's updated (i.e. released)

**Comment by rubengees** [comment]
Yes, that makes sense of course, looking forward to it!

**Comment by brianwernick** [comment]
Yep, There's actually only 1 breaking change (added method to that listener) so I'm pushing it to master but it won't be released until 4.1 (which should have other additions/changes as well) but I don't have a timeline for it yet

**Comment by rubengees** [comment]
Great! You mentioned you are busy, but maybe for future cases like this: How about setting up SNAPSHOTS so people can test the latest changes on master without waiting for a release?

**Comment by brianwernick** [comment]
Yeah, I've done previews before but typically it's only for major releases. But I like that idea, I'll submit a snapshot for you to use

**Comment by rubengees** [comment]
> Turns out snapshots aren't supported on bintray

All SNAPSHOTs i have seen were either hosted on Sonatype or Jitpack. Sonatype would require setting up some kind of CI and Jitpack is less secure.

I guess I'll just have to wait, but thanks for the effort! :+1:

**Comment by brianwernick** [comment]
Ah yes, I always forget about JitPack
