### ISSUE TITLE
Seekbar Change Position on Pause State hides play/next/prev buttons

### ISSUE THREAD

**Issue by amod2005** [brianwernick/ExoMedia#503]
- [ Y] I have verified there are no duplicate active or recent bugs, questions, or requests

###### Include the following:
 - ExoMedia version: `4.0.3`
 - Device OS version: `7.0`
 - Devide Manufacturer: `Google`
 - Device Name: `Pixel XL`
 
###### Reproduction Steps
Thanks for wonderful player
STEP 1 : Start ExoMedia Demo App
STEP 2 : Click Audio PlayBack
STEP 3 : Click Marsellies
STEP 4: After audio starts Click on Pause
STEP 5: After audio is paused use Seekbar to change start position ( anywhere)
 0.  

###### Expected Result
Play/Next/Prev buttons should be visible. User should be able to play from changed position. 
###### Actual Result
Play/Next/Prev buttons not visible. User unable be able to play from changed position. App looks like goes into infinite loop. Only way to play is from Service from Notification Manager. If we go back to main screen and come back to same file. it's still stuck. 
If we select a different audio track it plays correctly

**Comment by brianwernick** [comment]
This isn't an issue with ExoMedia itself, rather the playlist library version we are using for the demo app. And even though the newest version of the playlist library has fixed this issue there are other issues (that I don't remember atm) that caused me to not update the dependency yet. However, I'm currently working on a 2.0 release for the playlist library that the demo will be updated to when released.

**Comment by amod2005** [comment]
Thanks for your reply brianwernick. This is wonderful media player, we will be using in our app and looking forward for 2.0 release.
