### ISSUE TITLE
Exomedia player becomes pause when a sliding notification arrives

### ISSUE THREAD

**Issue by Farrukh381** [brianwernick/ExoMedia#505]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests

###### Include the following:
 - ExoMedia version: `4.0.0`
 - Device OS version: `7.0`
 - Devide Manufacturer: `samasung galaxy`
 - Device Name: `s8`
 
Exomedia player becomes pause when a sliding notification  arrives (which is new Feature in Android N) from whatsapp telegram apps etc.

i think its a bug
Waiting for your reply

**Comment by brianwernick** [comment]
This is working as designed; though there is an enhancement that I want to make that will allow it to resume once the focus is returned (i.e. not abandoning focus on transient focus losses)
The VideoView will automatically handle audio focus and pause when it is lost; which occurs when a notification plays a sound, phone call, etc. (see https://github.com/brianwernick/ExoMedia/blob/master/library/src/main/java/com/devbrackets/android/exomedia/ui/widget/VideoView.java#L794). This can be disabled by calling [`setHandleAudioFocus(false)`](https://github.com/brianwernick/ExoMedia/blob/master/library/src/main/java/com/devbrackets/android/exomedia/ui/widget/VideoView.java#L341)

**Comment by Farrukh381** [comment]
thanks got it
