### ISSUE TITLE
Error:Failed to resolve: com.android.support:appcompat-v7:25.4.0

### ISSUE THREAD

**Issue by lyzcom** [brianwernick/ExoMedia#506]
- [ ] I have verified there are no duplicate active or recent bugs, questions, or requests

###### Include the following:
 - ExoMedia version: `4.0.0`
 - Device OS version: `7.0`
 - Devide Manufacturer: `Google`
 - Device Name: `Pixel XL`
 
###### Reproduction Steps
 0.

**Comment by brianwernick** [comment]
Sounds like your build.gradle isn't setup correctly

**Comment by ahdai0718** [comment]
I faced the same problem couple days age, but i solved it.

add

> allprojects {
>     repositories {
>         jcenter()
>         maven {
>             url "https://maven.google.com"
>         }
>     }
> }

to your project build.gradle
