### ISSUE TITLE
Specify retry count or timeout limit?

### ISSUE THREAD

**Issue by Kisty** [brianwernick/ExoMedia#507]
Is there an easy way to set the retry count or timeout limit? I know this is possible for ExoPlayer but would have to put a lot of boilerplate to achieve this. I think I'd need to give a custom DataSourceProvider. Any ideas how to in this library?

- [X] I have verified there are no duplicate active or recent bugs, questions, or requests

###### Include the following:
 - ExoMedia version: `4.0.3`
 - Device OS version: `7.0`

**Comment by brianwernick** [comment]
See #86

**Comment by Kisty** [comment]
Neat-O! Thanks for that. Will check it out.

Cheers!
