### ISSUE TITLE
ScaleType

### ISSUE THREAD

**Issue by AIlll** [brianwernick/ExoMedia#512]
How can I make it full screen?

```java
<com.devbrackets.android.exomedia.ui.widget.VideoView
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        app:useTextureViewBacking="true"
        app:videoScale="fitCenter"/>
```
![image](https://user-images.githubusercontent.com/23742136/30739287-57b4a11e-9fbf-11e7-8166-50e494e81915.png)

I tried all the ScaleType，Up and down with a gray background

**Comment by AIlll** [comment]
And How do I screenshot?

**Comment by brianwernick** [comment]
See the demo app for an example of fullscreen and read the documentation around `setScaleType` for an explanation of what each one does.

As far as screenshots (video images) are concerned you can call `VideoView#getBitmap()`
