### ISSUE TITLE
Hide all video control tools except loading progress bar

### ISSUE THREAD

**Issue by mokoshalb** [brianwernick/ExoMedia#513]
- ExoMedia version: `4.0.0`
 - Device OS version: `7.0`
 - Devide Manufacturer: `Google`
 - Device Name: `Bluboo S1`
 
###### Reproduction Steps
 Ok!
Not a bug, not an issue, just an individual request.
I needed a hint on how to generally disable or hide the SEEKBAR and the Play/Pause controls.. I followed an already solved method here to disable the default control with:

`app:useDefaultControls="false"`

but using that also disable the buffering gif or is it called progressive "loading" gif? :)
All I need is like a code to disable the seek bar and play/pause functions or preferably hide them...

Not interesting but...couldn't figure it out.

###### Expected Result
Hide default control except "buffering", "loading" gif (basically that rolling loading gif :) )
###### Actual Result
All default controls are disabling, I want all to go except the loading...

**Comment by brianwernick** [comment]
See #276

**Comment by mokoshalb** [comment]
Unfortunately, after trying the solutions suggested on those issues, I still couldn't get it right..

`<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:background="@color/black"
    android:layout_width="match_parent"
    android:layout_height="match_parent">

    <com.devbrackets.android.exomedia.ui.widget.VideoView
        android:id="@+id/video_view"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        app:useDefaultControls="false"
        android:focusable="true">

        <ProgressBar
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:id="@+id/ProgressBar" />
    </com.devbrackets.android.exomedia.ui.widget.VideoView>

</RelativeLayout>
`
