### ISSUE TITLE
Video title, duration, description and image

### ISSUE THREAD

**Issue by mm-farag** [brianwernick/ExoMedia#515]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests

###### Include the following:
 - ExoMedia version: `4.0.0`
 - Device OS version: `7.0`
 - Devide Manufacturer: `Google`
 - Device Name: `Pixel XL`
 
###### Reproduction Steps

Is there a way to get the video title, duration, description and image ?

**Comment by brianwernick** [comment]
Are you asking if we can get this information from the metadata of the media file or via a different means?  The duration has a method in the media players called `getDuration()`.

**Comment by mfaragallah** [comment]
Thank you brianwernick for your reply.

Yes, I am asking if we can get this info from the metadata of the media file. Which other fields we can get from a HLS or DRM video url other than duration ?

**Comment by brianwernick** [comment]
You can register a `MetadataListener` via [`setId3MetadataListener()`](https://github.com/brianwernick/ExoMedia/blob/master/library/src/main/java/com/devbrackets/android/exomedia/ui/widget/VideoView.java#L668) that will return metadata information for the video (or audio in the `AudioPlayer`) when it has been loaded. 

Note that this is a direct passthrough for an `ExoPlayer` listener and I haven't used it in any of my projects so I don't know how consistent it is
