### ISSUE TITLE
resetting bitrate in 3.1.1, doesn't do it in 4.0.0 +

### ISSUE THREAD

**Issue by jboisjo** [brianwernick/ExoMedia#516]
- [ ] I have verified there are no duplicate active or recent bugs, questions, or requests

###### Include the following:
 - ExoMedia version: `4.0.3`
 - Device OS version: `7.0`
 - Devide Manufacturer: `Nvidia`
 - Device Name: `Shield TV`
 
###### Reproduction Steps
 Hey Brian! I know i created this issue couple months ago, but i just upgraded from 3.1.1 to 4.0.3 and i need to reset the bitrate when i play a new video, this is the standard in iOS and Cast :/. Is there a way we can add this options as a boolean or something? And also, this makes way more time to get the other profiles inside de m3u8. In 3.1.1 it took about 2-3seconds to get the next profile, in this one...takes about 10-15seconds...:D

**Comment by brianwernick** [comment]
We've already discussed this and I have made my decision clear on it. I don't see any reason not to load the bitrate that is closest to what it has _already_ been calculated
