### ISSUE TITLE
Playing next song is delayed when screen is off

### ISSUE THREAD

**Issue by arashn** [brianwernick/ExoMedia#517]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests

###### Include the following:
 - ExoMedia version: `4.0.3`
 - Device OS version: `8.0`
 - Devide Manufacturer: `Google`
 - Device Name: `Nexus 5X`
 
###### Reproduction Steps
 0.  Create a new AudioPlayer, and call the setWakeMode method on it, with PowerManager.PARTIAL_WAKE_LOCK.
1. Attach an OnCompletionListener to the AudioPlayer. Once the AudioPlayer is done playing an item, the OnCompletionListener prepares the AudioPlayer with the next item in a playlist.
2. Prepare the AudioPlayer with an HLS media source, as normal, and acquire WiFi lock.
3. Once the AudioPlayer is prepared, start playback of the item.
4. When the song is playing, turn off the screen.
5. Wait for the song to finish playing.

###### Expected Result
When the song finishes playing, the OnCompletionListener should prepare the AudioPlayer with the next item in the playlist, and the AudioPlayer should start playing shortly, once it is prepared.
###### Actual Result
Sometimes, once an item finishes playing, there is an unusual delay before the AudioPlayer starts playing the next item in the playlist.
At this time, turning on the screen causes the AudioPlayer to start playing the next song immediately.
Sometimes, even touching/moving the phone slightly causes the AudioPlayer to start playing the next song.

The Internet connection speed is high. It's as if the call to setWakeMode does nothing, and the AudioPlayer does not really manage the wake lock, as Android's MediaPlayer library does.
There is no issue when the screen is on. The issue is when the song finishes playing and the screen is off.

**Comment by brianwernick** [comment]
Are you running playback in a foreground service? Oreo updated how apps run in the background as well as how wake locks function

**Comment by arashn** [comment]
Yes. The service is in foreground mode for the entire duration that the song is playing. And although I listed this issue with Android 8.0, this happens in Android 6.0 and 7.0 as well.

**Comment by brianwernick** [comment]
Are you able to reproduce this in the demo app?  I'll try to reproduce it this weekend as well.

**Comment by arashn** [comment]
I did a bit of testing with the demo app, and the issue doesn't seem to appear there. However, I noticed that the audio samples used by the demo app are MP3 files, rather than HLS.

Also, looking through the demo app code, I noticed that it uses the PlaylistCore library's ListPlaylistManager and PlaylistServiceCore, which my app does not use. For playing the next media item, PlaylistServiceCore seems to create a new AudioPlayer each time it moves to a new song. My app does not do this; instead, when the AudioPlayer's OnCompletionListener is called, my app simply resets the existing AudioPlayer, and prepares it with a new data source.

**Comment by brianwernick** [comment]
The type of audio format shouldn't make a difference. The reason I asked if you could reproduce it in the demo app is that is sounds like a foreground/background issue with your service/app. PlaylistCore won't create a new AudioPlayer every time it plays an item, it only creates it once then calls `reset()` before playing the next item so that sounds like its the same as what you have setup.

**Comment by arashn** [comment]
I'm not sure if this is related to my service being foreground or background during playback. As I said before, the service is in the foreground state as long as it is playing media. It is only removed from foreground when playback is paused or stopped. Also, this affects not just Android 8.0, but goes back as far as Android 6.0.1, in my testing.

I'll try to see if there is anything interesting in the log when this happens. I'll post here if I do find something.

**Comment by brianwernick** [comment]
After testing this again I'm still unable to reproduce your results. It sounds like there is some configuration in your app that is causing issues as I previously mentioned.

**Comment by arashn** [comment]
Hi. As a follow-up, I suspect that Android's Doze mode is causing this delay. After I prepare the AudioPlayer with an item, I then perform other tasks, such as updating the MediaMetadata for the MediaSession, and loading images from the Internet. There is sometimes a significant delay (30 seconds to a minute) between songs.
