### ISSUE TITLE
VideoView has troubles with 4:3 aspect ratio videos

### ISSUE THREAD

**Issue by holywyvern** [brianwernick/ExoMedia#519]
- ExoMedia version: `4.0.3`
 - Device OS version: `6.0`
 - Devide Manufacturer: `Amlogic`
 - Device Name: `x96`
 
###### Reproduction Steps
 1.  Start an activity with the following layout

```xml
<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="match_parent">
    <com.devbrackets.android.exomedia.ui.widget.VideoView
        android:id="@+id/videoView"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
         />
</RelativeLayout>
````
And just load a 4:3 aspect ratio video

###### Expected Result

The video should look centered, with letterboxing to compesate the different ratio.

###### Actual Result
The letterboxing is displayed, but the video is stretched to be 16:9.

![Problem](https://i.imgur.com/yH2cOLb.jpg "Problem image")

###### Notes
The problem doesn't happen for 16:9 videos at all.

I could convert this particular video to 16:9 to solve it, but I can't control user content to be that way.

**Comment by brianwernick** [comment]
This sounds like it's related to #465, try adding `app:useTextureViewBacking="true"` to the VideoView attributes.

**Comment by holywyvern** [comment]
Yup after adding `app:useTextureViewBacking="true"` is solved.

Thanks

**Comment by brianwernick** [comment]
OK, I'm going to close this as a duplicate as the work for #465 will encapsulate this as well

**Comment by jenish1111** [comment]
hii
i am using portrait video but its not set on full screen
