### ISSUE TITLE
How to enable cache support.

### ISSUE THREAD

**Issue by ImGokulM** [brianwernick/ExoMedia#520]
Hi, the environment I'm using follows,
 - ExoMedia version: `4.0.0`
 - Device OS version: `8.0`
 - Devide Manufacturer: `LG`
 - Device Name: `Nexus 5X`
 
I'm just playing an online video using this player in my android app. Sample video is http://www.sample-videos.com/video/mp4/480/big_buck_bunny_480p_10mb.mp4.
I'm setting the URI to the VideoView to play the video like videoView.setVideoURI(Uri.parse(http://www.sample-videos.com/video/mp4/480/big_buck_bunny_480p_10mb.mp4));
 
Assume I've played half of the video and when I seek back, it starts loading the content again from that seek point. I expect it to play from the local cache instead.

I'm new to this library. So I'm unable to get the solution from the other answers related to this. Please help me on this. Thanks!

**Comment by brianwernick** [comment]
See #487 for an example on how to handle this
