### ISSUE TITLE
Thanks for this wonderful Library

### ISSUE THREAD

**Issue by rubanJoseph** [brianwernick/ExoMedia#521]
You have mentioned "**ExoMedia is a media playback library with similar APIs to the Android MediaPlayer and VideoView that uses the ExoPlayer as a backing when possible, otherwise the default Android MediaPlayer and VideoView are used**".

   Can you please tell exactly when Exoplayer called and when default android video view called.

Thanks in Advance.

**Comment by brianwernick** [comment]
The exact logic to determine if a device is CTS compliant (and thus use the ExoPlayer backing) can be found in the [DeviceUtil#L40](https://github.com/brianwernick/ExoMedia/blob/master/library/src/main/java/com/devbrackets/android/exomedia/util/DeviceUtil.java#L40). In short though, if the OS >= Jellybean or if the device is an Amazon device with an OS >= Lollipop then the ExoPlayer will be used

**Comment by rubanJoseph** [comment]
Thank you very much.
