### ISSUE TITLE
[Question] Video layout transformation

### ISSUE THREAD

**Issue by AllanWang** [brianwernick/ExoMedia#523]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests

 - ExoMedia version: `4.0.3`
 - Device OS version: `7.1.1`
 - Devide Manufacturer: `OnePlus`
 - Device Name: `OnePlus 3`
 
This is not a bug.

I was wondering if there are any methods to help with transforming the video view (much like a scene or transition, where it is a gradual change).

I'm looking into implementing a design like the youtube app, where the video is originally fullscreen and can be minimized to the bottom right of the screen.

Is there anything I should look into or will this involve using the `VideoViewApi` directly? Does the video view even support being resized externally after the video is loaded?

I see implementations using both the TextureView and SurfaceView (#371)

**Comment by brianwernick** [comment]
You should be able to do most transformations to the view using the standard animations, animators, etc. when you've specified it to use a `TextureView` backing (i.e. added `app:useTextureViewBacking="true"` to your layout)

**Comment by AllanWang** [comment]
I'm looking into it now. One thing I've noticed is that both the `VideoView` and the `VideoViewApi` return the same height. Is this expected behaviour? I thought the `VideoView` would return the parent height, but the `VideoViewApi` will only return the height of the video itself, without the controls and everything

**Comment by AllanWang** [comment]
Scaling and translating has been solved. See #524 for demo
