### ISSUE TITLE
VideoView does not adhere to parent's alpha value

### ISSUE THREAD

**Issue by AllanWang** [brianwernick/ExoMedia#524]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests

###### Include the following:
 - ExoMedia version: `4.0.3`
 - Device OS version: `7.1.1`
 - Devide Manufacturer: `OnePlus`
 - Device Name: `OnePlus 3`
 
###### Reproduction Steps
 Set the parent view to a given alpha

###### Expected Result
VideoView also has the same alpha

###### Actual Result
When using `animate()`, VideoView remains fully opaque.
When setting the value explicitly, VideoView immediately becomes invisible. Setting the alpha back to 1f does not result in any change. The view is still there as all other touch events are working.

Code for reference: https://github.com/AllanWang/Frost-for-Facebook/blob/feature/pip-video-2/app/src/main/kotlin/com/pitchedapps/frost/views/FrostVideoView.kt#L155

I can drag the view around just fine by modifying the parent, but I cannot have it fade while being dragged

**Comment by AllanWang** [comment]
Without alpha change

![giphy 1](https://user-images.githubusercontent.com/6251823/31568058-6ec9861c-b040-11e7-95f8-54d5dbb49cfc.gif)

With alpha change

![giphy](https://user-images.githubusercontent.com/6251823/31568054-6c5d7096-b040-11e7-9a8b-f692d9db1192.gif)

**Comment by brianwernick** [comment]
Is this using a `TextureVew` or `SurfaceView` backing (or both)?

**Comment by AllanWang** [comment]
As of now this is with surfaceview, as textureview doesn't show the bounds of the actual video

**Comment by AllanWang** [comment]
This works with textureview as expected. A few other things had to be done about the boundaries, but this is not a bug with exomedia
