### ISSUE TITLE
Change video resolution

### ISSUE THREAD

**Issue by sikanderkhcb** [brianwernick/ExoMedia#526]
- Can you help me how can i change the resolution 360 to 720 pixel I m using this and where can i play.

Iterator it = videoView.getAvailableTracks().entrySet().iterator();
                    while (it.hasNext()) {
                        Map.Entry pair = (Map.Entry)it.next();
                        System.out.println("key"+pair.getKey());
                        TrackGroupArray t = (TrackGroupArray)pair.getValue();
                        for(int i = 0; i < t.length; i++)
                        {
                            Log.d("values",""+t.get(i).getFormat(i));
                        }
                    }

Result: 
I/System.out: ---->CLOSED_CAPTION
 D/---->: Format(1/21, null, application/id3, -1, null, [-1, -1, -1.0], [-1, -1])
r I/System.out: ---->VIDEO
1 D/---->: Format(1/8219, null, application/cea-608, -1, null, [-1, -1, -1.0], [-1, -1])
 I/System.out: ---->AUDIO
 D/---->: Format(0, null, video/avc, 256000, null, [-1, -1, -1.0], [-1, -1])

###### Include the following:
 - ExoMedia version: `4.0.3`
 - Device OS version: `8.0`
 - Devide Manufacturer: `Google`
 - Device Name: `Pixel`

**Comment by brianwernick** [comment]
I don't understand the question. You already understand how to get the tracks and groups so all you have left is to set the track for the video that is associated with the size you want.

**Comment by sikanderkhcb** [comment]
Thanks to reply now i have solved the issued by my self.
