### ISSUE TITLE
[Feature Request] onControlVisibilityChangeListener

### ISSUE THREAD

**Issue by AllanWang** [brianwernick/ExoMedia#528]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests

(Not a bug, device info not given)

It would be nice to have a public listener to be notified on when a the playback controls are shown/hidden. For instance, if we wish to have a toolbar that also changes visibility with the controls.

We can easily replicate this for touch events, but there is a bit more work to be done when the video is playing, as tapping once will show the control for a short period of time (which also reset if another event is triggered etc).

**Comment by brianwernick** [comment]
Something like https://github.com/brianwernick/ExoMedia/blob/master/demo/src/main/java/com/devbrackets/android/exomediademo/ui/activity/FullScreenVideoPlayerActivity.java#L26?

**Comment by AllanWang** [comment]
Thanks for that. I will take a look at it and see if it suits my need
