### ISSUE TITLE
Dependencie v4.0.3 looks outdated

### ISSUE THREAD

**Issue by PFittech** [brianwernick/ExoMedia#530]
I use dependencies com.devbrackets.android:exomedia:4.0.3 but looks outdated. For example>
 ExoMedia.setDataSourceFactoryProvider is missing but in example you have library where is this funcion. Next for example in v4.0.3 is setHttpDataSourceFactoryProvider not deprecated but in exaple library is deprecarted. Do you update resources in dependecie? I also try AAR but the same ...old resources

**Comment by brianwernick** [comment]
The current master is what is slated for the 4.1.0 release and not what was released in 4.0.3.

**Comment by PFittech** [comment]
when we can expect a new version? Thx

**Comment by brianwernick** [comment]
I'm not going to give a timeline for the next release; I'll I can say is that I hope to get an update out sometime this month
