### ISSUE TITLE
How to add cookies????

### ISSUE THREAD

**Issue by kawadkarrocky** [brianwernick/ExoMedia#531]
Hi, I tried your example for playing HLS video and its working perfectly
but I need to know that how to play HLS video by setting cookies using Cloud Front because one of my video needs to set up cookie first,any help would be appreciateable.

**Comment by brianwernick** [comment]
You can specify the HttpDataSource using [ExoMedia.setHttpDataSourceFactoryProvider()](https://github.com/brianwernick/ExoMedia/blob/master/library/src/main/java/com/devbrackets/android/exomedia/ExoMedia.java#L82) in the current 4.0.x release which will allow you to control the cookies, etc.
Do note that this will be deprecated in 4.1 + in favor of [ExoMedia.setDataSourceFactoryProvider()](https://github.com/brianwernick/ExoMedia/blob/master/library/src/main/java/com/devbrackets/android/exomedia/ExoMedia.java#L94) which will be added in the same version (4.1.0)
