### ISSUE TITLE
Incompability with ExoPlayer 2.6.0

### ISSUE THREAD

**Issue by rubengees** [brianwernick/ExoMedia#533]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests

###### Include the following:
 - ExoMedia version: `latest master`
 - Device OS version: `irrelevant`
 - Devide Manufacturer: `irrelevant`
 - Device Name: `irrelevant`
 
Basically the same as #500.
`ExoPlayer` version `2.6.0` has been released and includes many [changes](https://github.com/google/ExoPlayer/blob/release-v2/RELEASENOTES.md), sadly also breaking ones:

```
com/devbrackets/android/exomedia/core/renderer/RendererProvider.buildCaptionRenderers:
()Ljava/util/List; references unknown class member: 
com/google/android/exoplayer2/text/TextRenderer.<init>:
(Lcom/google/android/exoplayer2/text/TextRenderer$Output;Landroid/os/Looper;)V

com/devbrackets/android/exomedia/core/renderer/RendererProvider.buildMetadataRenderers:
()Ljava/util/List; references unknown class member: 
com/google/android/exoplayer2/metadata/MetadataRenderer.<init>:
(Lcom/google/android/exoplayer2/metadata/MetadataRenderer$Output;Landroid/os/Looper;
Lcom/google/android/exoplayer2/metadata/MetadataDecoderFactory;)V
```

[This](https://github.com/google/ExoPlayer/commit/2470b39d9520618c59a8c857085120dd8da2ffee) seems to be the breaking commit.
An update for that on `master` would be great, so I can test the latest changes.
Thanks in advance! :grin:

**Comment by brianwernick** [comment]
Updated
