### ISSUE TITLE
Fullscreen doesnt work

### ISSUE THREAD

**Issue by bene25** [brianwernick/ExoMedia#534]
- exomedia:4.0.3
 - Device OS SDK : `22`
 - Device Name: `Minix Neo U1`
 
Hello. I have carefully read and implement fullscreen demo app, but however with our HLS stream, fullscreen doesnt work.

I added to all activities:
 android:configChanges="orientation|keyboardHidden|screenSize"

My video player activity looks like: 

<?xml version="1.0" encoding="utf-8"?>
<android.support.constraint.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:id="@+id/rootLayout"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:background="@android:color/black">

    <com.devbrackets.android.exomedia.ui.widget.VideoView
        android:id="@+id/mainVideo"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        />

    <FrameLayout
        android:id="@+id/placeholder"
        android:layout_width="0dp"
        android:layout_height="0dp"
        app:layout_constraintBottom_toBottomOf="parent"
        app:layout_constraintLeft_toLeftOf="parent"
        app:layout_constraintRight_toRightOf="parent"
        app:layout_constraintTop_toTopOf="parent" />
</android.support.constraint.ConstraintLayout>

And added almost all methods from FullScreenActivity.
Video stream is HLS.

Update1:

I tried to play video stream in demo app, and it also uses default size. 

Thanks for helping

**Comment by brianwernick** [comment]
The `FullscreenVideoPlayerActivity` in the demo shows how the `VideoView` can be used with the window flags and not how to make the video itself full screen (though this is a side effect in landscape if the video aspect ratio matches that of the phone/tablet)

With that in mind, I'm not sure quite what you are asking about nor what `"I tried to play video stream in demo app, and it also uses default size"` means in this context. :/  If you are trying to get the video to scale and fill the entire screen you will need to use the `setScaleType` method or `app:videoScale=""` xml attribute (though note that there is an issue with scaling in the SurfaceView backing in 4.0.x that is fixed in master, so you will need to use the `app:useTextureViewBacking="true"` xml attribute until 4.1.0 is released)

**Comment by bene25** [comment]
Yes it works, thanks. But I want to stretch view, to make it fill all area on screen without cropping.

**Comment by brianwernick** [comment]
`CENTER_CROP` should be the scale type you want

**Comment by bene25** [comment]
No, this feature stretches video horizontally, but crop vertically in case If default video fitted screen vertically and had horizontal black borders.

**Comment by brianwernick** [comment]
Ah yes, the scale types available only keep the aspect ratio. It sounds like what you want is something more akin to https://developer.android.com/reference/android/widget/ImageView.ScaleType.html#FIT_XY?

**Comment by bene25** [comment]
I have added this 

    <com.devbrackets.android.exomedia.ui.widget.VideoView
        android:id="@+id/mainVideo"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        app:useTextureViewBacking="true"
        android:scaleType="fitXY"/>

And video stretches like fit center.

**Comment by brianwernick** [comment]
That's because ExoMedia doesn't have a `fitXY` option. :(

**Comment by bene25** [comment]
Ok, are there any way to stretch video to whole screen?

**Comment by brianwernick** [comment]
Not easily without making modifications to ExoMedia itself. You can manually handle the scaleX and scaleY as long as you are confident around handling the video rotation aspects as well (e.g. similar to [MatrixManager#setScale()](https://github.com/brianwernick/ExoMedia/blob/master/library/src/main/java/com/devbrackets/android/exomedia/core/video/scale/MatrixManager.java#L194)). I'll add fitXY as a feature request for 4.1

**Comment by bene25** [comment]
Thanks. What approximately date of release?

**Comment by brianwernick** [comment]
I should have some time this weekend and coming week so tentatively about a week out (?)

**Comment by bene25** [comment]
Thanks!

**Comment by brianwernick** [comment]
Turns out that I had made `NONE` represent fitXY, I'm still going to add an actual representation to the enum, but you can use `none` in xml or the type `NONE` to get fitXY

**Comment by bene25** [comment]
Thanks. It works!

**Comment by elementzonline** [comment]
Works for me. Thanks
