### ISSUE TITLE
Adding Fastforward and rewind button

### ISSUE THREAD

**Issue by khazra18** [brianwernick/ExoMedia#539]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests

###### Include the following:
 - ExoMedia version: `4.0.0`
 - Device OS version: `6.0`
 - Devide Manufacturer: `Asus`
 - Device Name: `Z00LD`
 
Hii, I am not able to put fastforward and rewind button
Can you help me please 

video_view = (VideoView) findViewById(R.id.video_view);

        VideoControls videoControls = video_view.getVideoControls();
        if (videoControls != null) {
            //videoControls.setFastForwardButtonRemoved(false);
            videoControls.setFastForwardButtonEnabled(true);
        }

        video_view.setVideoURI(Uri.parse("abc.mp4"));
        video_view.start();

Next button and previous button is showing if i write

videoControls.setNextButtonRemoved(false);
videoControls.setPreviousButtonRemoved(false);

But,
The fast forward and Rewind button is not showing up...please can you help me !!!!

**Comment by brianwernick** [comment]
FastForward and Rewind will only show up in the Leanback (Android TV) view
