### ISSUE TITLE
VideoView freezes on Nexus 4

### ISSUE THREAD

**Issue by arashn** [brianwernick/ExoMedia#543]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests

###### Include the following:
 - ExoMedia version: `4.0.0`
 - Device OS version: `5.1.1`
 - Devide Manufacturer: `Google`
 - Device Name: `Nexus 4`
 
###### Reproduction Steps
 1. Prepare a VideoView with HD media

###### Expected Result
Video plays all the way through
###### Actual Result
Video freezes after a few minutes

Below is the device log a few moments before the video froze:

```
12-16 21:59:17.783 12953-13264/com.radiojavan.androidradio I/OMXClient: Using client-side OMX mux.
12-16 21:59:17.791 12953-13264/com.radiojavan.androidradio E/OMXMaster: A component of name 'OMX.qcom.audio.decoder.aac' already exists, ignoring this one.
12-16 21:59:17.810 12953-13268/com.radiojavan.androidradio I/OMXClient: Using client-side OMX mux.
12-16 21:59:17.833 12953-13249/com.radiojavan.androidradio W/MediaCodecVideoRenderer: Resolutions unknown. Codec max resolution: 848x476
12-16 21:59:17.833 12953-13249/com.radiojavan.androidradio W/MediaCodecVideoRenderer: Codec max resolution adjusted to: 1920x1078
12-16 21:59:17.839 12953-13268/com.radiojavan.androidradio E/ACodec: [OMX.qcom.video.decoder.avc] storeMetaDataInBuffers failed w/ err -2147483648
12-16 21:59:18.074 12953-13265/com.radiojavan.androidradio I/SoftAAC2: Reconfiguring decoder: 0->48000 Hz, 0->2 channels
12-16 21:59:24.787 12953-12968/com.radiojavan.androidradio I/art: Background sticky concurrent mark sweep GC freed 48308(3MB) AllocSpace objects, 55(1729KB) LOS objects, 10% free, 51MB/57MB, paused 5.157ms total 170.669ms
12-16 21:59:31.870 12953-12968/com.radiojavan.androidradio I/art: Background sticky concurrent mark sweep GC freed 10254(526KB) AllocSpace objects, 3(96KB) LOS objects, 1% free, 57MB/57MB, paused 5.096ms total 47.031ms
12-16 21:59:32.680 12953-12968/com.radiojavan.androidradio I/art: Background partial concurrent mark sweep GC freed 21142(1023KB) AllocSpace objects, 13(632KB) LOS objects, 22% free, 56MB/72MB, paused 2.075ms total 171.219ms
12-16 21:59:39.021 12953-13440/com.radiojavan.androidradio I/OMXClient: Using client-side OMX mux.
12-16 21:59:39.043 12953-13249/com.radiojavan.androidradio W/MediaCodecVideoRenderer: Resolutions unknown. Codec max resolution: 1920x1080
12-16 21:59:39.045 12953-13440/com.radiojavan.androidradio E/ACodec: [OMX.qcom.video.decoder.avc] storeMetaDataInBuffers failed w/ err -2147483648
```

**Comment by brianwernick** [comment]
Do you still see this with `4.1.0`? This is an ExoPlayer internal that seems to be having some trouble

**Comment by arashn** [comment]
I have not been able to reproduce this with version 4.0.3 yet. I will update this issue when I'm able to reproduce the issue with version 4.0.3, and if the bug still exists with 4.1.0.

**Comment by arashn** [comment]
Okay. I was able to reproduce the issue with version 4.0.3.
The issue also appears in version 4.1.0, but it's a bit different. The problematic video freezes at the same spot as before, but for a brief period it updates the frame once every few seconds. At one point the video started to play fine again, but then it froze, updating the frame once every few seconds again.

**Comment by brianwernick** [comment]
Can you provide a video to duplicate this with

**Comment by arashn** [comment]
Here's the video that I've been having problems with: https://host2.mediarj.com/media/music_video/hls/moein-z-nareye-chaah.m3u8

**Comment by brianwernick** [comment]
The Video file you posted is bad, the main manifest file exists but all the children get redirected to a web page

**Comment by arashn** [comment]
How would this affect video playback?

**Comment by brianwernick** [comment]
The video won't play at all

**Comment by arashn** [comment]
I tried it and the video does play, but the video stutters after a bit. And this is only on the Nexus 4. On a Nexus 5, for example, the same video plays fine.

**Comment by brianwernick** [comment]
They definitely don't exist in the location specified by the main `m3u8` file. 
```
Request URL:https://host2.mediarj.com/media/music_video/hls/file-3040k.m3u8
Request Method:GET
Status Code:302 Found
```

**Comment by arashn** [comment]
If you look closely, the link I posted above redirects to https://host2.mediarj.com/hls/moein-z-nareye-chaah/playlist.m3u8. So what you should be looking at is https://host2.mediarj.com/hls/moein-z-nareye-chaah/file-3040k.m3u8, which will give you the stream files for the video.

**Comment by brianwernick** [comment]
Ah, thats my bad then; Chrome wasn't showing the redirect for the main playlist.

Though it looks like there's something wrong with redirects, or at the very least the one you posted because the first url results in
```
E/ExoPlayerImplInternal: Source error.
    com.google.android.exoplayer2.source.UnrecognizedInputFormatException: Input does not start with the #EXTM3U header.
    at com.google.android.exoplayer2.source.hls.playlist.HlsPlaylistParser.parse(HlsPlaylistParser.java:131)
    at com.google.android.exoplayer2.source.hls.playlist.HlsPlaylistParser.parse(HlsPlaylistParser.java:47)
    at com.google.android.exoplayer2.upstream.ParsingLoadable.load(ParsingLoadable.java:126)
    at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:315)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
    at java.lang.Thread.run(Thread.java:764)
```
(NOTE: VLC can't play the first link either)

While using the second url provided plays as expected.

**Comment by arashn** [comment]
I can't see that error when I look at the logs. Also, I tried VLC, and it could follow the redirects for the first link and played the video just fine.

**Comment by arashn** [comment]
I suspect ExoPlayer has trouble switching between different bitrate streams. I noticed, on another device, at about the same time that the video froze on the Nexus 4, the video quality increased.

**Comment by arashn** [comment]
Since this seems to be an ExoPlayer issue, you can go ahead and close this issue.

**Comment by brianwernick** [comment]
I'm going to leave it open as a reminder to look in to why redirects aren't being handled correctly (It might be the OKHttp data source the demo app is using or maybe it was my works network doing something stupid).

**Comment by arashn** [comment]
I don't think redirection is the issue here, because even the original link I posted above played for me.
