### ISSUE TITLE
How can we make the scrubber move when we drag the scrubber instead of clicking on the seek bar 

### ISSUE THREAD

**Issue by shwetha-DabKick** [brianwernick/ExoMedia#544]
- [ ] I have verified there are no duplicate active or recent bugs, questions, or requests

Scrubber in seek bar is not draggable on the click events are triggered when clicked on seek bar.
How can we change the position of video by dragging the seekbar

###### Include the following:
 - ExoMedia version: `4.1.0`
 - Device OS version: `7.1.1`
 - Devide Manufacturer: `All manufactureres`
 - Device Name: `All Devices`
 
###### Reproduction Steps
 Play the video and try dragging the scrubber

###### Expected Result
We should be able to drag the scrubber

###### Actual Result
Not able to drag, if we try to drag video plays from first.

**Comment by brianwernick** [comment]
There are some cases where the ExoPlayer cannot seek within a video, `flv` being one of those formats (it used to work in ExoPlayer 1.x but was purposefully changed in 2.x).

**Comment by keshav1139** [comment]
Ok. But I am not able to scrub the video by dragging  in any of the formats, can you please let me know if any workaround for this. I have to implement this in my application.

**Comment by brianwernick** [comment]
This works in the demo app, with the exception mentioned above. As such I'm going to close the issue
