### ISSUE TITLE
Landscape mode video not streching full screen

### ISSUE THREAD

**Issue by khazra18** [brianwernick/ExoMedia#545]
- [] I have verified there are no duplicate active or recent bugs, questions, or requests

###### Include the following:
 - ExoMedia version: `4.1.0`
 - Device OS version: `7.0`
 - Devide Manufacturer: `Asus`
 - Device Name: `Zenfone 2  Laser`
 
Hiii
I am playing this video on Landscape mode 
But many of the videos aren't coming full screen 

I have used this code 

live_video_player.setScaleType(ScaleType.FIT_XY);
live_video_player.setOnPreparedListener(this);
live_video_player.setVideoURI(Uri.parse("some url"));

I am attaching some screenshots please check them 

![screenshot_20171221-152710](https://user-images.githubusercontent.com/34342669/34251421-0cbb21c2-e666-11e7-9ca3-d2089fd98d75.jpg)
![screenshot_20171221-154011](https://user-images.githubusercontent.com/34342669/34251422-0cfc0e08-e666-11e7-8b40-b00cb80e66b8.jpg)

Please can u suggest what can i do for this issue ?

**Comment by brianwernick** [comment]
See #465
