### ISSUE TITLE
ExoTextureVideoView set wrap_content has no effect

### ISSUE THREAD

**Issue by fenggit** [brianwernick/ExoMedia#548]
- [ ] I have verified there are no duplicate active or recent bugs, questions, or requests

###### Include the following:
 - ExoMedia version: `4.0.0`
 - Device OS version: `7.0`
 - Devide Manufacturer: `Google`
 - Device Name: `Pixel XL`
 
###### Reproduction Steps
 0.  I use ExoTextureVideoView , set android:layout_height="wrap_content" ,but it awlays full screen

**Comment by brianwernick** [comment]
Duplicate of #222
