### ISSUE TITLE
Get all the audios (languages) availables in a .m3u8 and subtitles?

### ISSUE THREAD

**Issue by billyjoker** [brianwernick/ExoMedia#551]
Hi Brian, do you have any method to show all the available audio languages and subtitle texts in a .m3u8 file? I'd like to show a menu to the user which shows all the options available to select them.

Thanks!!

**Comment by brianwernick** [comment]
You should be able to call [`getAvailableTracks`](https://github.com/brianwernick/ExoMedia/blob/master/library/src/main/java/com/devbrackets/android/exomedia/ui/widget/VideoView.java#L587) and grab the [`TrackGroupArray`](https://github.com/google/ExoPlayer/blob/2b20780482a9c6b07416bcbf4de829532859d10a/library/core/src/main/java/com/google/android/exoplayer2/source/TrackGroupArray.java) that's associated with [`RenderType.CLOSED_CAPTION`](https://github.com/brianwernick/ExoMedia/blob/master/library/src/main/java/com/devbrackets/android/exomedia/ExoMedia.java#L45). Then look at each of the [`TrackGroup's`](https://github.com/google/ExoPlayer/blob/2bebd526e1ece801ef53e6daeaaee76b0255ec6d/library/core/src/main/java/com/google/android/exoplayer2/source/TrackGroup.java) associated [`Format's`](https://github.com/google/ExoPlayer/blob/2bebd526e1ece801ef53e6daeaaee76b0255ec6d/library/core/src/main/java/com/google/android/exoplayer2/Format.java) to determine the metadata, etc. that you need.

**Comment by billyjoker** [comment]
Yes, i could debug and call to `getAvailableTracks`, but the info returned it is not what i waited. I mean, with the subtitles i have no information about language (it is filled with a null), so reading i do not see hte language of the available subtitle track when i get:

`getAvailableTracks().get(ExoMedia.RendererType.CLOSED_CAPTION).get(0).getFormat(0)`

![firstcaption](https://user-images.githubusercontent.com/4301306/34936687-a3e57d60-f9e2-11e7-94c9-a2d2ad532e87.png)

**Comment by brianwernick** [comment]
Does the track info available in the media actually contain the language information?

**Comment by billyjoker** [comment]
Afirmative, this is the .m3u8 file:

```
.#EXTM3U
#EXT-X-VERSION:3
#EXT-X-STREAM-INF:BANDWIDTH=2298000,CODECS="avc1.100.40,mp4a.40.2",RESOLUTION=1920x1080,AUDIO="aac"
chunklist_b2298000_vo.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=1660000,CODECS="avc1.77.30,mp4a.40.2",RESOLUTION=1280x720,AUDIO="aac"
chunklist_b1660000_vo.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=894000,CODECS="avc1.77.30,mp4a.40.2",RESOLUTION=854x480,AUDIO="aac"
chunklist_b894000_vo.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=511000,CODECS="avc1.77.30,mp4a.40.2",RESOLUTION=640x360,AUDIO="aac"
chunklist_b511000_vo.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=383000,CODECS="avc1.77.30,mp4a.40.2",RESOLUTION=426x240,AUDIO="aac"
chunklist_b383000_vo.m3u8
#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="aac",LANGUAGE="es",NAME="Spanish",DEFAULT=YES,URI="chunklist_b128000_ao_sles_t64U3BhbmlzaA==.m3u8"
#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="aac",LANGUAGE="en",NAME="English",DEFAULT=YES,URI="chunklist_b128000_ao_slen_t64RW5nbGlzaA==.m3u8"
#EXT-X-MEDIA:TYPE=SUBTITLES,GROUP-ID="subt",LANGUAGE="es",NAME="Spanish",DEFAULT=YES,URI="../es_subt.vtt"
```

**Comment by brianwernick** [comment]
Is the offset correct (see #541) in to the available tracks mapping? Looking at the ExoPlayer code it seems that it should correctly be grabbing the language, etc.

**Comment by brianwernick** [comment]
I'm going to assume it's related to #451 and close the issue
