### ISSUE TITLE
Can I get the current video buffer size?

### ISSUE THREAD

**Issue by LiqiNew** [brianwernick/ExoMedia#553]
- [ ] I have verified there are no duplicate active or recent bugs, questions, or requests

###### Include the following:
 - ExoMedia version: `4.0.0`
 - Device OS version: `7.0`
 - Devide Manufacturer: `Google`
 - Device Name: `Pixel XL`
 
###### Reproduction Steps
 0.

**Comment by brianwernick** [comment]
You can get the percent value from the [`OnBufferUpdateListener`](https://github.com/brianwernick/ExoMedia/blob/master/library/src/main/java/com/devbrackets/android/exomedia/listener/OnBufferUpdateListener.java)

**Comment by LiqiNew** [comment]
thank you very much
