### ISSUE TITLE
Cannot play HLS link.

### ISSUE THREAD

**Issue by darkokostic** [brianwernick/ExoMedia#555]
Hi there, thank you for creating this amazing library.
I wanted to use this library for my android app and I decided first to test your demo version.

When I changed urls from demo video samples to my video HLS streaming urls, one link is playing just fine, and another link cannot play at all. In logcat it seems that the app sending request to the server over and over in loop.

This is not server problem, because I tested this link with FFmpegMediaPlayer library, and it worked just fine, also I tested it with Perfect Player app from Google Play Store, it worked too.

- [x] I have verified there are no duplicate active or recent bugs, questions, or requests

###### Include the following:
 - ExoMedia version: demo app downloaded from this git repository on 17. 01. 2018.
 - Device OS version: `6.0`
 - Devide Manufacturer: `Sony`
 - Device Name: `Xperia M5`
 
###### Reproduction Steps
Just change the urls of HLS video in your demo app with my urls, which I will give you after you ping me on my email: kostic.darko95@gmail.com

I don't want this urls to see in public.

###### Expected Result
Expected result is that demo app play both HLS links.

###### Actual Result
One link works fine, another doesn't play.

I repeat, this is not the server problem, the link that doesn't play, works fine on other players.

I will be very thankful if anyone can help me.
Thanks

**Comment by brianwernick** [comment]
Would you mind posting the error log
