### ISSUE TITLE
Unable to handle invalid stream URL

### ISSUE THREAD

**Issue by tspvivek** [brianwernick/ExoMedia#558]
- [ Yes] I have verified there are no duplicate active or recent bugs, questions, or requests

###### Include the following:
 - ExoMedia version: `4.1.0`
 - Device OS version: `7.0`
 - Devide Manufacturer: `Xiaomi`
 - Device Name: `Redmi 5A`
 
###### Reproduction Steps
 0.  Tried playing a invalid stream url http://radiobanglaone.com:7721/stream#.mp3

###### Expected Result
Error Listener should be called or an exception should be thrown
###### Actual Result
But only prints the below line in console
01-18 19:41:54.839 30272-736/tech.radio.test E/ExoPlayerImplInternal: Source error.

Unable to handle the error when a invalid url is used

**Comment by brianwernick** [comment]
I just tried this in the Demo app and the error listener is correctly informed of the error.

**Comment by tspvivek** [comment]
Hi Brian,
Thanks for this amazing wrapper for ExoPlayer.

I figured out the issue and its a coding issue in my end. I used ffmpegmediaplayer as fallback if exoplayer failed to play certain streams. I messed up my code in the fallback part.  

I am extremely sorry for wasting your time.

**Comment by brianwernick** [comment]
No worries, it happens from time to time :). Glad you figured it out
