### ISSUE TITLE
How to set JWT token in Request Header

### ISSUE THREAD

**Issue by asimbashir** [brianwernick/ExoMedia#559]
It might have been posted and discussed earlier but I couldn't get a clear example or solution. Our videos are secured and require a JWT token to be passed in request headers. With native android VideoView we have a method `setVideoUri(Uri uri, Map headers)` but I couldn't find any such method provided by EmVideoView.

**Comment by asimbashir** [comment]
It might have been posted and discussed earlier but I couldn't get a clear example or solution. Our videos are secured and require a JWT token to be passed in request headers. With native android VideoView we have a method setVideoUri(Uri uri, Map headers) but I couldn't find at such method provided by EmVideoView.

**Comment by brianwernick** [comment]
See #103
