### ISSUE TITLE
setScaleType (ScaleType.FIT_XY) setting is invalid

### ISSUE THREAD

**Issue by LiqiNew** [brianwernick/ExoMedia#563]
- [ ] I have verified there are no duplicate active or recent bugs, questions, or requests

###### Include the following:
 - ExoMedia version: `4.0.0`
 - Device OS version: `7.0`
 - Devide Manufacturer: `Google`
 - Device Name: `Pixel XL`
 
###### Reproduction Steps
 0.  

###### Expected Result
 When playing video, both vertical and horizontal screens fill the entire width and height.
For example: I set the video player control width equal to 300, height equal to 300. I want to play the video fill my set width and height.
###### Actual Result
```
Chinese English, please forgive me.
Hope the author have time to check it.Thank you.
```

Debugging source found 
```java 
setScaleType (ScaleType.FIT_XY) 
``` 
method setting is invalid. 
The reason is that the 
``` 
MatrixManager
 ``` 
object 
```java 
scale (@NonNull View view, @NonNull ScaleType scaleType)
 ``` 
method in the call many times
,

When
 ```java
 scale (@NonNull View view, @NonNull ScaleType scaleType) 
```
 is reached
```java 
switch (scaleType) {
             case FIT_XY:
                 applyFitXy (view);
                 break;
         } 
```
The set 
```java  
ScaleType.FIT_XY 
```
 parameter will be cleared inside the 
```java
 applyFitXy (view) 
```
 method.

**Comment by brianwernick** [comment]
See #465
