### ISSUE TITLE
getExoPlayerTrackIndex returns 0 on AUDIO

### ISSUE THREAD

**Issue by bene25** [brianwernick/ExoMedia#564]
Hello.
ExoMedia 4.1.0
ExoPlayer 4.6.0

Method getExoPlayerTrackIndex, returns 0 on ExoMedia.RendererType.AUDIO type, but as remember AUDIO type in exoPlalyer is 1.

Сorrect me if I wrong:)

**Comment by brianwernick** [comment]
I'm assuming this is in reference to the changes made for #541. There's [`getExoPlayerTrackType`](https://github.com/brianwernick/ExoMedia/blob/master/library/src/main/java/com/devbrackets/android/exomedia/core/exoplayer/ExoMediaPlayer.java#L469) which in the case of `AUDIO` is `1`, and then there is the [`getExoPlayerTrackIndex`](https://github.com/brianwernick/ExoMedia/blob/master/library/src/main/java/com/devbrackets/android/exomedia/core/exoplayer/ExoMediaPlayer.java#L484) which in the case of `AUDIO` is `0`. The two have different meanings but are close enough that I didn't catch it on initial development; the types are 1-based while the indexes are 0-based.

**Comment by bene25** [comment]
Ok, should `exoPlayerTrackIndex` in 

`trackSelector.setSelectionOverride(exoPlayerTrackIndex, trackGroupArray, selectionOverride);`

set 0 or 1?

**Comment by brianwernick** [comment]
It takes the index so for Audio it would be `0`
