### ISSUE TITLE
How get video volume

### ISSUE THREAD

**Issue by fenggit** [brianwernick/ExoMedia#565]
- [ ] I have verified there are no duplicate active or recent bugs, questions, or requests

###### Include the following:
 - ExoMedia version: `4.0.0`
 - Device OS version: `7.0`
 - Devide Manufacturer: `Google`
 - Device Name: `Pixel XL`
 
###### Reproduction Steps
I use ExoTextureVideoView object ,How get video volume ,Thanks .

**Comment by brianwernick** [comment]
There isn't currently a way to get the audio volume from either the `VideoView` or `AudioPlayer`.

**Comment by fenggit** [comment]
okay ,  I want get current volume

**Comment by fenggit** [comment]
List video playback, after I release video, how to reuse video ？

**Comment by brianwernick** [comment]
That's not related to this question; you should ask a new question or preferably search the issues as that's been answered multiple times

**Comment by fenggit** [comment]
okay ，thanks
