### ISSUE TITLE
Can't play RTMP link even tough it has support for it....please add this feature too

### ISSUE THREAD

**Issue by Farrukh381** [brianwernick/ExoMedia#566]
Feature Request

**Comment by brianwernick** [comment]
RTMP is an [extension](https://github.com/google/ExoPlayer/tree/release-v2/extensions/rtmp) library for ExoPlayer so you will need to add 
``` gradle
compile 'com.google.android.exoplayer:extension-rtmp:2.6.1'
```
To your build.gradle and register the new [`RtmpDataSource`](https://github.com/google/ExoPlayer/blob/release-v2/extensions/rtmp/src/main/java/com/google/android/exoplayer2/ext/rtmp/RtmpDataSource.java) with [`ExoMedia#registerMediaSourceBuilder()`](https://github.com/brianwernick/ExoMedia/blob/master/library/src/main/java/com/devbrackets/android/exomedia/ExoMedia.java#L68).

e.g.
``` java
public class RtmpMediaSourceBuilder extends DefaultMediaSourceBuilder {
    @NonNull
    @Override
    protected DataSource.Factory buildDataSourceFactory(@NonNull Context context, @NonNull String userAgent, @Nullable TransferListener<? super DataSource> listener) {
        return new RtmpDataSourceFactory(listener);
    }
}

// And somewhere useful for you, I usually do this in the Application class or the VideoPlayer Activity
public void registerNewBuilders() {
    ExoMedia.registerMediaSourceBuilder(new MediaSourceProvider.SourceTypeBuilder(new RtmpMediaSourceBuilder(), "", "rtmp:.*"));
}

```

**Comment by ehsansouri23** [comment]
Type 'com.google.android.exoplayer2.upstream.TransferListener' does not have type parameters

this error happened while copying your code for rtmp streaming

**Comment by tunjid** [comment]
@ehsansouri23 make sure your version of `com.google.android.exoplayer:extension-rtmp:2.6.1` uses the same version of exoplayer this library uses. The generic type seems to have been removed between versions.
