### ISSUE TITLE
End Time showing --:-- when a video is staged and progress bar keeps spinning but video starts to play

### ISSUE THREAD

**Issue by keshav1139** [brianwernick/ExoMedia#567]
###### Include the following:
 - ExoMedia version: `4.1.0`
 - Device OS version: `All Versions`
 - Devide Manufacturer: `All manufacturers`
 - Device Name: `All Devices`
 
###### Reproduction Steps
 1. Stage a video
 2. Stage Another video

###### Expected Result
Video should play properly by showing all details correctly

###### Actual Result
Progress bar keeps loading bit video starts to play. End time is displayed as -:-

PS: I have tried debugging, this happens only when duration param of setDuration method is -ve.

Also if we click on the seek bar then the video gets played correctly, also when the video is staged seek bar will be at the end of video and not at the start. 

Please let me know if I am missing something and also please let us know possible solution or work around for the same.

**Comment by brianwernick** [comment]
This is part of #454

**Comment by keshav1139** [comment]
@brianwernick  Can we have some work around for time being?
