### ISSUE TITLE
Video Flickers for few seconds when layout is changed

### ISSUE THREAD

**Issue by keshav1139** [brianwernick/ExoMedia#568]
- [ ] I have verified there are no duplicate active or recent bugs, questions, or requests

###### Include the following:
 - ExoMedia version: `4.1.0`
 - Device OS version: `All Versions`
 - Devide Manufacturer: `All Manufacturers`
 - Device Name: `All Devices`
 
My Scenario is as stated below:

I have to FrameLayouts MainLayout and Mini Layout, Initially when the video is staged it will be in the Main layout and another item will be in mini layout. When user clicks on mini layout, item present in mini layout will be shifted to Main Layout and video comes back to mini layout.

Both Mini layout and Main layout have recycler views as their children.

Every thing is working fine, but when user clicks on the video when it is in mini layout it starts to flicker, and this flickering is seen for few seconds. Again when clicks on the video same behavior is seen.

Code for shifting view from Main Layout to mini Layout:
```
View temp = mainLayout.getChildAt(0);
mainLayout.removeViewAt(0);
View miniChild = miniLayout.getChildAt(0);
layoutTag = miniChild.getTag().toString();
miniLayout.removeViewAt(0);
mainLayout.addView(miniChild);
 miniLayout.addView(temp);
```

###### Reproduction Steps
1. Play  a video
2. change the position of video
3. Click on video    

###### Expected Result
Video controls must be displayed

###### Actual Result
Video controls are displayed but video flickers

Please let me know If I am missing something, so that I can fix this issue.

**Comment by brianwernick** [comment]
This sounds like an issue somewhere in the app or related to the backing implementation of the video view. Have you tried using the texture view backing?

**Comment by keshav1139** [comment]
@brianwernick No I have not tried that. I will have to change every where if I try to use texture view at this point. Please do let us know if you know any solution.
