### ISSUE TITLE
Is it possible to keep the preview image in the player rather than hiding upon media loaded

### ISSUE THREAD

**Issue by liveaffiliates** [brianwernick/ExoMedia#572]
I commented on the other thread where the preview image is not showing at all. Currently it is not working in both emulator(Nexus 5), Cubot zorro 100 and Wiko Tommy 2.

Comment here:
https://github.com/brianwernick/ExoMedia/issues/35

But when i worked out what how to get it working. Is it possible to keep the preview image in the player and not hide it, for example when you are playing audio only.

Thanks

**Comment by brianwernick** [comment]
I've locked the other thread as it's well over a year old and that issue was resolved, so I've quoted what you wrote there
> Hi, This is still not working.
> 
> This is my code:
> 
> videoView = findViewById(R.id.video_view);
> videoView.setPreviewImage(Uri.parse(downloadedAlarmToPlay.getAlarmPackImageLocation()));
> videoView.setVideoURI(Uri.parse(downloadedAlarmToPlay.getAlarmMediaLocation()));
> Log.d("Chex ", "image = " + downloadedAlarmToPlay.getAlarmPackImageLocation());
> videoView.setOnPreparedListener(this);
> 
> I checked the image link and it is fine. Is there maybe only certain image formats maybe?
> 
> It just gives a black screen and the loading icon and then the music starts (it is not a video would that make a difference?) .
> 
> Thanks

**Comment by brianwernick** [comment]
Using the `VideoView` to play just audio is pretty heavy as it attaches to the surface. I recommend using the `AudioPlayer` instead and using different controls or if you really want the same controls you can extend `VideoControls` and override `updateProgress()`, `onAttachedToWindow()`, and provide a custom `InternalListener` that handles the `AudioPlayer` instead.

That being said, the `VideoControls` don't control the preview image so has no affect on it. If you want to prevent the image from being hidden under certain circumstances you will need to extend `VideoView` and provide a custom [`MuxNotifier`](https://github.com/brianwernick/ExoMedia/blob/master/library/src/main/java/com/devbrackets/android/exomedia/ui/widget/VideoView.java#L910) that overrides [`onPreviewImageStateChanged(boolean)`](https://github.com/brianwernick/ExoMedia/blob/master/library/src/main/java/com/devbrackets/android/exomedia/ui/widget/VideoView.java#L964)

**Comment by liveaffiliates** [comment]
Hi,

Thanks for responding so quickly and thanks for the recommendations, I will study your recommendations to try and find the best solution . In my case I am sometimes opening video and sometimes audio. These can also be from either a local source or from a url. So I was hoping to use one implementation for all of them but if it works better using the audio and video players I will change it. 

I am still puzzled why the preview is not showing up at all on, am I doing something wrong in the code?

**Comment by liveaffiliates** [comment]
I got it working by setting creating a bitmap first and then setting the preview with a bitmap.

`private void setupVideoView() {
        videoView = findViewById(R.id.video_view);
        videoView.setScaleType(ScaleType.CENTER_CROP);
        videoView.setOnPreparedListener(this);
        videoView.showControls();

        Picasso.with(this)
                .load(downloadedAlarmToPlay.getAlarmPackImageLocation())
                .into(new Target() {
                    @Override
                    public void onBitmapLoaded(Bitmap bitmap, Picasso.LoadedFrom from) {
      
                        videoView.setVideoURI(Uri.parse(downloadedAlarmToPlay.getAlarmMediaLocation()));
                    }

                    @Override
                    public void onBitmapFailed(Drawable errorDrawable) {
                        videoView.setVideoURI(Uri.parse(downloadedAlarmToPlay.getAlarmMediaLocation()));
                    }

                    @Override
                    public void onPrepareLoad(Drawable placeHolderDrawable) {
                    }
                });
    }`
