### ISSUE TITLE
Udp Uri Support

### ISSUE THREAD

**Issue by MustajabJafry** [brianwernick/ExoMedia#574]
Will there ever be support for **Udp** links in **exoplayer**?

I have tried number of players like **vitamio**, **vlc** and default **android video player**, but the stream causes lag and sometimes stream disconnects.

Please help.

**Comment by brianwernick** [comment]
The ExoPlayer has support for UDP in some of the extension libraries where the media format supports it (e.g. https://github.com/google/ExoPlayer/tree/release-v2/extensions/rtmp). However, if you are having frame drops and eventually disconnects it's probably the source server having issues or your network and not the player.

**Comment by MustajabJafry** [comment]
The source server has no issues. I am using android box to play udp stream. With android native player the stream is smooth and there are no frame drops on one box, while on the other box it causes problem. With vlc player both boxes cause problem. So I am not pretty sure whether the issue lye in the player or maybe the hardware of the box does not support the codecs with which the source stream has been coded.
