### ISSUE TITLE
Status Bar not showing up when double tapping on sample

### ISSUE THREAD

**Issue by bernaferrari** [brianwernick/ExoMedia#575]
I am having the following problem, which is reproducible in the sample and, while a different issue, gives the same effect as #392:

![screenshot_20180307-220707](https://user-images.githubusercontent.com/351125/37129425-b541a392-225d-11e8-909a-2d5821f9b2c5.png)

How to reproduce:
- play a video in landscape mode
- tap to hide the controls
- wait like 0.2 seconds and before the statusbar is hidden, tap again to show it (try again if needed)
- the controls will show up, the status bar will not 😭

**Comment by brianwernick** [comment]
This isn't a library issue rather an issue with the triggering of the OS UI visibilities in the demo app. I'll look in to it when I get a chance but it's pretty low priority

**Comment by bernaferrari** [comment]
Sure, might even be a bug on android itself, this was the best place I found to see if there was a solution. Thanks!!

**Comment by brianwernick** [comment]
This is fixed in the Demo app with https://github.com/brianwernick/ExoMedia/commit/0759ff51b5603f6827ca613af788f4a245aa6407

**Comment by bernaferrari** [comment]
Really awesome!! Thanks!!!
