### ISSUE TITLE
Play living stream

### ISSUE THREAD

**Issue by dannyZhou** [brianwernick/ExoMedia#578]
https://github.com/brianwernick/ExoMedia/blob/9f151d903609c7514269f32b75d1eb84533613eb/demo/src/main/java/com/devbrackets/android/exomediademo/App.java#L82

Because of cache, living stream will have bug.

**Comment by brianwernick** [comment]
It shouldn't unless the client is using it incorrectly. It's more likely that `LoadControl` has a min-buffer size specified that is larger than what you want. If it is causing issues with your live streaming then just don't include the `CacheDataSourceFactory` in your implementation
