### ISSUE TITLE
Set using TextureView or SurfaceView programmatically.

### ISSUE THREAD

**Issue by bene25** [brianwernick/ExoMedia#580]
Hello. Are there way to set using TextureView or SurfaceView programmatically?

**Comment by brianwernick** [comment]
Because of the way the `VideoView` handles inflation and attaching to the surface there isn't currently a way to programmatically specify if it should use a `SurfaceView` or `TextureView` backing.

**Comment by bene25** [comment]
Thanks. Because on old android devices we have "pixalated" channels. And looks like setting surface view in this cases helps. So we want to set it depend on SDK version. Or maybe you suggest something else:)

**Comment by brianwernick** [comment]
You can use separate layouts for older android devices (e.g. `layout-v16` and `layout-v21`)

**Comment by bene25** [comment]
Thanks! And how I can make surfaceView to fitXY?

**Comment by brianwernick** [comment]
See #465 for the fitXY, however in short it won't work correctly with the SurfaceView :(
