### ISSUE TITLE
Redirections (302)

### ISSUE THREAD

**Issue by vinecole27** [brianwernick/ExoMedia#581]
I am experiencing exactly same issue with https://github.com/google/ExoPlayer/issues/1190
but I am not sure how to pass allowCrossProtocolRedirects=true to the DefaultUriDataSource constructor.
Can you help?

**Comment by brianwernick** [comment]
You can specify a DataSourceProvider with [`ExoMedia#setDataSourceFactoryProvider()`](https://github.com/brianwernick/ExoMedia/blob/master/library/src/main/java/com/devbrackets/android/exomedia/ExoMedia.java#L94) that provides your customized data source that handles cross origin and cross protocol redirects

**Comment by vinecole27** [comment]
@brianwernick I am only using AudioPlayer class

**Comment by brianwernick** [comment]
That doesn't matter, the [`ExoMedia#setDataSourceFactoryProvider()`](https://github.com/brianwernick/ExoMedia/blob/master/library/src/main/java/com/devbrackets/android/exomedia/ExoMedia.java#L94) will affect both the `AudioPlayer` and `VideoView`

**Comment by vinecole27** [comment]
Can you write the code here how to do that?

**Comment by vinecole27** [comment]
```
ExoMedia.setDataSourceFactoryProvider(new ExoMedia.DataSourceFactoryProvider() {
            @NonNull
            @Override
            public DataSource.Factory provide(@NonNull String userAgent, @Nullable TransferListener<? super DataSource> listener) {
                
            }
        });

```
@brianwernick How to handle cross origin and protocol redirects here?

**Comment by vinecole27** [comment]
@brianwernick Thanks a lot!! it worked!!
