### ISSUE TITLE
I am with this problem:

### ISSUE THREAD

**Issue by oseiasmribeiro** [brianwernick/ExoMedia#584]
- [ ] I have verified there are no duplicate active or recent bugs, questions, or requests

###### Include the following:
 - ExoMedia version: `4.1.0`
 
###### Reproduction Steps
 0.  
![image](https://user-images.githubusercontent.com/36827173/37876534-0f1fab2e-3024-11e8-99f8-62dffe6b0850.png)

**Comment by oseiasmribeiro** [comment]
Solved!

**Comment by brianwernick** [comment]
`ExoMedia` has a transitive dependency on `ExoPlayer` (`2.6.0` for ExoMedia `4.1.0). There are some breaking changes in ExoPlayer `2.7.0` so you'll need to remove the explicit ExoPlayer dependency
