### ISSUE TITLE
Play UDP / Multicast stream / MPEG2TS ?

### ISSUE THREAD

**Issue by voipworld** [brianwernick/ExoMedia#595]
- [ ] I have verified there are no duplicate active or recent bugs, questions, or requests

###### Include the following:
 - ExoMedia version: `4.1.0`
 - Device OS version: `5.1.1`
 - Devide Manufacturer: `Brondt`
 - Device Name: `Smart TV (32 Inch)`
 
###### Reproduction Steps
 0.  stream any video using ffmpeg to a multicast address, better to be pre-ancoded to H.264/AAC, or also MPEG2 Video / MPEG2 audio (both case), using: ffmpeg -re -i video_file.mp4 -acodec copy -vcodec copy -f mpegts udp://@239.100.0.0:1234 / then play the output stream using exo player.

###### Expected Result
video should play, like using vlc or ffmpeg based player
###### Actual Result
udp prefix not recognised+

**Comment by brianwernick** [comment]
I have plans (undocumented plans) to update the media source providers to correctly handle prefixes which will be needed for things like RTSP (prefix) as well. I'm not sure when I'll get to this yet, I'll update the Milestone when I have more details

**Comment by brianwernick** [comment]
The uri scheme (prefix) handling was added in https://github.com/brianwernick/ExoMedia/commit/1b3d652c5e4f32d33e27550cd0f24072ff9ccbe2

**Comment by OLIMUTH** [comment]
The Exoplayer  Play the   UDP video only.can not play audio how to do  that.
