### ISSUE TITLE
Enable/Disable player notification controls

### ISSUE THREAD

**Issue by DEx2Uk** [brianwernick/ExoMedia#596]
Hi @brianwernick ,

I have a question. Is there any possible way to enable/disable player controls within notification? Such as disable previous/next. Also how can we invoke activity on notification click? 

 - ExoMedia version: `4.1.0`
 - Device OS version: `8.0`
 - Devide Manufacturer: `OnePlus`
 - Device Name: `OP 3T`

**Comment by brianwernick** [comment]
`ExoMedia` doesn't provide any notification support; the demo app uses a library called `PlaylistCore` to handle the notifications, etc. You should look at that repository and if you still have a question ask it there instead
