### ISSUE TITLE
Release schedule

### ISSUE THREAD

**Issue by RedshirtMB** [brianwernick/ExoMedia#597]
With the recent dependency updates I'd love to see another release. I know I can clone the repo and just add the .aar as a library module but I'd prefer to not add the extra module to my project. Thanks, and keep up the good work.

**Comment by brianwernick** [comment]
I'm hoping to get an updated release out soon that fixes some of the bugs in the current version and update dependencies. I would also love to get some of the feature requests in but that might have to wait for a later release

**Comment by brianwernick** [comment]
`4.2.0` was just released
