### ISSUE TITLE
blank screen

### ISSUE THREAD

**Issue by 1242128273wangpeng** [brianwernick/ExoMedia#598]
Include the following:
 - ExoMedia version: `4.1.0`
 - Device OS version: `6.0`，`7.0`
 - Device Name: `Meitu T8(6.0)`，`MEIZU PRO 7 Plus(7.0)`

But HUIWEI (8.0) not happen this problem

Reproduction Steps
I download the ExoMedia demo,and run it,  I got same problem
Steps：
play a video wait a minutes than click button to pause，
then click home,
than reopen the app, 
now you will got a blank screen 。 
Activity Lifecycle :
onResume-->onPause-->onResume
                                                                                     
How to solve the problem which screen is blank?

[log.txt](https://github.com/brianwernick/ExoMedia/files/1898886/log.txt)

**Comment by brianwernick** [comment]
See #345

**Comment by impeterwayne** [comment]
i got this same error, please help me
