### ISSUE TITLE
Multiple exomedia player streams in one Activity not working

### ISSUE THREAD

**Issue by thesultanster** [brianwernick/ExoMedia#599]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests

###### Include the following:
 - ExoMedia version: `4.1.0`
 - Device OS version: `8.0`
 - Devide Manufacturer: `Samsung`
 - Device Name: `S9`
 
###### Reproduction Steps
I have inflated two fragments in one activity. Each one of them is supposed to stream a video. However only one of them works at a time.

**Comment by brianwernick** [comment]
What is your setup process, layout, etc.
