### ISSUE TITLE
ScaleType.FIT_XY

### ISSUE THREAD

**Issue by iospoisson** [brianwernick/ExoMedia#605]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests

###### Include the following:
 - ExoMedia version: `4.1.0`
 - Device OS version: `8.0`
 - Devide Manufacturer: `Samsung`
 - Device Name: `Note8`
 
###### Reproduction Steps
 0.  

###### Actual Result

I manage to play the live video 4:3 to fit the screen however this is happen only on landscape when i turn around the phone.This is the code i am using    

public class ActivityStreaming extends Activity implements OnPreparedListener {

    private long exitTime = 0;
    private VideoView videoView;
    String url;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

        this.getWindow().setFlags(WindowManager.LayoutParams.FLAG_FULLSCREEN, WindowManager.LayoutParams.FLAG_FULLSCREEN);
        setContentView(R.layout.activity_streaming);

        url = getIntent().getStringExtra("url");

        videoView = (VideoView) findViewById(R.id.video_view);
        videoView.setOnPreparedListener(this);

        Uri videoUri = Uri.parse(url);
        videoView.setVideoURI(videoUri);
        videoView.setMeasureBasedOnAspectRatioEnabled(false);
        videoView.setScaleType(ScaleType.FIT_XY);

    }

    @Override
    public void onPrepared() {
        //Starts the video playback as soon as it is ready
        videoView.start();

    }

    public void onBackPressed() {
        super.onBackPressed();
    }

    public void closeStreaming() {
        if ((System.currentTimeMillis() - exitTime) > 2000) {
            Toast.makeText(this, getString(R.string.press_again_to_close_streaming), Toast.LENGTH_SHORT).show();
            exitTime = System.currentTimeMillis();
        } else {
            finish();
        }
    }

}

**Comment by brianwernick** [comment]
See #465
