### ISSUE TITLE
SeekBar progress

### ISSUE THREAD

**Issue by YogevUzan** [brianwernick/ExoMedia#606]
Hi, I'm developing a music app that plays songs from the device.

- [ ] I have verified there are no duplicate active or recent bugs, questions, or requests

###### Include the following:
 - ExoMedia version: `4.0.0`
 - Device OS version: `7.0`
 - Devide Manufacturer: `Samsung`
 - Device Name: `Galaxy S6`
 
###### Reproduction Steps
 0.  Video gets downloaded from the internet.
 1. The video is added to "Favorite List".
 2. I'm using a RecyclerView to populate the list.

Everything works fine, except when sometimes I double click an item and instead of showing the video length, it shows " --.-- " ,  And the SeekBar is at its maximum.

To play a video I'm using this:
mVideoView.setVideoURI(Uri.parse(context.getExternalCacheDir() + videoPath));

###### Expected Result
The player is supposed to show the video length.

###### Actual Result
![image](https://user-images.githubusercontent.com/37194910/39245899-af095248-489d-11e8-8795-7f3e79638172.png)

**Comment by brianwernick** [comment]
Please include the information requested in the issue template, otherwise we can't help

**Comment by YogevUzan** [comment]
Fixed. Wasn't aware of that.

**Comment by brianwernick** [comment]
Posting an intent doesn't have any affect on the duration determination. What is the log output when you see this issue?

**Comment by YogevUzan** [comment]
Obviously it shouldn't, but somehow it does...
I don't see anything special in the log, it just happens

**Comment by YogevUzan** [comment]
Ok, my bad... it still happens... not sure why tho.

**Comment by brianwernick** [comment]
Is there a reason you are using `4.0.0` instead of `4.1.0`? There were bugfixes around duration determination in the `ExoPlayer` version updated to (`2.6.0`) in the `4.1.0` release

**Comment by YogevUzan** [comment]
4.0.0 is the default version in the template, so I thought it's updated and I kept it this way. 
I'm using 4.1.0.

**Comment by brianwernick** [comment]
What format is the media in (e.g. `.mp4`) that you see this issue with?

**Comment by YogevUzan** [comment]
.mp4

**Comment by YogevUzan** [comment]
If i'm not mistaken, the demo app streams videos from the internet and I'm loading videos from the app cache folder. Maybe that's where the issue is...

**Comment by brianwernick** [comment]
Oh, right, let me see if that makes a difference

**Comment by YogevUzan** [comment]
After 4.2.0 update that issue is gone. Great! Thanks.
