### ISSUE TITLE
Video getting stretched

### ISSUE THREAD

**Issue by ravirajjak** [brianwernick/ExoMedia#608]
- [ ] I have verified there are no duplicate active or recent bugs, questions, or requests

###### Include the following:
 - ExoMedia version: `4.0.0`
 - Device OS version: `7.0`
 - Devide Manufacturer: `Samsung `
 - Device Name: `S7 Edge`
 
###### Reproduction Steps
 0. Play Portrait Video in Video View

###### Expected Result
It Should play portrait video not to stretched

###### Actual Result
It is getting stretched

**Comment by brianwernick** [comment]
See #465
