### ISSUE TITLE
There is nothing any listener like video player stop, pause etc for VideoView. I am using implementation 'com.devbrackets.android:exomedia:3.0.0-preview1' dependency 

### ISSUE THREAD

**Issue by lagadpankaj** [brianwernick/ExoMedia#614]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests

###### Include the following:
 - ExoMedia version: `4.0.0`
 - Device OS version: `7.0`
 - Devide Manufacturer: `Google`
 - Device Name: `Pixel XL`
 
###### Reproduction Steps
 0.

**Comment by brianwernick** [comment]
Update your library version.

Some of what you want can be found in the [listeners](https://github.com/brianwernick/ExoMedia/tree/master/library/src/main/java/com/devbrackets/android/exomedia/listener) package, otherwise see #257
