### ISSUE TITLE
Can we download hls video in mobile storage?

### ISSUE THREAD

**Issue by Waleedasim** [brianwernick/ExoMedia#615]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests

###### Include the following:
 - ExoMedia version: `4.0.0`
 - Device OS version: `7.0`
 - Devide Manufacturer: `Google`
 - Device Name: `Pixel XL`
 
###### Reproduction Steps
 0.

**Comment by brianwernick** [comment]
See #573
