### ISSUE TITLE
getAvailableTracks()  returning empty TrackGroupArray for RendererType VIDEO, even when tracks exist.

### ISSUE THREAD

**Issue by YugankaS** [brianwernick/ExoMedia#616]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests

###### Include the following:
 - ExoMedia version: `4.1.0`
 - Device OS version: `4.4`
 - Devide Manufacturer: `HTC`
 - Device Name: `Desire 526G Plus`
 
###### Reproduction Steps
 1. I have set videoView uri as - 

        videoView.setVideoURI(Uri.parse(url), new DashMediaSourceBuilder().build(context, Uri.parse
                (url), "some random string", null, null));  

2. Then, in onPrepared, I do this - 

        if (videoView.trackSelectionAvailable()) {

            Map<ExoMedia.RendererType, TrackGroupArray> tracks = videoView.getAvailableTracks();

            Log.e("tracks", " are " + tracks);

            for (ExoMedia.RendererType rendererType : tracks.keySet()) {

                TrackGroupArray trackGroupArray = tracks.get(rendererType);

                Log.e("Renderer", " is " + rendererType);
                Log.e("Length", " is " + trackGroupArray.length);

                for (int i = 0; i < trackGroupArray.length; i++) {
                    Log.e("Track " + rendererType.toString() + " " + i, "is " + trackGroupArray
                            .get(i).toString());
                }
            }
        }

###### Expected Result

I open the mpd link in an xml viewer and find this, among other things - 

![video tracks](https://user-images.githubusercontent.com/19201095/40238302-703c7726-5ad0-11e8-906c-da0e6ae5c871.png)

Meaning, that there are 5 video tracks.

###### Actual Result

...E/tracks:  are {CLOSED_CAPTION=com.google.android.exoplayer2.source.TrackGroupArray@1, AUDIO=com.google.android.exoplayer2.source.TrackGroupArray@4496699e, VIDEO=com.google.android.exoplayer2.source.TrackGroupArray@1}
...E/Renderer:  is CLOSED_CAPTION
...E/Length:  is 0
...E/Renderer:  is AUDIO
...E/Length:  is 1
...E/Track AUDIO 0: is com.google.android.exoplayer2.source.TrackGroup@4496697f
...E/Renderer:  is VIDEO
...E/Length:  is 0

Why is the getAvailableTracks() method returning an array size of 0 for RendererType VIDEO and not able to find the video tracks?

Also, I think you should mention in the docs that one should only call getAvailableTracks() after onPrepared, else it will cause an NPE.

**Comment by brianwernick** [comment]
See #541. You'll need to update your version to `4.2.0`

**Comment by YugankaS** [comment]
Thanks Brain, it is working in 4.2.0.

**Comment by YugankaS** [comment]
However, I am facing another issue here and hope you could help me.

The setTrack method needs a RendererType (no issue there) and a trackIndex.

Now, getAvailableTracks returns a map where the value is a TrackGroupArray, which has a length 1, and the 1st object is a TrackGroup which has a length of 5 (video tracks) in my case.

When I am calling setTrack and passing any value more than 0, I am getting an ArrayIndexOutofBoundsException and I think it is checking for the TrackGroupArray's length and not the length of TrackGroup.

Where am I going wrong?

**Comment by brianwernick** [comment]
The [`setSelectedTrack(...)`](https://github.com/brianwernick/ExoMedia/blob/master/library/src/main/java/com/devbrackets/android/exomedia/core/exoplayer/ExoMediaPlayer.java#L304) method isn't verifying the index itself so the Exception is coming from somewhere in the ExoPlayer. Would you mind posting the stack trace to help track down where it's actually going wrong as there might be something slightly incorrect with that method.

**Comment by YugankaS** [comment]
Hey, here is the stacktrace - 

 java.lang.ArrayIndexOutOfBoundsException: length=1; index=1
        at com.google.android.exoplayer2.source.TrackGroupArray.get(TrackGroupArray.java:64)
        at com.google.android.exoplayer2.trackselection.DefaultTrackSelector.selectTracks(DefaultTrackSelector.java:1199)
        at com.google.android.exoplayer2.trackselection.MappingTrackSelector.selectTracks(MappingTrackSelector.java:383)
        at com.google.android.exoplayer2.MediaPeriodHolder.selectTracks(MediaPeriodHolder.java:162)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.reselectTracksInternal(ExoPlayerImplInternal.java:987)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:325)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by shenzhen2017** [comment]
same Problem

**Comment by brianwernick** [comment]
Sorry for the long delay, I've been pretty busy lately :(

It looks like there's something with the `SelectionOverride` logic that doesn't quite match what is expected; specifically on line [314](https://github.com/brianwernick/ExoMedia/blob/master/library/src/main/java/com/devbrackets/android/exomedia/core/exoplayer/ExoMediaPlayer.java#L314). I'll try to look in to this in the next few days to get a patch pushed out.

**Comment by brianwernick** [comment]
I've added a new method [setTrack(RenderType, int, int)](https://github.com/brianwernick/ExoMedia/blob/master/library/src/main/java/com/devbrackets/android/exomedia/ui/widget/VideoView.java#L679) that correctly allows you to specify the group index in the `TrackGroupArray`. If you use the old `setTrack(RenderType, int)` method it will default to `0` for the group index which might not be what you want.
