### ISSUE TITLE
AudioFocus

### ISSUE THREAD

**Issue by YogevUzan** [brianwernick/ExoMedia#620]
- [ ] I have verified there are no duplicate active or recent bugs, questions, or requests

###### Include the following:
 - ExoMedia version: `4.2.0`
 - Device OS version: `7.0`
 - Devide Manufacturer: `Samsung`
 - Device Name: `Galaxy S6`
 
###### Reproduction Steps
 Everytime I receive a phone call or even sometimes when I watch Facebook videos, the song continues to play.
I've read the documentation of "setHandleAudioFocus" and I must note that I'm not using a service to handle the playback.

###### Actual Result
ExoMedia does not handle the focus loss correctly.

**Comment by brianwernick** [comment]
The `VideoView` will handle audio focus for you however the `AudioPlayer` won't. You need to handle the audio focus yourself (and should for the `VideoView` as well since you will know your requirements)
