### ISSUE TITLE
Show loading progress when video is buffering 

### ISSUE THREAD

**Issue by IOException722** [brianwernick/ExoMedia#623]
I have gone through all the somewhat related issue and implemented ExoPlayerListener which have interface `onStateChanged(boolean playWhenReady, int playbackState) `  but this overridden method doesn't get called when the video is buffering so not able to show loading when the video is buffering.

I have gone through all the issue didn't find any correct solution.

Could you please tell me if buffering state has been implemented in ExoMedia 4.2.1 version and how to use it (if implemented)?

- [x] I have verified there are no duplicate active or recent bugs, questions, or requests

###### Include the following:
 - ExoMedia version: `4.2.1`
 - Device OS version: `8.0`
 - Devide Manufacturer: `Hongkong based company`
 - Device Name: `Infinix hot s3`
 
###### Reproduction Steps
 I have disabled default controls and added custom control in the video layout. For example custom button for pause, resume , restart e.t.c

**Comment by brianwernick** [comment]
See #102

**Comment by IOException722** [comment]
Just wanted to know whether this is implemented in 4.2.1 and how to use it. it would be great if you can give some brief idea.

Cannot get enough idea whether this is implemented in 4.2.1 or not and if it is implemented how can I use it?

**Comment by Jaydeepbhayani** [comment]
how to add custom control?

**Comment by Jaydeepbhayani** [comment]
how to add custom control?
