### ISSUE TITLE
AndroidX / JetPack Incompatibility

### ISSUE THREAD

**Issue by MrAnima** [brianwernick/ExoMedia#624]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests

###### Include the following:
 - ExoMedia version: `4.2.1`
 - Android Studio version: `3.1.2`
 - compileSdkVersion: '`android-P`'
 - JetPack (androidx & jetifier enabled)
 
###### Reproduction Steps
 0.  Include _ExoMedia_ in an 'android-P' project
 1.  Sync
 2.  Copy the demo code in the Readme
 3.  Compile & Run

The compilation fails with the following error:
```
Program type already present: android.support.v4.app.INotificationSideChannel$Stub$Proxy
Message{kind=ERROR, text=Program type already present: android.support.v4.app.INotificationSideChannel$Stub$Proxy, sources=[Unknown source file], tool name=Optional.of(D8)}
```

**Comment by brianwernick** [comment]
While I have plans on migrating to the AndroidX package I don't think it's quite time. The error you are getting looks more like a generic jetifier issue (I'm surprised it works in AS 3.1.2 at all, I thought it was a 3.2 + only mechanism). 
I'll keep the issue open as a way to track the migration to AndroidX

**Comment by MrAnima** [comment]
Okay, thanks for the quick reply. I'll try to find an alternative that supports HLS :thumbsup:

**Comment by hellenxu** [comment]
Me, too. Have this issue when trying to migrate to AndroidX.

**Comment by aemssid** [comment]
I have this issue too. Using trying to migrate to AndroidX

**Comment by hansenji** [comment]
My fix for this issue was moving all of my support libraries directly referenced in my build.gradle to androidX. After that a clean build and the problem went away. My team has been successfully migrating projects using ExoMedia since September.

**Comment by gopal-fp** [comment]
+1

**Comment by eygraber** [comment]
Please update to use androidx dependencies. This library is the only thing preventing us from turning off jetifier.
