### ISSUE TITLE
Listeners (ExoPlayerListener ,VideoControlsSeekListener,OnBufferUpdateListener, OnSeekCompletionListener) are not getting called

### ISSUE THREAD

**Issue by IOException722** [brianwernick/ExoMedia#626]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests

###### Include the following:

ExoMedia version: 4.2.1
Device OS version: 8.0
Devide Manufacturer: Hongkong based company
Device Name: Infinix hot s3

I have implemented interfaces like `ExoPlayerListener ,VideoControlsSeekListener,OnBufferUpdateListener, OnSeekCompletionListener` in my android app. But it's not getting called in any scenarios in the implemented methods below.

 These are methods above interfaces implements
```
  @Override
    public void onSeekComplete() {
        Log.d(TAG, "On Seek Complete");
    }

    @Override
    public void onBufferingUpdate(int percent) {
        Log.d(TAG, "Buffering % "+ percent);

    }

    @Override
    public boolean onSeekStarted() {
        Log.d(TAG, "on seek started");
        return false;
    }

    @Override
    public boolean onSeekEnded(long seekTime) {
        Log.d(TAG, "on seek end");
        return false;
    }

    @Override
    public void onStateChanged(boolean playWhenReady, int playbackState) {

        Log.d(TAG, "On state change");
    }

    @Override
    public void onError(ExoMediaPlayer exoMediaPlayer, Exception e) {
        Log.d(TAG, "On error");
    }

    @Override
    public void onVideoSizeChanged(int width, int height, int unAppliedRotationDegrees, float pixelWidthHeightRatio) {
        Log.d(TAG, "on video size changed");
    }
```
But non of the above log gets printed.

###### Reproduction Steps
1.    This line of code `videoView.seekTo(stopPosition+resumeTime-pausedTime);` does not call any of the above impmented methods of listeners interfaces but video seeks work(Current video playing time gets increases )
2. When video is frozen due to low internet and restart after few seconds
3. When coming from background to foregound , video freeze for few second then video restart

###### Expected Result

In all above three cases ,neither of the implmented methods of above interfaces /listeners gets called.

###### Actual Result
Listeners are not working as expected

**Comment by brianwernick** [comment]
How are you registering the listeners? Some of them (e.g. `ExoPlayerListener`) are used internally so would be more difficult to register and would break some other functionality by overwriting an expected listener. We should be using the listeners under `com.devbrackets.android.exomedia.listener.*`. As far as the rebuffering goes, see #102
