### ISSUE TITLE
How to add a single audio and get a playlist

### ISSUE THREAD

**Issue by cmz-one** [brianwernick/ExoMedia#627]
playlistManager.setParameters() can add audio list，
But if i just add a audio to the playlist, What should I do？

And，How do I get a playlist？

**Comment by cmz-one** [comment]
I mean add an one audio to an existing playlist

**Comment by brianwernick** [comment]
`ExoMedia` doesn't handle the functionality for playlists, what you are referencing is [PlaylistCore](https://github.com/brianwernick/PlaylistCore) and should open a ticket there instead
