### ISSUE TITLE
Callback on manifest refresh

### ISSUE THREAD

**Issue by bartoszwilk** [brianwernick/ExoMedia#629]
I wanted to ask you what is the best way to be notified about manifest refresh?
Previously there was a callback onTimelineChanged in ExoMediaPlayer, which you have purposefully left overridden as blank (you deleted it in commit 735e92ff83ce63baf52e2db23e51d3a4dc4e36ed for the sake of default implementation in DefaultEventListener).
Why you decided not to pass onTimelineChanged along with all other events out of VideoView component? 
Do you know any better solution to be notified before/after manifest is refreshed?
What was the purpose of leaving onTimelineChanged blank?

I will briefly describe my case to be 100% clear.
I want to set an extra cookie before each manifest reload event so that exoplayer will use it with the the next network call for manifest.

**Comment by brianwernick** [comment]
The `DefaultEventListener` already handles No-Oping of the `onTimelineChanged` and other events which you can still access as you would previously. In your case though you might want to look at using OkHttp with a network interceptor to handle the cookie additions instead
