### ISSUE TITLE
ExoPlayer extensions support

### ISSUE THREAD

**Issue by httpdispatch** [brianwernick/ExoMedia#632]
The constructor used in the `RendererProvider` is absent in the actual exoplayer extensions so they can't be used without the code modification.

https://github.com/brianwernick/ExoMedia/blob/5d36323f83c36cb7e494da9bbfaca90b4327a8a4/library/src/main/java/com/devbrackets/android/exomedia/core/renderer/RendererProvider.java#L114

https://github.com/google/ExoPlayer/blob/release-v2/extensions/opus/src/main/java/com/google/android/exoplayer2/ext/opus/LibopusAudioRenderer.java#L48-L51

https://github.com/google/ExoPlayer/blob/release-v2/extensions/flac/src/main/java/com/google/android/exoplayer2/ext/flac/LibflacAudioRenderer.java#L45-L48

**Comment by brianwernick** [comment]
This was updated with the re-organization of the render providers and/or ExoPlayer version update
