### ISSUE TITLE
Unable to setAudio Track

### ISSUE THREAD

**Issue by Muvidevlopers** [brianwernick/ExoMedia#639]
- [ ] I have verified there are no duplicate active or recent bugs, questions, or requests

I am able to get that there are 4 audiotracks in the video, but when the audio index is set using setTrack, the audio is not changed. 

###### Include the following:
 -  exoPlayerVersion = "2.8.1"
 - Device OS version: `7.0`
 - Devide Manufacturer: `Google`
 - Device Name: `Pixel XL`
 
###### Reproduction Steps
videoView.setOnPreparedListener(new OnPreparedListener() {
            int ii= 0, audioTrackIndex= 0 ;
            @Override
            public void onPrepared() {
                if (emVideoView.trackSelectionAvailable()) {
                    Map<ExoMedia.RendererType, TrackGroupArray> tracks =
                            emVideoView.getAvailableTracks();
                    Log.e("tracks", " are " + tracks);
                    for (ExoMedia.RendererType rendererType : tracks.keySet()) {
                        TrackGroupArray trackGroupArray = tracks.get(rendererType);
                        Log.e("Renderer", " is " + rendererType);
                        Log.e("Length", " is " + trackGroupArray.length);
                        if (rendererType.equals("AUDIO")){
                            audioTrackIndex= ii;
                        }else{
                            ii++;
                        }
                        for (int i = 0; i < trackGroupArray.length; i++) {
                            Log.e("Track " + rendererType.toString() + " " + i, "is " + trackGroupArray.get(i).toString());
                        }
                    }
                }
                videoView.setTrack(ExoMedia.RendererType.AUDIO,audioTrackIndex,3);
                videoView.start();
            }
        });

###### Expected Result
I am able to get from the output that there are 4 audio tracks but when any of the index is set in setTrack, the audio is not changed. 

###### Actual Result
E/tracks: are {CLOSED_CAPTION=com.google.android.exoplayer2.source.TrackGroupArray@1, AUDIO=com.google.android.exoplayer2.source.TrackGroupArray@cba2fa17, METADATA=com.google.android.exoplayer2.source.TrackGroupArray@1, VIDEO=com.google.android.exoplayer2.source.TrackGroupArray@3e5dbb15} 
E/Renderer: is CLOSED_CAPTION 
E/Length: is 0 
E/Renderer: is AUDIO 
E/Length: is 4 
E/Track AUDIO 0: is com.google.android.exoplayer2.source.TrackGroup@2c5aaa67 
E/Track AUDIO 1: is com.google.android.exoplayer2.source.TrackGroup@1b159a8d 
E/Track AUDIO 2: is com.google.android.exoplayer2.source.TrackGroup@f557c05c 
E/Track AUDIO 3: is com.google.android.exoplayer2.source.TrackGroup@deff83ec 
E/Renderer: is METADATA 
E/Length: is 0 
E/Renderer: is VIDEO 
E/Length: is 1 
E/Track VIDEO 0: is com.google.android.exoplayer2.source.TrackGroup@3e5dbaf6

**Comment by brianwernick** [comment]
Version `2.8.1` is no longer supported, please update to the most recent version (`4.2.2`) and see #616 for more information.
