### ISSUE TITLE
Adding exomedia to dependencies causes errors

### ISSUE THREAD

**Issue by jorgegil96** [brianwernick/ExoMedia#64]
When i add 

    compile 'com.devbrackets.android:exomedia:2.5.0'  

 to my dependencies in gradle it causes xml theme errors:  

    Error:(2) Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Inverse'.

    Error:(2) Error retrieving parent for item: No resource found that matches the given name 'android:Widget.Material.Button.Colored'.  

I'm using appcombat support library v7:22.2.1  and targeting SDK 22

Any idea of what's happening?

**Comment by brianwernick** [comment]
It's probably a support library version issue.  ExoMedia uses 23.1.1

**Comment by soshial** [comment]
Then this has to be written in documentation and main Github page of ExoMedia, doesn't it? I also encountered this problem.
