### ISSUE TITLE
Convert to Kotlin

### ISSUE THREAD

**Issue by brianwernick** [brianwernick/ExoMedia#643]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
Converting to Kotlin will help with maintainability of the library through simplified code and integrated nullability handling.

**Comment by jankowskib** [comment]
Hi, what's current state of the task?

**Comment by brianwernick** [comment]
I've gotten pretty far in to it, just going through and cleaning up a few things to be more idiomatic Kotlin
e.g.
```
if (listener != null) {
    listener.notify(something);
}
```
to
```
listener?.notify(something)
```

**Comment by jankowskib** [comment]
Thanks for update. Do you need help in development? I'd be glad to contribute the code if you're interested.

**Comment by brianwernick** [comment]
I would love some help, just let me get the initial Kotlin migration done and task out what is left more thoroughly. I'll let you know when that is ready :)

**Comment by brianwernick** [comment]
As an update, I'm still working on this just rather slowly; I'm hoping to get some time shortly (next few weeks) to focus on getting ExoMedia updated and in to a state for an 5.0 Alpha/Beta which includes this Kotlin Conversion. As I get that initial migration done I'll update this ticket; If you are still willing to help that would be great otherwise thanks for the offer

**Comment by jankowskib** [comment]
Yeah, I'm eager to help :)

**Comment by AllanWang** [comment]
I'm willing to help with Kotlin conversions as well :)

**Comment by brianwernick** [comment]
Thanks for the help and input everyone. Because we've merged the kotlin_transliteration branch I'm going to close this ticket knowing that as we progress towards the 5.0 release we'll be cleaning things up more and changing things (e.g. converting to kotlin delegation).
