### ISSUE TITLE
useTextureViewBacking blank screen

### ISSUE THREAD

**Issue by YogevUzan** [brianwernick/ExoMedia#644]
- [ ] I have verified there are no duplicate active or recent bugs, questions, or requests

###### Include the following:
 - ExoMedia version: `4.2.3`
 - Device OS version: `7.0`
 - Devide Manufacturer: `Samsung`
 - Device Name: `Galaxy S6`
 

Hey, I have a video that is looping in the background but it doesn't cover the whole screen, 
so I used "useTextureViewBacking=true" attribute and it fixed it. 
It worked very well until today, I started that activity and it showed a blank screen.  I haven't changed anything in that activity nor touched it since it's already finished.
when I delete that attribute everything works fine, but again, it doesn't cover my screen... I have tried it with multiple devices, I also tried to change a video but none of this works.

XML :
>    <com.devbrackets.android.exomedia.ui.widget.VideoView
>         android:id="@+id/vv_background"
>         android:layout_width="match_parent"
>         android:layout_height="match_parent"
>         app:useTextureViewBacking="true"/>

Code :
>         mBackgroundVideo.setVideoURI(Uri.parse("/android_asset/background_video.mp4"));
>         mBackgroundVideo.start();

**Comment by brianwernick** [comment]
Something must have changed. Did you update any dependencies, etc.?

**Comment by YogevUzan** [comment]
The only thing I changed is the compiled Sdk version from 27 to 28.
I tried changing that back but it didn't work, so I guess that's not the problem.
