### ISSUE TITLE
Player notification issue for android version oreo 8.1

### ISSUE THREAD

**Issue by VenkatReddyGlobussoft** [brianwernick/ExoMedia#646]
###### Include the following:
 - ExoMedia version: `r1.5.9`
 - playlistcore:1.1.1
 - Device OS version: `8.0 and 8.1 (oreo)`
 - Devide Manufacturer: `Google`
 
###### Reproduction Steps
   I have integrated https://github.com/brianwernick/ExoMedia/releases/tag/3.0.0 version and it' s working fine in oreo and showing player notification at the top while playing audio.
The same library version i have implemened in my demo project and when playing the audio file in oreo(8.1) getting crashed.

![player notificatio issue](https://user-images.githubusercontent.com/30926617/45140193-a6d31c80-b1cf-11e8-8aa9-dd1b8bb5c246.jpg)

**Comment by brianwernick** [comment]
ExoMedia 3.0 + doesn't handle the playlist, including the notifications. Make sure you are using the most up-to-date PlaylistCore; if you still have a problem open an issue on the PlaylistCore repository instead.
