### ISSUE TITLE
DataSourceException while playing RTP source

### ISSUE THREAD

**Issue by kaas3031** [brianwernick/ExoMedia#647]
- [ yes] I have verified there are no duplicate active or recent bugs, questions, or requests

###### Include the following:
 - ExoMedia version: `4.2.3`
 - Device OS version: `7.0`
 - Devide Manufacturer: `Motorola`
 - Device Name: `G5s+`
 
Hi i am receiving following error while try to play RTP source,
the same can be directly play with EXO-Player with 
```
DataSource.Factory udsf = new UdpDataSource.Factory() {
                        @Override
                        public DataSource createDataSource () {
                            return new UdpDataSource(null, 1024 * 20, 100000);
                        }
                    };
                    ExtractorsFactory tsExtractorFactory = new ExtractorsFactory() {
                        @Override
                        public Extractor[] createExtractors () {
                            return new TsExtractor[]{new TsExtractor(TsExtractor.MODE_SINGLE_PMT,
                                    new TimestampAdjuster(0), new DefaultTsPayloadReaderFactory())};
                        }
                    };


                    MediaSource videoSource = new ExtractorMediaSource
                            (uri, udsf, tsExtractorFactory, null, null);
```

but when i try to use Exo-media as following i am receiving exception
###### Reproduction Steps
 0.  
```
       videoView.setOnPreparedListener(new OnPreparedListener() {
            @Override
            public void onPrepared () {
                mSimpleExoPlayer.start();
            }
        });
        videoView.setVideoURI(uri);
```

###### Actual Result
Source error. com.google.android.exoplayer2.upstream.HttpDataSource$Http DataSourceException: Unable to connect to rtp://0.0.0.0:6001

**Comment by brianwernick** [comment]
ExoMedia doesn't include RTP support by default, you can either send in the `MediaSource` like you did for the ExoPlayer or you can register a new `MediaSourceProvider` as described in #566. The `MediaSourceProvider` was updated in https://github.com/brianwernick/ExoMedia/commit/1b3d652c5e4f32d33e27550cd0f24072ff9ccbe2 to allow specifying the uri scheme which in your case would be `rtp`
