### ISSUE TITLE
BufferQueue has been abbandoned

### ISSUE THREAD

**Issue by crazycoder1999** [brianwernick/ExoMedia#650]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests

###### Include the following:
 - ExoMedia version: `4.2.3` 
 - Device OS version: `8.0`
 - Devide Manufacturer: `Samsung`
 - Device Name: `Galaxy S7`
 
I have built an app with ExoMedia that play a playlist of video in a "**ConcatenatingMediaSource**": the video are from an https source.
I'm handling app rotation: when you rotate the screen also the videoview rotate, landscape(fullscreen) and portrait inside a fragment.

While the playlist is running, sometimes, randomly this error happens:

```
BufferQueueProducer: [SurfaceTexture-0-27306-98] queueBuffer: BufferQueue has been abandoned
09-14 15:09:42.102 27306-28880/com.standard E/Surface: queueBuffer: error queuing buffer to SurfaceTexture, -19
09-14 15:09:42.102 27306-28880/com.standard E/ACodec: [OMX.Exynos.avc.dec] BaseState::onOutputBufferDrained returning error -19
    signalError(omxError 0x80001001, internalError -19)
09-14 15:09:42.102 27306-28879/com.standard E/MediaCodec: Codec reported err 0xffffffed, actionCode 0, while in state 6
09-14 15:09:42.102 27306-28879/com.standard D/SurfaceUtils: disconnecting from surface 0x7b38621010, reason disconnectFromSurface
09-14 15:09:42.103 27306-28704/com.standard E/ExoPlayerImplInternal: Internal runtime error.
    java.lang.IllegalStateException
        at android.media.MediaCodec.native_dequeueInputBuffer(Native Method)
        at android.media.MediaCodec.dequeueInputBuffer(MediaCodec.java:2559)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.feedInputBuffer(MediaCodecRenderer.java:637)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:574)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:518)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:301)
        at android.os.Handler.dispatchMessage(Handler.java:101)
        at android.os.Looper.loop(Looper.java:164)
        at android.os.HandlerThread.run(HandlerThread.java:65)
```

If I do no rotation or very few rotation the video play normally.
I don't know if it is related to HOW I manage the rotation.. 
Any Idea about this error and why does it happen? 
thanks you

**Comment by brianwernick** [comment]
How are you handling device rotation? Is it any different from how the demo app is handling rotation?

**Comment by crazycoder1999** [comment]
I don't understand where you handle the rotation in the demo.
Can you please point me to the source code part?
Thanks you

**Comment by crazycoder1999** [comment]
ok, thanks you for the answer.
That's why it works in the demo version. 
My app in portrait mode have a complex layout: a recyclerview where each item can potentially play a video.
When you switch to landscape it become a fullscreen video app with the current video selected open.

The list is like a list of images. 
Each image have click event attached.
Once you click on one of the image, I anchor an instance of the videoview to replace the image clicked and start the playlist of the video.
If I rotate the phone in landscape , I detach the videoview from the list and attach it to the Window of the activity (to show it in fullscreen).
When I rotate back to portrait, I detach the videoview from the Window of the activity and attach again to the correct row of the recyclerview.

The videos load are a playlist. 
The playlist during play can change.

I don't know if the problem is related to this "attach" "detach" mechanism I used.
