### ISSUE TITLE
Manage power saving when phone is locked

### ISSUE THREAD

**Issue by Gregoirevda** [brianwernick/ExoMedia#654]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests

###### Include the following:
 - ExoMedia version: `4.2.3`
 - Device OS version: `8.0`
 - Devide Manufacturer: `Google`
 - Device Name: `Samsung`
 
###### Reproduction Steps
Set phone in 'Power saving' mode
Play audio
Lock screen
wait 20 seconds for streaming to be stopped

###### Expected Result
Music should continue playing

###### Actual Result
Music stops after 20 seconds

There should be an option for music not to stop playing even in 'Power saving' mode.

**Comment by brianwernick** [comment]
ExoMedia doesn't handle wake locks, services, etc. If you are looking for media to be played when the screen is locked look at [PlaylistCore](https://github.com/brianwernick/playlistcore)

**Comment by Gregoirevda** [comment]
`setWakeMode(context, PowerManager.PARTIAL_WAKE_LOCK)` has no effect then?

**Comment by brianwernick** [comment]
`setWakeMode` tells the CPU to not sleep when the screen is turned off but won't keep media playing in the background indefinitely. Additionally, there's things like `AudioFocus` and Notification control that's easier to manage with a service in addition to allowing the media to continue playing even if the application is closed (not just backgrounded).
