### ISSUE TITLE
Hi, how can I get the index of the selected track?

### ISSUE THREAD

**Issue by mrgaric** [brianwernick/ExoMedia#658]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests

###### Include the following:
 - ExoMedia version: `4.2.3`
 - Device OS version: `8.0`
 - Devide Manufacturer: `Google`
 - Device Name: `Pixel XL`
 
I'm wanted to get an index of the selected track. I find this method in the ExoMediaPlayer
`public int getSelectedTrackIndex(@NonNull RendererType type)`
Сould You add it in VideoView?

**Comment by brianwernick** [comment]
I feel like there was a reason that method wasn't piped through like the others... I don't remember why that is now so I'll add this as a task to pipe it up to the `VideoView`

**Comment by brianwernick** [comment]
I've added methods that will be in the next release
