### ISSUE TITLE
Building project issue with local library -> Update ExoPlayer to 2.9.0

### ISSUE THREAD

**Issue by bene25** [brianwernick/ExoMedia#659]
Hi, we have an issue while build project with ExoMedia locally. See screenshot

 - ExoMedia version: `4.2.3`

![error](https://user-images.githubusercontent.com/11219968/46297884-713f0a80-c5a6-11e8-86c8-6070ec199a25.png)

**Comment by brianwernick** [comment]
This will be in the next release
