### ISSUE TITLE
HSL stream gets clipped after few seconds

### ISSUE THREAD

**Issue by veresvit** [brianwernick/ExoMedia#66]
Hello,
thank you for this great library which make work with ExoPlayer much easier.

I am dealing with issue of clipping the video when streaming from an HSL stream. After some time (in case of my stream it is after 8 seconds) the video gets clipped. I am testing this on a phone with Android 5.0.1.  You can see the changes on on these pictures: http://imgur.com/a/vUT6C

First picture shows the full screen video right after the stream starts, everything is how it supposed to be. Second image shows how the video gets clipped after first 8 seconds of playback. I have enabled the layout bounds so you can see it clearly.

You can try this same issue with this HSL stream video (in this case it got clipped after 20 seconds of video): http://qthttp.apple.com.edgesuite.net/1010qwoeiuryfg/sl.m3u8

This issue happends when **onVideoSizeChanged** event is called (in my case when the video size is changed to higher resolution).

Is there any way how to avoid this issue? Not sure if its and issue of ExoPlayer configuration or the ExoMedia view.

Thank you for your assistance, Vit Veres

**Comment by brianwernick** [comment]
It's probably an issue with the shutter calculations.  I'll look in to it this weekend.

**Comment by veresvit** [comment]
Thank you, I'd appreciate it. :)

**Comment by brianwernick** [comment]
OK, it turns out that the ExoPlayer will sometimes give us the video size before it is scaled.  I have added a check for this before we update the shutter sizes. (see https://github.com/brianwernick/ExoMedia/pull/67)

2.5.1 has been released with the fix above

**Comment by veresvit** [comment]
Thank you, problem solved!
