### ISSUE TITLE
Issue when compile ExoPlayer and ExoMedia locally

### ISSUE THREAD

**Issue by bene25** [brianwernick/ExoMedia#662]
- ExoMedia version: `4.2.3`
 - ExoPlayer 2.8.4 

Hi, I have an issue while compiling ExoPlayer and ExoMedia locally

```
Error:Program type already present: com.google.android.exoplayer2.C$AudioContentType
Error:com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives: /home/aleksandr/AndroidProjects/ldraft/app/build/intermediates/transforms/dexBuilder/main/debug/0, /home/aleksandr/AndroidProjects/ldraft/app/build/intermediates/transforms/externalLibsDexMerger/main/debug/0, /home/aleksandr/AndroidProjects/ldraft/app/build/intermediates/transforms/dexBuilder/main/debug/1.jar, /home/aleksandr/AndroidProjects/ldraft/app/build/intermediates/transforms/dexBuilder/main/debug/2.jar, /home/aleksandr/AndroidProjects/ldraft/app/build/intermediates/transforms/dexBuilder/main/debug/3.jar, /home/aleksandr/AndroidProjects/ldraft/app/build/intermediates/transforms/dexBuilder/main/debug/4.jar, /home/aleksandr/AndroidProjects/ldraft/app/build/intermediates/transforms/dexBuilder/main/debug/5.jar, /home/aleksandr/AndroidProjects/ldraft/app/build/intermediates/transforms/dexBuilder/main/debug/6.jar, /home/aleksandr/AndroidProjects/ldraft/app/build/intermediates/transforms/dexBuilder/main/debug/7.jar, /home/aleksandr/AndroidProjects/ldraft/app/build/intermediates/transforms/dexBuilder/main/debug/8.jar, /home/aleksandr/AndroidProjects/ldraft/app/build/intermediates/transforms/dexBuilder/main/debug/9.jar, /home/aleksandr/AndroidProjects/ldraft/app/build/intermediates/transforms/dexBuilder/main/debug/10.jar, /home/aleksandr/AndroidProjects/ldraft/app/build/intermediates/transforms/dexBuilder/main/debug/11.jar, /home/aleksandr/AndroidProjects/ldraft/app/build/intermediates/transforms/dexBuilder/main/debug/12.jar, /home/aleksandr/AndroidProjects/ldraft/app/build/intermediates/transforms/dexBuilder/main/debug/13.jar, /home/aleksandr/AndroidProjects/ldraft/app/build/intermediates/transforms/dexBuilder/main/debug/14.jar, /home/aleksandr/AndroidProjects/ldraft/app/build/intermediates/transforms/dexBuilder/main/debug/15.jar
Error:com.android.tools.r8.CompilationFailedException: Compilation failed to complete
Error:com.android.tools.r8.utils.AbortException
```

**Comment by brianwernick** [comment]
Are you building ExoMedia in the library project or within your app? If you are trying to include the ExoPlayer dependencies from source you'll have to disable the transitive dependencies in ExoMedia from pulling those specific ones.

**Comment by davima** [comment]
Hi. I'm having the same issue. I am trying to include the exoplayer into my project. How do I disable these transitive dependencies? I tried disabling all transitive dependencies including:
configurations.all {
    transitive = false
}
 and then Kotlin started crashing: Exception in thread "main" java.lang.NoClassDefFoundError: kotlin/jvm/internal/Intrinsics

**Comment by brianwernick** [comment]
You can exclude transitive dependencies for _only_ `ExoMedia` with 
```
 implementation('com.devbrackets.android:exomedia:4.3.0') {
     exclude group: 'com.google.android.exoplayer' module: 'exoplayer-core'
     exclude group: 'com.google.android.exoplayer' module: 'exoplayer-dash'
     exclude group: 'com.google.android.exoplayer' module: 'exoplayer-hls'
     exclude group: 'com.google.android.exoplayer' module: 'exoplayer-smoothstreaming'
  }
```

You can read more about managing transitive dependencies in Gradles [User Guide](https://docs.gradle.org/current/userguide/managing_transitive_dependencies.html#sec:excluding_transitive_module_dependencies)

**Comment by bayazetyan** [comment]
> * ExoMedia version: `4.2.3`
> * ExoPlayer 2.8.4
> 
> Hi, I have an issue while compiling ExoPlayer and ExoMedia locally
> 
> ```
> Error:Program type already present: com.google.android.exoplayer2.C$AudioContentType
> Error:com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives: /home/aleksandr/AndroidProjects/ldraft/app/build/intermediates/transforms/dexBuilder/main/debug/0, /home/aleksandr/AndroidProjects/ldraft/app/build/intermediates/transforms/externalLibsDexMerger/main/debug/0, /home/aleksandr/AndroidProjects/ldraft/app/build/intermediates/transforms/dexBuilder/main/debug/1.jar, /home/aleksandr/AndroidProjects/ldraft/app/build/intermediates/transforms/dexBuilder/main/debug/2.jar, /home/aleksandr/AndroidProjects/ldraft/app/build/intermediates/transforms/dexBuilder/main/debug/3.jar, /home/aleksandr/AndroidProjects/ldraft/app/build/intermediates/transforms/dexBuilder/main/debug/4.jar, /home/aleksandr/AndroidProjects/ldraft/app/build/intermediates/transforms/dexBuilder/main/debug/5.jar, /home/aleksandr/AndroidProjects/ldraft/app/build/intermediates/transforms/dexBuilder/main/debug/6.jar, /home/aleksandr/AndroidProjects/ldraft/app/build/intermediates/transforms/dexBuilder/main/debug/7.jar, /home/aleksandr/AndroidProjects/ldraft/app/build/intermediates/transforms/dexBuilder/main/debug/8.jar, /home/aleksandr/AndroidProjects/ldraft/app/build/intermediates/transforms/dexBuilder/main/debug/9.jar, /home/aleksandr/AndroidProjects/ldraft/app/build/intermediates/transforms/dexBuilder/main/debug/10.jar, /home/aleksandr/AndroidProjects/ldraft/app/build/intermediates/transforms/dexBuilder/main/debug/11.jar, /home/aleksandr/AndroidProjects/ldraft/app/build/intermediates/transforms/dexBuilder/main/debug/12.jar, /home/aleksandr/AndroidProjects/ldraft/app/build/intermediates/transforms/dexBuilder/main/debug/13.jar, /home/aleksandr/AndroidProjects/ldraft/app/build/intermediates/transforms/dexBuilder/main/debug/14.jar, /home/aleksandr/AndroidProjects/ldraft/app/build/intermediates/transforms/dexBuilder/main/debug/15.jar
> Error:com.android.tools.r8.CompilationFailedException: Compilation failed to complete
> Error:com.android.tools.r8.utils.AbortException
> ```

do you have any solution ?
