### ISSUE TITLE
Leanback VideoControls do not fade away properly after trickplay

### ISSUE THREAD

**Issue by harenj** [brianwernick/ExoMedia#663]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests

###### Include the following:
 - ExoMedia version: `4.2.3`
 - Device OS version: `7.0`
 - Devide Manufacturer: `Amazon`
 - Device Name: `Fire TV`
 
###### Reproduction Steps
Using the default leanback controls, when I trick play with FF or RWD hardware buttons, the controls UI would not pop up when I press the button, but after the hide duration would expire it would briefly flash and fade out. This was seen after I added the following to enable FF and RWD:

```
final VideoControls videoControls = videoView.getVideoControls();
videoControls.setFastForwardButtonEnabled(true);
videoControls.setRewindButtonEnabled(true);
```

###### Expected Result
I believe the expected result is that as soon as FF or RWD is pressed, the `VideoControls` UI appears, and then after the `hideDelay` time expires, it fades out. 

###### Actual Result
See reproduction steps.

### How I fixed the issue
I solved this problem by creating the following class:

```
public class ForkedVideoControlsLeanback extends VideoControlsLeanback {
    public ForkedVideoControlsLeanback(Context context) {
        super(context);
    }

    public ForkedVideoControlsLeanback(Context context, AttributeSet attrs) {
        super(context, attrs);
    }

    public ForkedVideoControlsLeanback(Context context, AttributeSet attrs, int defStyleAttr) {
        super(context, attrs, defStyleAttr);
    }

    @Override
    protected void performSeek(long seekToTime) {
        super.show(); // <-------------------- the key line for the fix
        super.performSeek(seekToTime);
    }
}
```

and then I applied this as such to my `VideoView`:

```
final ForkedVideoControlsLeanback videoControls = new ForkedVideoControlsLeanback(this);
videoView.setControls(videoControls);
videoControls.setFastForwardButtonEnabled(true);
videoControls.setRewindButtonEnabled(true);
```

My fix worked perfectly and I now have the desired behavior.

Thanks for a great library!

**Comment by brianwernick** [comment]
Fixed in #664
