### ISSUE TITLE
Gradle project syn failed after updating it to 4.6 from 3.2.0

### ISSUE THREAD

**Issue by VenkatReddyGlobussoft** [brianwernick/ExoMedia#669]
###### Include the following:
 - ExoMedia version: `4.2.3`
 - Device OS version: `8.1.0`
 
###### Reproduction Steps
 0. After gradle plugin update from 3.2.0 to 4.6
1.here is the screen shot:
![photo_2018-10-31_13-06-53](https://user-images.githubusercontent.com/30926617/47772968-73fc5f00-dd0e-11e8-8a8f-799a1d150194.jpg)
)

###### Expected Result
Code should work fine after updating the gradle plugin from 3.2.0 to 4.6
###### Actual Result
Cause: com.novoda.gradle.release.AndroidLibrary$LibraryUsage.getDependencyConstraints()Ljava/util/Set;
1.here is the scree shot:
![photo_2018-10-31_13-10-29](https://user-images.githubusercontent.com/30926617/47773048-c3db2600-dd0e-11e8-9b9b-5357f9b3f02b.jpg)

**Comment by brianwernick** [comment]
This was already fixed in #667

**Comment by VenkatReddyGlobussoft** [comment]
thank you
