### ISSUE TITLE
How can i play video in progressive way like you tube or like instagram... Currently in my implementation i can see first video is fully downloaded and then getting start,,,  .. i want to start playing video as soon as buffering start..

### ISSUE THREAD

**Issue by Ashish1593** [brianwernick/ExoMedia#675]
- [ ] I have verified there are no duplicate active or recent bugs, questions, or requests

###### Include the following:
 - ExoMedia version: `4.0.0`
 - Device OS version: `7.0`
 - Devide Manufacturer: `Google`
 - Device Name: `Pixel XL`
 
###### Reproduction Steps
 0.

**Comment by brianwernick** [comment]
This isn't a question about the use of this library, this is more of a question for StackOverflow.com. 

You'll want to look in to video streaming formats such as MPEG Dash, HLS, Smooth Stream
