### ISSUE TITLE
How to cache mp4 videos from url and play from  cache data.  And I am using RecyclerView and want to cache next video while playing the current video and then play next video from Cache. 

### ISSUE THREAD

**Issue by Ashish1593** [brianwernick/ExoMedia#677]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests

###### Include the following:
 - ExoMedia version: `4.0.0`
 - Device OS version: `7.0`
 - Devide Manufacturer: `Google`
 - Device Name: `Pixel XL`
 
###### Reproduction Steps
 0.

**Comment by brianwernick** [comment]
You already asked the caching question in #676 so I'll defer to the response there.
You don't have enough information for us to know about your setup but you might be interested in looking at the [ConcatenatingMediaSource](https://github.com/google/ExoPlayer/blob/b5beb32618ac99adc58b537031a6f7c3dd761b9a/library/core/src/main/java/com/google/android/exoplayer2/source/ConcatenatingMediaSource.java#L48) which will pre-fetch the next video in the list (similar to if the list were a single HLS or MPEG Dash stream).
