### ISSUE TITLE
how can I get the callback for video stopped playing and start playing?

### ISSUE THREAD

**Issue by Ashish1593** [brianwernick/ExoMedia#680]
- [ ] I have verified there are no duplicate active or recent bugs, questions, or requests

###### Include the following:
 - ExoMedia version: `4.3.0`
 - Device OS version: `7.0`
 - Devide Manufacturer: `Google`
 - Device Name: `Pixel XL`

Hello 
I want to stop some animator progress bar when video stop playing and start animation when video start playing .. But I am not getting any callback to check whether video stops playing or not..  
So achieve this I use below code

Currently I am using OnBufferUpdateListener and inside onBufferingUpdate I am checking whether video is playing or not. but this is not correct approach  there is some delay  in stopping animator . 
Can you tell me the correct way of getting video playback start and stop callback.

                    playerView.setOnBufferUpdateListener(new OnBufferUpdateListener() {

                        @Override
                        public void onBufferingUpdate(int percent) {
                            if (playerView.isPlaying()) {
                                hideVideoBufferLoader();
                            } else {
                                if (meetup.storyModels.get(counter).isVideo()) {
                                    showVideoBufferLoader();
                                }
                            }
                        }
                    });

**Comment by brianwernick** [comment]
It sounds like you want what #257 will add, in the meantime you can workaround it by using a [Repeater](https://github.com/brianwernick/ExoMedia/blob/master/library/src/main/java/com/devbrackets/android/exomedia/util/Repeater.java) that checks if the video is playing every so often to hide/show the re-buffering loader. I'm hoping to have time near the end of this month to sit down and get the majority of the work for `5.0` done (which will include #257) so hopefully this workaround isn't necessary for too long
