### ISSUE TITLE
Response code: 403

### ISSUE THREAD

**Issue by Dule95D** [brianwernick/ExoMedia#682]
- [ ] I have verified there are no duplicate active or recent bugs, questions, or requests

###### Include the following:
 - ExoMedia version: `4.0.0`
 - Device OS version: `7.0`
 - Devide Manufacturer: `Google`
 - Device Name: `Pixel XL`
 
###### Reproduction Steps
 1. Start the video (HLS m3u8 format) in catch up
 2. After 52, 53 seconds video stops and onError() is being called printing this message:
com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 403 

###### Expected Result
Should continue the video. Also I should mention that seek bar not working

###### Actual Result
This error:
E/ExoPlayerImplInternal: Source error.
    com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 403

When I play Live video, it is running well, but when I play video which has start and end time I get this error at 53 seconds, almost always. My guess is that maybe I need to pass some headers.

**Comment by brianwernick** [comment]
This doesn't look like anything we are doing wrong on the client side, a `403` is the server not fulfilling the request. Make sure you aren't requesting a time that is outside the bounds of the video and the server can support offset requests.

**Comment by Dule95D** [comment]
Hi @brianwernick, thank you for the quick reply. There is another application with ijkplayer using and there link for streaming is working as usual.
