### ISSUE TITLE
How to get the decryption key after authentication?

### ISSUE THREAD

**Issue by tushar09** [brianwernick/ExoMedia#683]
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-MEDIA-SEQUENCE:0
#EXT-X-ALLOW-CACHE:YES
#EXT-X-TARGETDURATION:7
#EXT-X-KEY:METHOD=AES-128,URI="https://video-stream-node.herokuapp.com/data",IV=0x4f6*************
#EXTINF:6.046444,
hls600000000.ts
#EXTINF:6.000000,
hls600000001.ts
#EXTINF:3.000000,
hls600000002.ts
#EXTINF:6.000000,
hls600000003.ts
#EXTINF:6.000000,
hls600000004.ts
#EXTINF:3.000000,
hls600000005.ts
#EXTINF:0.033333,
hls600000006.ts
#EXT-X-ENDLIST

You can see the key url is https://video-stream-node.herokuapp.com/data. How can I send data in header to get the key? Any sample code snippet?

**Comment by brianwernick** [comment]
Have you set the DRM Callback in the [`VideoView.setDrmCallback`](https://github.com/brianwernick/ExoMedia/blob/c0f4bc3a98cea8c10ee47bcc8788ba3a30081570/library/src/main/java/com/devbrackets/android/exomedia/ui/widget/VideoView.java#L348) or the similar Audio player version?
