### ISSUE TITLE
How can I play next audio file after current audio file ended?

### ISSUE THREAD

**Issue by vsay01** [brianwernick/ExoMedia#69]
Thank for the library,

I want to set listener so that player will play next audio file after the current one ended. 

How can I achieve that?

In Exoplayer, I found sth like this:

    @Override
    public void onPlayerStateChanged(boolean playWhenReady, int playbackState) {
        if(playbackState == ExoPlayer.STATE_ENDED){
        
        }
    }

**Comment by brianwernick** [comment]
You register for media completion the same way you do with the Android MediaPlayer (`public void setOnCompletionListener(MediaPlayer.OnCompletionListener listener)`)

**Comment by vsay01** [comment]
Thank for reply;
I use AudioPlayerActivity in demo, so can you elaborate more above answer?
    do I need to create instance MediaPlayer inside AudioPlayerActivity?
    
    player.setOnCompletionListener(new OnCompletionListener() {
        @Override
        public void onCompletion(MediaPlayer mp) {
            // TODO Auto-generated method stub
            
        }
    }

**Comment by brianwernick** [comment]
Oh, if you are using the PlaylistService then you will need to override the `performMediaCompletion()` method in the PlaylistService (note: the documentation is currently incorrect, it doesn't perform `next()` by default anymore)

**Comment by vsay01** [comment]
I cannot override performMediaCompletion() in AudioPlayerActivity demo.

Where can I override this from ?

**Comment by brianwernick** [comment]
In the PlaylistService (AudioService in the demo)

**Comment by vsay01** [comment]
Thank, Here what I added in AudioService

    @Override
    protected void performMediaCompletion() {
        super.performMediaCompletion();
        getMediaPlaylistManager().invokeNext();
    }

Seems like nothing change....

**Comment by brianwernick** [comment]
It should work, that's what I'm doing with other applications.  The only difference is I'm not going through the playlistManager to perform the next functionality
```java
@Override
protected void performMediaCompletion() {
    performNext();
}
```

**Comment by vsay01** [comment]
I see, I tested using your function performNext(), it loaded the next song but:

- It not automatically play ( it paused unless i click on play to play the song )
- I need to change the title of the audio file so in AudioPlayActivity.java I have a function to change the title in the AudioPlayActivity as follow:

    setTitle(AudioArrayPlayList, selectedIndex);
If I used your function then how can I change the current title of audio in the AudioPlayActivity.java?

**Comment by brianwernick** [comment]
If you have specified the audio to start paused the you will need to set `immediatelyPause = false;` before you call `performNext();`.
In your activity you should register for the `EMPlaylistServiceCallback` to know when to update your title (and images, etc.)

**Comment by vsay01** [comment]
Regarding the paused issue I put changed it to 

    @Override
    protected void performMediaCompletion() {
        super.performMediaCompletion();
        immediatelyPause = false;
        performNext();
    }

Still same issue happened, It loaded but paused

Am I set it wrongly ?

**Comment by brianwernick** [comment]
OK, sorry for the confusion.  `performNext()` checks the current playback state and sets `immediatelyPause` accordingly, meaning you need to manually set it to true after you call `performNext()`.  e.g. 
```java
    @Override
    protected void performMediaCompletion() {
        super.performMediaCompletion();
        performNext();
        immediatelyPause = false;
    }
```

This is something that I will look in to re-addressing for the 3.0 release since it is a little confusing

**Comment by vsay01** [comment]
Oh, ok now it's working :+1: 

For updating UI of the AudioPlayerActivity as you mentioned I need to register EMPlaylistServiceCallback and It already was implemented in the demo

Is it the method that I need to call and change the UI isn't it?
    
    boolean onPlaylistItemChanged(EMPlaylistManager.PlaylistItem currentItem, boolean hasNext, boolean hasPrevious);

I tried to call setTitle() in this method, one things is that in this method I can get the currentItem above but since I have more than one playlist how can I know that the playlist of the item? 

Here is my signature of my setTitle

    public void setTitle(ArrayList<MediaItem> arr, int selectedIndex)

So if I know the playlist Id of currentItem from onPlaylistItemChanged then I can set it for my method.

Thank for patient with me ...

**Comment by brianwernick** [comment]
Since each of your lists of items to play should have a unique id associated with it once it is added to the PlaylistManager, you should be able to compare the id from either the `currentItem` or `playlistManager.getPlaylistId()` to that of the list of items.  

e.g.
```java
public void setTitle(MediaItem currentItem) {
    long playlistId = playlistManager.getPlaylistId();
    if (playlistId == PLAYLIST_ONE_ID) {
        //Set the title from the first playlist
    } else if (playlistId == PLAYLIST_TWO_ID) {
        //Set the title from the second playlist
    }
}
```

**Comment by vsay01** [comment]
It works fine I set Id attribute to each audio instance...
Thank :+1:
