### ISSUE TITLE
Enabling Ahead of Time Media Caching

### ISSUE THREAD

**Issue by kevincianfarini** [brianwernick/ExoMedia#693]
###### Include the following:
 - ExoMedia version: `4.3.0`
 - Device OS version: `8.1`
 - Devide Manufacturer: `OnePlus`
 - Device Name: `5T`

The application I'm working on requires that I be able to cache media ahead of time for the user. Very similar to how Google Play Music allows you to download songs for offline play as well as on the fly caching as you listen to your music. 

I'm aware of some of the questions that have been answered like #520 which enables caching. I'm wondering how the cache determines that they media you're requesting has already been cached? I'd assume cached files are tied to the URI that they were requested from. 

I've taken a look at this code and I'm not quite sure where what I'm attempting to do fits in. 
```kotlin
    private fun configureExoMedia() {
        // Registers the media sources to use the OkHttp client instead of the standard Apache one
        // Note: the OkHttpDataSourceFactory can be found in the ExoPlayer extension library `extension-okhttp`
        ExoMedia.setDataSourceFactoryProvider(object : ExoMedia.DataSourceFactoryProvider {
            private var instance: CacheDataSourceFactory? = null

            override fun provide(userAgent: String, listener: TransferListener?): DataSource.Factory {
                if (instance == null) {
                    // Updates the network data source to use the OKHttp implementation
                    val upstreamFactory = OkHttpDataSourceFactory(OkHttpClient(), userAgent, listener)

                    // Adds a cache around the upstreamFactory
                    val cache = SimpleCache(File(cacheDir, "ExoMediaCache"), LeastRecentlyUsedCacheEvictor((50 * 1024 * 1024).toLong()))
                    instance = CacheDataSourceFactory(cache, upstreamFactory, CacheDataSource.FLAG_IGNORE_CACHE_ON_ERROR)
                }

                return instance!!
            }
        })
```

**Comment by kevincianfarini** [comment]
I'm dumb. Sorry for opening this issue. Looks what I should have been looking for `[CacheUtils.cache()](https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/upstream/cache/CacheUtil.html#cache-com.google.android.exoplayer2.upstream.DataSpec-com.google.android.exoplayer2.upstream.cache.Cache-com.google.android.exoplayer2.upstream.cache.CacheDataSource-byte:A-com.google.android.exoplayer2.util.PriorityTaskManager-int-com.google.android.exoplayer2.upstream.cache.CacheUtil.CachingCounters-java.util.concurrent.atomic.AtomicBoolean-boolean-)`

**Comment by brianwernick** [comment]
I apologize for not answering sooner.
You don't need to be sorry about opening this issue, it's a good question that others are likely to have and now there's documentation in the form of an issue/question.

Best of luck on your project and please let me know if you have any more questions

**Comment by kevincianfarini** [comment]
If the implementation turns out to be non-trivial, would you be interested in me making a pull request with the solution I've come up with? 

Hopefully that would simplify some things and make it reusable.

**Comment by brianwernick** [comment]
Absolutely. However please be aware that I'm near the end of #643

**Comment by kevincianfarini** [comment]
That's great! I'm implementing it in Kotlin anyway.
