### ISSUE TITLE
Auto frame rate

### ISSUE THREAD

**Issue by djnice** [brianwernick/ExoMedia#695]
Hi,

Can you implement the auto frame rate function like this?
[https://github.com/yuliskov/SmartYouTubeTV/blob/new-exo-player/exoplayeractivity/src/main/java/com/liskovsoft/smartyoutubetv/flavors/exoplayer/player/autoframerate/AutoFrameRateManager.java](url)

Many thanks!

**Comment by brianwernick** [comment]
I'll have to look more in to this when I get a chance

**Comment by brianwernick** [comment]
Linked code is no longer available and looking online I can't find it. I'm going to close this issue, if there is a more specific request please open a new ticket
