### ISSUE TITLE
How to have a good storage structure for multiple playlists?

### ISSUE THREAD

**Issue by vsay01** [brianwernick/ExoMedia#70]
Hi,
I notice there is a static variable PlayListManager that will be used in the AudioPlayerActivity.java

Each time this method invoked in the AudioPlayerActivity
    playlistManagerAudioActivity.play(selectedIndex, false);

The AudioService.class will be started.

I followed the demo and it works fine for one playlist.

However, if I have multiple playlist then should I :
- have different AudioPlayerActivity for each playlist?

- continue using the static variable in App.java which is the playListManager for all playlists?
One issue that I met using static variable in App.java which is the playListManager for all playlists was that when I play a song from list 1, then switch back select another song from list 2 when I click on the foreground notification it will play a song that I chose from list 1 and not the latest one.

What do you think?
Thank

**Comment by brianwernick** [comment]
You should continue using a static (singleton) implementation for the PlaylistManager.  When switching a playlist you will need to 
1. Update the actual playlist storage in the PlaylistManager (`setParameters(...)`)
2. Update the playlist id (`setPlaylistId(...)`)
3. Set the index of the item to play (`setCurrentItem(...)`)
4. Start playback (`play(...)`)

**Comment by vsay01** [comment]
As I mentioned I tried to use static implementation:
Here is the current issue I have Though I will recheck it again.
Scenario:
- I click on a song called A from list 1 --> AudioPlayerAcitivty.java started and play song A
- go back and choose a song called A" from list 2 --> AudioPlayerActivity.java started ( go to onResume - since already created before) and play song A"
- go back to playlist or home screen 
- select the foreground notification

Expected: open AudioPlayerActivity and play song A" list 2

Actual: open AudioPlayerActivity and play song A list 1

=========
I tried to track down the value static playlistManager in the App.java, it changed when A" from list 2 clicked but the problem is that when A' from list 1 clicked and play the service started already and when A" from list 2 clicked the player not started again since it will fire the onResume() callback of the AudioPlayerActivity.java.

Let me know if you need clarification...
Thank

**Comment by brianwernick** [comment]
What is your implementation of `protected PendingIntent getNotificationClickPendingIntent()` in the PlaylistService?

**Comment by vsay01** [comment]
Here it is  
  @Override
    protected PendingIntent getNotificationClickPendingIntent() {
        Log.e("AuoSeice geNotiClkP= ", getMediaPlaylistManager().getPlayListId()+"");
        Intent intent = new Intent(getApplicationContext(), AudioPlayerActivity.class);
        intent.putExtra(AudioPlayerActivity.EXTRA_INDEX, getMediaPlaylistManager().getCurrentIndex());
        intent.putExtra(AudioPlayerActivity.EXTRA_PLAYLISTID, (int)getMediaPlaylistManager().getPlayListId());
        return PendingIntent.getActivity(getApplicationContext(), FOREGROUND_REQUEST_CODE, intent, PendingIntent.FLAG_UPDATE_CURRENT);
    }

**Comment by brianwernick** [comment]
OK, currently the pendingIntent is only updated when the service is set as a Foreground service. I'll update it shortly to correctly update when the notification is updated.

**Comment by vsay01** [comment]
Great thank

**Comment by brianwernick** [comment]
Yep.  I usually have a different setup so I haven't hit this issue before.  I should be releasing 2.5.2 in a few minutes

**Comment by brianwernick** [comment]
2.5.2 has been released

**Comment by vsay01** [comment]
Confirm fixed.. Thank
