### ISSUE TITLE
Can not inflate videoview

### ISSUE THREAD

**Issue by lucazin** [brianwernick/ExoMedia#700]
- [ ] I have verified there are no duplicate active or recent bugs, questions, or requests

###### Include the following:
 - ExoMedia version: `4.2.3`
 - Device OS version: `9.0`
 - Devide Manufacturer: `Samsung`
 - Device Name: `A70`
 
###### Reproduction Steps

Enter in fragment

###### Expected Result

Not Exception

###### Actual Result

Can not inflate this guy below... 
WHats happen ?

   <com.devbrackets.android.exomedia.ui.widget.VideoView
                    android:id="@+id/video_view"
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content"
                    android:adjustViewBounds="true"
                    app:videoScale="fitXY"
                    app:useDefaultControls="true" />

**Comment by brianwernick** [comment]
Have you tried the demo app to verify it isn't your project setup that's the issue?

**Comment by lucazin** [comment]
No man.. its not working..

The exception throw when inflate view in xml ...if i take off   build and
work normally

Em seg, 15 de jul de 2019 às 16:19, Brian Wernick <notifications@github.com>
escreveu:

**Comment by brianwernick** [comment]
Please post a stacktrace, otherwise I can't help track down the issue
