### ISSUE TITLE
About native m3u8.

### ISSUE THREAD

**Issue by yangwuan55** [brianwernick/ExoMedia#701]
Can I play m3u8 with this?
```
videoView.setVideoURI(Uri.parse("/file/path.m3u8"));

```
It's file path not the url.

**Comment by brianwernick** [comment]
As long as you have a valid uri (local or remote) an HLS file will play. If the file is an asset see #32, otherwise `Uri.parse(FILE_PATH)` should work

**Comment by yangwuan55** [comment]
3q!!!!
