### ISSUE TITLE
Playing facebook video

### ISSUE THREAD

**Issue by appsgardenbd** [brianwernick/ExoMedia#702]
How can I play video from facebook url or youtube url?

**Comment by brianwernick** [comment]
You'll need to extract the direct URLs from either YouTube's APIs or Facebook's APIs, once you have that you should be able to play by just passing that url in to ExoMedia

**Comment by LunevNF** [comment]
Not working

[https://rr3---sn-hxb54vo-3w5e.googlevideo.com/videoplayback?expire=1706313529&ei=2fKzZbGPJZmz0u8PvtSWsAg&ip=194.8.136.185&id=o-AI6CeKOslU_hz_rAfIwJjGVosENJhhIYzYSEtoqSPHVi&itag=18&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ%3D%3D&mh=lh&mm=31%2C29&mn=sn-hxb54vo-3w5e%2Csn-n8v7kn7e&ms=au%2Crdu&mv=m&mvi=3&pcm2cms=yes&pl=22&initcwndbps=1738750&vprv=1&svpuc=1&mime=video%2Fmp4&gir=yes&clen=135262702&ratebypass=yes&dur=3116.419&lmt=1706269644280450&mt=1706291600&fvip=11&fexp=24007246&c=ANDROID&txp=7309224&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cxpc%2Cvprv%2Csvpuc%2Cmime%2Cgir%2Cclen%2Cratebypass%2Cdur%2Clmt&sig=AJfQdSswRQIgTKVTf2_RQtb5tncj92Qjplibgy4ROlj63fGSkE4pU2UCIQD8FOLhJM5jY_XWncYgXph6g2OIvvCFxbPuGlvD4Hp71w%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpcm2cms%2Cpl%2Cinitcwndbps&lsig=AAO5W4owRQIhAP1BXNstZ74jBqTNQoDxU1YjT24gErWIXkcfc62M2gmgAiBnqXz3fILDqpBtkfsAUjIyYzT7V_F5GGJxnBkJ_E2Vhw%3D%3D&cpn=-h69fxYKcZocHDbV](url)
