### ISSUE TITLE
java.lang.VerifyError on Android 4.1 and 4.2

### ISSUE THREAD

**Issue by artyomn** [brianwernick/ExoMedia#703]
- [+ ] I have verified there are no duplicate active or recent bugs, questions, or requests

###### Include the following:
 - ExoMedia version: `4.3.0`
 - Device OS version: `4.1.2`, `4.2.2`
 - Devide Manufacturer: `Samsung`, `Digma`, `Lenovo`, `LG`, `Sony Ericsson`
 
###### Reproduction Steps
 0.  `mp = new AudioPlayer(App.context);`

###### Expected Result
No exception thrown

###### Actual Result
App crashes with the following:
```
Fatal Exception: java.lang.VerifyError: e/d/a/a/a/c/b
       at com.devbrackets.android.exomedia.core.audio.ExoAudioPlayer.(ExoAudioPlayer.java:3)
       at com.devbrackets.android.exomedia.AudioPlayer.(AudioPlayer.java:4)
```
This error appeared after switching to R8. Switching back to ProGuard resolves the issue.
But since R8 is going to be a replacement to ProGuard it would be better to be able to use this library with new code obfuscator.

**Comment by brianwernick** [comment]
Was this in your app or the Demo app?

**Comment by artyomn** [comment]
I haven't tried Demo app, it was in my app

**Comment by brianwernick** [comment]
Closing since the minimum API is now 21 (Android 5.0)
