### ISSUE TITLE
Multiple Agent support?

### ISSUE THREAD

**Issue by jmimohsin** [brianwernick/ExoMedia#705]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests

###### Include the following:
 - ExoMedia version: `4.0.0`
 - Device OS version: `7.0`
 - Devide Manufacturer: `Google`
 - Device Name: `Pixel XL`
 
###### Reproduction Steps
 0.  

###### Actual Result

I am using ExoMedia in radio app and want to know does it support Agent. Like I want to change url with new agent. Does it possible?

Every time new url will load with different agent thats mean change agent dynamically.

**Comment by brianwernick** [comment]
Unfortunately there's not an easy/quick way to do it currently. How you can currently do it (hacky) is to create a custom [MediaSourceProvider](https://github.com/brianwernick/ExoMedia/blob/master/library/src/main/java/com/devbrackets/android/exomedia/core/source/MediaSourceProvider.java) and override the [`generate`](https://github.com/brianwernick/ExoMedia/blob/master/library/src/main/java/com/devbrackets/android/exomedia/core/source/MediaSourceProvider.java#L48) method to define your own `userAgent`. 
e.g.
```java
public class CustomMediaSourceProvider extends MediaSourceProvider {
    @Override
    @NonNull
    public MediaSource generate(@NonNull Context context, @NonNull Handler handler, @NonNull Uri uri, @Nullable TransferListener transferListener ) {
        SourceTypeBuilder sourceTypeBuilder = findByProviders(uri);

        // If a registered builder wasn't found then use the default
        MediaSourceBuilder builder = sourceTypeBuilder != null ? sourceTypeBuilder.builder : new DefaultMediaSourceBuilder();

        //TODO customize this userAgent for your use
        String customAgent = "Your Agent";
        return builder.build(context, uri, customAgent, handler, transferListener);
    }
}
```

You can then override the default `MediaSourceBuilder` in [ExoMedia.Data](https://github.com/brianwernick/ExoMedia/blob/master/library/src/main/java/com/devbrackets/android/exomedia/ExoMedia.java#L141) 
e.g.
```java
ExoMedia.Data.mediaSourceProvider = new CustomMediaSourceProvider();
```

**Comment by jmimohsin** [comment]
Thanks for your quick reply. I will implement and update you if all work fine. Thanks

**Comment by jmimohsin** [comment]
I am using AudioPlayer. Can I use like this..

```kotlin
if(activeAudio!!.chAgent != null)
  ExoMedia.Data.mediaSourceProvider = CustomMediaSourceProvider(activeAudio!!.chAgent)
mediaPlayer!!.setDataSource(Uri.parse(activeAudio!!.chUrl))
mediaPlayer!!.prepareAsync()
```

**Comment by brianwernick** [comment]
In ExoMedia `5.0` this is now supported. To define a custom user-agent for each media url you will need to pass a `MediaSource` to the AudioPlayer/VideoView instead of a URI.
