### ISSUE TITLE
Inflation Error

### ISSUE THREAD

**Issue by hmawla** [brianwernick/ExoMedia#706]
Hi,

The app always crashes when setContentView() is called in an activity that contains VideoPlayer with the following output:
https://pastebin.com/raw/UuKB4dKu

I even created a new test app and copied almost everything from the demo app, all stayed the same.
Any help would be appreciated

**Comment by 0xCTF** [comment]
I'm stuck in the same problem, please if you found a solution, share it

**Comment by hmawla** [comment]
> I'm stuck in the same problem, please if you found a solution, share it

Unfortunately, I had to switch to another library.

**Comment by 0xCTF** [comment]
> > I'm stuck in the same problem, please if you found a solution, share it
> 
> Unfortunately, I had to switch to another library.

Please, if possible, let me know which alternative library you used

**Comment by hmawla** [comment]
> > > I'm stuck in the same problem, please if you found a solution, share it
> > 
> > 
> > Unfortunately, I had to switch to another library.
> 
> Please, if possible, let me know which alternative library you used

I am using raw exoplayer implementation, check this guide:
https://blog.mindorks.com/using-exoplayer-to-play-video-and-audio-in-android-like-a-pro

**Comment by 0xCTF** [comment]
> > > > I'm stuck in the same problem, please if you found a solution, share it
> > > 
> > > 
> > > Unfortunately, I had to switch to another library.
> > 
> > 
> > Please, if possible, let me know which alternative library you used
> 
> I am using raw exoplayer implementation, check this guide:
> https://blog.mindorks.com/using-exoplayer-to-play-video-and-audio-in-android-like-a-pro

Thank you, appreciate your help !

**Comment by brianwernick** [comment]
For others that happen across this issue; please make sure that you aren't explicitly (or implicitly through other dependencies) including a different `exoplayer` version than the one that's expected by `exomedia`. This can cause a mismatch in the constructors the ExoMedia is expecting from ExoPlayer. If you have verified that and are still seeing this issue please open a new issue
