### ISSUE TITLE
QoE Metrics?

### ISSUE THREAD

**Issue by cipher009** [brianwernick/ExoMedia#707]
I would like to have feedback on the quality of experience of the streaming service. Are there any custom listeners I could use or should I look for Exoplayer listeners instead?
I am interested in the number of interruptions, bitrate, resolution etc..

**Comment by brianwernick** [comment]
I realize that this is an old question and you likely found a solution or moved to a different video player. For everyone else's reference, there is an `AnalyticsListener` provided by ExoPlayer that you can register that will be informed of many different events such as the video size, bitrate, etc.
