### ISSUE TITLE
version

### ISSUE THREAD

**Issue by SummerMineJack** [brianwernick/ExoMedia#708]
- [ ] I have verified there are no duplicate active or recent bugs, questions, or requests

###### Include the following:
 - ExoMedia version: `4.0.0`
 - Device OS version: `7.0`
 - Devide Manufacturer: `Google`
 - Device Name: `Pixel XL`
 
###### Reproduction Steps
 0.  

###### Actual Result

Can you give a Java version？？

**Comment by brianwernick** [comment]
If you are asking for the Java version that the library is targeted towards it's Java 7
