### ISSUE TITLE
[Question] Is it possible to playback RTSP stream?

### ISSUE THREAD

**Issue by isabsent** [brianwernick/ExoMedia#709]
There is `dev-v2-rtsp` branch in `ExoPlayer`. Is it possible to playback `RTSP` stream if I use it instead of main `ExoPlayer` branch to compile your code?

**Comment by brianwernick** [comment]
It is possible but with some modifications/updates. The [research/rtsp branch](https://github.com/brianwernick/ExoMedia/tree/research/rtsp) was using the work done in `dev-v2-rtsp` however it's fairly old so I'm sure some changes were made in the exoplayer branch that would cause necessary updates in the `research/rtsp` branch.
