### ISSUE TITLE
Next Button and Previous Button shown incorrect shape for Android 5.0

### ISSUE THREAD

**Issue by vsay01** [brianwernick/ExoMedia#71]
Another issue I faced is the next button and previous button are shown in not correctly.

Both in AudioPlayerActivity and the foreground notification, in my device Android 5.0 both button not shown in correct shape I was forced to download both images from ExoMedia and put locally then it works fine.

so I can change fine both button for the AudioPlayerActivity but not the foreground notification.

Do you happen to know the reason ?
Thank

**Comment by brianwernick** [comment]
It might be an issue with the vector drawable generation on 5.0.  I'll look in to it when I get some more time

**Comment by brianwernick** [comment]
I'm not seeing any issues with the next button, but I have fixed the issues with the previous button in https://github.com/brianwernick/ExoMedia/commit/cdf4f743de24b3692adc7b415b3d7ace195a6475

**Comment by vsay01** [comment]
Great, So basically i need to recompile and build my project to get changes right?

**Comment by brianwernick** [comment]
After I perform the next release, yes.

**Comment by vsay01** [comment]
ok
