### ISSUE TITLE
ExoPlayer is update to 2.11.1, is any plan to update this lib?

### ISSUE THREAD

**Issue by peerless2012** [brianwernick/ExoMedia#713]
###### Include the following:
- Exoplayer : `2.9.6`
 - ExoMedia version: `4.3.0`
 - Device OS version: `7.0`
 - Devide Manufacturer: `Google`
 - Device Name: `Pixel XL`
 
Exoplayer is update to 2.11.1, and some constructor method have changed, so if i update the exoplayer to 2.11.1, build error. so is any plan to update this lib?

**Comment by brianwernick** [comment]
Honestly I'm not sure if I'll do another release. I've been trying to get enough time and focus to push through a 5.0 release to be an LTS

**Comment by AdityaAnand1** [comment]
My two cents: This library's releases should follow ExoPlayer's so we get all downstream updates as soon as they are available 😄 

Fantastic job on this repo btw 💯

**Comment by phiamo** [comment]
That would be amazing, if we could use it with new exoplayer > 2.11

**Comment by brianwernick** [comment]
My apologies for being absent for so long. Yesterday I started the process of updating all of the dependencies in the `dev/5.0` branch (on my machine); there's still a lot to do on top of updating the dependencies so I don't have a clear timeline as to when a `5.0` version will be released but would expect it sometime in the next few months.

**Comment by phiamo** [comment]
Hi Brian,
thats amazing news!
Thanks a Lot!

Am Do., 3. Dez. 2020 um 15:00 Uhr schrieb Brian Wernick <
notifications@github.com>:

**Comment by assembleMHN** [comment]
@brianwernick any news about your version 5.0? :) And thanks for all your work on this library :)

**Comment by brianwernick** [comment]
Being realistic with myself, and everyone else, I don't really have a time frame. It's been difficult to motivate myself to work on the libraries after my workday, however what I will say for the 5.0 release is that I'll try to work at least a few hours a week towards it and any help would be appreciated.

I appreciate how patient everyone has been :bow:

**Comment by peerless2012** [comment]
I find 5.0.0 in readme, does it means 5.0.0 can be use for production environment?

**Comment by brianwernick** [comment]
I'm going to close this as handled in 5.0 (not yet released, but getting close) since we now use the `media3` version `1.0.0-beta02` which correlates with the `2.18.1` version

**Comment by peerless2012** [comment]
ExoMedia will use media3?

In my project i use media1 and use exomedia as a MediaPlayer.

**Comment by brianwernick** [comment]
The Media3 libraries are the new home for the ExoPlayer library, so they are currently publishing changes to both the current `exoplayer` and `media3` packages but in the future (I read somewhere later this year but can't find the blog post again) will only publish updates to `media3`. You can read more about this in the Media 3 [Release Notes](https://developer.android.com/jetpack/androidx/releases/media3#new_features_2); I've copied the important part about the ExoPlayer

> ExoPlayer was previously hosted in a separate [ExoPlayer GitHub project](https://github.com/google/ExoPlayer). In Media3 its package name is androidx.media3.exoplayer. We plan to continue to maintain and release the ExoPlayer GitHub project for a while to give apps time to migrate to Media3. Media3 has replacements for all the ExoPlayer modules, except for the legacy media2 and mediasession extensions, which are replaced by the new media3-session module. This provides direct integration between players and media sessions without needing to use an adapter/connector class.

**Comment by peerless2012** [comment]
But I still think it's need to keep this repo update, because this repo make it easy to use `Exoplayer` just like `MediaPlayer`,  because some project may just use `Exoplayer` as a simple `MediaPlayer`, or some project (like us) is just maintain, not big update to change `media1` to `media3`. Hope to see your idea.

**Comment by brianwernick** [comment]
@peerless2012 I can sympathize with your situation of being in a maintenance mode on a project; however this situation doesn't affect the direction a 3rd party library that you are using (ExoMedia) will move. In this case, to properly plan for the future, we have updated ExoMedia to use the `media3` library version of the ExoPlayer for the `5.0` (and subsequent) release. 

In your situation you have a few options:
1. Continue to use a previous version of ExoMedia (e.g. `4.3.0`)
2. Try to use ExoMedia `5.0` when it's released to see if there are actually conflicts between `media1` and `media3` packages
3. Use your own fork of ExoMedia that uses the old `exoplayer` package instead of `media3`

**Comment by peerless2012** [comment]
It means `ExoMedia` 5.0 already use media3?

I always think `ExoMedia` just wrap the `ExoPlayer` to `MediaPlayer`'s api, and `ExoMedia` is under the `AndroidX Media` library, not above the `AndridX Media`. and provide a easy way to use `ExoPlayer` as `MediaPlayer`.

Don't you think, that the new `ExoPlayer` is too heavy for the simple usage ?
