### ISSUE TITLE
Adding a fullscreen button in controls

### ISSUE THREAD

**Issue by jewom** [brianwernick/ExoMedia#714]
I try to add a fullscreen button in the controls but I don't understand how I can do that.
Wich method do I have to use ?
<img width="574" alt="Screenshot 2020-02-27 at 07 53 18" src="https://user-images.githubusercontent.com/13538667/75419521-46d9b400-5936-11ea-966e-8b58f80644bc.png">

**Comment by brianwernick** [comment]
You can add additional views (buttons, etc.) by using the [addExtraView](https://github.com/brianwernick/ExoMedia/blob/127b5f339be0c2d9f9f29cfc4bba5dbffc5853a0/library/src/main/java/com/devbrackets/android/exomedia/ui/widget/VideoControls.java#L466) function in the `VideoControls`. E.g.
```java
videoPlayer.getVideoControlsCore().addExtraView(theButton)
```
