### ISSUE TITLE
m3u8 playing issue in android exoplayer and jw player sdk 

### ISSUE THREAD

**Issue by RealSoftDevs** [brianwernick/ExoMedia#716]
m3u8 online players able to play like jw stream tester

Link to get m3u8 = https://my-json-server.typicode.com/MannForApi/real_tv_apis/ch2_link

Strange thing is jw stream tester and html5 hls player able to play.

but when created an android app with exoplayer and jw player its not working.

When we do get to these m3u8 file we get below details 

HTTP/1.1 200 OK
Server: nginx/1.16.1
X-MediaPackage-Request-Id: 84e45db93370d77e1484c229a40709e1
X-Amz-Cf-Pop: AMS50-C1
X-Amz-Cf-Id: ujRvd2-0CyrBs-lf43zm-Kiae-KqvF_-cTtj3hja4MriO0LuJtTHTg==
Content-Encoding: gzip
Content-Length: 125
Expires: Wed, 08 Apr 2020 12:19:47 GMT
Cache-Control: max-age=0, no-cache, no-store
Pragma: no-cache
Date: Wed, 08 Apr 2020 12:19:47 GMT
Connection: keep-alive
Vary: Accept-Encoding
Akamai-Mon-Iucid-Del: 860809
Alt-Svc: quic=":443"; v="48,46,43,39"; ma=93600
Content-Type: application/x-mpegURL
Access-Control-Max-Age: 86400
Access-Control-Allow-Credentials: true
Access-Control-Expose-Headers: Server,range,hdntl,hdnts,Akamai-Mon-Iucid-Ing,Akamai-Mon-Iucid-Del,Akamai-Request-BC
Access-Control-Allow-Headers: origin,range,hdntl,hdnts
Access-Control-Allow-Methods: GET,POST,OPTIONS
Access-Control-Allow-Origin: *

#EXTM3U
#EXT-X-VERSION:3
#EXT-X-TARGETDURATION:6
#EXT-X-MEDIA-SEQUENCE:1195156
#EXTINF:6.000,
index_21_1195156.ts?m=1579174896
#EXTINF:6.000,
index_21_1195157.ts?m=1579174896

:::::::::::::::::::::::::::::>
not sure how to play in android app , if same is playable in html5 and jw stream tester without any issue.

**Comment by brianwernick** [comment]
I understand that this question is old and I hope that you found a solution shortly after asking it.

ExoMedia natively support HLS (m3u8) streams so all that is needed is passing the URL to the `VideoView`. Are you by chance attempting to use the [ExoPlayer](https://github.com/google/ExoPlayer) itself instead of `ExoMedia` or are you configuring a custom provider to use JW player?
