### ISSUE TITLE
How Do I Play A Different Video And Audio But Make Them Sync Using 1 Player?

### ISSUE THREAD

**Issue by UserI33X** [brianwernick/ExoMedia#718]
`videoView.setVideoURI(Uri.parse(videoUrl));
                        videoView.start();`

The code above enables you to put 1 source into the videoview and start it but how do I make it so I can load a different videourl and audiourl and start them at the same time for sync?

**Comment by brianwernick** [comment]
If you want to have media playing from multiple sources you will need to create a custom `MediaSource` which can be provided to the VideoView through the [setVideoUri(URI, MediaSource)](https://github.com/brianwernick/ExoMedia/blob/master/library/src/main/java/com/devbrackets/android/exomedia/core/api/VideoViewApi.java#L56) method.

An example of how to construct a `MediaSource` can be found in the [DefaultMediaSourceBuilder](https://github.com/brianwernick/ExoMedia/blob/master/library/src/main/java/com/devbrackets/android/exomedia/core/source/builder/DefaultMediaSourceBuilder.java#L34)
