### ISSUE TITLE
Not supprting .mov file format

### ISSUE THREAD

**Issue by Gmrevo** [brianwernick/ExoMedia#721]
- [ ] I have verified there are no duplicate active or recent bugs, questions, or requests

###### Include the following:
 - ExoMedia version: `4.0.0`
 - Device OS version: `7.0`
 - Devide Manufacturer: `Google`
 - Device Name: `Pixel XL`
 
###### Reproduction Steps
 0.

**Comment by brianwernick** [comment]
Closing due to not enough information. If you are requesting additional functionality please open a new ticket and describe what you would like
