### ISSUE TITLE
android.view.ViewRootImpl$CalledFromWrongThreadException

### ISSUE THREAD

**Issue by IAmWilling** [brianwernick/ExoMedia#722]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests

###### Include the following:
 - ExoMedia version: `4.0.0`
 - Device OS version: `7.0 ~ 10.0`
 - Devide Manufacturer: `HUAWEI`
 - Device Name: `HERO YAL AL00`
 
###### Reproduction Steps
 0.  

###### Expected Result
![问题](https://user-images.githubusercontent.com/39398882/108798239-50890c80-75c8-11eb-9b4f-847a2d6cf558.jpg)
![问题2](https://user-images.githubusercontent.com/39398882/108798293-72828f00-75c8-11eb-98ba-4b821bab5459.jpg)

**Comment by IAmWilling** [comment]
What's the problem? Thank you! It's urgent

**Comment by brianwernick** [comment]
I can't quite tell from the information you have provided however it may be related to calling `setVisibility` on a non-UI thread. I am 2 months late on the reply so I'm assuming that you were able to figure out what the problem was, as such I'm going to close this issue.
