### ISSUE TITLE
Migrate Publications to Maven Central

### ISSUE THREAD

**Issue by brianwernick** [brianwernick/ExoMedia#723]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests

JFrog is [ending support for JCenter](https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/) by February 1st, 2022 in 2 parts:
 1. Stop accepting new publications on March 31st, 2021
 2. Shutdown servers on February 1st, 2022

This means that for ExoMedia to still be available after February 1st 2022 we need to migrate any existing versions to MavenCentral, and any new versions after March 31st 2021 will need to be published directly to MavenCentral.

**Comment by nichiyoshi** [comment]
That's nice to hear!

**Comment by kevin4dhd** [comment]
any solution?

**Comment by hwangjr** [comment]
@brianwernick  can you publish 5.0.0-snapshot version to mavenCentral, 4.3.0 version has dependencies conflict error, appcompat VS support.

**Comment by zsmb13** [comment]
@hwangjr If you're willing to do it, you can depend on 5.0 versions via Jitpack.

**Comment by hwangjr** [comment]
ok.
```
    repositories {
        maven { url 'https://jitpack.io' }
    }

dependencies {
    implementation 'com.github.brianwernick:ExoMedia:master-SNAPSHOT'
}
```

**Comment by fahimurrahman** [comment]
@brianwernick please migrate this library from jcenter to mavenCentral. Because i can not run my application without this library. all of my project convert jcenter to mavencentral.

**Comment by brianwernick** [comment]
> @brianwernick please migrate this library from jcenter to mavenCentral. Because i can not run my application without this library. all of my project convert jcenter to mavencentral.

I'm planning on tackling the migration work as part of the `5.0.0` release (I don't have a solid timeframe to communicate at this time), however in the meantime your app can still depend on JCenter as they have committed to continue hosting _existing_ libraries for the foreseeable future (past the initial February 2022 date).

If you would like to limit the libraries that are pulled from JCenter you can do so by updating your `repositories` definition in gradle to define the content, e.g.
```gradle
jcenter() {
  content {
    // Included until ExoMedia is deployed to MavenCentral (https://github.com/brianwernick/ExoMedia/issues/723)
    includeGroup "com.devbrackets.android" 
  }
}
```

**Comment by dbnaza** [comment]
Any update on this issue?

**Comment by brianwernick** [comment]
The deployment process has been updated so the next release will be published to Maven Central

**Comment by jorgefduran** [comment]
Any update?
