### ISSUE TITLE
Next Button on Foreground Notif Too Small for Android 4.2.2

### ISSUE THREAD

**Issue by liwewe** [brianwernick/ExoMedia#73]
![foreground notif](https://cloud.githubusercontent.com/assets/10824291/12542177/5faaeb6c-c352-11e5-99ba-9e6717fcd8ac.png)

Next button on foreground notification is too small just like the picture above and I can't change it.

Do you know how to solve this problem?
Thanks.

**Comment by brianwernick** [comment]
What device are you seeing this on?  What is the screen resolution?

**Comment by liwewe** [comment]
My device is Samsung Galaxy Grand I9082 . The screen resolution is 480 x 800 pixels (~187 ppi pixel density).

**Comment by brianwernick** [comment]
Thanks, I'll get to it a little later.  I'm assuming that it is a problem with the amount of spacing between the previous, play/pause, and next buttons which is forcing the last button to scale so that it correctly fits on the screen.

**Comment by veresvit** [comment]
Hi, similar problem but different case.

First, at the beginning of the playlist it looks ok.
![screenshot_2016-01-27-20-25-38-329](https://cloud.githubusercontent.com/assets/7145384/12625604/c8de59dc-c534-11e5-8612-8ed25c3c3e32.jpeg)

After the next button is pushed, previous appears deformed.
![screenshot_2016-01-27-20-25-50-094](https://cloud.githubusercontent.com/assets/7145384/12625608/d3064258-c534-11e5-9f22-4caeee3bcd7e.jpeg)

**Tested on devices:**
Lenovo Yoga 2 10", Android 5.0.1
Xiaomi Redmi Note 2. Android 5.0.2

Thank you for your time. :)

**Comment by brianwernick** [comment]
@veresvit see https://github.com/brianwernick/ExoMedia/issues/71

**Comment by brianwernick** [comment]
OK, this has been fixed in https://github.com/brianwernick/ExoMedia/commit/d29e63121106bc35bb1f54592c884185938c9207 and will be in the next release
