### ISSUE TITLE
Adding extra headers in 5.x

### ISSUE THREAD

**Issue by zsmb13** [brianwernick/ExoMedia#733]
Is there an API to add extra headers to requests in 5.x versions of the library, like discussed in https://github.com/brianwernick/ExoMedia/issues/103 for earlier versions?

**Comment by brianwernick** [comment]
The solution is the same as #86 by providing your own `DataSourceFactoryProvider` with the caveat that accessing that has been shifted a bit. See the [Demo](https://github.com/brianwernick/ExoMedia/blob/743fa9757cc9d898218467dc08c252a7c6c22e8d/demo/src/main/kotlin/com/devbrackets/android/exomediademo/App.kt#L21) for an example of how to do this for the VideoPlayer. The [AudioPlayer](https://github.com/brianwernick/ExoMedia/blob/743fa9757cc9d898218467dc08c252a7c6c22e8d/library/src/main/kotlin/com/devbrackets/android/exomedia/AudioPlayer.kt#L57) takes a `PlayerConfig` that you can specify the `DataSourceFactoryProvider`.

e.x.
```kotlin
    /**
     * A custom PlayerConfigProvider that uses the OKHttpDataSource that can be passed
     * to the `AudioPlayer` directly. For the `VideoView` this is referenced in the
     * `video_player_activity` VideoView layout attributes.
     */
    @Suppress("unused")
    class OkPlayerConfigProvider: PlayerConfigProvider {
        override fun getConfig(context: Context): PlayerConfig {
            return PlayerConfigBuilder(context)
                .setDataSourceFactoryProvider(OkHttpDataSourceFactoryProvider(context))
                .build()
        }
    }
```

And for the VideoView
```xml
<com.devbrackets.android.exomedia.ui.widget.VideoView
        android:id="@+id/videoView"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        app:playerConfigProvider="com.devbrackets.android.exomediademo.App$OkPlayerConfigProvider"
        app:useDefaultControls="true"/>
```

**Comment by zsmb13** [comment]
Thank you @brianwernick, looking forward to a stable release of this 😀
