### ISSUE TITLE
Unable to add header

### ISSUE THREAD

**Issue by ss0715jj** [brianwernick/ExoMedia#735]
- [ ] I have verified there are no duplicate active or recent bugs, questions, or requests

###### Include the following:
 - ExoMedia version: `5.0.0`
 - Device OS version: `11`
 - Devide Manufacturer: `SAMSUNG`
 - Device Name: `GLAXY NOTE 20`
 
###### Reproduction Steps
 1. Add headers before playing images.
 2. Play when the image is `ready.`

###### Expected Result
It plays normally.

###### Actual Result
403 Error pops up and doesn't play.

I found a solution.

----- Solution plan -----
In the ExoMediaPlayerImpl.kt file, pass config.dataSourceFactoryProvider from the setMediaUri method to function normally.

```
override fun setMediaUri(uri: Uri?) {
        val mediaSource = uri?.let {
            val attributes = MediaSourceBuilder.MediaSourceAttributes(
                config.context,
                it,
                config.handler,
                config.userAgentProvider.userAgent,
                config.bandwidthMeter.transferListener,
                drmSessionManagerProvider,
                config.dataSourceFactoryProvider
            )

            config.mediaSourceProvider.generate(attributes)
        }

        setMediaSource(mediaSource)
    }
```

----------------------------------------------------------------------------------------------------------------

I'd appreciate it if you could review it and reflect it.

**Comment by brianwernick** [comment]
Thanks for reporting this :+1:
