### ISSUE TITLE
Can't download from jcenter

### ISSUE THREAD

**Issue by peerless2012** [brianwernick/ExoMedia#739]
###### Include the following:
 - ExoMedia version: `5.0.0`
 - Device OS version: `11.0`
 - Devide Manufacturer: `Google`
 - Device Name: `Pixel 5`
 
###### Reproduction Steps
Add 5.0  dependence

###### Expected Result
Download the dependence

###### Actual Result
Can't download, and jcenter is unuseful current now. may be move to another publish platform?

**Comment by kevin4dhd** [comment]
same problem

**Comment by brianwernick** [comment]
See #723 for the publication migration

The most recent release is `4.3.0` (see [Releases](https://github.com/brianwernick/ExoMedia/releases))
