### ISSUE TITLE
Not importing in gradle

### ISSUE THREAD

**Issue by Jamalzahid** [brianwernick/ExoMedia#741]
- [ ] I have verified there are no duplicate active or recent bugs, questions, or requests

###### Include the following:
 - ExoMedia version: `4.0.0`
 - Device OS version: `7.0`
 - Devide Manufacturer: `Google`
 - Device Name: `Pixel XL`
 
###### Reproduction Steps
 0.  

###### Actual Result
****

**Comment by shahabgohar** [comment]
@brianwernick @Jamalzahid  I can confirm that
