### ISSUE TITLE
PendingIntent.FLAG_MUTABLE

### ISSUE THREAD

**Issue by sikhworldapp** [brianwernick/ExoMedia#742]
Caused by: java.lang.IllegalArgumentException: com.devbrackets.android.exomediademo: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
    Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.

**Comment by brianwernick** [comment]
This is caused by the Playlist Core issue [#80](https://github.com/brianwernick/PlaylistCore/issues/80), When I get an opportunity I'll work on updating both libs (and demos)

**Comment by brianwernick** [comment]
PlaylistCore `2.1.0` has been released that fixes this issue and ExoPlayer updated in #746
