### ISSUE TITLE
There seems to be no 5.0.0 release

### ISSUE THREAD

**Issue by Quyunshuo** [brianwernick/ExoMedia#743]
There seems to be no 5.0.0 release.I see redeme has updated the 5.0.0 publication.

**Comment by brianwernick** [comment]
That's correct, I thought that I'd reverted that change but must have missed it. The current version is `4.3.0` (in JCenter). I haven't had the opportunity to work on wrapping up the 5.0 changes so don't have a timeframe that I can give at this time either.
