### ISSUE TITLE
Missing setProgressCallback() in EMAudioPlayer

### ISSUE THREAD

**Issue by bkhall** [brianwernick/ExoMedia#75]
There is currently no way to set the progressCallback variable without calling startProgressPoll(). But the start() method, calls startProgressPoll() for us. We need a way to set the callback before calling start() and without having to call startProgressPoll(). And really, startProgressPoll() should not require any arguments - one method to start polling and sending updated to whichever bus or progressCallback.

**Comment by brianwernick** [comment]
Oops, I updated the VideoView (https://github.com/brianwernick/ExoMedia/blob/master/library%2Fsrc%2Fmain%2Fjava%2Fcom%2Fdevbrackets%2Fandroid%2Fexomedia%2FEMVideoView.java#L490) a while ago but I must have forgotten the AudioPlayer.

**Comment by bkhall** [comment]
Still great work!

**Comment by brianwernick** [comment]
Out of curiosity, what are you using the progressPoll for?  Are you using your own Playlist service implementation?

**Comment by bkhall** [comment]
In the particular app I'm writing, we are using your EMAudioPlayer to stream a pure audio only feed. There is no video so I do not want to implement your full-up player. But we still need to display the playing time in the app. So I am using the EMMediaProgressEvent broadcast on our own EMEventBus. via the setBus() method. But the EMEventBus is kind of heavy when all I need is a progress message.

If there were a proper setProgressCallback() method, I could just set one there, instead of doing a startProgressPoll() followed immediately by a stopProgressPoll(). Right now, calling the startProgressPoll() is the only way to pass in the progressCallback.

**Comment by brianwernick** [comment]
OK.  The main reason I ask is because I'm in the process of moving the playlist service (and associated functionality) to its own library, and since that is the only location I was performing the polling I'm contemplating removing it.  But since you are using it now; I may leave it in there with some modifications (since I'm removing EventBus support in 3.0)

**Comment by brianwernick** [comment]
Alright, I've fixed the inconsistencies and added the requested method (https://github.com/brianwernick/ExoMedia/commit/16a0ebaa55347b68e82d1116dfb437a143e59111)

**Comment by bkhall** [comment]
Excellent, thank you!
