### ISSUE TITLE
how to download 4.3.0 java version library

### ISSUE THREAD

**Issue by Jacko07** [brianwernick/ExoMedia#762]
hi,  i  download the demo,but it was kotlin code.  i want to  download 4.3.0 java version library so that i can changes the RenderersFactory to rotate the video content with surface .  because  some portrait video play in landscape  on tv by using ResizingSurfaceView (ExoTextureVideoView not smoothly with some videos) .   videoPlayer.setRotation(90) seems no effct on rotate the video content but only rotate the surface.   besizes, how to support the avi video ,thanks.

**Comment by brianwernick** [comment]
If you want to make custom modifications to any version, including 4.3.0 then you will need to create a fork and modify the code from there. In this specific case you will want to checkout the code from the `4.3.0` tag once you have forked the repository

**Comment by Jacko07** [comment]
> If you want to make custom modifications to any version, including 4.3.0 then you will need to create a fork and modify the code from there. In this specific case you will want to checkout the code from the `4.3.0` tag once you have forked the repository

thanks , is there a easy way to  rotate the video content with surface . because some portrait video play in landscape on tv by using ResizingSurfaceView (ExoTextureVideoView not smoothly with some videos) . videoPlayer.setRotation(90) seems no effct on rotate the video content but only rotate the surface

**Comment by brianwernick** [comment]
This is related to #465. 

Hmm, that's interesting that it's performing a rotation of the clip (surface) instead of the content; would you mind opening up a separate issue for that with a screenshot or two that shows the issue. This is probably still represented in the `master` (will be `5.0.0`) branch since we haven't updated how the scaling and rotation is actually performed

**Comment by Jacko07** [comment]
> This is related to #465.
> 
> Hmm, that's interesting that it's performing a rotation of the clip (surface) instead of the content; would you mind opening up a separate issue for that with a screenshot or two that shows the issue. This is probably still represented in the `master` (will be `5.0.0`) branch since we haven't updated how the scaling and rotation is actually performed

ok, i will open a new issue tomorrow with some screenshot , i think maybe because the video has angle property ,https://blog.csdn.net/weixin_39842955/article/details/112053930

**Comment by brianwernick** [comment]
I've created #764 for the video rotation issue.
