### ISSUE TITLE
how to support avi video 

### ISSUE THREAD

**Issue by Jacko07** [brianwernick/ExoMedia#763]
hi,i want to know how to support avi video or other format video,thanks

**Comment by brianwernick** [comment]
It looks like partial support for the `.avi` container format was added recently (July 5, 2022) to the ExoPlayer [Issue-2092](https://github.com/google/ExoPlayer/issues/2092). I'm not sure if this has made it in to a release yet but if it has by time we release ExoMedia `5.0.0` then that support will be included.
