### ISSUE TITLE
OverideDuration is not working

### ISSUE THREAD

**Issue by pavelsust** [brianwernick/ExoMedia#769]
I want to use 
binding.videoView.overrideDuration(4000)
    binding.videoView.overridePosition(true)

this 2 function but after 4 second video is still playing.

**Comment by brianwernick** [comment]
There seems to be a misunderstanding of what the `override*` functionality does. 

*overrideDuration* only replaces the value returned from `getDuration` and does not stop media playback at that point. This is intended to be used in cases that a live stream is being played which doesn't include the correct timestamp information.

*overridePosition* is typically used in conjunction with *overrideDuration* when playing a live stream that represents multiple media items (such as a streamed radio station).
