### ISSUE TITLE
AppBar show during controller show in full screen.

### ISSUE THREAD

**Issue by pavelsust** [brianwernick/ExoMedia#775]
Hello,
I am facing an issue. When default controller shows app bar also shows with it but I don't want to show app bar during controller show.

How can stop app bar show???

**Comment by brianwernick** [comment]
ExoMedia doesn't automatically handle hiding and showing the Top/Bottom AppBar (Toolbar) components. It's possible you have tied your App Bar visibility to the controls visibility or UI state. You can see how the system UI visibility is handled in the [Demo app](https://github.com/brianwernick/ExoMedia/blob/d254e323476655736b1d6e00d4b828dd2db3489f/demo/src/main/kotlin/com/devbrackets/android/exomediademo/ui/media/VideoPlayerActivity.kt#L182) (or the [4.3.0 Version](https://github.com/brianwernick/ExoMedia/blob/dea8b6cce48f29d098dfc51df580a6c4a05a055d/demo/src/main/java/com/devbrackets/android/exomediademo/ui/activity/FullScreenVideoPlayerActivity.java#L118)).

**Comment by pavelsust** [comment]
Thanks for your response it's working grate.
