### ISSUE TITLE
Video does not fill the container

### ISSUE THREAD

**Issue by alfdev** [brianwernick/ExoMedia#78]
Hi,

this lib has saved me! Thank you

why the video does not fill the container, even if is set to match_parent both for width and height?

thanks

**Comment by brianwernick** [comment]
Do you have an example URL?  The videos should be matching at least one of the sides, the other is changed so that the video's aspect ratio is retained.

**Comment by alfdev** [comment]
This is an example of a squared video: https://www.dropbox.com/s/ylzpl758ix5cj8g/wooo01.mp4?dl=0

**Comment by brianwernick** [comment]
It seems to be working fine for me... (as does https://archive.org/download/Popeye_forPresident/Popeye_forPresident_512kb.mp4) so, what device are you running (and what OS version).

**Comment by alfdev** [comment]
I've tested on lg g3, lg g4 and nexus 5 with kitkat and lollypop (kitkat on the g3).

**Comment by brianwernick** [comment]
OK, I'll look more in to it when I get some time.  If possible, I would appreciate a screenshot of the issue as well :)

**Comment by alfdev** [comment]
Thank you, this is a screenshot

https://www.dropbox.com/s/isqvr31e4qtm9an/Screenshot_2016-02-01-18-39-37.png?dl=0

**Comment by alfdev** [comment]
Hi Brian,

i found a workaround, i've extended a ViewGroup thant contains your EMVideoView:

`    @Override
    protected void onMeasure(int widthMeasureSpec, int heightMeasureSpec) {
        super.onMeasure(widthMeasureSpec, heightMeasureSpec);

        int width = View.MeasureSpec.getSize(widthMeasureSpec);
        int height = View.MeasureSpec.getSize(heightMeasureSpec);

        setMeasuredDimension(width, width);

        videoView.getLayoutParams().width = width;
        videoView.getLayoutParams().height = width;
    }`

in this way i've forced the video widget size.

**Comment by brianwernick** [comment]
OK, seeing as you have a temporary workaround I may push this off until the next path (2.5.4).

**Comment by brianwernick** [comment]
Sadly the video you linked is unplayable (both streaming and downloaded) on the ExoPlayer.  However I did find a source of a 1:1 video (`
        items.add(new VideoItem("Fill Container Test 0", "http://www.dpsinc.com/wp-content/uploads/2013/10/4751d20838e211e3800122000aeb0c37_1014.mp4"));`) that I was unable to reproduce the issue with.  Are you still having the same issue when you aren't extending a custom ViewGroup?

It might also be specific to the layout you have specified
