### ISSUE TITLE
When will 5.0.0 be released?

### ISSUE THREAD

**Issue by emanonwzy** [brianwernick/ExoMedia#781]
We have dependency on 4.3.0, it was released five years ago. We hope can update this dependency. Do you have plan to release 5.0.0?
Thanks.

**Comment by brianwernick** [comment]
We plan on releasing the `5.0.0` version shortly after the ExoPlayer Media3 libraries reach `1.0.0` (currently `1.0.0-rc02`) which should be within the next few months. We are currently close to being feature complete for the `5.0.0` release, then we'll go through a period of testing in which we may release a beta version.

**Comment by brianwernick** [comment]
This morning we published a `5.0.0-beta01` release to `mavenCentral()`. This should be fairly close to what the final version will look like, however we opted for a `beta` label since we may perform some final package updates before the final release.

**Comment by brianwernick** [comment]
After a period of a few months in a beta I've gone ahead and performed the full release of `5.0.0` today.
