### ISSUE TITLE
jetifier enabled in demo app (migrate constraintlayout)

### ISSUE THREAD

**Issue by ghenry22** [brianwernick/ExoMedia#795]
### Environment:
 - ExoMedia version: `5.0.0`

Seem like 'com.android.support.constraint:constraint-layout:2.0.4' is the last remaining legacy support library dep, I was just reading through this info on migrating this to androidx and thought I'd share it in case it's useful:
https://stackoverflow.com/questions/57903216/didnt-find-class-androidx-constraintlayout-constraintlayout

When looking at the demo app in this repo is there anything else pending migration to androidx libs that would require jetifier to be enabled?

Sorry it doesn't follow the issue template but this doesn't really fit as it's more of a question.

**Comment by brianwernick** [comment]
Thanks for reporting this / asking about it. This was an oversight when migrating to the AndroidX libraries and should be converted especially since ExoPlayer is now an AndroidX library. At this point we should be able to remove the jettifier as well

**Comment by ghenry22** [comment]
gradle.properties in the repo root still has jetifierenabled = true.  I presume this could be disabled here for the building the module as well?

**Comment by brianwernick** [comment]
Haha, yep. I just missed removing that one as well
