### ISSUE TITLE
Authentication: Bearer token

### ISSUE THREAD

**Issue by dev-manager-uk** [brianwernick/ExoMedia#799]
Is it possible to pass an Authentication: Bearer token with an http player request possibly?

**Comment by brianwernick** [comment]
You can add network request headers through a custom `DataSourceFactoryProvider` similar to how the demo apps [`OkHttpDataSourceFactoryProvider`](https://github.com/brianwernick/ExoMedia/blob/master/demo/src/main/kotlin/com/devbrackets/android/exomediademo/util/OkHttpDataSourceFactoryProvider.kt) provides an OKHttp `DataSourceFactory`

**Comment by dev-manager-uk** [comment]
Nice, thank you.  I'll give that a try!
