### ISSUE TITLE
How to set CENTER_CROP?

### ISSUE THREAD

**Issue by meNESS** [brianwernick/ExoMedia#80]
Hi,

I'm currently using 'Android-ScalableVideoView' library but I need to use your library too. The problem is I don't know how to set CENTER_CROP for the video view and I need more listeners such as `setOnBufferingUpdateListener`.

**Comment by brianwernick** [comment]
Currently the EMVideoView doesn't support setting the scale type; this is something that I have on my list of things to do in the 3.x pipeline (it probably won't be in the 3.0 release).

As far as the buffering updates go, you can either poll the `getBufferPercentate()` or register a `EMProgressCallback` which contains the buffer percent

**Comment by alirezaaa** [comment]
Thanks for the reply. Does `ExoPlayer` supports center crop?

**Comment by brianwernick** [comment]
I'm not positive, however the MediaCodecVideoTrackRenderer (inside the RenderBuilders) uses a VideoScalingMode type which is currently set to `MediaCodec.VIDEO_SCALING_MODE_SCALE_TO_FIT`.  Changing this to `MediaCodec.VIDEO_SCALING_MODE_SCALE_TO_FIT_WITH_CROPPING` may result in what you expect but there currently isn't a way of specifying this in ExoMedia at the moment (unless you create your own RenderBuilder).

**Comment by eygraber** [comment]
@brianwernick Would you be open to a PR that allows a custom `TextureView` to be used, so that something like [Android-ScalableVideoView](https://github.com/yqritc/Android-ScalableVideoView) could be used instead of `VideoTextureView`?

**Comment by brianwernick** [comment]
Go ahead :)... Though, you should probably make it against the 3.0 branch

**Comment by eygraber** [comment]
Awesome! I'll check that out. Any ETA on 3.0 or is it too early for that?

**Comment by brianwernick** [comment]
The dev work will probably be done in the next week or so, however since it is such a large change I want to get a migration guide and update all the documentation beforehand. (not to mention I should publish [PlaylistCore][PlaylistCore] first)

[PlaylistCore]:https://github.com/brianwernick/PlaylistCore

**Comment by eygraber** [comment]
Cool. `VideoViewApi` is exactly what I had in mind. I'll just add the ability to replace the default implementations.

**Comment by alirezaaa** [comment]
@eygraber You have to provide a `SurfaceView` to the player not a `TextureView` or something else. So, you cannot use the [Android-ScalableVideoView](https://github.com/yqritc/Android-ScalableVideoView) directly.

**Comment by eygraber** [comment]
@alirezaaa you can't use the `ScalableVideoView` itself, but the `ScaleManager` is `public`, and that's what provides most of the functionality. You'd just glue it to a custom implementation of `VideoViewApi`.

**Comment by brianwernick** [comment]
I've added basic scaling options to the EMVideoView in the linked PR

**Comment by ArsalRaza** [comment]
I have fixed it, by just adding the below lines and now videos are center crop without losing their aspect ratios.
`mPlayerView.setResizeMode(AspectRatioFrameLayout.RESIZE_MODE_ZOOM);`

**Comment by pedromarthon** [comment]
> I have fixed it, by just adding the below lines and now videos are center crop without losing their aspect ratios.
> `mPlayerView.setResizeMode(AspectRatioFrameLayout.RESIZE_MODE_ZOOM);`

This will make problems in RecyclerView, you don't want your list items to resize while scrolling.
