### ISSUE TITLE
can this project support  to a minium version of android 17?

### ISSUE THREAD

**Issue by skyhzx** [brianwernick/ExoMedia#806]
### Environment:
 - ExoMedia version: `5.0.0`
 - Device OS version: `12.0`
 - Device Manufacturer: `Google`
 - Device Name: `Pixel 7 Pro`
 
### Reproduction Steps
 0.

**Comment by brianwernick** [comment]
No, the current minSdk supported is 21 (see [build.gradle#L29](https://github.com/brianwernick/ExoMedia/blob/master/library/build.gradle#L29))
