### ISSUE TITLE
Kotlin version error

### ISSUE THREAD

**Issue by kapilgulabani** [brianwernick/ExoMedia#808]
.jar!/META-INF/library_release.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.7.1.
how to fix??

**Comment by brianwernick** [comment]
ExoMedia uses Kotlin `1.9.x`. It sounds like your app is using an older (`1.7.x`) version of Kotlin, so you will need to update the Kotlin version of your app
