### ISSUE TITLE
how to hide and show next and forward button code snippet

### ISSUE THREAD

**Issue by rajam1215** [brianwernick/ExoMedia#810]
@brianwernick I am working on some project, I show videos in listing, everything is working fine, but **need to hide next and forward button**

can you explain how i can do this

Thanks

**Comment by EugeneAsti** [comment]
Also intresting how to add rewind and fastForward buttons on mobile app?
Thanks

**Comment by brianwernick** [comment]
@rajam1215 You can hide the previous and next buttons with [setPreviousButtonRemoved](https://github.com/brianwernick/ExoMedia/blob/master/library/src/main/kotlin/com/devbrackets/android/exomedia/ui/widget/controls/DefaultVideoControls.kt#L468) and [setNextButtonRemoved](https://github.com/brianwernick/ExoMedia/blob/master/library/src/main/kotlin/com/devbrackets/android/exomedia/ui/widget/controls/DefaultVideoControls.kt#L478) if you are using the default `VideoControls` provided

e.g.
```kotlin
(videoView.videoControls as? DefaultControls)?.let { controls ->
    controls.setPreviousButtonRemoved(true)
    controls.setNextButtonRemoved(true)
}
```

**Comment by rajam1215** [comment]
> @rajam1215 You can hide the previous and next buttons with [setPreviousButtonRemoved](https://github.com/brianwernick/ExoMedia/blob/master/library/src/main/kotlin/com/devbrackets/android/exomedia/ui/widget/controls/DefaultVideoControls.kt#L468) and [setNextButtonRemoved](https://github.com/brianwernick/ExoMedia/blob/master/library/src/main/kotlin/com/devbrackets/android/exomedia/ui/widget/controls/DefaultVideoControls.kt#L478) if you are using the default `VideoControls` provided
> 
> e.g.
> 
> ```kotlin
> (videoView.videoControls as? DefaultControls)?.let { controls ->
>     controls.setPreviousButtonRemoved(true)
>     controls.setNextButtonRemoved(true)
> }
> ```

@brianwernick in java it is look like this, Is it Ok?
        DefaultVideoControls controls =
                            (DefaultVideoControls) dataBinding.videoView.getVideoControls();
                    if (controls != null) {
                        controls.setPreviousButtonRemoved(true);
                        controls.setNextButtonRemoved(true);
                    }

**Comment by brianwernick** [comment]
Ah, I see. There's a bug that was likely introduced when we re-wrote the controls for `5.0` where the "remove" request isn't retained through media load states. Specifically the visibility updates in [onLoadEnded](https://github.com/brianwernick/ExoMedia/blob/master/library/src/main/kotlin/com/devbrackets/android/exomedia/ui/widget/controls/VideoControlsMobile.kt#L133) will always set the next/previous buttons as visible.

**Comment by brianwernick** [comment]
There are a few other things that I'm going to look into updating/fixing; but I'm tentatively planning on releasing the update later this week

**Comment by brianwernick** [comment]
`5.2.0` has been released
