### ISSUE TITLE
how to make custom design layout with VideoControlsProvider

### ISSUE THREAD

**Issue by rajam1215** [brianwernick/ExoMedia#811]
### Environment:
 - ExoMedia version: `5.0.1`

@brianwernick I want to make hide only previous button and next button from the video view except all is ok, can you please give example how can I achieve this with **VideoControlsProvider** , and It will more help full , if you make code then make in both native codes **Kotlin** and **Java**

Thanks

**Comment by brianwernick** [comment]
You will need to extend the `VideoControlsProvider` class and return your own `VideoControls` implementation when [getControls()](https://github.com/brianwernick/ExoMedia/blob/master/library/src/main/kotlin/com/devbrackets/android/exomedia/ui/widget/controls/VideoControlsProvider.kt#L15) is called.

e.g.
```kotlin
class CustomVideoControlsProvier: VideoControlsProvider() {
  override fun getControls(context: Context): VideoControls? {
    // TODO: Your implementation
  } 
}
```

Then in your XML layout file you will reference the `CustomVideoControlsProvider` in the `videoControlsProvider` attribute for the `VideoView`, e.g.
```xml
  <com.devbrackets.android.exomedia.ui.widget.VideoView
    android:id="@+id/videoView"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    app:videoControlsProvider="YOUR_PACKAGE.CustomControlsProvider"/>
```

**Comment by rajam1215** [comment]
> You will need to extend the `VideoControlsProvider` class and return your own `VideoControls` implementation when [getControls()](https://github.com/brianwernick/ExoMedia/blob/master/library/src/main/kotlin/com/devbrackets/android/exomedia/ui/widget/controls/VideoControlsProvider.kt#L15) is called.
> 
> e.g.
> 
> ```kotlin
> class CustomVideoControlsProvier: VideoControlsProvider() {
>   override fun getControls(context: Context): VideoControls? {
>     // TODO: Your implementation
>   } 
> }
> ```
> 
> Then in your XML layout file you will reference the `CustomVideoControlsProvider` in the `videoControlsProvider` attribute for the `VideoView`, e.g.
> 
> ```
>   <com.devbrackets.android.exomedia.ui.widget.VideoView
>     android:id="@+id/videoView"
>     android:layout_width="match_parent"
>     android:layout_height="match_parent"
>     app:videoControlsProvider="YOUR_PACKAGE.CustomControlsProvider"/>
> ```

@brianwernick for example I want to hide **seek bar or video previous button** then how can i return seekbar in getControls method with return type of **VideoControls**, can I give me once example of that

**Comment by brianwernick** [comment]
You can look at the existing VideoControls implementations to get an idea of how to customize the controls for your needs.

**Comment by rajam1215** [comment]
@brianwernick can you provide the **link** of class name here

**Comment by brianwernick** [comment]
See [VideoControlsProvider#getControls](https://github.com/brianwernick/ExoMedia/blob/master/library/src/main/kotlin/com/devbrackets/android/exomedia/ui/widget/controls/VideoControlsProvider.kt#L15)
