### ISSUE TITLE
Rotation Issue

### ISSUE THREAD

**Issue by cbedoya** [brianwernick/ExoMedia#82]
Hello

First of all, thanks for this library, its awesome and makes it easier to use the ExoPlayer.

I have an issue on android phones with version lower than lolipop, the video doesn't rotate correctly. On lollipop it works perfectly. Actually there is a bug from the ExoPlayer repo: https://github.com/google/ExoPlayer/issues/91, they suggest to rotate the video using this listener:
```
public void onVideoSizeChanged(int width, int height, int unAppliedRotationDegrees, float pixelWidthHeightRatio);
```

So, not sure if this is something you can fix or should wait for the ExoPlayer team to fix it.

Thanks!

**Comment by brianwernick** [comment]
Could you be more explicit on what the issue is you are seeing.  I tried this on a KitKat device and the video rotates correctly

**Comment by cbedoya** [comment]
For example, I record a video on iOS and play it on a lollipop device, and it rotates correctly, but when playing it on a kitkat device it is rotated 90 degrees

**Comment by brianwernick** [comment]
Alright.  I'll try to find a few more KitKat devices to try it on.  If I can't reproduce it I'll just attempt a fix and let you test it.  It will probably be tomorrow or Friday when I get the chance though

**Comment by cbedoya** [comment]
Here is a video recorded on iOS, and on some phones it appears rotated 90 degrees
https://dl.dropboxusercontent.com/s/8evvodziythdnw2/20160206_235342.mp4

Anyway I will try to make a fix and send you a PR :)

**Comment by brianwernick** [comment]
I've started working on this fix (https://github.com/brianwernick/ExoMedia/tree/video_rotation_fix) however there is still an issue with the video being sized, and consequently squeezed, when rotating.  It may be a timing issue of when the video is resized, a scaling issue, or something else entirely.

**Comment by cbedoya** [comment]
I had the same issue, what I ended up was to only calculate the aspect ratio if no rotation needed, and the video looks fine, not sure if that affects when you have videos of different aspect ratio

**Comment by brianwernick** [comment]
I have updated the 3.0 branch to correctly apply video rotation, see the referenced PR

**Comment by volser** [comment]
I still have problem with rotation:

I have video rotate=90 width=1280 height=720
Android 4.4

And video doesn't rotate correctly.
How to fix it?

**Comment by volser** [comment]
1. setScaleType(ScaleType.CENTER_CROP); doesn't work correctly
2. After .restart() video are rotated again (90, 180, 270, ....)

Source video:
https://drive.google.com/file/d/0BwgmgDZTQevyT2NUV2VDQWJwc1NMWWhXYnE5YWpMbE9Uem9r/view?usp=sharing

Bug:
https://drive.google.com/file/d/0BwgmgDZTQevyUy1xT3U4WVJCb0o2UHdzV09RSGVqZUcwdGNR/view?usp=sharing

**Comment by volser** [comment]
My code:

```
videoView.setScaleType(ScaleType.CENTER_CROP);
videoView.setOnCompletionListener(new OnCompletionListener() {
                        @Override
                        public void onCompletion() {
                            videoView.restart();
                        }
                    });
videoView.setVideoURI(fileUri);
videoView.start();
```

**Comment by brianwernick** [comment]
@volser open up a new ticket
