### ISSUE TITLE
How to keep the notification while playing a video in the background

### ISSUE THREAD

**Issue by jjvargas** [brianwernick/ExoMedia#83]
On the Demo app, if I play a video and put the app in the background , I can still listen to the audio but the notification disappears, how to avoid this?

**Comment by brianwernick** [comment]
This is actually a Bug in the Demo app.  However, If you want to keep the notification then in the `VideoPlayerActivity` on line 40, comment out (or remove) the `playlistManager.invokeStop();` call.
