### ISSUE TITLE
What defines the streaming protocol?

### ISSUE THREAD

**Issue by cbcnos** [brianwernick/ExoMedia#85]
I have a simple doubt: how can I ensure that the DASH streaming is being used on Android 4.0 and above? I didn't find any method to set the protocol or get information about what is being used.

Thanks for any help

**Comment by brianwernick** [comment]
When you specify the Audio or Video Url it will determine if you are using a streaming protocol (HLS, DASH, SS) and use the appropriate RenderBuilder.  Otherwise it will use the default RenderBuilder which will determine the format itself (supporting many formats including mp4, aac, mp3, etc.)
