### ISSUE TITLE
Proposal: API for providing HttpDataSource

### ISSUE THREAD

**Issue by hzsweers** [brianwernick/ExoMedia#86]
ExoPlayer allows for providing a custom HttpDataSource. One such use would be providing your own, more up-to-date OkHttpClient instance rather than relying on the older one in the Android framework. It's also useful if you have custom logging in your HttpClient implementation that you'd like to track in the video.

**Comment by brianwernick** [comment]
I like this idea however it will have to wait until a 3.x version

**Comment by se-bastiaan** [comment]
You can provide your own `RenderBuilder` in using `setVideoURI(Uri uri, RenderBuilder renderBuilder)` in which you use a different `DataSource`.

**Comment by hzsweers** [comment]
`RenderBuilder` doesn't provide the option for specifying your own `DataSource` as far as I can see?

**Comment by brianwernick** [comment]
@hzsweers You would need to create your own RenderBuilder and specify a `DataSource` of your own.  See https://github.com/brianwernick/ExoMedia/blob/master/library%2Fsrc%2Fmain%2Fjava%2Fcom%2Fdevbrackets%2Fandroid%2Fexomedia%2Fbuilder%2FRenderBuilder.java#L79

**Comment by brianwernick** [comment]
Because this isn't a major issue and the ability to specify the DataSource via the RenderBuilders I'm moving a more simplified solution to a later 3.x release

**Comment by hzsweers** [comment]
I would argue this is a significant issue and specifying via datarenderers isn't simple, but I suppose it's down to the consumer. At the very least, a sample or wiki example would be good to have in the meantime.

**Comment by 9Arca9** [comment]
Any updates on this?

I would love to be able to set HTTPHeaders for HLS Requests.

**Comment by brianwernick** [comment]
No, It's a low-priority issue as you can specify you own DataSource via the RenderBuilders currently

**Comment by 9Arca9** [comment]
Alright, i actually just removed exomedia and used the demo exoPlayer as it was easier to set it that way.

**Comment by brianwernick** [comment]
I'm not sure why that is easier than just specifying your own RenderBuilder but I'm happy it works for you

**Comment by SalmanTKhan** [comment]
Where do you supply your own RenderBuilder?

**Comment by brianwernick** [comment]
This functionality has been added to the working `4.0.0` branch. The Demo's App.java has an example, but for posterity I'm reproducing it here as well.

```java
// Registers the media sources to use the OkHttp client instead of the standard Apache one
// Note: the OkHttpDataSourceFactory can be found in the ExoPlayer extension library `extension-okhttp`
ExoMedia.setHttpDataSourceFactoryProvider(new ExoMedia.HttpDataSourceFactoryProvider() {
    @Override
    public HttpDataSource.BaseFactory provide(@NonNull String userAgent, @Nullable TransferListener<? super DataSource> listener) {
        return new OkHttpDataSourceFactory(new OkHttpClient(), userAgent, listener);
    }
});
```
