### ISSUE TITLE
How to show the playlist on the main fullScreen?

### ISSUE THREAD

**Issue by adetheprince** [brianwernick/ExoMedia#87]
Hi there
I first would like to thank you for saving our time with this nice Videoview library.
I have tested with many video type and it works well with almost every video format I tried, so far very happy with it.
I am very new to android video streaming, so I am wondering if you could lead me on where to edit if we want to show the playlist on the main videoview or fullscreen, I mean when a user click a button or mousehover/Ontouch event, it should show the playlist, just like how it shows now the DefaultControls when a user touch the screen, so rather then showing only DefaultControls I would love to show the video playlist ( that is now outside the VideoView ) on the right or left above the DefaultControls, something like a widget inside the fullscreen view or scroll Listview , for now I am forcing user to click back/return to main playlist page (which I would like to change this behavior). 
I tried to change/modify EMVideoView.java file but nothing happened.
Is this even possible?.
Many thanks in advance.

**Comment by brianwernick** [comment]
You can register for the visibility (and other) events with `emVideoView.setVideoViewControlsCallback(null);'.

**Comment by adetheprince** [comment]
Thanks for your prompt reply, I will see if I can do that as I am still learning java, so hopefully it will be trouble free.
Thanks.
