### ISSUE TITLE
Playing a video in the background for a few minutes suddenly stops.

### ISSUE THREAD

**Issue by jjvargas** [brianwernick/ExoMedia#88]
After 1 or 2 minutes of the video playing in the background, it suddenly stops playing as I cannot hear the audio anymore. I have tried with a Moto G and a Samsung Galaxy Note 4 , and its the same
any clues?

**Comment by brianwernick** [comment]
Playing video in the background isn't supported functionality.  If you want to play just the audio, you can pass the same URL to the EMAudioPlayer.  If you want to look in to it some more, It is most likely due to the `onDetachedFromWindow()` call

**Comment by jjvargas** [comment]
I commented out the code from onDetachedFromWindow()  but still the same, I also tried to make the service START_STICKY but no change. Any more hints?
