### ISSUE TITLE
Proposal: Use a TextureView-based VideoView implementation for the fallback

### ISSUE THREAD

**Issue by hzsweers** [brianwernick/ExoMedia#89]
For the same reasons touched on in #79 

Specifically, I've used this: https://github.com/sprylab/texturevideoview. It's a ready-made drop-in replacement. Would be happy to open a PR if you're up for it.

**Comment by brianwernick** [comment]
Because of how minimal the fallback should be used, I'm not sure if it is worth while at the moment.  Given, Kindles have a pretty large use base and those don't support the ExoPlayer

**Comment by hzsweers** [comment]
It uses the same API as a normal videoview, so it would be a pretty seamless swap. Let me know what you decide!

**Comment by brianwernick** [comment]
In order to keep the same source styles and similar architecture as the ExoVideoView (and other files) I ended up writing a TextureVideoView from scratch.  I haven't tested it yet but the initial setup was in https://github.com/brianwernick/ExoMedia/commit/62eb4a1d7ee158ce66e55447bc99e1fc3b3e3d99

**Comment by hzsweers** [comment]
:+1:
