### ISSUE TITLE
Is Lock Screen working?

### ISSUE THREAD

**Issue by jjvargas** [brianwernick/ExoMedia#9]
I executed the sample, played an Audio Track, I can see the notification with the player controls, but when I lock the phone, I don't see the background image or the controls on the lock screen.

**Comment by brianwernick** [comment]
@jjvargas What OS version are you running?  Lollipop doesn't support the lock screen controls the same way it did on older versions.  It is something on my list of things to do, but have yet to get to it.

**Comment by jjvargas** [comment]
I tried on a 5.1 and could not see them. However, in a 4.3 device I can see the controls but they are not working.   Are you following the Universal Music Player project ? it has some good examples for this. and someone has already ported it < Lollipop.   I will have a look a bit more closer to the code.  Congrats for ExoMedia, I think it has a lot of very good advantages using ExoPlayer :)

**Comment by brianwernick** [comment]
OK, I'll take a look at why the controls aren't informing the service when I get a chance (possibly this weekend).  It will probably be a few weeks before I add lockscreen notification support to Lollipop+ devices

**Comment by brianwernick** [comment]
@jjvargas The lockscreen has been fixed for devices lower than Lollipop in 2.3.1.  I have a few other projects that are higher priority right now, so the Lollipop lockscreen notification will probably be a couple of weeks before it is added.

**Comment by jjvargas** [comment]
Cool Thanks

**Comment by brianwernick** [comment]
The Lollipop lockscreen notification has been added in 2.3.3
