### ISSUE TITLE
Black overlays when changing EMVideoView's parent's LayoutParams

### ISSUE THREAD

**Issue by Thijsiez** [brianwernick/ExoMedia#91]
Hej there,

First of all, thank you so much for the amazing library, it has saved me a lot of time and I can't wait for 3.0!!  
Unfortunately, 2.5.3 is giving me some problem that I can't seem to wrap my head around. For my application I have a resizing layout which has a EMVideoView as a child view. The parent's dimension is changed by switching the LayoutParams around. Now when the EMVideoView is instantiated, the parent's width is 1080 pixels and the forced to a 16:9 aspect ratio. When I change the LayoutParams to a smaller variant, for example 800 pixels wide, some weird black bar overlays appear on the EMVideoView, which didn't happen before with the standard Android VideoView. I have some screenshots here:

1080 pixels wide
![1080](https://cloud.githubusercontent.com/assets/2866734/12886025/e8d1c956-ce6a-11e5-8170-b379f8d062ef.png)

960 pixels wide
![960](https://cloud.githubusercontent.com/assets/2866734/12886222/11858b8e-ce6c-11e5-9014-d62b4fdc2357.png)

800 pixels wide
![800](https://cloud.githubusercontent.com/assets/2866734/12886228/1ab9a21c-ce6c-11e5-961f-be24b18a9d6e.png)

640 pixels wide
![640](https://cloud.githubusercontent.com/assets/2866734/12886237/24b0361e-ce6c-11e5-8add-da0df7f1ed8f.png)

540 pixels wide (half width)
![540](https://cloud.githubusercontent.com/assets/2866734/12886244/2ed551ba-ce6c-11e5-89f7-12b1dea1cd6b.png)

As you can see, the black overlay is exactly the amount of pixels that the EMVideoView is smaller than 1080 pixels wide, on each side. Therefore, when the EMVideoView is half as wide compared to when it was instantiated, the overlays are completely covering the video. Is there any way I could counter this or is this a bug in the library?

Thanks in advance!

**Comment by brianwernick** [comment]
Hmm, This is probably an issue with the shutters.  What android version are you seeing this on (really I just want to know if this is an issue with the sizing with the ExoPlayer backing, or the VideoView backing)

**Comment by Thijsiez** [comment]
I'm running this on a OnePlus One running Cyanogen OS 12.1.1 which is Android 5.1.1, so I'm guessing it's the ExoPlayer backing that's causing it. My app is min SDK 17 anyways so I don't think the VideoView backing is even used

**Comment by brianwernick** [comment]
OK, Thanks.  I'm fairly certain I'm just missing a callback for when the view size changes that needs to inform shutters (or the videos surface) to resize.

**Comment by Thijsiez** [comment]
If there's any info you need about my implementation or if I should test something, just let me know ;)

**Comment by brianwernick** [comment]
OK, this has been fixed in https://github.com/brianwernick/ExoMedia/commit/3df369b2dd09b583a26a80f8eccc433aaf5e325d and will be in the next release
