### ISSUE TITLE
On ARC Welder: Playback of remote MP4 doesn't work

### ISSUE THREAD

**Issue by afollestad** [brianwernick/ExoMedia#94]
It seemed to work at one point, not sure if something in the library or something in ARC Welder broke it recently.

All that is seen is a blank screen with no video or audio. Buffering finishes, but playback does not begin (and the duration does not go past 0).

![capture](https://cloud.githubusercontent.com/assets/1820165/12930876/6403b672-cf40-11e5-97ed-6c04ee57fa6e.JPG)

---

**I should also note that local playback _does_ work, e.g. a video recorded by the camera.**

**Comment by afollestad** [comment]
To add to that, local MP4 playback (e.g. recorded from the local camera) does work.

**Comment by afollestad** [comment]
Sorry, one more thing.

Setting `useExo` to `false` on ARC Welder as seen [on this commit in my fork](https://github.com/afollestad/ExoMedia/commit/4c933825a4924240cc3abaf43732fe30105b250e) solves the problem half way.

As I mentioned on #93, audio works but video does not.

**Comment by brianwernick** [comment]
I just tested the MP4 url from the demo (Big Buck Bunny) with the current master from ExoPlayer and had the same issue.

**Comment by brianwernick** [comment]
###### Update:
Still has issues with the ExoPlayer 1.5.8 (and most recent Arc Welder)

**Comment by brianwernick** [comment]
This is no longer an issue on the `dev_v4` branch. My assumption is that it was fixed in the ExoPlayer 2.0 release
