### ISSUE TITLE
Fix Flv video exoplayer

### ISSUE THREAD

**Issue by diaconuliviu85** [brianwernick/ExoMedia#96]
Hello
I do not know if it will help much for a new version that works with flv. but I found it and put it here.
I hope to help

https://github.com/KMK-ONLINE/ExoPlayer/commit/82fd57c94acaf7031ce4e59aae02464d7dffcb12

**Comment by se-bastiaan** [comment]
I do not understand what a commit on the ExoPlayer project has to do with ExoMedia?

**Comment by diaconuliviu85** [comment]
exomedia is based on exoplayer. Perhaps this information can be useful for exomedia creator.

**Comment by se-bastiaan** [comment]
That doesn't mean that ExoMedia should fix something that is in ExoPlayer.


The commit was made on the dev branch of the ExoPlayer project, which means that when the version of ExoPlayer is used by ExoMedia is updated the real issue (https://github.com/google/ExoPlayer/issues/1137) is solved when you use ExoMedia.

**Comment by diaconuliviu85** [comment]
ok

**Comment by brianwernick** [comment]
This is also probably in the ExoPlayer 1.5.5 release that the most recent version of ExoMedia uses.  (Sorry for the late reply, I've been trying to focus on work for the last few days)
