### ISSUE TITLE
Don't Use MediaPlayer Interfaces

### ISSUE THREAD

**Issue by eygraber** [brianwernick/ExoMedia#98]
It's somewhat confusing to use the `MediaPlayer` interfaces when using `ExoPlayer`. I get that there's the `EMListenerMux`, and why it uses the `MediaPlayer` interfaces, but have you given this any thought?

**Comment by brianwernick** [comment]
Yes, for the 3.0 release I will be creating my own callbacks instead of the MediaPlayer callbacks.  (something similar to the listeners in the PlaylistCore https://github.com/brianwernick/PlaylistCore/tree/master/library/src/main/java/com/devbrackets/android/playlistcore/listener)

**Comment by brianwernick** [comment]
New interfaces have now been implemented on the 3.0 branch.

https://github.com/brianwernick/ExoMedia/commit/de481d05246594cedf6ac66f045e6c01b766563b
